force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <externalId>true</externalId>
    <label>Código do vendedor</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SellerDocumentsController.cls
public class SellerDocumentsController {

    @AuraEnabled
    public static List<Document> getDocumentList(Id userId){
        List<Seller__c> listSeller = [SELECT Id, SellerNumberNmb__c FROM Seller__c WHERE UserLkp__c =: userId];
        if(listSeller.isEmpty()) return null;
        List<String> sellerNumbers = new List<String>();
        for(Seller__c s : listSeller){
            sellerNumbers.add(s.SellerNumberNmb__c.leftPad(8, '0') + '%');
        }
        system.debug(sellerNumbers);
        List<Document> listDocs = [SELECT Id, Name, URL FROM Document WHERE Name LIKE :sellerNumbers AND Folder.DeveloperName = 'SellerFiles'];
        return listDocs;
    }
    
    @AuraEnabled
    public static String deleteDocument(Id docId){
        try{
            delete new Document(Id = docId);
            return 'SUCCESS';
        }
        catch(Exception e){
            return e.getMessage();
        }
    }
    
}