force-app/main/default/objects/CaseMotive__c/CaseMotive__c.object-meta.xml
<CustomObject>
    <description>[a05][CaseMotive__c] Objeto que relaciona motivo do caso o tipo de caso e perfil de visualização.</description>
    <label>Motivo do caso</label>
    <nameField>
        <label>Motivo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Motivos dos casos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseMotive__c/fields/CaseTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>CaseTypeTxt__c</fullName>
    <label>Tipo de caso</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMotive__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMotive__c/fields/ContactTxt__c.field-meta.xml
<CustomField>
    <fullName>ContactTxt__c</fullName>
    <label>Contato</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMotive__c/fields/NatureTxt__c.field-meta.xml
<CustomField>
    <fullName>NatureTxt__c</fullName>
    <label>Natureza</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseMotive__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Perfil</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Administrador do sistema</fullName>
            </value>
            <value>
                <fullName>Analista SAC</fullName>
            </value>
            <value>
                <fullName>Coordenador SAC</fullName>
            </value>
            <value>
                <fullName>Interface Salesforce</fullName>
            </value>
            <value>
                <fullName>Analista serviços técnicos</fullName>
            </value>
            <value>
                <fullName>Analista financeiro</fullName>
            </value>
            <value>
                <fullName>Analista fiscal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSECaseMotiveSelector.cls
public with sharing class CSECaseMotiveSelector extends fflib_SObjectSelector{

    public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			CaseMotive__c.Id,
			CaseMotive__c.Name,
			CaseMotive__c.CaseTypeTxt__c,
			CaseMotive__c.Profile__c,
			CaseMotive__c.ContactTxt__c,
			CaseMotive__c.NatureTxt__c,
			CaseMotive__c.Category__c
		};
	}
	
	public Schema.SObjectType getSObjectType() {
		return CaseMotive__c.sObjectType;
	}

    public List<CaseMotive__c> selectAll() {
    	
        String query = String.format(
            ' SELECT {0}' + 
            ' FROM {1}' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()              
            }
        );  
        return (List<CaseMotive__c>)Database.query(query);       
    }
	
}