force-app/main/default/objects/Case/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Preenchido automaticamente caso só haja uma opção</description>
    <inlineHelpText>Preenchido automaticamente caso só haja uma opção</inlineHelpText>
    <label>Área de Negócios</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/OpportunityLkp__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderStatusTxt__c</fullName>
    <label>Status da ordem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>InApproval</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>SentToSAP</fullName>
                <label>Enviado SAP</label>
            </value>
            <value>
                <fullName>Não processado</fullName>
            </value>
            <value>
                <fullName>Processado parcialmente</fullName>
            </value>
            <value>
                <fullName>Processado completamente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente com ZNOV caso deixe em branco</inlineHelpText>
    <label>Tipo de Ordem</label>
    <referenceTo>OrderType__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypePicklistTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderTypePicklistTxt__c</fullName>
    <defaultValue>&apos;ZNOV&apos;</defaultValue>
    <label>Tipo de Ordem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>OrderType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentTermLkp__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>PaymentTerm__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentTermTxt__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermTxt__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PaymentTerm</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/PrimaryBln__c.field-meta.xml
<CustomField>
    <fullName>PrimaryBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o pedido é o principal de uma oportunidade</description>
    <inlineHelpText>Somente uma ordem primária por oportunidade.</inlineHelpText>
    <label>Primário</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/classes/CSEOrderDOM.cls
public with sharing class CSEOrderDOM extends fflib_SObjectDomain implements ITestAble {
    CSEOrderBO orderBO = new CSEOrderBO();
    public CSEOrderDOM(List<Order__c> sObjectList){
        super((List<SObject>)sObjectList);
    }
    
    public override void onBeforeInsert(){
        
        orderBO.setCarrierDescription((List<Order__c>) records);
        
        orderBO.setSalesAreaOrAccount((List<Order__c>) records);
        
        orderBo.setOwner((List<Order__c>) records);
        
        List<Order__c> listOrders = new List<Order__c>();
        for(Order__c o : (List<Order__c>) records){
            if((o.PaymentTermLkp__c == null && o.PaymentTermTxt__c != null) || (o.OrderTypeLkp__c == null && o.OrderTypePicklistTxt__c != null))
                listOrders.add(o);
        }
        if(listOrders.size() > 0)
            orderBO.setPaymentTermAndOrderType((List<Order__c>) listOrders);
        
        orderBO.validateOrderType((List<Order__c>) records);
                
        for(Order__c o : (List<Order__c>) records){
            if(o.OpportunityLkp__c != null) o.PrimaryBln__c = true;
        }
        //orderBO.setAccountReceiver((List<Order__c>) records);
      
    }

    public override void onAfterInsert(){
     	// Set status in Case
     	//orderBO.setStatusCase((List<Order__c>)records);
     	
     	// Set Order in Caso, field CreatedOrderLkp__c
     	orderBO.setOrderInCase((List<Order__c>)records);
        
        
        List<Id> listPrimary = new List<Id>();
        List<Order__c> listNewOrders = new List<Order__c>();
        
        for(Order__c o : (List<Order__c>)records){
            if(o.AccountLkp__c != null && o.AccountAreaSalesLkp__c != null && o.CustomIdTxt__c == null && !System.Test.isRunningTest()){
                OrderIntegrationUtils.createQuoteOnSAPFuture(o.Id);
            }
            if(o.AccountLkp__c != null){
                listNewOrders.add(o);
            }
            if(o.OpportunityLkp__c != null && o.PrimaryBln__c == true){
                listPrimary.add(o.Id);
            }
        }
        try{
            orderBO.setPrimaryOrders(listPrimary);
            orderBO.setPurchaseDateAccount(listNewOrders);
        }
        catch(Exception e){
            records[0].addError(e.getMessage());
        }
    }
    
    public override void onBeforeUpdate(Map<Id, SObject> existingRecords){
        orderBO.setCarrierDescription((List<Order__c>) records);
        
        List<Order__c> listOrders = new List<Order__c>();
        for(Order__c o : (List<Order__c>)records){
            Order__c oldOrder = (Order__c) existingRecords.get(o.Id);
            if(oldOrder.PaymentTermTxt__c != o.PaymentTermTxt__c || oldOrder.OrderTypePicklistTxt__c != o.OrderTypePicklistTxt__c){
                listOrders.add(o);
            }
        }
        try{
            orderBO.setPaymentTermAndOrderType(listOrders);
        }
        catch(Exception e){
            records[0].addError(e.getMessage());
        }
    }
    
    public override void onAfterUpdate(Map<Id,SObject> existingRecords){
    	if (existingRecords != null) {
            //orderBO.setStatusCase((List<Order__c>)records);
            List<Order__c> listChangedPaymentTerm = new List<Order__c>();
            //List<Order__c> listSentToSAP = new List<Order__c>();
            List<Id> listPrimary = new List<Id>();
            
            orderBO.setOrderInCase((List<Order__c>)records);
            
            for(Order__c o : (List<Order__c>)records){
                Order__c oldOrder = (Order__c) existingRecords.get(o.Id);
                if(o.OpportunityLkp__c != null && o.PrimaryBln__c == true && oldOrder.PrimaryBln__c == false){
                    listPrimary.add(o.Id);
                }
                
                if(oldOrder.PaymentTermTxt__c != o.PaymentTermTxt__c && o.OrderStatusTxt__c == 'Rascunho'){
                    listChangedPaymentTerm.add(o);
                }
                /*if(o.CustomIDTxt__c != null && o.OrderStatusTxt__c == 'SentToSAP' && o.OrderStatusTxt__c != oldOrder.OrderStatusTxt__c)
                    listSentToSAP.add(o);
*/
            }
            try{
                orderBO.setPrimaryOrders(listPrimary);
                orderBO.recalculatePrices(listChangedPaymentTerm);
                //orderBO.updateOrderSAP(listSentToSAP);
            }
            catch(Exception e){
                records[0].addError(e.getMessage());
            }
        }
    }

    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new CSEOrderDOM(sObjectList);
        }
    }

    public static Order__c getSampleObject() {
        return new Order__c();
    }
}