force-app/main/default/objects/Case/fields/ByPassBln__c.field-meta.xml
<CustomField>
    <fullName>ByPassBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ByPass</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarrierEmailEml__c.field-meta.xml
<CustomField>
    <fullName>CarrierEmailEml__c</fullName>
    <inlineHelpText>Email informado no cadastro da transportadora.</inlineHelpText>
    <label>Transportadora email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/ClouseReasonTxt__c.field-meta.xml
<CustomField>
    <fullName>ClouseReasonTxt__c</fullName>
    <label>Motivo do encerramento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Crédito liberado</fullName>
            </value>
            <value>
                <fullName>Improcedente</fullName>
            </value>
            <value>
                <fullName>Negociação comercial</fullName>
            </value>
            <value>
                <fullName>Ordem cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido alterado</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Prorrogação atendida</fullName>
            </value>
            <value>
                <fullName>Reclamação não procede</fullName>
            </value>
            <value>
                <fullName>Nota fiscal entregue</fullName>
            </value>
            <value>
                <fullName>Reposição reprovada</fullName>
            </value>
            <value>
                <fullName>Sucesso</fullName>
            </value>
            <value>
                <fullName>Termo de quitação recebido</fullName>
            </value>
            <value>
                <fullName>Informado por email</fullName>
            </value>
            <value>
                <fullName>Informado por telefone</fullName>
            </value>
            <value>
                <fullName>Sinistro total</fullName>
            </value>
            <value>
                <fullName>Sinistro parcial</fullName>
            </value>
            <value>
                <fullName>Ordem em duplicidade</fullName>
            </value>
            <value>
                <fullName>Solicitação do vendedor</fullName>
            </value>
            <value>
                <fullName>Substituição reprovada</fullName>
            </value>
            <value>
                <fullName>Substituição efetuada</fullName>
            </value>
            <value>
                <fullName>Revertido vendedor</fullName>
            </value>
            <value>
                <fullName>Revertido analista</fullName>
            </value>
            <value>
                <fullName>NFC de Devolução Incorreta</fullName>
            </value>
            <value>
                <fullName>Devolução não Aprovada</fullName>
            </value>
            <value>
                <fullName>Novo pedido entregue ao cliente</fullName>
            </value>
            <value>
                <fullName>Cliente não aceitou novo pedido</fullName>
            </value>
            <value>
                <fullName>Transportadora localizou mercadoria</fullName>
            </value>
            <value>
                <fullName>Indicação de BNDES realizada</fullName>
            </value>
            <value>
                <fullName>Indicação de BNDES não realizada</fullName>
            </value>
            <value>
                <fullName>Carta de correção enviada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/DeliveryDateInvoiceCreatedDte__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDateInvoiceCreatedDte__c</fullName>
    <label>Data de entrega NF criada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DeliveryTxt__c.field-meta.xml
<CustomField>
    <fullName>DeliveryTxt__c</fullName>
    <label>Entrega</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pós</fullName>
            </value>
            <value>
                <fullName>Ato</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/DevolutionOrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>DevolutionOrderStatusTxt__c</fullName>
    <label>Status da ordem de devolução</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/DevolutionOrderTxt__c.field-meta.xml
<CustomField>
    <fullName>DevolutionOrderTxt__c</fullName>
    <label>Ordem de devolução</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceCreatedTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCreatedTxt__c</fullName>
    <label>Nota fiscal criada</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceReplacementTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReplacementTxt__c</fullName>
    <label>Nota fiscal de substituição</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewOrderReplacementTxt__c.field-meta.xml
<CustomField>
    <fullName>NewOrderReplacementTxt__c</fullName>
    <label>Nova ordem de Substituição</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/NewSalesOrder__c.field-meta.xml
<CustomField>
    <fullName>NewSalesOrder__c</fullName>
    <label>Nova ordem de venda</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderDevolutionStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderDevolutionStatusTxt__c</fullName>
    <label>Status ordem criada</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ReplacementOrderTxt__c.field-meta.xml
<CustomField>
    <fullName>ReplacementOrderTxt__c</fullName>
    <label>Ordem de reposição</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SalesOrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrderStatusTxt__c</fullName>
    <label>Status da ordem de venda</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SellerEmailEml__c.field-meta.xml
<CustomField>
    <fullName>SellerEmailEml__c</fullName>
    <inlineHelpText>Email informado no cadastro do vendedor.</inlineHelpText>
    <label>Vendedor email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Case/fields/SinisterTxt__c.field-meta.xml
<CustomField>
    <fullName>SinisterTxt__c</fullName>
    <label>Sinistro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TaxclassificationTxt__c.field-meta.xml
<CustomField>
    <fullName>TaxclassificationTxt__c</fullName>
    <label>Classificação fiscal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSECaseSelector.cls
public with sharing class CSECaseSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
        return new List<Schema.SObjectField> {
            Case.Id,
            Case.AccountId,
            Case.InvoiceLkp__c,
            Case.CarrierEmailEml__c,
            Case.SellerEmailEml__c,
            Case.RecordTypeId,
            Case.Status,
            Case.ContactId,
            Case.ClouseReasonTxt__c,
            Case.TaxclassificationTxt__c,
            Case.OwnerId,
            Case.Type,
            Case.OrderLkp__c,
            Case.SinisterTxt__c,
            Case.NewSalesOrder__c,
            Case.CaseNumber,
            Case.CustomIDTxt__c,
            Case.DevolutionOrderTxt__c,
            Case.OrderDevolutionStatusTxt__c,
            Case.NewOrderReplacementTxt__c,
            Case.DeliveryDateInvoiceCreatedDte__c,
            Case.ByPassBln__c,
            Case.DeliveryTxt__c,
            Case.Reason,
            Case.SalesOrderStatusTxt__c,
            Case.DevolutionOrderStatusTxt__c,
            Case.InvoiceCreatedTxt__c,
            Case.ReplacementOrderTxt__c,
            Case.InvoiceReplacementTxt__c
        };
    }
    
    public Schema.SObjectType getSObjectType() {
        return Case.sObjectType;
    }
    
    public List<Case> selectById(Set<Id> idSet) {

        String query = String.format(
            ' SELECT {0} ' + 
            ' FROM {1}' +
            ' WHERE Id IN :idSet',
            new List<String>{
                getFieldListString(),
                getSObjectName()                     
            }
        );  

        return (List<Case>)Database.query(query);       
    }
    
    public List<Case> selectByInvoice(Id invoiceId) {

        String query = String.format(
            ' SELECT {0} ' + 
            ' FROM {1}' +
            ' WHERE InvoiceLkp__c = :invoiceId',
            new List<String>{
                getFieldListString(),
                getSObjectName()                     
            }
        );  

        return (List<Case>)Database.query(query);       
    }
    
    public List<Case> selectByOrder(Id orderId) {

        String query = String.format(
            ' SELECT {0} ' + 
            ' FROM {1}' +
            ' WHERE OrderLkp__c = :orderId',
            new List<String>{
                getFieldListString(),
                getSObjectName()                     
            }
        );  

        return (List<Case>)Database.query(query);       
    }
}