force-app/main/default/objects/Case/fields/ComplaintNatureTxt__c.field-meta.xml
<CustomField>
    <fullName>ComplaintNatureTxt__c</fullName>
    <label>Natureza da reclamação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>04-Expedição</fullName>
            </value>
            <value>
                <fullName>06-Produto</fullName>
            </value>
            <value>
                <fullName>07-Representante/Vendedor</fullName>
            </value>
            <value>
                <fullName>08-Transportadora</fullName>
            </value>
            <value>
                <fullName>09-Planejamento Logístico</fullName>
            </value>
            <value>
                <fullName>11-Cliente</fullName>
            </value>
            <value>
                <fullName>12-Atendimento Amanco 0800</fullName>
            </value>
            <value>
                <fullName>14-Cadastro</fullName>
            </value>
            <value>
                <fullName>15-Fiscal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NonConformityTxt__c.field-meta.xml
<CustomField>
    <fullName>NonConformityTxt__c</fullName>
    <label>Não conformidade</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RegisterTxt__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>---Expedição</fullName>
            </value>
            <value>
                <fullName>0401-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0401-Produto faltante</fullName>
            </value>
            <value>
                <fullName>0402-Produto a mais</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado, diferente da NF</fullName>
            </value>
            <value>
                <fullName>0404-Volume com etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0405-Atraso no embarque</fullName>
            </value>
            <value>
                <fullName>0405-Pedido faturado sem inspeção</fullName>
            </value>
            <value>
                <fullName>0406-Agendamento não cumprido</fullName>
            </value>
            <value>
                <fullName>0407-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0408-Faturamento antecipado / Fechamento</fullName>
            </value>
            <value>
                <fullName>0408-Produto danificado no embarque</fullName>
            </value>
            <value>
                <fullName>0409-Demora no faturamento da remessa</fullName>
            </value>
            <value>
                <fullName>0409-SUSTAR DUPLICATA DA NF</fullName>
            </value>
            <value>
                <fullName>0411-Etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0412-Faturado sem estoque</fullName>
            </value>
            <value>
                <fullName>0414-Material Não Embarcou</fullName>
            </value>
            <value>
                <fullName>---Produto</fullName>
            </value>
            <value>
                <fullName>0601-Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>0601-Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>0601-Prazo de validade vencido.</fullName>
            </value>
            <value>
                <fullName>0602-Falta dentro emb prim</fullName>
            </value>
            <value>
                <fullName>0602-Prazo de validade vencido</fullName>
            </value>
            <value>
                <fullName>0602-Problema com a embalagem.</fullName>
            </value>
            <value>
                <fullName>0603-Problema com a embalagem</fullName>
            </value>
            <value>
                <fullName>0603-Produto com problema de fabricação.</fullName>
            </value>
            <value>
                <fullName>0604-Código de barras divergente.</fullName>
            </value>
            <value>
                <fullName>0604-Produto com problema de fabricação</fullName>
            </value>
            <value>
                <fullName>0605-Código de barras divergente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/VolumeNmb__c.field-meta.xml
<CustomField>
    <fullName>VolumeNmb__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/WeightNmb__c.field-meta.xml
<CustomField>
    <fullName>WeightNmb__c</fullName>
    <label>Peso</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CaseDAO.cls
public with sharing class CaseDAO {
	
	public static List<Case> getById(Set<Id> idSet) {
		return [SELECT 
					Id,
					ComplaintNatureTxt__c,
					NonConformityTxt__c ,
					OrderLkp__c,
					OrderLkp__r.VolumeNmb__c,
					OrderLkp__r.WeightNmb__c,
					Status,
					RecordTypeId
				FROM Case 
				WHERE Id IN :idSet];
	}
    
    public static Map<Id, Case> selectByIdSet(Set<Id> idSet)
    {
		Map<Id, Case> caseById = new Map<Id, Case>(
			[SELECT Id, RecordTypeId, Status, Type
			   FROM Case 
			  WHERE Id IN :idSet]);
		return caseById;
	}
}