force-app/main/default/objects/Case/fields/ComplaintNatureTxt__c.field-meta.xml
<CustomField>
    <fullName>ComplaintNatureTxt__c</fullName>
    <label>Natureza da reclamação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>04-Expedição</fullName>
            </value>
            <value>
                <fullName>06-Produto</fullName>
            </value>
            <value>
                <fullName>07-Representante/Vendedor</fullName>
            </value>
            <value>
                <fullName>08-Transportadora</fullName>
            </value>
            <value>
                <fullName>09-Planejamento Logístico</fullName>
            </value>
            <value>
                <fullName>11-Cliente</fullName>
            </value>
            <value>
                <fullName>12-Atendimento Amanco 0800</fullName>
            </value>
            <value>
                <fullName>14-Cadastro</fullName>
            </value>
            <value>
                <fullName>15-Fiscal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/NonConformityTxt__c.field-meta.xml
<CustomField>
    <fullName>NonConformityTxt__c</fullName>
    <label>Não conformidade</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RegisterTxt__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>---Expedição</fullName>
            </value>
            <value>
                <fullName>0401-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0401-Produto faltante</fullName>
            </value>
            <value>
                <fullName>0402-Produto a mais</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado, diferente da NF</fullName>
            </value>
            <value>
                <fullName>0404-Volume com etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0405-Atraso no embarque</fullName>
            </value>
            <value>
                <fullName>0405-Pedido faturado sem inspeção</fullName>
            </value>
            <value>
                <fullName>0406-Agendamento não cumprido</fullName>
            </value>
            <value>
                <fullName>0407-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0408-Faturamento antecipado / Fechamento</fullName>
            </value>
            <value>
                <fullName>0408-Produto danificado no embarque</fullName>
            </value>
            <value>
                <fullName>0409-Demora no faturamento da remessa</fullName>
            </value>
            <value>
                <fullName>0409-SUSTAR DUPLICATA DA NF</fullName>
            </value>
            <value>
                <fullName>0411-Etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0412-Faturado sem estoque</fullName>
            </value>
            <value>
                <fullName>0414-Material Não Embarcou</fullName>
            </value>
            <value>
                <fullName>---Produto</fullName>
            </value>
            <value>
                <fullName>0601-Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>0601-Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>0601-Prazo de validade vencido.</fullName>
            </value>
            <value>
                <fullName>0602-Falta dentro emb prim</fullName>
            </value>
            <value>
                <fullName>0602-Prazo de validade vencido</fullName>
            </value>
            <value>
                <fullName>0602-Problema com a embalagem.</fullName>
            </value>
            <value>
                <fullName>0603-Problema com a embalagem</fullName>
            </value>
            <value>
                <fullName>0603-Produto com problema de fabricação.</fullName>
            </value>
            <value>
                <fullName>0604-Código de barras divergente.</fullName>
            </value>
            <value>
                <fullName>0604-Produto com problema de fabricação</fullName>
            </value>
            <value>
                <fullName>0605-Código de barras divergente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Código organização de vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/ComplaintReasonTxt__c.field-meta.xml
<CustomField>
    <fullName>ComplaintReasonTxt__c</fullName>
    <label>Natureza da reclamação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>04-Expedição</fullName>
            </value>
            <value>
                <fullName>06-Produto</fullName>
            </value>
            <value>
                <fullName>07-Representante/Vendedor</fullName>
            </value>
            <value>
                <fullName>08-Transportadora</fullName>
            </value>
            <value>
                <fullName>09-Planejamento Logístico</fullName>
            </value>
            <value>
                <fullName>11-Cliente</fullName>
            </value>
            <value>
                <fullName>12-Atendimento Amanco 0800</fullName>
            </value>
            <value>
                <fullName>14-Cadastro</fullName>
            </value>
            <value>
                <fullName>15-Fiscal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/ManufacturingCenterTxt__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingCenterTxt__c</fullName>
    <label>Centro de fabricação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0100-SUMARE</fullName>
            </value>
            <value>
                <fullName>0300-UBERABA</fullName>
            </value>
            <value>
                <fullName>0600-CONEXOES</fullName>
            </value>
            <value>
                <fullName>0700-ACESSORIOS</fullName>
            </value>
            <value>
                <fullName>0850-AP.GOIANIA</fullName>
            </value>
            <value>
                <fullName>0870-ANAPOLIS</fullName>
            </value>
            <value>
                <fullName>0900-SUAPE</fullName>
            </value>
            <value>
                <fullName>BR10-MEXICHEM TRADING</fullName>
            </value>
            <value>
                <fullName>BR20-SUAPE TRADING</fullName>
            </value>
            <value>
                <fullName>BR30-BIDIM.</fullName>
            </value>
            <value>
                <fullName>BR31-PLASTUBOS MG</fullName>
            </value>
            <value>
                <fullName>BR33-PLASTUBOS AL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/NonConformityTxt__c.field-meta.xml
<CustomField>
    <fullName>NonConformityTxt__c</fullName>
    <label>Não conformidade</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTxt__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>---Expedição</fullName>
            </value>
            <value>
                <fullName>0401-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0401-Produto faltante</fullName>
            </value>
            <value>
                <fullName>0402-Produto a mais</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado</fullName>
            </value>
            <value>
                <fullName>0403-Produto trocado, diferente da NF</fullName>
            </value>
            <value>
                <fullName>0404-Volume com etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0405-Atraso no embarque</fullName>
            </value>
            <value>
                <fullName>0405-Pedido faturado sem inspeção</fullName>
            </value>
            <value>
                <fullName>0406-Agendamento não cumprido</fullName>
            </value>
            <value>
                <fullName>0407-Código de barras trocado</fullName>
            </value>
            <value>
                <fullName>0408-Faturamento antecipado / Fechamento</fullName>
            </value>
            <value>
                <fullName>0408-Produto danificado no embarque</fullName>
            </value>
            <value>
                <fullName>0409-Demora no faturamento da remessa</fullName>
            </value>
            <value>
                <fullName>0409-SUSTAR DUPLICATA DA NF</fullName>
            </value>
            <value>
                <fullName>0411-Etiqueta trocada</fullName>
            </value>
            <value>
                <fullName>0412-Faturado sem estoque</fullName>
            </value>
            <value>
                <fullName>0414-Material Não Embarcou</fullName>
            </value>
            <value>
                <fullName>---Produto</fullName>
            </value>
            <value>
                <fullName>0601-Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>0601-Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>0601-Prazo de validade vencido.</fullName>
            </value>
            <value>
                <fullName>0602-Falta dentro emb prim</fullName>
            </value>
            <value>
                <fullName>0602-Prazo de validade vencido</fullName>
            </value>
            <value>
                <fullName>0602-Problema com a embalagem.</fullName>
            </value>
            <value>
                <fullName>0603-Problema com a embalagem</fullName>
            </value>
            <value>
                <fullName>0603-Produto com problema de fabricação.</fullName>
            </value>
            <value>
                <fullName>0604-Código de barras divergente.</fullName>
            </value>
            <value>
                <fullName>0604-Produto com problema de fabricação</fullName>
            </value>
            <value>
                <fullName>0605-Código de barras divergente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/RecordTxt__c.field-meta.xml
<CustomField>
    <fullName>RecordTxt__c</fullName>
    <label>Registro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>Substituição</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QMCfgDefault.cls
public virtual class QMCfgDefault implements IQMConfigurator {
	
	public virtual String getRecordTypeDevName() {
		return null;
	}
	
	public virtual QM__c configure(QM__c qm, Case cse) {
		qm.CaseLkp__c = cse.Id;
		//qm.ManufacturingCenterTxt__c = cse.OrderLkp__r.CodeSalesOrganizationTxt__c;
		//qm.SellerLkp__c = cse.OrderLkp__r.SellerLkp__c;
		//qm.ClientOrderTxt__c = cse.OrderLkp__r.Name;
		//qm.ComplaintReasonTxt__c = cse.ComplaintNatureTxt__c;
		//qm.RecordTxt__c = cse.RecordTxt__c;
		//qm.NonConformityTxt__c = cse.NonConformityTxt__c;
		//qm.InvoiceLkp__c = cse.InvoiceLkp__c;
		return qm;
	}
    
}