force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/DevolutionOrderTxt__c.field-meta.xml
<CustomField>
    <fullName>DevolutionOrderTxt__c</fullName>
    <label>Ordem de devolução</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SinisterTxt__c.field-meta.xml
<CustomField>
    <fullName>SinisterTxt__c</fullName>
    <label>Sinistro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/TecnicianLkp__c.field-meta.xml
<CustomField>
    <fullName>TecnicianLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>[Case Id + Product Id]</description>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeTxt__c</fullName>
    <label>Código do Tipo de ordem</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nota fiscal</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Technician__c/Technician__c.object-meta.xml
<CustomObject>
    <description>[a0L][Technician__c] Técnicos utilizados pelo time de serviço técnico.</description>
    <label>Técnico</label>
    <nameField>
        <label>Nome de técnico</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Técnicos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateNewQMCtrl.cls
public with sharing class CreateNewQMCtrl {
    
    @AuraEnabled
    public static Case getcaso(Id caseId) {
        system.debug('caseId'+ caseId);      
        
        Case caso = [
            
            SELECT AccountId,ContactId,InvoiceLkp__c,OrderLkp__c,SellerLkp__c,TecnicianLkp__c,RecordTypeId,Status, CaseNumber,  SinisterTxt__c, DevolutionOrderTxt__c,
             InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id, TecnicianLkp__r.Name, RecordType.Name
            FROM Case
            WHERE Id = :caseId
        ];
        
           String [] caseaccessFields = new String [] {'InvoiceLkp__c','OrderLkp__c','SellerLkp__c','TecnicianLkp__c'
                       										   };
                // Obtain the field name/token map for the Expense object
        Map<String,Schema.SObjectField> m = Schema.SObjectType.Case.fields.getMap();
        for (String fieldToCheck : caseaccessFields) {
            // Check if the user has access to view field
            if (!m.get(fieldToCheck).getDescribe().isCreateable()) {
                // Pass error to client
                throw new System.NoAccessException();
                // Suppress editor logs
                return null;
            }
        }
        
        system.debug('caso' + caso);
        return caso;
        
    }
    
    @AuraEnabled
    public static QM__c getqm(Id caseId) {
        system.debug('caseId'+ caseId);
        List<QM__c> qm = [
            
            SELECT Id
            FROM QM__c
            WHERE CaseLkp__c = :caseId
            LIMIT 1
        ];
        
        system.debug('qm'+qm);
        if(qm.size()>0)
            return qm[0];
        else
            return null;   
        
    }
    
    @AuraEnabled
    public static Order__c getorder(Id caseId) {
        system.debug('caseId'+ caseId);
        List<Order__c> order = [
            
            SELECT Id,OrderTypeTxt__c, Name, SellerLkp__c, CustomIDTxt__c
            FROM Order__c
            WHERE CaseLkp__c = :caseId
            LIMIT 1
        ];
        
        system.debug('order'+ order);
        if(order.size()>0)
            return order[0];
        else
            return null;  
        
    }
    
    @AuraEnabled
    public static Order__c getorderdev (String namedev) {
        system.debug('namedev'+ namedev);
        List <Order__c> orderdev = [
            
            SELECT Id, Name, CustomIDTxt__c
            FROM Order__c
            WHERE Name = :namedev
            LIMIT 1
        ];
        
        system.debug('ordemdevolucao'+ orderdev);
        if(orderdev.size()>0)
            return orderdev[0];
        else
            return null;
        
    }
    
    @AuraEnabled
    public static CaseItem__c getcaseitem (Id caseId) {
        system.debug('caseId'+ caseId);
        List<CaseItem__c> caseitem = [
            
            SELECT Id, Name
            FROM CaseItem__c
            WHERE CaseMdt__c  = :caseId
            
        ];
        
        system.debug('caseitem'+caseitem);
        if(caseitem.size()>0)
            return caseitem[0];
        else
            return null;  
    }
    @AuraEnabled
    public static Order__c getorderNRO(String NRO) {
        system.debug('NRO'+ NRO);
        List<Order__c> orderNRO = [
            
            SELECT Id, Name, SellerLkp__c, CustomIDTxt__c
            FROM Order__c
            WHERE Id = :NRO
            LIMIT 1
        ];
        
        system.debug('orderNRO'+ orderNRO);
        if(orderNRO.size()>0)
            return orderNRO[0];
        else
            return null;  
        
    }
    
    @AuraEnabled
    public static List<RecordType> getqmrecordtype() {     
        List<RecordType> qmrecordtype = [
            SELECT Id, Name 
            FROM RecordType 
            WHERE SobjectType = 'QM__c' 
            AND IsActive = true
        ];
        system.debug('qmrecordtype'+ qmrecordtype);
        return qmrecordtype;
    }
    
}