force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/CommentsTxt__c.field-meta.xml
<CustomField>
    <fullName>CommentsTxt__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>[Case Id + Product Id]</description>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/FailureTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>FailureTypeTxt__c</fullName>
    <label>Tipo de avaria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Extravio de produto</fullName>
            </value>
            <value>
                <fullName>Produto faltante</fullName>
            </value>
            <value>
                <fullName>Negociação comercial</fullName>
            </value>
            <value>
                <fullName>Extravio de volume</fullName>
            </value>
            <value>
                <fullName>Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>Danificado dentro embalagem</fullName>
            </value>
            <value>
                <fullName>Deformação</fullName>
            </value>
            <value>
                <fullName>Desbitolamento</fullName>
            </value>
            <value>
                <fullName>Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>Embalagem danificada</fullName>
            </value>
            <value>
                <fullName>Embalagem errada</fullName>
            </value>
            <value>
                <fullName>Liga e não puxa agua</fullName>
            </value>
            <value>
                <fullName>Produto com problema fabricação</fullName>
            </value>
            <value>
                <fullName>Produto Danificado Expedição</fullName>
            </value>
            <value>
                <fullName>Produto danificado transporte</fullName>
            </value>
            <value>
                <fullName>Produto danificado cliente</fullName>
            </value>
            <value>
                <fullName>Produto amassado</fullName>
            </value>
            <value>
                <fullName>Produto com Vazamento</fullName>
            </value>
            <value>
                <fullName>Produto com Bolha</fullName>
            </value>
            <value>
                <fullName>Produto danificado</fullName>
            </value>
            <value>
                <fullName>Produto evaporou</fullName>
            </value>
            <value>
                <fullName>Produto furado</fullName>
            </value>
            <value>
                <fullName>Produto não aquece</fullName>
            </value>
            <value>
                <fullName>Produto não liga</fullName>
            </value>
            <value>
                <fullName>Produto quebrado</fullName>
            </value>
            <value>
                <fullName>Produto queimado</fullName>
            </value>
            <value>
                <fullName>Produto trincado</fullName>
            </value>
            <value>
                <fullName>Super Aquecimento</fullName>
            </value>
            <value>
                <fullName>Tubo sem marcação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QualityProblemTxt__c.field-meta.xml
<CustomField>
    <fullName>QualityProblemTxt__c</fullName>
    <label>Problemas de qualidade</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>QuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ItensCasoController.cls
public with sharing class ItensCasoController {
    
    public List<CaseItemVO> itemList {get; set;}
    public String CaseId {get; set;}
    public List<SelectOption> failureTypeList {get; set;}
    private ApexPages.StandardController controller;
    public ItensCasoBO itensCasoBO {get; set;}
    
    public Boolean ShowProdutoTrocado {get; set;}
    public Boolean ShowComments {get; set;}
    public Boolean ShowQualityProblem {get; set;}
    public Boolean canEditProduct {get;set;}
    public Boolean isReclamacao {get;set;}
    public Boolean isSubstituicao {get;set;}
    
    private String urlId {get;set;}
    private Case currentCase {get;set;}
    
    public ItensCasoController(ApexPages.StandardController controller) {
       this.controller = controller;
        getParams();
        initialize();
    }
    
    private void getParams() {
        currentCase = (Case)this.controller.getRecord();
        CaseId = currentCase.Id;
    }
    
    public void initialize() {      
        
        itensCasoBO = new itensCasoBO(CaseId);
        failureTypeList = itensCasoBO.getFailureOptions();
        ShowProdutoTrocado = itensCasoBO.getShowProdutoTrocado();
        ShowComments = itensCasoBO.getShowComments();
        ShowQualityProblem = itensCasoBO.getShowQualityProblem();
        canEditProduct = itensCasoBO.canEditProduct();
        isReclamacao = itensCasoBO.isReclamacao();
        isSubstituicao = itensCasoBO.isSubstituicao();
        itemList = itensCasoBO.loadCaseItemVO(CaseId);
    }

    public PageReference save() {
    	
        List<CaseItem__c> caseItemToUpsert = new List<CaseItem__c>();
        List<CaseItem__c> caseItemToDeleted = new List<CaseItem__c>();
        
        CaseItem__c caseItem;
        
        for(CaseItemVO item: itemList) {
            caseItem = updateCaseItem(item);
            if(item.Checked == true) {
            	caseItem.Id = null;
            	caseItemToUpsert.add(caseItem);
            } else {
                if(item.CaseItem.Id != null) {
                    /* Unchecked and existing CaseItem: Delete */
                    caseItemToDeleted.add(caseItem);
                }
            }
        }
        
		System.debug(LoggingLevel.FINEST, '*** save() caseItemToUpsert ' + caseItemToUpsert);
		System.debug(LoggingLevel.FINEST, '*** save() caseItemToDeleted ' + caseItemToDeleted);
        upsert caseItemToUpsert CustomIdTxt__c;
    	delete caseItemToDeleted;	
        
        refresh();
        
        // TODO redirect?
        //initialize();
        
        return doBack();
    }
    
    private CaseItem__c updateCaseItem (CaseItemVO itemVO) {
        Boolean isNew = false;
        CaseItem__c caseItem = itemVO.CaseItem;
        if(caseItem == null) {
            isNew = true;
            caseItem = new CaseItem__c();
        }
        
        //caseItem.QuantityNmb__c = itemVO.Quantity;
        caseItem.FailureTypeTxt__c = itemVO.FailureType;
        
        //todo refactor custom id to trigger's case
        caseItem.CustomIdTxt__c = CaseId + itemVO.CaseItem.ProductLkp__c;
        caseItem.QualityProblemTxt__c = itemVO.QualityProblem;
        caseItem.CommentsTxt__c = itemVO.Comments;

        if(isNew) { 
            caseItem.CaseMdt__c = CaseId;
            caseItem.ProductLkp__c = itemVO.CaseItem.ProductLkp__c;
        }
        
        return caseItem;
    }
    
    public void refresh() {
		System.debug(LoggingLevel.FINEST, '*** refresh()' + itemList);
    }
    
    public PageReference doBack() {
    	PageReference page;
        page = new PageReference('/' + CaseId); 
        page.setRedirect(true); 
        
 		return page;
    }
    
}