force-app/main/default/objects/Case/fields/DataCollectionAdditionalTxt__c.field-meta.xml
<CustomField>
    <fullName>DataCollectionAdditionalTxt__c</fullName>
    <label>Dados adicionais coleta</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceCustomerDevolutionTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCustomerDevolutionTxt__c</fullName>
    <label>Nota fiscal devolução cliente</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/VolumeNmb__c.field-meta.xml
<CustomField>
    <fullName>VolumeNmb__c</fullName>
    <label>Volume</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/WeightNmb__c.field-meta.xml
<CustomField>
    <fullName>WeightNmb__c</fullName>
    <label>Peso</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/AditionalDataTxt__c.field-meta.xml
<CustomField>
    <fullName>AditionalDataTxt__c</fullName>
    <label>Dados adicionais coleta</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/GrossWeightNmb__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightNmb__c</fullName>
    <label>Peso bruto</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/NumberClientInvoiceTxt__c.field-meta.xml
<CustomField>
    <fullName>NumberClientInvoiceTxt__c</fullName>
    <label>Número nota fiscal cliente</label>
    <length>9</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/VolumeNmb__c.field-meta.xml
<CustomField>
    <fullName>VolumeNmb__c</fullName>
    <label>Volume</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QM__c/recordTypes/QMReposicaoItemII.recordType-meta.xml
<RecordType>
    <fullName>QMReposicaoItemII</fullName>
    <active>true</active>
    <description>QM aberta a partir do caso de reposição em que o problema é com item e Ordem de reposição criada.</description>
    <label>Reposição por item ZREP</label>
</RecordType>

force-app/main/default/classes/QMCfgReposicaoItemII.cls
public virtual class QMCfgReposicaoItemII extends QMCfgDefault {

	public override String getRecordTypeDevName() {
		return 'QMReposicaoItemII';
	}
	
	public override QM__c configure(QM__c qm, Case cse) {
		qm = super.configure(qm, cse);
		//qm.AditionalDataTxt__c = cse.DataCollectionAdditionalTxt__c;
		//qm.NumberClientInvoiceTxt__c = cse.InvoiceCustomerDevolutionTxt__c;
		//qm.VolumeNmb__c = cse.OrderLkp__r.VolumeNmb__c;
		//qm.GrossWeightNmb__c = cse.OrderLkp__r.WeightNmb__c;
		return qm;
	}
    
}