force-app/main/default/objects/Case/fields/DeliveryDateInvoiceCreatedDte__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDateInvoiceCreatedDte__c</fullName>
    <label>Data de entrega NF criada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DeliveryDateInvoiceReplacementDte__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDateInvoiceReplacementDte__c</fullName>
    <label>Data de entrega NF substituição</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/DevolutionOrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>DevolutionOrderStatusTxt__c</fullName>
    <label>Status da ordem de devolução</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceCreatedTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceCreatedTxt__c</fullName>
    <label>Nota fiscal criada</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceReplacementTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceReplacementTxt__c</fullName>
    <label>Nota fiscal de substituição</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderDevolutionStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderDevolutionStatusTxt__c</fullName>
    <label>Status ordem criada</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipmentDeliveredFml__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDeliveredFml__c</fullName>
    <formula>InvoiceLkp__r.ShipmentDeliveredFml__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data de entrega</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/SinisterTxt__c.field-meta.xml
<CustomField>
    <fullName>SinisterTxt__c</fullName>
    <label>Sinistro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ExtravioNotaFiscal.recordType-meta.xml
<RecordType>
    <fullName>ExtravioNotaFiscal</fullName>
    <active>true</active>
    <businessProcess>SAC Extravio de nota fiscal</businessProcess>
    <description>Abertura caso extravio de nota fiscal</description>
    <label>Extravio de nota fiscal</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ProdutoTrocado.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTrocado</fullName>
    <active>true</active>
    <businessProcess>SAC Produto trocado</businessProcess>
    <description>Abertura de caso tipo produto trocado</description>
    <label>Produto trocado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Refaturamento.recordType-meta.xml
<RecordType>
    <fullName>Refaturamento</fullName>
    <active>true</active>
    <businessProcess>SAC Refaturamento</businessProcess>
    <description>Abertura de caso refaturamento</description>
    <label>Refaturamento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicao.recordType-meta.xml
<RecordType>
    <fullName>Reposicao</fullName>
    <active>true</active>
    <businessProcess>SAC Reposição</businessProcess>
    <description>Abertura de reposição de volume ou item</description>
    <label>Reposição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sinistro.recordType-meta.xml
<RecordType>
    <fullName>Sinistro</fullName>
    <active>true</active>
    <businessProcess>SAC Sinistro</businessProcess>
    <description>Abertura de caso onde houve sinistro</description>
    <label>Sinistro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Substituicao.recordType-meta.xml
<RecordType>
    <fullName>Substituicao</fullName>
    <active>true</active>
    <businessProcess>SAC Substituição</businessProcess>
    <description>Abertura de substituição de produto</description>
    <label>Substituição</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ShipmentDeliveredFml__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDeliveredFml__c</fullName>
    <formula>RemittanceLkp__r.ShipmentDeliveredDte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercadoria entregue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/RMTRemittanceBO.cls
public with sharing class RMTRemittanceBO {
    
    public void verifyAndSetInvoiceToCase(Set<id> rmtIdSet) {
        system.debug('verifica invoice:: ');
    	
        String profileName = getProfile(); 
        if(profileName != 'Administrador do sistema' && profileName != 'Interface Salesforce') {
            return;
        }

        Set<Case> caseToUpdateSet = new Set<Case>();

        // Retrieving remittance objects.
    	RMTRemittanceSelector remittanceSelector = new RMTRemittanceSelector();
    	List<Remittance__c> remittanceList = remittanceSelector.selectById(rmtIdSet);
    	
        // Retrieving other objects related to remittence.
        Map<Id, Invoice__c> invoiceMap = getInvoiceMap(remittanceList);
    	Map<String, Id> recordMap = RecordTypeDAO.getRecordTypeMap('Case');
        List<Order__c> orderList = getOrderList(remittanceList);
        Map<Id, Case> caseMap = getCaseMap(orderList);

        // Parsing quantity of QMs per case. Used only when Produto trocado needs to be updated.
        Map<String, Integer> qmQuantityPerCase = getQmQuantityPerCase(orderList, caseMap, recordMap);

        for(Remittance__c remittance : remittanceList) {

            // Validating the existence of the remittance's order.
            if(remittance.OrderLkp__c == null) {

                continue;
            }

            // Validating the existence of the order's case.
            if(remittance.OrderLkp__r.CaseLkp__c == null) {

                continue;
            }

            // Validating the order's case status.
            if(remittance.OrderLkp__r.CaseLkp__r.Status.equals('Cancelado') ||
               remittance.OrderLkp__r.CaseLkp__r.Status.equals('Encerrado')) {

                continue;
            }

            // Storing record type Id of the case.
            String recordTypeId = remittance.OrderLkp__r.CaseLkp__r.RecordTypeId;

            // Storing the current case of the remittance.
            Case currentCase = caseMap.get(remittance.OrderLkp__r.CaseLkp__c);
	System.debug('OLHA AQUI: '+currentCase);
            // Validating the existence of the remittance's invoice.
            Invoice__c invoice = invoiceMap.get(remittance.Id);
            if(invoice == null) { continue; }

            if(recordTypeId.equals(recordMap.get('Reposicao')) ||
               recordTypeId.equals(recordMap.get('ExtravioNotaFiscal'))) {

                currentCase.InvoiceCreatedTxt__c = invoice.Name;
                currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                if(invoice.ShipmentDeliveredFml__c != null && currentCase.Status != 'Aguardando encerramento') {
                            
                    currentCase.Status = 'Aguardando encerramento';
                }

                caseToUpdateSet.add(currentCase);
            }
            else if(recordTypeId.equals(recordMap.get('Sinistro'))) {

                currentCase.InvoiceCreatedTxt__c = invoice.Name;
                currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                if(currentCase.SinisterTxt__c.equals('Total')) {
                            
                    currentCase.InvoiceCreatedTxt__c = invoice.Name;
                    currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                            
                    if((invoice.ShipmentDeliveredFml__c != null) &&
                       (currentCase.Status != 'Aguardando encerramento')) {
                                
                       currentCase.Status = 'Aguardando encerramento';
                    }                         
                } 
                else if(currentCase.SinisterTxt__c.equals('Parcial')) {
                            
                    currentCase.InvoiceCreatedTxt__c = invoice.Name;
                    currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                            
                    if((invoice.ShipmentDeliveredFml__c != null) &&
                       (currentCase.Status != 'Aguardando encerramento') &&
                       (currentCase.OrderDevolutionStatusTxt__c.equals('Processado completamente'))) {
                                
                        currentCase.Status = 'Aguardando encerramento';     
                    }
                }

                caseToUpdateSet.add(currentCase);
            }
            else if(recordTypeId.equals(recordMap.get('Refaturamento'))) {
			 //RSILVA 11/01/2018 - LINHAS DUPLICADAS COMENTADAS 
             //   currentCase.InvoiceCreatedTxt__c = invoice.Name;
             //   currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                currentCase.InvoiceCreatedTxt__c = invoice.Name;
                currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                if((invoice.ShipmentDeliveredFml__c != null) &&
                   (currentCase.Status != 'Aguardando encerramento') &&
                   (currentCase.OrderDevolutionStatusTxt__c.equals('Processado completamente'))){
                        
                    currentCase.Status = 'Aguardando encerramento';
                }
                                            
                caseToUpdateSet.add(currentCase);
            }
            else if(recordTypeId.equals(recordMap.get('Substituicao'))) {
				//RSILVA 10/01/2018 - LINHAS DUPLICADAS COMENTADAS 
                //currentCase.InvoiceCreatedTxt__c = invoice.Name;
                //currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                currentCase.InvoiceCreatedTxt__c = invoice.Name;
                currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                        
                if((invoice.ShipmentDeliveredFml__c != null) &&
                   (currentCase.Status != 'Aguardando encerramento') &&
                   (currentCase.OrderDevolutionStatusTxt__c != null) &&
                   (currentCase.OrderDevolutionStatusTxt__c.equals('Processado completamente'))) {
                            
                     currentCase.Status = 'Aguardando encerramento';
                }
                                            
                caseToUpdateSet.add(currentCase);
            }
            else if(recordTypeId.equals(recordMap.get('ProdutoTrocado'))) {

                if(currentCase.Type.equals('Quantidades iguais')) {
                            
                    currentCase.InvoiceReplacementTxt__c = invoice.Name;
                    currentCase.DeliveryDateInvoiceReplacementDte__c = invoice.ShipmentDeliveredFml__c;
                
                    if((invoice.ShipmentDeliveredFml__c != null) &&
                       (currentCase.Status != 'Aguardando encerramento') &&
                       (currentCase.DevolutionOrderStatusTxt__c!= null) &&
                       (currentCase.DevolutionOrderStatusTxt__c.equals('Processado completamente'))) {
                  
                            currentCase.Status = 'Aguardando encerramento';
                        }
                }
                else if(currentCase.Type.equals('Quantidades diferentes')) {

                    currentCase.InvoiceCreatedTxt__c = invoice.Name;
                    currentCase.DeliveryDateInvoiceCreatedDte__c = invoice.ShipmentDeliveredFml__c;
                            
                    // Rotina para avançar o status do caso para “Aguardando encerramento”.
                    if(CSEOrderBO.checkForAwaitingClosure(currentCase, qmQuantityPerCase)) {

                        currentCase.Status = 'Aguardando encerramento';
                    }
                }

                caseToUpdateSet.add(currentCase);
            }
        }

        // Updating all necessary cases.
        update new List<Case>(caseToUpdateSet);
    }

    //get profle from current user
    private String getProfile() {
        Id profId = UserInfo.getProfileId();
        Profile profile = ProfileDAO.getNameFromId(profId);
        return profile.Name;
    }

    // Retrives all invoices related to every remittance.
    private Map<Id, Invoice__c> getInvoiceMap(List<Remittance__c> remittanceList) {

        CSEInvoiceSelector invoiceSelector = new CSEInvoiceSelector();
        Set<Id> remittanceIdSet = new Set<Id>();
        Map<Id, Invoice__c> invoiceMap = new Map<Id, Invoice__c>();

        for(Remittance__c remittance : remittanceList) {

            remittanceIdSet.add(remittance.Id);
        }

        List<Invoice__c> invoiceList = invoiceSelector.selectByRemittanceId2(remittanceIdSet);

        for(Invoice__c invoice : invoiceList) {

            invoiceMap.put(invoice.RemittanceLkp__c, invoice);
        }

        return invoiceMap;
    }

    // Retrives all orders related to every remittance.
    private List<Order__c> getOrderList(List<Remittance__c> remittanceList) {

        Set<Id> orderIdSet = new Set<Id>();
        List<Order__c> orderList = new List<Order__c>();

        for (Remittance__c remittance : remittanceList) {

            orderIdSet.add(remittance.OrderLkp__c);
        }

        orderList = [SELECT CaseLkp__c FROM Order__c WHERE Id IN :orderIdSet];

        return orderList;
    }

    // Retrives all cases related to every order.
    private Map<Id, Case> getCaseMap(List<Order__c> orderList) {

        CSECaseSelector caseSelector = new CSECaseSelector();

        Set<Id> caseIdSet = new Set<Id>();
        Map<Id, Case> caseMap = new Map<Id, Case>();
    
        for(Order__c ordem : orderList) {
            caseIdSet.add(ordem.CaseLkp__c);
        }

        List<Case> caseList = caseSelector.selectById(caseIdSet);
        caseMap = new Map<Id, Case>(caseList);

        return caseMap;
    }

    // Retrives quantity of QMs per case.
    private Map<String, Integer> getQmQuantityPerCase(List<Order__c> orderList, Map<Id, Case> caseMap, Map<String, Id> recordMap) {
        
        Map<String, Integer> qmMap = new Map<String, Integer>();
        
        /* Validando parâmetros */
        if((orderList == null) || (caseMap == null) || (recordMap == null)) { return qmMap; }
        
        Set<Id> idSetCase = new Set<Id>();
        for(Order__c ordem : orderList) {

            if(ordem.CaseLkp__c == null) { continue; }

            Case currentCase = caseMap.get(ordem.CaseLkp__c);
            
            if(currentCase == null) { continue; }
            
            if (currentCase.RecordTypeId == recordMap.get('Produto trocado') &&
                currentCase.Type.equals('Quantidades diferentes')) {
                
                idSetCase.add(ordem.CaseLkp__c);
            }
        }

        List<QM__c> qmList = QMDAO.getByCaseId(idSetCase);
        
        if (qmList == null) { return qmMap; }

        /* Levantando QMs distintas */
        for(QM__c qm : qmList) {

            if(qmMap.get(qm.CaseLkp__c) == null) {

                qmMap.put(qm.CaseLkp__c, 0);
            }
        }

        /* Contando numero de QMs por caso */
        for(QM__c qm : qmList) {

            qmMap.put(qm.CaseLkp__c, qmMap.get(qm.CaseLkp__c) + 1);
        }

        return qmMap;
    }
}