force-app/main/default/objects/Case/fields/FinishDateDte__c.field-meta.xml
<CustomField>
    <fullName>FinishDateDte__c</fullName>
    <label>Finalização desejada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderNumberTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderNumberTxt__c</fullName>
    <label>Número de ordem</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/OriginTxt__c.field-meta.xml
<CustomField>
    <fullName>OriginTxt__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Fiscal</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Logística</fullName>
            </value>
            <value>
                <fullName>Expedição</fullName>
            </value>
            <value>
                <fullName>Roteirização</fullName>
            </value>
            <value>
                <fullName>Faturamento</fullName>
            </value>
            <value>
                <fullName>Contratação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/PriorityTxt__c.field-meta.xml
<CustomField>
    <fullName>PriorityTxt__c</fullName>
    <label>Prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Médio</fullName>
            </value>
            <value>
                <fullName>Alta</fullName>
            </value>
            <value>
                <fullName>Baixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/StartDateDte__c.field-meta.xml
<CustomField>
    <fullName>StartDateDte__c</fullName>
    <label>Inicio desejado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/TecnicianLkp__c.field-meta.xml
<CustomField>
    <fullName>TecnicianLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/AccountIssuerLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountIssuerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Emissor da ordem</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/FinishDateDte__c.field-meta.xml
<CustomField>
    <fullName>FinishDateDte__c</fullName>
    <label>Finalização desejada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/ManufacturingCenterTxt__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingCenterTxt__c</fullName>
    <label>Centro de fabricação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0100-SUMARE</fullName>
            </value>
            <value>
                <fullName>0300-UBERABA</fullName>
            </value>
            <value>
                <fullName>0600-CONEXOES</fullName>
            </value>
            <value>
                <fullName>0700-ACESSORIOS</fullName>
            </value>
            <value>
                <fullName>0850-AP.GOIANIA</fullName>
            </value>
            <value>
                <fullName>0870-ANAPOLIS</fullName>
            </value>
            <value>
                <fullName>0900-SUAPE</fullName>
            </value>
            <value>
                <fullName>BR10-MEXICHEM TRADING</fullName>
            </value>
            <value>
                <fullName>BR20-SUAPE TRADING</fullName>
            </value>
            <value>
                <fullName>BR30-BIDIM.</fullName>
            </value>
            <value>
                <fullName>BR31-PLASTUBOS MG</fullName>
            </value>
            <value>
                <fullName>BR33-PLASTUBOS AL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/OrderNumberTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderNumberTxt__c</fullName>
    <label>Número de ordem</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/OriginTxt__c.field-meta.xml
<CustomField>
    <fullName>OriginTxt__c</fullName>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0800</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>Reclame aqui</fullName>
            </value>
            <value>
                <fullName>Agente campo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/PriorityTxt__c.field-meta.xml
<CustomField>
    <fullName>PriorityTxt__c</fullName>
    <label>Prioridade</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Baixa</fullName>
            </value>
            <value>
                <fullName>1-Muito alta</fullName>
            </value>
            <value>
                <fullName>2-Alta</fullName>
            </value>
            <value>
                <fullName>3-Média</fullName>
            </value>
            <value>
                <fullName>4-Baixa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QM__c/fields/StartDateDte__c.field-meta.xml
<CustomField>
    <fullName>StartDateDte__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Inicio desejado</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/TechnicianLkp__c.field-meta.xml
<CustomField>
    <fullName>TechnicianLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Técnico</label>
    <referenceTo>Technician__c</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/recordTypes/QMReclamacao.recordType-meta.xml
<RecordType>
    <fullName>QMReclamacao</fullName>
    <active>true</active>
    <description>QM utilizada pelo time de serviço técnico.</description>
    <label>Reclamação</label>
</RecordType>

force-app/main/default/classes/QMCfgReclamacao.cls
public with sharing class QMCfgReclamacao extends QMCfgDefault {
	
	public override String getRecordTypeDevName() {
		return 'QMReclamacao';
	}

	public override QM__c configure(QM__c qm, Case cse) {
		qm = super.configure(qm, cse);
		//qm.TechnicianLkp__c = cse.TecnicianLkp__c;
		//qm.OrderNumberTxt__c = cse.OrderNumberTxt__c;
		//qm.OriginTxt__c = cse.Origin;
		//qm.AccountIssuerLkp__c = cse.AccountIssuerLkp__c;
		//qm.ProductLkp__c = cse.CaseItem__r.ProductLkp__c;
		//qm.ManufacturingCenterTxt__c = cse.CaseItem__r.ManufacturingCenterTxt__c;
		//qm.QuantityNmb__c = cse.CaseItem__r.QuantityNmb__c;
		//qm.PriorityTxt__c = cse.Priority;
		//qm.StartDateDte__c = cse.StartDateDte__c;  
		//qm.FinishDateDte__c = cse.StartFinishDte__c;
		//qm.CoordinatorTxt__c = cse.CoordinatorTxt__c;
		//qm.ProductSalesOrganizationTxt__c = cse.CaseItem__r.ProductSalesOrganizationTxt__c;
		//qm.ProductDistributionChannelTxt__c = cse.CaseItem__r.ProductDistributionChannelTxt__c; 
		//qm.ProductActivitySectorTxt__c = cse.CaseItem__r.ProductActivitySectorTxt__c; 
		//qm.ProductSalesOfficeTxt__c = cse.CaseItem__r.ProductSalesOfficeTxt__c; 
		//qm.ProductSalesTeamTxt__c = cse.CaseItem__r.ProductSalesTeamTxt__c; 
		return qm;
	}
    
}