force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderDateDte__c.field-meta.xml
<CustomField>
    <fullName>OrderDateDte__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Data pedido</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DAO_Case.cls
/*
    Classe de DAO para objeto Case
    
    Dev: Renata
    Data: 24/01/2017
    =====================================
    Alteração: alteração do método getOrdersIdInCase() para retornar ordens que estão abertos ou fechadas do tipo 'Reclamação' ou 'Substituição'
    Dev: Carlos Diogo de Oliveira
    Data: 03/02/2017
*/
public class DAO_Case {
  
    public static Set<Id> getOrdersIdInCase() {
        List<Case> casos =  [SELECT Id
                                  , OrderLkp__r.Id
                                  , InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id 
                                  , isClosed
                                  , RecordType.Name
                                  , (SELECT Id FROM Ordens__r)
                             FROM Case 
                             WHERE (OrderLkp__c != null OR InvoiceLkp__c != null)];
                      
        Set<Id> ids = new Set<Id>();
        for (Case caso : casos){
            if ((caso.OrderLkp__r.Id != null 
                && !caso.isClosed)
                || (caso.isClosed && (caso.RecordType.Name == 'Reclamação' || caso.RecordType.Name == 'Substituição'))){
                ids.add(caso.OrderLkp__r.Id);
                    
                for(Order__c ordem: caso.Ordens__r){
                    ids.add(ordem.Id);
                }    
            }
            if ((caso.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id != null 
                && !caso.isClosed)
                || (caso.isClosed && (caso.RecordType.Name == 'Reclamação' || caso.RecordType.Name == 'Substituição'))){
                ids.add(caso.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id);
                    
                for(Order__c ordem: caso.Ordens__r){
                    ids.add(ordem.Id);
                }    
            }
        }
        return ids;
    }
    
    
    public static Set<Id> getOrdersIdInCaseLast30DAYS(){
        List<Case> casos =  [SELECT Id
                                , OrderLkp__r.Id
                                , InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id
                                , isClosed
                            FROM Case
                            WHERE (OrderLkp__c != null OR InvoiceLkp__c != null)
                                OR (OrderLkp__r.OrderDateDte__c = LAST_N_DAYS:30 
                                OR InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.OrderDateDte__c = LAST_N_DAYS:30)];
        
        Set<Id> ordersId = new Set<Id>(); 
        for (Case caso : casos){
            if (caso.OrderLkp__r.Id != null){
                ordersId.add(caso.OrderLkp__r.Id);
            }
            if (caso.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id != null) {
                if (!caso.isClosed){
                    ordersId.add(caso.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id);
                }   
            }
            
        }
        return ordersId;
    }
   
}