force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderDateDte__c.field-meta.xml
<CustomField>
    <fullName>OrderDateDte__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Data pedido</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PurgeOrderBatch.cls
global class PurgeOrderBatch implements Database.Batchable<sObject> {
	
	global Database.QueryLocator start(Database.BatchableContext BC) {

		List<Case> caseList = new List<Case>();
		Set<Id> orderIdSet = new Set<Id>();

		//selecting cases that are related to invoices or orders
		//or the order date was in the last 30 days
		caseList = [SELECT Id, OrderLkp__r.Id, InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id 
						FROM Case
							WHERE (OrderLkp__c != null OR InvoiceLkp__c != null)
							OR (OrderLkp__r.OrderDateDte__c = LAST_N_DAYS:30 OR InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.OrderDateDte__c = LAST_N_DAYS:30)
					];

		for (Case cse : caseList) {
			if (cse.OrderLkp__r != null) {	
				orderIdSet.add(cse.OrderLkp__r.Id);				
			} else if (cse.InvoiceLkp__r != null) {
				if (cse.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r != null) {					
					orderIdSet.add(cse.InvoiceLkp__r.RemittanceLkp__r.OrderLkp__r.Id);
				}
			}
		}

		return Database.getQueryLocator([
											SELECT Id, CaseLkp__c, OrderDateDte__c,  (SELECT Id FROM Remessas__r), 
												(SELECT Id FROM Notas_fiscais__r)
												FROM Order__c
												WHERE Id NOT IN: orderIdSet
												AND CaseLkp__c = null
												AND OrderDateDte__c < LAST_N_DAYS:30
										]);

	}

   	global void execute(Database.BatchableContext BC, List<Order__c> orderList) {

		List<Order__c> orderToDelete = new List<Order__c>();
		List<Remittance__c> shippingToDelete = new List<Remittance__c>();
		List<Invoice__c> invoiceToDelete = new List<SObject>();
		
		for(Order__c ord : orderList){
			orderToDelete.add(ord);
			shippingToDelete.addAll(ord.Remessas__r);
			invoiceToDelete.addAll(ord.Notas_fiscais__r);
		}

		Database.delete(invoiceToDelete);
		Database.delete(shippingToDelete);
		Database.delete(orderToDelete);

	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}