force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipmentDateDte__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDateDte__c</fullName>
    <label>Data de embarque</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Case/fields/ShipmentDeliveredDte__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDeliveredDte__c</fullName>
    <label>Mercadoria entregue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/DaysDueNmb__c.field-meta.xml
<CustomField>
    <fullName>DaysDueNmb__c</fullName>
    <label>Dias em atraso</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/DeliveryDateDte__c.field-meta.xml
<CustomField>
    <fullName>DeliveryDateDte__c</fullName>
    <label>Mercadoria entregue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nota fiscal</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/ShipmentDateDte__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDateDte__c</fullName>
    <label>Mercadoria embarcada</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/QM__c/recordTypes/QMProrrocacao.recordType-meta.xml
<RecordType>
    <fullName>QMProrrocacao</fullName>
    <active>true</active>
    <description>QM de prorrogação por atraso de entrega ou embarque.</description>
    <label>Prorrogação</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QMCFGProrrogacao.cls
public with sharing class QMCFGProrrogacao extends QMCfgDefault {

	public override String getRecordTypeDevName() {
		return 'QMProrrocacao';
	}
	
	public override QM__c configure(QM__c qm, Case cse) {
		qm = super.configure(qm, cse);
		//qm.ShipmentDateDte__c = cse.InvoiceLkp__r.RemittanceLkp__r.ShipmentTransitDte__c;
		//qm.DeliveryDateDte__c = cse.InvoiceLkp__r.RemittanceLkp__r.ShipmentDeliveredDte__c;
		//qm.DaysDueNmb__c = cse.InvoiceLkp__r.DaysDueNmb__c; 
		return qm;
	}
    
}