force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/DocumentDateDte__c.field-meta.xml
<CustomField>
    <fullName>DocumentDateDte__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Batch_Invoice.cls
/*
    Rotinas de limpeza:
    PurgeOrderItemSchedule + PurgeOrderItemBatch
    PurgeOrderSchedule + PurgeOrderBatch
    PurgeInvoiceSchedule + Batch_Invoice
    PurgeOrderRemittanceSchedule + PurgeOrderRemittanceBatch

    Data: 23/01/2017
    Dev: Renata
    Caso: 00025639
    Objetivo: Excluir as notas fiscais que não tem relacionamento com ordens nem casos
*/
global class Batch_Invoice implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator([SELECT Id 
                                        FROM Invoice__c 
                                        WHERE OrderLkp__c = null 
                                            AND DocumentDateDte__c < LAST_N_DAYS:30
                                            AND Id NOT IN (SELECT InvoiceLkp__c FROM Case) ]);
    }

    global void execute(Database.BatchableContext BC, List<Invoice__c> invoiceList) {
        System.debug(invoiceList.size());
        
        Database.delete(invoiceList);

    }
    
    global void finish(Database.BatchableContext BC) {
     
    }
    
}