force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/CommentsTxt__c.field-meta.xml
<CustomField>
    <fullName>CommentsTxt__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/FailureTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>FailureTypeTxt__c</fullName>
    <label>Tipo de avaria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Extravio de produto</fullName>
            </value>
            <value>
                <fullName>Produto faltante</fullName>
            </value>
            <value>
                <fullName>Negociação comercial</fullName>
            </value>
            <value>
                <fullName>Extravio de volume</fullName>
            </value>
            <value>
                <fullName>Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>Danificado dentro embalagem</fullName>
            </value>
            <value>
                <fullName>Deformação</fullName>
            </value>
            <value>
                <fullName>Desbitolamento</fullName>
            </value>
            <value>
                <fullName>Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>Embalagem danificada</fullName>
            </value>
            <value>
                <fullName>Embalagem errada</fullName>
            </value>
            <value>
                <fullName>Liga e não puxa agua</fullName>
            </value>
            <value>
                <fullName>Produto com problema fabricação</fullName>
            </value>
            <value>
                <fullName>Produto Danificado Expedição</fullName>
            </value>
            <value>
                <fullName>Produto danificado transporte</fullName>
            </value>
            <value>
                <fullName>Produto danificado cliente</fullName>
            </value>
            <value>
                <fullName>Produto amassado</fullName>
            </value>
            <value>
                <fullName>Produto com Vazamento</fullName>
            </value>
            <value>
                <fullName>Produto com Bolha</fullName>
            </value>
            <value>
                <fullName>Produto danificado</fullName>
            </value>
            <value>
                <fullName>Produto evaporou</fullName>
            </value>
            <value>
                <fullName>Produto furado</fullName>
            </value>
            <value>
                <fullName>Produto não aquece</fullName>
            </value>
            <value>
                <fullName>Produto não liga</fullName>
            </value>
            <value>
                <fullName>Produto quebrado</fullName>
            </value>
            <value>
                <fullName>Produto queimado</fullName>
            </value>
            <value>
                <fullName>Produto trincado</fullName>
            </value>
            <value>
                <fullName>Super Aquecimento</fullName>
            </value>
            <value>
                <fullName>Tubo sem marcação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QualityProblemTxt__c.field-meta.xml
<CustomField>
    <fullName>QualityProblemTxt__c</fullName>
    <label>Problemas de qualidade</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>QuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>Itens_da_nota_fiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/QuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>QuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/OfflinePrices__c.object-meta.xml
<CustomObject>
    <description>Tabela de preços do Offline</description>
    <label>Preços Offline</label>
    <nameField>
        <label>Nome de Preços Offline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Offline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfflinePrices__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Preços Offline</relationshipLabel>
    <relationshipName>ProductLkp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ItensCasoBO.cls
public with sharing class ItensCasoBO {
	
    public String CaseId {get; set;}
    public String Tipo {get; set;}
    public String Registro {get; set;}
    
    public String Comments {get; set;}
    public String QualityProblem {get; set;}
    
    private static final String REG_REPOSICAO = 'Reposição';
    private static final String REG_DEVOLUCAO = 'Devolução';
    private static final String REG_SUBSTITUICAO = 'Substituição';
    private static final String REG_PRODUTOTROCADO = 'Produto trocado';
    private static final String REG_RECLAMACAO = 'Reclamação';
    
    private static final String TIPO_ITEM = 'Item';
    private static final String TIPO_VOLUME = 'Volume';
    
    private static final String FAILURE_FALTANTE = 'Produto faltante';
    private static final String FAILURE_EXTRAVIO = 'Extravio de volume';
    private static final String FAILURE_NEGOCIACAO = 'Negociação comercial';
    
    public ItensCasoBO(String CaseId) {
    	this.CaseId = CaseId;
    	loadTipoRegistro(CaseId);
    }
    
    private void loadTipoRegistro(String caseId) {
    	CSECaseSelector caseSelector = new CSECaseSelector();
    	
    	Set<Id> caseIdSet = new Set<Id>();
    	caseIdSet.add(caseId);
    	List<Case> caseList = caseSelector.selectById(caseIdSet);
    	
    	if(caseList != null && !caseList.isEmpty()) {
    		Tipo = caseList[0].Type;
    		Registro = loadRegistro(caseList[0]);
    	} else {
    		Tipo = '';
    		Registro = '';
    	}
    }
    
    private String loadRegistro(Case caseObj) {
    	
    	CSERecordTypeSelector recordTypeSelector = new CSERecordTypeSelector();
    	
    	Set<Id> recordTypeIdSet = new Set<Id>();
		recordTypeIdSet.add(caseObj.RecordTypeId);
		List<RecordType> recordTypeList = recordTypeSelector.selectById(recordTypeIdSet);
		
		if(recordTypeList != null && !recordTypeList.isEmpty()) {
			return recordTypeList[0].Name;
		} else {
			return '';
		}
		
    }

    public Boolean isReclamacao() {
    	return Registro == REG_RECLAMACAO;
    }

	public Boolean isSubstituicao() {
		return Registro == REG_SUBSTITUICAO;
	}

    public Boolean canEditProduct() {
    	return Registro == REG_RECLAMACAO;
    }
    
    public Boolean getShowProdutoTrocado() {
    	return Registro == REG_PRODUTOTROCADO;
    }
    
    public Boolean getShowComments() {
    	return (registro == REG_SUBSTITUICAO) || (registro == REG_RECLAMACAO);
    }
    
    public Boolean getShowQualityProblem() {
    	return false;//registro == REG_SUBSTITUICAO;
    }
    
    public List<SelectOption> getFailureOptions() {
    	return getFailureOptions(Tipo, Registro);
    }
    
    private List<SelectOption> getFailureOptions(String tipo, String registro) {
    	List<SelectOption> options = new List<SelectOption>();
    	if (registro == REG_DEVOLUCAO) {
				options.add(new SelectOption(FAILURE_FALTANTE, FAILURE_FALTANTE));
				options.add(new SelectOption(FAILURE_NEGOCIACAO, FAILURE_NEGOCIACAO));
				options.add(new SelectOption(FAILURE_EXTRAVIO, FAILURE_EXTRAVIO));
    	} else if(registro == REG_REPOSICAO) {
			if(tipo == TIPO_ITEM) {
				options.add(new SelectOption(FAILURE_FALTANTE, FAILURE_FALTANTE));
				options.add(new SelectOption(FAILURE_NEGOCIACAO, FAILURE_NEGOCIACAO));
			} else if(tipo == TIPO_VOLUME) {
				options.add(new SelectOption(FAILURE_EXTRAVIO, FAILURE_EXTRAVIO));
				options.add(new SelectOption(FAILURE_NEGOCIACAO, FAILURE_NEGOCIACAO));
			} else {
				options = getAllFailureOptions();
			}
		} else if(registro == REG_SUBSTITUICAO) {
			options = getAllFailureOptions();
		}
		return options;
    }
    
    private List<SelectOption> getAllFailureOptions() {
    	List<SelectOption> options = new List<SelectOption>();
    	Schema.DescribeFieldResult fieldResult = CaseItem__c.FailureTypeTxt__c.getDescribe();
    	List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    	
    	for(Schema.PicklistEntry f: ple) {
    		options.add(new SelectOption(f.getLabel(), f.getValue()));
    	}
    	return options;
    }
    
    public List<CaseItemVO> loadCaseItemVO(Id caseId) {
    	
		System.debug(LoggingLevel.FINEST, '*** loadCaseItemVO ' + Registro);
    	
    	CSECaseSelector caseSelector = new CSECaseSelector();
    	CSEInvoiceItemSelector invoiceItemSelector = new CSEInvoiceItemSelector();
    	CSECaseItemSelector caseItemSelector = new CSECaseItemSelector();
    	
    	List<CaseItemVO> itemVoList = new List<CaseItemVO>();
    	
    	Set<Id> caseIdSet = new Set<Id>();
    	caseIdSet.add(caseId);
    	List<Case> caseList = caseSelector.selectById(caseIdSet);
    	
    	if (Registro == REG_RECLAMACAO) {

    		List<CaseItem__c> caseItemList = new List<CaseItem__c>();
    		caseItemList = caseItemSelector.selectByCaseId(caseId);
    		
    		if (!caseItemList.isEmpty()) {

	    		CaseItemVO vo = new CaseItemVO();
	    		vo.Checked = true;
	    		vo.CaseItem = caseItemList[0];
	    		itemVoList.add(vo);
    			
    		} else {

	    		CaseItemVO vo = new CaseItemVO();
	    		vo.Checked = true;
	    		vo.CaseItem = new CaseItem__c(CaseMdt__c = caseId);
	    		itemVoList.add(vo);
	    		
    		}
    		
    	} else if(caseList != null && !caseList.isEmpty()) {

    		Id invoiceId = caseList[0].InvoiceLkp__c;
    		List<InvoiceItem__c> invoiceList = invoiceItemSelector.selectByInvoiceId(invoiceId);
    		List<CaseItem__c> caseItemList =  caseItemSelector.selectByCaseId(caseId);
    		    		   		    		
    		itemVoList = convertCaseItemToVO(invoiceList, caseItemList);
    	} 
    	
    	return itemVoList;
    }
    
    private List<CaseItemVO> convertCaseItemToVO(List<InvoiceItem__c> invoiceList, List<CaseItem__c> caseItemList) {
    	List<CaseItemVO> items = new List<CaseItemVO>();
    	CaseItem__c caseItem;
    	CaseItemVO vo;
    	
    	if(invoiceList != null && caseItemList != null) {
    		for(InvoiceItem__c invoice: invoiceList) {
    			
    			Id productId = invoice.ProductLkp__r.Id;
    			
    			vo = new CaseItemVO();
    			//vo.ProductId = invoice.ProductLkp__r.Id;
    			//vo.ProductName = invoice.ProductLkp__r.Name;
    			//vo.Denomination = invoice.DenominationTxt__c;
    			vo.MaxQuantity = (Integer)invoice.QuantityNmb__c;
    			vo.Id = invoice.Id;
    			
    			caseItem = findCaseItemByProduct(productId, caseItemList);
    			
    			if(caseItem != null) {
    				vo.Checked = true;
    				//vo.Quantity = (Integer)caseItem.QuantityNmb__c;
    				vo.FailureType = caseItem.FailureTypeTxt__c;
    				vo.Comments = caseItem.CommentsTxt__c;    				
    				/*if(getShowComments() == true && Comments == '') {
    					Comments = vo.Comments;
    				}*/
    				vo.QualityProblem = caseItem.QualityProblemTxt__c;
    				/*if(getShowQualityProblem() == true && QualityProblem == '') {
    					QualityProblem = vo.QualityProblem;
    				}*/
    				vo.CaseItem = caseItem;
    			} else {
    				
    				vo.CaseItem = new CaseItem__c(CaseMdt__c = caseId, ProductLkp__c = productId);
    				vo.Checked = false;
    				
    			}
    			items.add(vo);
    		}
    	}
    	
    	return items;
    }
    
    private CaseItem__c findCaseItemByProduct(Id productId, List<CaseItem__c> caseItemList) {
    	CaseItem__c found = null;
    	
    	for(CaseItem__c item: caseItemList) {
    		if(item.ProductLkp__c == productId) {
    			found = item;
    			break;
    		}
    	}
    	
    	return found;
    }
}