force-app/main/default/objects/CatalogElement__c/CatalogElement__c.object-meta.xml
<CustomObject>
    <description>[###][CatalogElement__c] Elementos de Catálogo de Preços, para montar a hierarquia</description>
    <label>Elemento de Catálogo</label>
    <nameField>
        <label>Nome do Elemento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elementos de Catálogo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CatalogElement__c/fields/IndexNmb__c.field-meta.xml
<CustomField>
    <fullName>IndexNmb__c</fullName>
    <description>Indica a ordem que os elementos serão exibidos</description>
    <inlineHelpText>Ordem de exibição dos elementos no catálogo. Exibidos em ordem crescente, nulos por último</inlineHelpText>
    <label>Ordem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/NextElementLkp__c.field-meta.xml
<CustomField>
    <fullName>NextElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Próximo elemento em relação à ordem definida no catálogo, entre os irmãos do elemento atual. Preenchido via trigger</description>
    <label>Próximo Elemento</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Elementos Anteriores</relationshipLabel>
    <relationshipName>PreviousElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/ParentElementLkp__c.field-meta.xml
<CustomField>
    <fullName>ParentElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elemento Pai</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Elementos Filhos</relationshipLabel>
    <relationshipName>ChildElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/PreviousElementLkp__c.field-meta.xml
<CustomField>
    <fullName>PreviousElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vide Próximo Elemento</description>
    <label>Elemento Anterior</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Próximos Elementos</relationshipLabel>
    <relationshipName>NextElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CatalogElementTriggerHandler.cls
@isTest
private class Test_CatalogElementTriggerHandler {
    
    @isTest static void testIndex(){
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        CatalogElement__c element1 = TestData.createCatalogElement('TestElement1', 1, pb.Id, null);
        CatalogElement__c element2 = TestData.createCatalogElement('TestElement2', 20, pb.Id, null);
        CatalogElement__c element3 = TestData.createCatalogElement('TestElement3', 3, pb.Id, null);
        CatalogElement__c elementMaster = TestData.createCatalogElement('TestElementMaster', null, null, null);
        CatalogElement__c element4 = TestData.createCatalogElement('TestElement4', 4, null, elementMaster.Id);
        CatalogElement__c element5 = TestData.createCatalogElement('TestElement5', 7, null, elementMaster.Id);
        CatalogElement__c element6 = TestData.createCatalogElement('TestElement6', 6, null, elementMaster.Id);
        
        Test.startTest();
        element2.IndexNmb__c = 2;
        update element2;
        element5.IndexNmb__c = 5;
        update element5;
        Test.stopTest();
        
        element2 = [Select Id, PreviousElementLkp__c, NextElementLkp__c, ParentElementLkp__c
                    From CatalogElement__c
                    Where Id =: element2.Id];
        system.debug(element2);
        element5 = [Select Id, PreviousElementLkp__c, NextElementLkp__c, ParentElementLkp__c
                    From CatalogElement__c
                    Where Id =: element5.Id];
        System.assertEquals(element1.Id, element2.PreviousElementLkp__c);
        System.assertEquals(element3.Id, element2.NextElementLkp__c);
     	System.assertEquals(element4.Id, element5.PreviousElementLkp__c);
        System.assertEquals(element6.Id, element5.NextElementLkp__c);
    }

}