force-app/main/default/objects/CatalogElement__c/CatalogElement__c.object-meta.xml
<CustomObject>
    <description>[###][CatalogElement__c] Elementos de Catálogo de Preços, para montar a hierarquia</description>
    <label>Elemento de Catálogo</label>
    <nameField>
        <label>Nome do Elemento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elementos de Catálogo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CatalogElement__c/fields/IndexNmb__c.field-meta.xml
<CustomField>
    <fullName>IndexNmb__c</fullName>
    <description>Indica a ordem que os elementos serão exibidos</description>
    <inlineHelpText>Ordem de exibição dos elementos no catálogo. Exibidos em ordem crescente, nulos por último</inlineHelpText>
    <label>Ordem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/NextElementLkp__c.field-meta.xml
<CustomField>
    <fullName>NextElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Próximo elemento em relação à ordem definida no catálogo, entre os irmãos do elemento atual. Preenchido via trigger</description>
    <label>Próximo Elemento</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Elementos Anteriores</relationshipLabel>
    <relationshipName>PreviousElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/ParentElementLkp__c.field-meta.xml
<CustomField>
    <fullName>ParentElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elemento Pai</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Elementos Filhos</relationshipLabel>
    <relationshipName>ChildElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/PreviousElementLkp__c.field-meta.xml
<CustomField>
    <fullName>PreviousElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Vide Próximo Elemento</description>
    <label>Elemento Anterior</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Próximos Elementos</relationshipLabel>
    <relationshipName>NextElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/PricebookLkp__c.field-meta.xml
<CustomField>
    <fullName>PricebookLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catálogo de Preços</label>
    <referenceTo>Pricebook__c</referenceTo>
    <relationshipLabel>Elementos de Catálogo</relationshipLabel>
    <relationshipName>CatalogElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CatalogElementTriggerHandler.cls
public class CatalogElementTriggerHandler {
    @future
    public static void processOrder(List<Id> listIds){
        List<CatalogElement__c> listParentElems = [SELECT Id, 
                                                   (SELECT ID, IndexNmb__c FROM ChildElements__r ORDER BY IndexNmb__c, Name) 
                                                   FROM CatalogElement__c WHERE Id IN :listIds];
        system.debug(listParentElems);
        List<Pricebook__c> listPb = [SELECT Id,
                                    (SELECT ID, IndexNmb__c FROM CatalogElements__r ORDER BY IndexNmb__c, Name)
                                    FROM Pricebook__c WHERE Id IN :listIds];
		//system.debug(listPb[0].CatalogElements__r);        
        List<CatalogElement__c> listChildElems = new List<CatalogElement__c>();
        for(CatalogElement__c parentElem : listParentElems){
            if(parentElem.ChildElements__r.size() > 1){
                Id firstChildId = parentElem.ChildElements__r[0].Id;
                Id lastChildId = parentElem.ChildElements__r[parentElem.ChildElements__r.size()-1].Id;
                for(Integer i = 0; i < parentElem.ChildElements__r.size(); i++){
                    CatalogElement__c currentElem = parentElem.ChildElements__r[i];
                    currentElem.PreviousElementLkp__c = (i == 0) ? lastChildId : parentElem.ChildElements__r[i-1].Id;
                    currentElem.NextElementLkp__c = (i == parentElem.ChildElements__r.size() - 1) ? firstChildId : parentElem.ChildElements__r[i+1].Id;
                    listChildElems.add(currentElem);
                }
            }
        }
        
        for(Pricebook__c pb : listPb){
            if(pb.CatalogElements__r.size() > 1){
                Id firstChildId = pb.CatalogElements__r[0].Id;
                Id lastChildId = pb.CatalogElements__r[pb.CatalogElements__r.size()-1].Id;
                for(Integer i = 0; i < pb.CatalogElements__r.size(); i++){
                    CatalogElement__c currentElem = pb.CatalogElements__r[i];
                    currentElem.PreviousElementLkp__c = (i == 0) ? lastChildId : pb.CatalogElements__r[i-1].Id;
                    currentElem.NextElementLkp__c = (i == pb.CatalogElements__r.size() - 1) ? firstChildId : pb.CatalogElements__r[i+1].Id;
                    listChildElems.add(currentElem);
                }
            }
        }
        
        update listChildElems;
    }

}