force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/ActiveVerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>ActiveVerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco Ativo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>VerdeAmancoKit__c.ChannelLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Canais</relationshipLabel>
    <relationshipName>Channels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoKit__c/VerdeAmancoKit__c.object-meta.xml
<CustomObject>
    <description>[###][VerdeAmancoKit__c]</description>
    <label>Kit Verde Amanco</label>
    <nameField>
        <label>Nome de Kit Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kits Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoKit__c/fields/ActiveBln__c.field-meta.xml
<CustomField>
    <fullName>ActiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoKit__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Kits Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoKits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VerdeAmancoKitTriggerHandler.cls
public class VerdeAmancoKitTriggerHandler {
    public static void isBeforeInsert(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){

    }
    public static void isBeforeUpdate(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){
        
    }
    public static void isBeforeDelete(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){

    }
    public static void isAfterInsert(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){
            List<Id> listActiveKits = new List<Id>();
            
            
            for(VerdeAmancoKit__c o : listVerdeAmancoKit){
                //VerdeAmancoKit__c oldKit = oldMap.get(o.Id);
                //if(o.ChannelLkp__c != null && o.ActiveBln__c == true && oldKit.ActiveBln__c == false){
                //    listActiveKits.add(o.Id);
                //}
                if(o.ChannelLkp__c != null && o.ActiveBln__c == true){
                    listActiveKits.add(o.Id);
                }
            }
            try{
                setActiveKits(listActiveKits);
            }
            catch(Exception e){
                listVerdeAmancoKit[0].addError(e.getMessage());
            }
        
        
    }
    public static void isAfterUpdate(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){
            List<Id> listActiveKits = new List<Id>();
            
            
            for(VerdeAmancoKit__c o : listVerdeAmancoKit){
                VerdeAmancoKit__c oldKit = oldMap.get(o.Id);
                if(o.ChannelLkp__c != null && o.ActiveBln__c == true && oldKit.ActiveBln__c == false){
                    listActiveKits.add(o.Id);
                }
            }
            try{
                setActiveKits(listActiveKits);
            }
            catch(Exception e){
                listVerdeAmancoKit[0].addError(e.getMessage());
            }
        
    }
    public static void isAfterDelete(List<VerdeAmancoKit__c> listVerdeAmancoKit, Map<Id, VerdeAmancoKit__c> oldMap){
        
    }
    
    public static void setActiveKits(List<Id> listActiveKitIds){
        List<VerdeAmancoKit__c> listkits = [SELECT Id, ChannelLkp__c, ActiveBln__c FROM VerdeAmancoKit__c WHERE Id IN :listActiveKitIds];
        List<VerdeAmancoKit__c> kitsToUpdate = new List<VerdeAmancoKit__c>();
        List<Channel__c> channelToUpdate = new List<Channel__c>();
        List<Id> listChnIds = new List<Id>();
        
        for(VerdeAmancoKit__c o : listkits){
            listChnIds.add(o.ChannelLkp__c);
           channelToUpdate.add(new Channel__c(Id = o.ChannelLkp__c, ActiveVerdeAmancoKitLkp__c = o.Id));
        }
        for(VerdeAmancoKit__c o : [SELECT Id FROM VerdeAmancoKit__c WHERE ChannelLkp__c IN :listChnIds AND Id NOT IN :listActiveKitIds]){
            o.ActiveBln__c = false;
           kitsToUpdate.add(o);
        }
        
        upsert channelToUpdate;
        upsert kitsToUpdate;
        
    }
}