force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/ActiveVerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>ActiveVerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco Ativo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>VerdeAmancoKit__c.ChannelLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Canais</relationshipLabel>
    <relationshipName>Channels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoKit__c/VerdeAmancoKit__c.object-meta.xml
<CustomObject>
    <description>[###][VerdeAmancoKit__c]</description>
    <label>Kit Verde Amanco</label>
    <nameField>
        <label>Nome de Kit Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kits Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoKit__c/fields/ActiveBln__c.field-meta.xml
<CustomField>
    <fullName>ActiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/Test_VAKitTriggerHandler.cls
@isTest
private class Test_VAKitTriggerHandler {
    
    @isTest static void insertActiveKit(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('kitTES', chn.Id, true);
        chn = [Select Id, ActiveVerdeAmancoKitLkp__c
               From Channel__c
               Where Id = :chn.Id];
        System.assertEquals(kit.Id, chn.ActiveVerdeAmancoKitLkp__c);
        
    }
    
    @isTest static void updateActiveKit(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('kitTES', chn.Id, false);
        VerdeAmancoKit__c oldKit = TestData.createVerdeAmancoKit('oldKitTES', chn.Id, true);
        kit.ActiveBln__c = true;
        update kit;
        chn = [Select Id, ActiveVerdeAmancoKitLkp__c
               From Channel__c
               Where Id = :chn.Id];
        oldKit = [Select Id, ActiveBln__c
                  From VerdeAmancoKit__c
                  Where Id = :oldKit.Id];
        System.assertEquals(kit.Id, chn.ActiveVerdeAmancoKitLkp__c);
        System.assertEquals(false, oldKit.ActiveBln__c);
        
    }  

}