force-app/main/default/objects/ExpurgoFaturamentoSumarizado__c/ExpurgoFaturamentoSumarizado__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Expurgo Faturamento Sumarizado</label>
</CustomObject>

force-app/main/default/objects/ExpurgoFaturamentoSumarizado__c/fields/Dias_para_expurgo__c.field-meta.xml
<CustomField>
    <fullName>Dias_para_expurgo__c</fullName>
    <label>Dias para Expurgo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SummarizedRevenue__c/SummarizedRevenue__c.object-meta.xml
<CustomObject>
    <description>[SummarizedRevenue__c] Faturamentos sumarizados, originados no BI</description>
    <label>Faturamento Sumarizado</label>
    <nameField>
        <label>Nome de Faturamento Sumarizado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos Sumarizados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_CleanSummarizedRevenue.cls
global class Batch_CleanSummarizedRevenue implements Database.Batchable<sObject> {
    
    ExpurgoFaturamentoSumarizado__c numDias = ExpurgoFaturamentoSumarizado__c.getInstance();
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
            'SELECT ID FROM SummarizedRevenue__c WHERE isDeleted = false AND CreatedDate <= LAST_N_DAYS:' + Integer.valueOf(numDias.Dias_para_expurgo__c)
        ); 
    }
    global void execute(Database.BatchableContext bc, List<SUmmarizedRevenue__c> scope){
        delete scope;
    }
    global void finish(Database.BatchableContext bc){
        
    }
}