force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>E-mail</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Refaturamento.recordType-meta.xml
<RecordType>
    <fullName>Refaturamento</fullName>
    <active>true</active>
    <businessProcess>SAC Refaturamento</businessProcess>
    <description>Abertura de caso refaturamento</description>
    <label>Refaturamento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sinistro.recordType-meta.xml
<RecordType>
    <fullName>Sinistro</fullName>
    <active>true</active>
    <businessProcess>SAC Sinistro</businessProcess>
    <description>Abertura de caso onde houve sinistro</description>
    <label>Sinistro</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorista</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Carrier__c.TypeTxt__c</field>
            <operation>equals</operation>
            <value>PE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recebedor mercadoria</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/CoordinatorEmailTxt__c.field-meta.xml
<CustomField>
    <fullName>CoordinatorEmailTxt__c</fullName>
    <label>Coordenador e-mail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/ManagerEmailTxt__c.field-meta.xml
<CustomField>
    <fullName>ManagerEmailTxt__c</fullName>
    <label>Gerente e-mail</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/SellerEmailTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerEmailTxt__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CreateNewCaseCtrl.cls
public with sharing class CreateNewCaseCtrl {
    
    @AuraEnabled
    public static Invoice__c getinvoice(Id invoiceId) {
        system.debug('invoiceId'+ invoiceId);      
        
        Invoice__c invoice = [
            
            SELECT Id,Name,AccountLkp__c,OrderLkp__c,CarrierLkp__c,RemittanceLkp__c,RemittanceLkp__r.OrderLkp__r.SellerLkp__c,CarrierLkp__r.EmailTxt__c,RemittanceLkp__r.OrderLkp__r.SellerLkp__r.SellerEmailTxt__c,RemittanceLkp__r.OrderLkp__r.SellerLkp__r.ManagerEmailTxt__c,RemittanceLkp__r.OrderLkp__r.SellerLkp__r.CoordinatorEmailTxt__c
            FROM Invoice__c
            WHERE Id = :invoiceId
        ];
        
        system.debug('invoice' + invoice);
        return invoice;
        
    }
    
    @AuraEnabled
    public static Order__c getorder(Id orderId) {
        system.debug('orderId'+ orderId);      
        
        Order__c order = [
            
            SELECT Id,Name,AccountLkp__c,SellerLkp__r.SellerEmailTxt__c,SellerLkp__r.CoordinatorEmailTxt__c 
            FROM Order__c
            WHERE Id = :orderId
        ];
        
        system.debug('order' + order);
        return order;
        
    }
    
    
    @AuraEnabled
    public static List<RecordType> getcaserecordtype() {     
        List<RecordType> caserecordtype = [
            SELECT Id, Name 
            FROM RecordType 
            WHERE SobjectType = 'Case' 
            AND IsActive = true
            AND Name IN ('Devolução', 'Carta de correção', 'Prorrogação', 'Transtorno na entrega', 
                         'Sustação', 'Extravio de nota fiscal', 'Sinistro', 'Produto Trocado', 
                         'Refaturamento', 'Reposição', 'Substituição', 'Informações Gerais')
            ORDER BY Name ASC
        ];
        system.debug('caserecordtype'+ caserecordtype);
        return caserecordtype;
    }
    
    @AuraEnabled
    public static List <RecordType> getcaserecordtypeO() {     
        List<RecordType> caserecordtypeO = [
            SELECT Id, Name 
            FROM RecordType 
            WHERE SobjectType = 'Case' 
            AND IsActive = true
            AND Name IN ('Consulta de pedido','Alteração de pedido','Cancelamento de pedido', 'Informações Gerais')
            ORDER BY Name ASC
            
        ];
        system.debug('caserecordtypeO'+ caserecordtypeO);    
        return caserecordtypeO;
        
    }
    
    @AuraEnabled
    public static List<RecordType> getcaserecordtypeA() {     
        List<RecordType> caserecordtypeA = [
            SELECT Id, Name 
            FROM RecordType 
            WHERE SobjectType = 'Case' 
            AND IsActive = true
            AND Name IN ('Indicação de vendedor', 'Informações Gerais', 'Indicação BNDES','Reclamação contra o vendedor')
            ORDER BY Name ASC
        ];
        system.debug('caserecordtypeA'+ caserecordtypeA);
        return caserecordtypeA;
    }
    
}