force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>E-mail</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/DocumentDateDte__c.field-meta.xml
<CustomField>
    <fullName>DocumentDateDte__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/RemittanceLkp__c.field-meta.xml
<CustomField>
    <fullName>RemittanceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/ShipmentDeliveredFml__c.field-meta.xml
<CustomField>
    <fullName>ShipmentDeliveredFml__c</fullName>
    <formula>RemittanceLkp__r.ShipmentDeliveredDte__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Mercadoria entregue</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorista</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Carrier__c.TypeTxt__c</field>
            <operation>equals</operation>
            <value>PE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recebedor mercadoria</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/DocumentDateDte__c.field-meta.xml
<CustomField>
    <fullName>DocumentDateDte__c</fullName>
    <label>Data da remessa</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CSEInvoiceSelector.cls
public with sharing class CSEInvoiceSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Invoice__c.Id,
			Invoice__c.Name,
			Invoice__c.CarrierLkp__c,
			Invoice__c.DocumentDateDte__c,
			Invoice__c.RemittanceLkp__c,
			Invoice__c.ShipmentDeliveredFml__c
		};
	}
	
	public Schema.SObjectType getSObjectType() {
		return Invoice__c.sObjectType;
	}
	
	public List<Invoice__c> selectById(Set<Id> idSet) {

        String query = String.format(
            ' SELECT {0}, OrderLkp__r.Name ' + 
            ' FROM {1}' +
            ' WHERE Id IN :idSet' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        return (List<Invoice__c>)Database.query(query);       
    }
    
    public List<Invoice__c> selectByNumber(String invoiceNumber) {
		
        String query = String.format(
            ' SELECT {0}, OrderLkp__r.Name, CarrierLkp__r.EmailTxt__c, CarrierLkp__r.Name, OrderLkp__r.SellerLkp__r.Id, OrderLkp__r.SellerLkp__r.Name, OrderLkp__r.SellerLkp__r.SellerEmailTxt__c, OrderLkp__r.SellerLkp__r.CoordinatorEmailTxt__c, OrderLkp__r.SellerLkp__r.ManagerEmailTxt__c ' + 
            ' FROM {1}' +
            ' WHERE Name = :invoiceNumber' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug(query);
        return (List<Invoice__c>)Database.query(query);       
    }
    
    public List<Invoice__c> selectByNumberAndCustomer(String invoiceNumber, String accountId) {
		
		System.debug('**invoice number: ' + invoiceNumber + ' ***accountId: ' + accountId);
		
        String query = String.format(
            ' SELECT {0}, RemittanceLkp__r.OrderLkp__r.Name, RemittanceLkp__r.OrderLkp__c, CarrierLkp__r.EmailTxt__c, CarrierLkp__r.Name, RemittanceLkp__r.OrderLkp__r.SellerLkp__r.Id, RemittanceLkp__r.OrderLkp__r.SellerLkp__r.Name, RemittanceLkp__r.OrderLkp__r.SellerLkp__r.SellerEmailTxt__c, RemittanceLkp__r.OrderLkp__r.SellerLkp__r.CoordinatorEmailTxt__c, RemittanceLkp__r.OrderLkp__r.SellerLkp__r.ManagerEmailTxt__c ' + 
            ' FROM {1}' +
            ' WHERE Name = :invoiceNumber and AccountLkp__c = :accountId' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug('*** ' + query);
        return (List<Invoice__c>)Database.query(query);       
    }
    
    public List<Invoice__c> selectByOrderId(Id orderId) {
		
        String query = String.format(
            ' SELECT {0}, CarrierLkp__r.EmailTxt__c, CarrierLkp__r.Name ' + 
            ' FROM {1}' +
            ' WHERE OrderLkp__c = :orderId' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug(query);
        return (List<Invoice__c>)Database.query(query);       
    }
    
    public List<Invoice__c> selectByRemittanceId(Id remittanceId) {
		
        String query = String.format(
            ' SELECT {0}, CarrierLkp__r.EmailTxt__c, CarrierLkp__r.Name ' + 
            ' FROM {1}' +
            ' WHERE OrderLkp__c = :orderId' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug(query);
        return (List<Invoice__c>)Database.query(query);       
    }
    
    public List<Invoice__c> selectByRemittanceId2(Id remittanceId) {
		
        String query = String.format(
            ' SELECT {0}' + 
            ' FROM {1}' +
            ' WHERE RemittanceLkp__c = :remittanceId' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug(query);
        return (List<Invoice__c>)Database.query(query);       
    }

    public List<Invoice__c> selectByRemittanceId2(Set<Id> remittanceIdList) {
        
        String query = String.format(
            ' SELECT {0}' + 
            ' FROM {1}' +
            ' WHERE RemittanceLkp__c in :remittanceIdList' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        System.debug(query);
        return (List<Invoice__c>)Database.query(query);       
    }
}