force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>E-mail</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSECarrierSelector.cls
public with sharing class CSECarrierSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Carrier__c.Id,
			Carrier__c.Name,
			Carrier__c.EmailTxt__c
		};
	}
	
	public Schema.SObjectType getSObjectType() {
		return Carrier__c.sObjectType;
	}
	
	public List<Carrier__c> selectById(Set<Id> idSet) {

        String query = String.format(
            ' SELECT {0} ' + 
            ' FROM {1}' +
            ' WHERE Id IN :idSet' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        return (List<Carrier__c>)Database.query(query);       
    }
    
}