force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/InvoiceMdt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceMdt__c</fullName>
    <label>Número da nota fiscal</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>Itens_da_nota_fiscal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>Itens_da_nota_fiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InvoiceItem__c/fields/QuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>QuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/OfflinePrices__c.object-meta.xml
<CustomObject>
    <description>Tabela de preços do Offline</description>
    <label>Preços Offline</label>
    <nameField>
        <label>Nome de Preços Offline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Offline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfflinePrices__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Preços Offline</relationshipLabel>
    <relationshipName>ProductLkp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CSEInvoiceItemSelector.cls
public with sharing class CSEInvoiceItemSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		InvoiceItem__c.Id,
    		InvoiceItem__c.ProductLkp__c,
    		InvoiceItem__c.QuantityNmb__c,
    		InvoiceItem__c.DenominationTxt__c
    	};
    }
    
    public Schema.SObjectType getSObjectType() {
    	return InvoiceItem__c.sObjectType;
    }
    
    public List<InvoiceItem__c> selectById(Set<Id> idSet) {
    	String query = String.format(
    		' SELECT {0}' +
    		' FROM {1}' +
    		' WHERE Id IN :idSet' +
    		' ORDER BY {2}',
    		new List<String>{
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<InvoiceItem__c>)Database.query(query);
    }
    
    public List<InvoiceItem__c> selectByInvoiceId(Id invoiceId) {
    	String query = String.format(
    		' SELECT {0}, ProductLkp__r.Name, ProductLkp__r.Id' +
    		' FROM {1}' +
    		' WHERE InvoiceMdt__c = :invoiceId' +
    		' ORDER BY {2}',
    		new List<String>{
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<InvoiceItem__c>)Database.query(query);
    }
}