force-app/main/default/objects/CaseInvoice__c/CaseInvoice__c.object-meta.xml
<CustomObject>
    <description>[a00][CaseInvoice__c] Notas fiscais do caso.</description>
    <label>Nota fiscal do caso</label>
    <nameField>
        <label>Nota fiscal do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseInvoice__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/CreditNmb__c.field-meta.xml
<CustomField>
    <fullName>CreditNmb__c</fullName>
    <label>Crédito</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/ExtendDaysNmb__c.field-meta.xml
<CustomField>
    <fullName>ExtendDaysNmb__c</fullName>
    <label>Dias a prorrogar</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nota fiscal</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Notas fiscais do caso</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais do caso</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/QuotaNmb__c.field-meta.xml
<CustomField>
    <fullName>QuotaNmb__c</fullName>
    <label>Parcela</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/classes/CSECaseInvoiceSelector.cls
public with sharing class CSECaseInvoiceSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			CaseInvoice__c.Id,
			CaseInvoice__c.CaseMdt__c,
			CaseInvoice__c.OrderLkp__c,
			CaseInvoice__c.CreditNmb__c,
			CaseInvoice__c.ExtendDaysNmb__c,
			CaseInvoice__c.QuotaNmb__c,
			CaseInvoice__c.InvoiceLkp__c
		};
	}
	
	public Schema.SObjectType getSObjectType() {
		return CaseInvoice__c.sObjectType;
	}
	
	public List<CaseInvoice__c> selectById(Set<Id> idSet) {

        String query = String.format(
            ' SELECT {0}, OrderLkp__r.Name, InvoiceLkp__r.Name ' + 
            ' FROM {1}' +
            ' WHERE Id IN :idSet' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        return (List<CaseInvoice__c>)Database.query(query);       
    }
    
    public List<CaseInvoice__c> selectByCase(String caso) {

        String query = String.format(
            ' SELECT {0}, OrderLkp__r.Name, InvoiceLkp__r.Name ' + 
            ' FROM {1}' +
            ' WHERE CaseMdt__c = :caso' +
            ' ORDER BY {2}',
            new List<String>{
                getFieldListString(),
                getSObjectName(),               
                getOrderBy()            
            }
        );  
        return (List<CaseInvoice__c>)Database.query(query);       
    }
}