force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>[a0q][Campaign__c] Campanha de Trade Marketing</description>
    <label>Campanha</label>
    <nameField>
        <label>Nome da Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMechanics__c/CampaignMechanics__c.object-meta.xml
<CustomObject>
    <description>[a0t][CampaignMechanics__c] Mecânica definida para a campanha de Trade: Maneira de apuração e pagamento de benefício</description>
    <label>Mecânica de Campanha</label>
    <nameField>
        <displayFormat>CGO-{YYYY}{00000}</displayFormat>
        <label>Código de Mecânica de Campanha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mecânicas de Campanhas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMechanics__c/fields/ApplyDiscountBenefitBln__c.field-meta.xml
<CustomField>
    <fullName>ApplyDiscountBenefitBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplicar Desconto Benefício</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMechanics__c/fields/ApplyDiscountBln__c.field-meta.xml
<CustomField>
    <fullName>ApplyDiscountBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aplicar Desconto</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CampaignMechanics__c/fields/CampaignLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignLkp__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Mecânicas de Campanha</relationshipLabel>
    <relationshipName>CampaignMechanics</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_NCDiscount.cls
global class Batch_NCDiscount implements Database.Batchable<sObject>, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
        	'SELECT ID, Name, (SELECT Id, Name FROM CampaignMechanics__r WHERE ApplyDiscountBln__c = TRUE OR ApplyDiscountBenefitBln__c = TRUE) FROM Campaign__c WHERE Active__c = TRUE'
        );   
    }
    global void execute(Database.BatchableContext bc, List<Campaign__c> scope){
        //List<Campaign__c> campaigns = new List<Campaign__c>();
        for (Campaign__c cmp : scope){
            if(cmp.CampaignMechanics__r.size() > 0){
                //System.debug('Campanha: '+cmp.Name+' possui '+cmp.CampaignMechanics__r.size()+' mecânicas que precisam de cálculo do desconto de NC');
            	CampaignUtility.getNCDiscount(cmp.Id, System.today());    
            }
        }
    }
    global void finish(Database.BatchableContext bc){       
        Batch_CampaignRecovery batchCampaignRecovery = new Batch_CampaignRecovery(); 
		Id batchId = Database.executeBatch(batchCampaignRecovery, 1); 
    }
}