force-app/main/default/objects/IntegrationMap__c/IntegrationMap__c.object-meta.xml
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationMap__c/fields/SObjectApiNameTxt__c.field-meta.xml
<CustomField>
    <fullName>SObjectApiNameTxt__c</fullName>
    <label>API name do objeto</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RemittanceItem__c/RemittanceItem__c.object-meta.xml
<CustomObject>
    <description>[a0H][RemittanceItem__c] Itens da Remessa.</description>
    <label>Item da remessa</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da remessa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/OrderRemoteCall.cls
public without sharing class OrderRemoteCall 
    extends RestBaseServiceAbstraction
    implements integ_IRemoteCall{

    public String invoiceNumber {get;set;}
    public String customerCode {get;set;}
    public String orderNumber {get;set;}

    public OrderRemoteCall(String invoiceNumber, String customerCode, String orderNumber, Boolean bol) {
    }    

    public OrderRemoteCall(String invoiceNumber, String customerCode, String orderNumber) {
        super();
        this.invoiceNumber = invoiceNumber;
        this.customerCode = customerCode;
        this.orderNumber = orderNumber;
    }

    public String getBodyContent() {
        
        String bodyContent = null;
        
        if (this.orderNumber != null) {
            OrderRequestByOrderNumberJSON orderNumberRequest = new OrderRequestByOrderNumberJSON();
            orderNumberRequest.PEDIDO = this.orderNumber;
            SapRequestJSON sapReq = new SapRequestJSON(orderNumberRequest);
            bodyContent = JSON.serialize(sapReq);

        } else if ((this.orderNumber == null) && (this.customerCode != null) && (this.invoiceNumber == null)) {
            OrderRequestByCustomerLast30DaysJSON orderNumberRequest = new OrderRequestByCustomerLast30DaysJSON(this.customerCode);
            SapRequestJSON sapReq = new SapRequestJSON(orderNumberRequest);
            bodyContent = JSON.serialize(sapReq);
        } else {
            bodyContent = OrderRequestJSONCreater.execute(invoiceNumber, customerCode); 
        }

        return bodyContent;

    }

    public Object execute() {
        return parseAndExecuteResponse(this.callService('POST'));
    }
    
    private List<Invoice__c> parseAndExecuteResponse(String response) {
        system.debug('entrou 1');
        //response = response.substring(1, response.length());
        response = response.substring(1, response.length() - 1);
                
        String jsonStr = response.unescapeEcmaScript()
                            .unescapeEcmaScript();

        //ASHIROTA 20171611: ajuste de homolog
        jsonStr = jsonStr.substring(13, jsonStr.length()-1);
        
        Object obj = JSON.deserializeUntyped(jsonStr);
        
        system.debug('entrou 2');
        Map<String, Object> mp = (Map<String, Object>)obj;
        System.debug('***' + mp.get('invoiceData'));
   
        if(mp.get('invoiceData') == null || mp.get('orderData') == null || mp.get('shippingData') == null) {
            return null;
        }
        
        system.debug('entrou 3');
        List<IntegrationMap__c> integrationList = IntegrationMapDAO.getAll();
        Map<String, IntegrationMap__c> integMap = new Map<String, IntegrationMap__c>();
        system.debug('entrou 4');
        for(IntegrationMap__c aux : integrationList) {
            integMap.put(aux.SObjectApiNameTxt__c, aux);
        }
        
        integ_JSONTransformer jsonTransformer = new integ_JSONTransformer();
        system.debug('entrou 5');
        //add order and order item flow
        new integ_CustomOperationOrder().execute(jsonTransformer.convertToSObjectList(integMap.get('Order__c'), JSON.serialize(mp.get('orderData'))));
        new integ_CustomOperationOrderItem().execute(jsonTransformer.convertToSObjectList(integMap.get('OrderItem__c'), JSON.serialize(mp.get('orderData'))));
 system.debug('entrou 6');
        //add remittance and remittance item flow
        new integ_CustomOperationShipping().execute(jsonTransformer.convertToSObjectList(integMap.get('Remittance__c'), JSON.serialize(mp.get('shippingData'))));
        new integ_CustomOperationShippingItem().execute(jsonTransformer.convertToSObjectList(integMap.get('RemittanceItem__c'), JSON.serialize(mp.get('shippingData'))));
        system.debug('entrou 7');
        //add invoice and invoice item flow
        integ_CustomOperationInvoice invoiceOp = new integ_CustomOperationInvoice();
        List<Invoice__c> invoiceList = ((List<Invoice__c>)invoiceOp.execute(jsonTransformer.convertToSObjectList(integMap.get('Invoice__c'), JSON.serialize(mp.get('invoiceData')))));
        new integ_CustomOperationInvoiceItem().execute(jsonTransformer.convertToSObjectList(integMap.get('InvoiceItem__c'), JSON.serialize(mp.get('invoiceData'))));
system.debug('entrou 8');

        return invoiceList;

    }
    
    
}