force-app/main/default/objects/IntegrationMap__c/IntegrationMap__c.object-meta.xml
<CustomObject>
    <description>[a09][IntegrationMap__c] Mapa de integração.</description>
    <label>Mapa de integração</label>
    <nameField>
        <label>Integração</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapas de integração</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationMap__c/fields/CommandClassName__c.field-meta.xml
<CustomField>
    <fullName>CommandClassName__c</fullName>
    <defaultValue>&quot;GenericIntegrationService&quot;</defaultValue>
    <label>Classe de comando</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/IntegrationMap__c/fields/IntegrationId__c.field-meta.xml
<CustomField>
    <fullName>IntegrationId__c</fullName>
    <label>ID da integração</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/IntegrationMapChild__c/IntegrationMapChild__c.object-meta.xml
<CustomObject>
    <description>[a07][IntegrationMapChild__c] Mapa da integração filha.</description>
    <label>Mapa da integração filha</label>
    <nameField>
        <label>Nome de Mapa da integração filha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mapa da integração filha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/IntegrationMapChild__c/fields/ChildLkp__c.field-meta.xml
<CustomField>
    <fullName>ChildLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mapa de integração</label>
    <referenceTo>IntegrationMap__c</referenceTo>
    <relationshipLabel>Mapa da integração filha (Mapa de integração)</relationshipLabel>
    <relationshipName>Mapa_da_integra_o_filha</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/IntegrationMapChild__c/fields/ParentLkp__c.field-meta.xml
<CustomField>
    <fullName>ParentLkp__c</fullName>
    <label>Mapa de integração</label>
    <referenceTo>IntegrationMap__c</referenceTo>
    <relationshipLabel>Mapa da integração filha</relationshipLabel>
    <relationshipName>IntegratioMapParents</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/EventQueueCommandMappping.cls
public with sharing class EventQueueCommandMappping {
	
	public Map<String, IntegrationMap__c> integrationMap {get;set;}
	
	public EventQueueCommandMappping (){
		this.integrationMap = new Map<String, IntegrationMap__c>();
		
		List<IntegrationMap__c> integrationMapList = new List<IntegrationMap__c>();
		integrationMapList = IntegrationMapDAO.getAll();
		
		for (IntegrationMap__c record : integrationMapList) {
			this.integrationMap.put(record.IntegrationId__c, record);
		}
		
	}
		
	public IIntegrationService getCommand(String eventName) {
		if (!hasHandlerFor(eventName)) return new UnHandledIntegration();  
		return createIntanceFor(eventName);
	} 
	
	//to delete
	public IIntegrationService getCommand(EventQueue eventName) {
		if (!hasHandlerFor(eventName)) return new UnHandledIntegration();  
		return createIntanceFor(eventName);
	} 
		
		
	public Boolean hasHandlerFor (String eventName) {
		return this.integrationMap.containsKey(eventName);
	}	
	
	//to delete
	public Boolean hasHandlerFor (EventQueue event) {
		return this.integrationMap.containsKey(event.getEventName());
	}	
	
	public IntegrationMap__c getDeliveryInfoFor(String eventName)  {
		return integrationMap.get(eventName);		
	}
	
	/*
		Determine execution of event execution
		Eg.
			1 - Invoice
				2 - Invoice Item
				3 - another Child Item
	*/
	public List<String> getEventListOrderExecution(String eventName) {

		List<String> eventList = new List<String>();

		IntegrationMap__c intMap = integrationMap.get(eventName);
		
		//first add the main event
		eventList.add(eventName);
		
		//and add child integrations
		for (IntegrationMapChild__c child : intMap.IntegratioMapParents__r) {
			eventList.add(child.ChildLkp__r.IntegrationId__c);
		}
		
		return eventList;
		
	}

	public Map<String, IntegrationMap__c> getDeliveryInfoMap(String eventName)  {
		return integrationMap;
	}
	
	//to delete
	public IIntegrationService createIntanceFor (EventQueue event) {
		IntegrationMap__c integrationInfo = getDeliveryInfoFor(event.getEventName());	
		event.deliveryInfo = integrationInfo;
		Type commandType = Type.forName(integrationInfo.CommandClassName__c);
		IIntegrationService integrationService = (IIntegrationService) commandType.newInstance();
		return integrationService;
	}
	
	public IIntegrationService createIntanceFor (String eventName) {
		IntegrationMap__c integrationInfo = getDeliveryInfoFor(eventName);	
		//event.deliveryInfo = integrationInfo;
		Type commandType = Type.forName(integrationInfo.CommandClassName__c);
		IIntegrationService integrationService = (IIntegrationService) commandType.newInstance();
		return integrationService;
	}

}