force-app/main/default/objects/LogInterface__c/LogInterface__c.object-meta.xml
<CustomObject>
    <label>Log Interface</label>
    <nameField>
        <displayFormat>LI - {00000000}</displayFormat>
        <label>Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log Interfaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/LogInterface__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <label>Data</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/LogInterface__c/fields/FailQuantity__c.field-meta.xml
<CustomField>
    <fullName>FailQuantity__c</fullName>
    <label>Qtde. Falhas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogInterface__c/fields/Interface__c.field-meta.xml
<CustomField>
    <fullName>Interface__c</fullName>
    <label>Interface/Classe</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogInterface__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF (  FailQuantity__c == 0, &apos;Sucesso&apos;, IF (  SuccessQuantity__c == 0, &apos;Erro&apos;, &apos;Parcial&apos;))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/LogInterface__c/fields/SuccessQuantity__c.field-meta.xml
<CustomField>
    <fullName>SuccessQuantity__c</fullName>
    <label>Qtde. Sucessos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/LogInterface__c/fields/TotalQuantity__c.field-meta.xml
<CustomField>
    <fullName>TotalQuantity__c</fullName>
    <formula>FailQuantity__c + SuccessQuantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Qtde. Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SendToLogInformation__c/SendToLogInformation__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>E-mail addresses to which will be sent an e-mail with log results, right after a interface finishes its execution.</description>
    <label>Send To - Log Information</label>
</CustomObject>

force-app/main/default/classes/SendMail.cls
public with sharing class SendMail {
    /*
	public static void sendLogInterfaceMail(LogInterface__c logInterface) {
		
        List<String> 	   cc 	 		= new List<String>();
        List<String> 	   to 	 		= new List<String>();
		String 			   logMessage;

        // Retrieve all custom setting e-mails
        Map<String, SendToLogInformation__c> css = SendToLogInformation__c.getAll();

        Integer counter = 0;
        for (String cs : css.keySet()) {
            if (counter == 0) 
                to.add(css.get(cs).Email__c);
            else
                cc.add(css.get(cs).Email__c);
            
            counter++;
        }

        Map<String, Schema.SObjectField> fields = LogInterface__c.sObjectType.getDescribe().fields.getMap();
        
        logInterface = LogInterfaceBO.getInstance().getRecord(logInterface.id);
        
		logMessage = 	fields.get('Interface__c').getDescribe().getLabel()			+ ': ' + logInterface.Interface__c 			+ '\n' +
						fields.get('Status__c').getDescribe().getLabel() 			+ ': ' + logInterface.Status__c				+ '\n' +
				 	 	fields.get('Date__c').getDescribe().getLabel()				+ ': ' + logInterface.Date__c				+ '\n' +
				 	 	fields.get('FailQuantity__c').getDescribe().getLabel() 		+ ': ' + logInterface.FailQuantity__c		+ '\n' +
				 	 	fields.get('SuccessQuantity__c').getDescribe().getLabel()  	+ ': ' + logInterface.SuccessQuantity__c 	+ '\n' +
            			fields.get('TotalQuantity__c').getDescribe().getLabel()  	+ ': ' + logInterface.TotalQuantity__c 		+ '\n' +
				 	 	'Link'									  	+ ': ' + URL.getSalesforceBaseUrl().toExternalForm() + '/'  + logInterface.Id;
        
		Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
		message.setSaveAsActivity(false);
        message.setSubject('Informações de Log');
        message.setUseSignature(false);
        message.setPlainTextBody(logMessage);
        message.setToAddresses(to);
        message.setSenderDisplayName(UserInfo.getName());
        if (!cc.isEmpty())
            message.setCcAddresses(cc);
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { message });
       
	}
    */
}