force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/OrderDevolutionStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderDevolutionStatusTxt__c</fullName>
    <label>Status ordem criada</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/SinisterTxt__c.field-meta.xml
<CustomField>
    <fullName>SinisterTxt__c</fullName>
    <label>Sinistro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/ProdutoTrocado.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTrocado</fullName>
    <active>true</active>
    <businessProcess>SAC Produto trocado</businessProcess>
    <description>Abertura de caso tipo produto trocado</description>
    <label>Produto trocado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Refaturamento.recordType-meta.xml
<RecordType>
    <fullName>Refaturamento</fullName>
    <active>true</active>
    <businessProcess>SAC Refaturamento</businessProcess>
    <description>Abertura de caso refaturamento</description>
    <label>Refaturamento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicao.recordType-meta.xml
<RecordType>
    <fullName>Reposicao</fullName>
    <active>true</active>
    <businessProcess>SAC Reposição</businessProcess>
    <description>Abertura de reposição de volume ou item</description>
    <label>Reposição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sinistro.recordType-meta.xml
<RecordType>
    <fullName>Sinistro</fullName>
    <active>true</active>
    <businessProcess>SAC Sinistro</businessProcess>
    <description>Abertura de caso onde houve sinistro</description>
    <label>Sinistro</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZTRMTRemittanceBO.cls
@isTest
private class ZTRMTRemittanceBO {
    private static Map<String, Id> mapRecType;
    private static Seller__c seller;
    private static Account account;
    private static AccountAreaSales__c accountAreaSales;
    private static Contact contact;
    private static Carrier__c carrier;
    private static Product2 product;
    private static Invoice__c invoice;
    private static InvoiceItem__c invoiceItem;

    private static void init() {
        // Prepare test data
        mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
        
        seller = ULTestData.createSeller('John Doe', '1000');
        insert seller;
        
        account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
        insert account;     
        
        accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
        insert accountAreaSales;
        
        contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
        insert contact;
        
        carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
        insert carrier;
        
        product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
        insert product;
        
        invoice = ULTestData.createInvoice(carrier.Id, '02568');
        insert invoice;
        
        invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
        insert invoiceItem;
        
        
    }

    static testMEthod void testOne() {
        ZTRMTRemittanceBO.init();
        Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
        case1.OrderDevolutionStatusTxt__c = 'Processado completamente';
        insert case1;
        
        Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
        order1.CaseLkp__c = case1.Id;
        insert order1;
        
        Remittance__c remittance1 = ULTestData.createRemittance('name', null, '99902888A', Date.today(), Date.today());
        insert remittance1; 
    }

    static testMEthod void testTwo() {
        ZTRMTRemittanceBO.init();
        Case case2 = ULTestData.createCase(mapRecType.get('Sinistro'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
        case2.OrderDevolutionStatusTxt__c = 'Processado completamente';
        case2.SinisterTxt__c = 'Total';
        insert case2;
        
        Order__c order2 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '542245');
        order2.CaseLkp__c = case2.Id;
        insert order2;
        
        Remittance__c remittance2 = ULTestData.createRemittance('name', null, '42524554', Date.today(), Date.today());
        insert remittance2;    
    }

    static testMEthod void testThree() {
        ZTRMTRemittanceBO.init();
        Case case3 = ULTestData.createCase(mapRecType.get('Refaturamento'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
        case3.OrderDevolutionStatusTxt__c = 'Processado completamente';
        //case3.SinisterTxt__c = 'Total';
        insert case3;
        
        Order__c order3 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '45425542');
        order3.CaseLkp__c = case3.Id;
        insert order3;
        
        Remittance__c remittance3 = ULTestData.createRemittance('name', null, '425452', Date.today(), Date.today());
        insert remittance3;
        
    }

    static testMEthod void testFour() {
        ZTRMTRemittanceBO.init();
        Case case4 = ULTestData.createCase(mapRecType.get('ProdutoTrocado'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Quantidades iguais', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
        case4.OrderDevolutionStatusTxt__c = 'Processado completamente';
        //case3.SinisterTxt__c = 'Total';
        insert case4;
        
        Order__c order4 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '42454554');
        order4.CaseLkp__c = case4.Id;
        insert order4;
        
        Remittance__c remittance4 = ULTestData.createRemittance('name', null, '52445252', Date.today(), Date.today());
        insert remittance4;  

    }
    	
}