force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>[a10][Quota__c] Cota definida mensalmente para cada coordenador/vendedor.</description>
    <label>Planejamento</label>
    <nameField>
        <displayFormat>Cota {0000000}</displayFormat>
        <label>Nome de Planejamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/CurrentMonthTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentMonthTxt__c</fullName>
    <label>Mês Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/CurrentYearTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentYearTxt__c</fullName>
    <label>Ano Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/RevenueNmb__c.field-meta.xml
<CustomField>
    <fullName>RevenueNmb__c</fullName>
    <label>Faturamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/SalesPlanning__c.object-meta.xml
<CustomObject>
    <description>[a17][SalesPlanning__c] Planejamento de vendas definido a partir da cota do vendedor para suas contas.</description>
    <label>Planejamento de Vendas</label>
    <nameField>
        <displayFormat>Plan. {0000000}</displayFormat>
        <label>Nome de Planejamento de Vendas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/fields/CurrentMonthTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentMonthTxt__c</fullName>
    <label>Mês Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/CurrentYearTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentYearTxt__c</fullName>
    <label>Ano Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
                <default>true</default>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/RevenueNmb__c.field-meta.xml
<CustomField>
    <fullName>RevenueNmb__c</fullName>
    <label>Faturamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SummarizedRevenue__c/SummarizedRevenue__c.object-meta.xml
<CustomObject>
    <description>[SummarizedRevenue__c] Faturamentos sumarizados, originados no BI</description>
    <label>Faturamento Sumarizado</label>
    <nameField>
        <label>Nome de Faturamento Sumarizado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos Sumarizados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SummarizedRevenue__c/fields/DateDt__c.field-meta.xml
<CustomField>
    <fullName>DateDt__c</fullName>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SummarizedRevenue__c/fields/ROBNmb__c.field-meta.xml
<CustomField>
    <fullName>ROBNmb__c</fullName>
    <label>ROB s/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Test_SummarizedRevenueTriggerHandler.cls
@isTest
private class Test_SummarizedRevenueTriggerHandler {
    
    @isTest static void testAfter(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        Account acct = TestData.createAccount('Test Account', null, null, rtSACAcc);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, null);
        SummarizedRevenue__c sr = TestData.createSummarizedRevenue('TestSummarizedRevenue', '1132143', salesArea.Id);
        
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User u = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', u.Id);
        Seller__c sel = TestData.createSeller('TestSeller', u.Id, so.Id);
		Quota__c quota = TestData.createQuota(sel, '2018', '01', 'Atingimento de Cota', u);        
        //SalesPlanning__c sp = TestData.createSalesPlanning(salesArea.Id, null, null);
        SalesPlanning__c sp = TestData.createSalesPlanning(salesArea.Id, null, quota.Id);
        
        Date myDate = Date.Today();
        sp.CurrentYearTxt__c = String.valueOf(myDate.year());
        sp.CurrentMonthTxt__c = '0' + String.valueOf(myDate.month());
        update sp;
        sp = [Select Id, RevenueNmb__c
              From SalesPlanning__c
              Where Id =: sp.Id];
        System.assertEquals(null, sp.RevenueNmb__c);
        sr.ROBNmb__c = 100.10;
        sr.DateDt__c = Date.Today();
        update sr;
        sp = [Select Id, RevenueNmb__c
              From SalesPlanning__c
              Where Id =: sp.Id];
        System.assertEquals(100.10, sp.RevenueNmb__c);
    }
}