force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/recordTypes/Reclamacao.recordType-meta.xml
<RecordType>
    <fullName>Reclamacao</fullName>
    <active>true</active>
    <businessProcess>SAC Reclamação</businessProcess>
    <description>Abertura de reclamação de produto</description>
    <label>Reclamação</label>
</RecordType>

force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZTItensCasoController.cls
@isTest
private class ZTItensCasoController
{
    static testMethod void testAll()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Entitlement entitlement = ULTestData.createEntitlement(account.Id, 'Name');
    	insert entitlement;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	Case aCase = ULTestData.createCase(mapRecType.get('Reclamacao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Elogio', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert aCase;
    	
    	CaseItem__c caseItem1 = ULTestData.createCaseItem(aCase.Id, '999550000037unAAAQ01t55000000JhBjAAK', 'failureType', 'comments', 'qualityProblem');
    	caseItem1.ProductLkp__c = product.Id;
    	insert caseItem1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ApexPages.StandardController std = new ApexPages.StandardController(aCase);
		
		// create controller
    	ItensCasoController ctrl = new ItensCasoController(std);
    	
    	// call methods
    	ctrl.save();
    	ctrl.refresh();
    	ctrl.doBack();
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		//System.assert(lstAccountAddress != null);
    }
}