force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Opty_Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Opty_Sales_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>AccountAreaSales__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Cliente Concorrência</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_OpportunityTriggerHandler.cls
@isTest
private class Test_OpportunityTriggerHandler {
    
    @isTest static void testOpp(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        Account acc = TestData.createAccount('TestAccount', null, null, rtSACAcc);
        AccountAreaSales__c sa = TestData.createAccountAreaSales(acc.Id, null, null);
        Opportunity oppWithSA = TestData.createOpportunity('TestOpportunity', 'Qualificação', null, sa.Id);
        oppWithSA = [Select Id, AccountId
               From Opportunity
               Where Id =: oppWithSA.Id];
        Opportunity oppWithAcc = TestData.createOpportunity('TestOpp', 'Qualificação', acc.Id, null);
        oppWithAcc = [Select Id, Opty_Sales_Area__c
               From Opportunity
               Where Id =: oppWithAcc.Id];
        System.assertEquals(acc.Id, oppWithSA.AccountId);
        System.assertEquals(sa.Id, oppWithAcc.Opty_Sales_Area__c);
    }

}