force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/NotSendemailBln__c.field-meta.xml
<CustomField>
    <fullName>NotSendemailBln__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Caso selecionado não será enviado email automático a partir do caso.</inlineHelpText>
    <label>Não enviar email automático</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <businessProcess>SAC Devolução</businessProcess>
    <description>Abertura de devolução de produto</description>
    <label>Devolução</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reclamacao.recordType-meta.xml
<RecordType>
    <fullName>Reclamacao</fullName>
    <active>true</active>
    <businessProcess>SAC Reclamação</businessProcess>
    <description>Abertura de reclamação de produto</description>
    <label>Reclamação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicao.recordType-meta.xml
<RecordType>
    <fullName>Reposicao</fullName>
    <active>true</active>
    <businessProcess>SAC Reposição</businessProcess>
    <description>Abertura de reposição de volume ou item</description>
    <label>Reposição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Substituicao.recordType-meta.xml
<RecordType>
    <fullName>Substituicao</fullName>
    <active>true</active>
    <businessProcess>SAC Substituição</businessProcess>
    <description>Abertura de substituição de produto</description>
    <label>Substituição</label>
</RecordType>

force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>Itens_da_nota_fiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ZTItensCasoBO.cls
@isTest
private class ZTItensCasoBO
{
    static testMethod void testReposicaoItem()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
    
    static testMethod void testReposicaoVolume()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Volume', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	case1.NotSendemailBln__c = true;
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
    
    static testMethod void testReposicaoOutro()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Outro', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
    
    static testMethod void testDevolucao()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Devolucao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	system.debug(case1.AccountId);
        insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
	
	static testMethod void testSubstituicao()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Substituicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	CaseItem__c caseItem1 = ULTestData.createCaseItem(case1.Id, '999550000037unAAAQ01t55000000JhBjAAK', 'failureType', 'comments', 'qualityProblem');
    	caseItem1.ProductLkp__c = product.Id;
    	insert caseItem1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
    
    static testMethod void testReclamacaoWithItem()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reclamacao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	CaseItem__c caseItem1 = ULTestData.createCaseItem(case1.Id, '999550000037unAAAQ01t55000000JhBjAAK', 'failureType', 'comments', 'qualityProblem');
    	insert caseItem1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
    
    static testMethod void testReclamacaoWithoutItem()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reclamacao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	ItensCasoBO itensCasoBO = new ItensCasoBO(case1.Id);
    	
    	// call getters
    	String var01 = itensCasoBO.Comments;
    	String var02 = itensCasoBO.QualityProblem;
    	
    	// call methods
    	Boolean test01 = itensCasoBO.isReclamacao();
		Boolean test02 = itensCasoBO.isSubstituicao();
    	Boolean test03 = itensCasoBO.canEditProduct();
    	Boolean test04 = itensCasoBO.getShowProdutoTrocado();
    	Boolean test05 = itensCasoBO.getShowComments();
    	Boolean test06 = itensCasoBO.getShowQualityProblem();
    	List<SelectOption> test07 = itensCasoBO.getFailureOptions();
    	List<CaseItemVO> test08 = itensCasoBO.loadCaseItemVO(case1.Id); 
    	
    	// Stop Test
		System.Test.stopTest();
    }
}