force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/SinisterTxt__c.field-meta.xml
<CustomField>
    <fullName>SinisterTxt__c</fullName>
    <label>Sinistro</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Parcial</fullName>
            </value>
            <value>
                <fullName>Total</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <businessProcess>SAC Devolução</businessProcess>
    <description>Abertura de devolução de produto</description>
    <label>Devolução</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ExtravioNotaFiscal.recordType-meta.xml
<RecordType>
    <fullName>ExtravioNotaFiscal</fullName>
    <active>true</active>
    <businessProcess>SAC Extravio de nota fiscal</businessProcess>
    <description>Abertura caso extravio de nota fiscal</description>
    <label>Extravio de nota fiscal</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ProdutoTrocado.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTrocado</fullName>
    <active>true</active>
    <businessProcess>SAC Produto trocado</businessProcess>
    <description>Abertura de caso tipo produto trocado</description>
    <label>Produto trocado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reclamacao.recordType-meta.xml
<RecordType>
    <fullName>Reclamacao</fullName>
    <active>true</active>
    <businessProcess>SAC Reclamação</businessProcess>
    <description>Abertura de reclamação de produto</description>
    <label>Reclamação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Refaturamento.recordType-meta.xml
<RecordType>
    <fullName>Refaturamento</fullName>
    <active>true</active>
    <businessProcess>SAC Refaturamento</businessProcess>
    <description>Abertura de caso refaturamento</description>
    <label>Refaturamento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicao.recordType-meta.xml
<RecordType>
    <fullName>Reposicao</fullName>
    <active>true</active>
    <businessProcess>SAC Reposição</businessProcess>
    <description>Abertura de reposição de volume ou item</description>
    <label>Reposição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sinistro.recordType-meta.xml
<RecordType>
    <fullName>Sinistro</fullName>
    <active>true</active>
    <businessProcess>SAC Sinistro</businessProcess>
    <description>Abertura de caso onde houve sinistro</description>
    <label>Sinistro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Substituicao.recordType-meta.xml
<RecordType>
    <fullName>Substituicao</fullName>
    <active>true</active>
    <businessProcess>SAC Substituição</businessProcess>
    <description>Abertura de substituição de produto</description>
    <label>Substituição</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/InvoiceItem__c/InvoiceItem__c.object-meta.xml
<CustomObject>
    <description>[a0A][InvoiceItem__c] Itens da Nota fiscal.</description>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>NF-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderStatusTxt__c</fullName>
    <label>Status da ordem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>InApproval</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>SentToSAP</fullName>
                <label>Enviado SAP</label>
            </value>
            <value>
                <fullName>Não processado</fullName>
            </value>
            <value>
                <fullName>Processado parcialmente</fullName>
            </value>
            <value>
                <fullName>Processado completamente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeTxt__c</fullName>
    <label>Código do Tipo de ordem</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZTCSEOrderBO.cls
@isTest
private class ZTCSEOrderBO
{
    static testMethod void testOrderSubstituicao()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Substituicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
		Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'Cancelada';
    	insert order1;
    	
    	order1.OrderStatusTxt__c = 'Cancelada';
    	update order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderRefaturamento()
    {
        // Prepare test data
        Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
        
        Seller__c seller = ULTestData.createSeller('John Doe', '1000');
        insert seller;
        
        Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
        insert account;     
        
        AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
        insert accountAreaSales;
        
        Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
        insert contact;
        contact.Email = 'teste@testecontato.com';
        update contact;
        
        Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
        insert carrier;
        
        Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
        insert product;
        
        Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
        insert invoice;
        
        InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
        insert invoiceItem;
        
        Case case1 = ULTestData.createCase(mapRecType.get('Refaturamento'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
        insert case1;
        
        // Start Test
        System.Test.startTest();
        
        Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
        order1.CaseLkp__c = case1.Id;
        order1.OrderStatusTxt__c = 'Não processado';
        order1.OrderTypeTxt__c = 'ZDOP';
        insert order1;
        
        order1.OrderStatusTxt__c = 'Processado complatamente';
        update order1;

        Order__c order2 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998714');
        order2.CaseLkp__c = case1.Id;
        order2.OrderStatusTxt__c = 'Não processado';
        order2.OrderTypeTxt__c = 'ZDSO';
        insert order2;
        
        order2.OrderStatusTxt__c = 'Processado complatamente';
        update order2;
        
        
        // Stop Test
        System.Test.stopTest();
        
        // Verify data
        System.assert(order1 != null);
    }
    
    static testMethod void testSetStatusCase()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Substituicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'Cancelada';
    	insert order1;
    	
    	// Start Test
		System.Test.startTest();
		
    	CSEOrderBO orderBO = new CSEOrderBO();
    	orderBO.setStatusCase(new List<Order__c>{order1});
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderReposicao_StatusAberto()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	case1.Status = 'Aberto';
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'Processado completamente';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderReposicao_StatusNaoCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	case1.Status = 'Aguardando amostra';
    	update case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderReposicao_StatusCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reposicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'Cancelada';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderExtravioNotaFiscal_StatusNaoCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('ExtravioNotaFiscal'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	case1.Status = 'Aguardando amostra';
    	update case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';

		try {
    		insert order1;
		}
    	catch (Exception ex) {}
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderSinistro_StatusNaoCanceladaParcial()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Sinistro'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	case1.SinisterTxt__c = 'Total';
    	insert case1;
    	
    	case1.Status = 'Aguardando amostra';
    	update case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderSinistro_StatusNaoCanceladaTotal()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Sinistro'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	case1.SinisterTxt__c = 'Parcial';
    	insert case1;
    	
    	case1.Status = 'Aguardando amostra';
    	update case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderReclamacao_StatusNaoCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Reclamacao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert case1;
    	
    	case1.Status = 'Aguardando amostra';
    	update case1;
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderDevolucao_StatusNaoCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('Devolucao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');

		try {
    		insert case1;
		}
		catch (Exception ex) {}
    	
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
    
    static testMethod void testOrderProdutoTrocado_StatusNaoCancelada()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
    	Seller__c seller = ULTestData.createSeller('John Doe', '1000');
    	insert seller;
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	AccountAreaSales__c accountAreaSales = ULTestData.createAccountAreaSales(account.Id, seller.Id, '999333AM01RVPR00009090');
    	insert accountAreaSales;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Product2 product = ULTestData.createProduct('FITA VIDEO', '900000000000001010');
    	insert product;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	InvoiceItem__c invoiceItem = ULTestData.createInvoiceItem(invoice.Id, product.Id, '394368000010', 10);
    	insert invoiceItem;
    	
    	Case case1 = ULTestData.createCase(mapRecType.get('ProdutoTrocado'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aguardando nota fiscal de devolução', 'Item', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	case1.Type = 'Quantidades iguais';

		try {
    		insert case1;
		}
		catch (Exception ex) {}
		
    	// Start Test
		System.Test.startTest();
		
    	Order__c order1 = ULTestData.createOrder(account.Id, accountAreaSales.Id, '9998713');
    	order1.CaseLkp__c = case1.Id;
    	order1.OrderStatusTxt__c = 'xpto';
    	order1.OrderTypeTxt__c = 'ZDOP';
    	insert order1;
    	
    	// Stop Test
		System.Test.stopTest();
		
		// Verify data
		System.assert(order1 != null);
    }
}