force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/recordTypes/Substituicao.recordType-meta.xml
<RecordType>
    <fullName>Substituicao</fullName>
    <active>true</active>
    <businessProcess>SAC Substituição</businessProcess>
    <description>Abertura de substituição de produto</description>
    <label>Substituição</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZTUniqueIdConfigurator.cls
@isTest
private class ZTUniqueIdConfigurator
{
    static testMethod void testAll()
    {
    	// Prepare test data
    	Map<String, Id> mapRecType = RecordTypeDAO.selectRecordTypeDevNameMapByObjectNameSetCached(new Set<String>{'Account', 'Contact', 'Case'});
    	
		RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = ULTestData.createAccount(mapRecType.get('BusinessAccountSAC'), 'Testador da pagina', '26830528000181');
    	insert account;    	
    	
    	Entitlement entitlement = ULTestData.createEntitlement(account.Id, 'Name');
    	insert entitlement;
    	
    	Contact contact = ULTestData.createContact(mapRecType.get('ContactSAC'), account.Id, 'Testa', 'Tudo');
    	insert contact;
    	
    	Carrier__c carrier = ULTestData.createCarrier('Transporta tudo', 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Invoice__c invoice = ULTestData.createInvoice(carrier.Id, '02568');
    	insert invoice;
    	
    	Case aCase = ULTestData.createCase(mapRecType.get('Substituicao'), account.Id, contact.Id, invoice.Id, 'Reclamação não procede', 'Aberto', 'Elogio', 'Transportadora', 'Email', 'email@seller.com', 'email@carrier.com');
    	insert aCase;
    	
    	// Start Test
		System.Test.startTest();
		
    	UniqueIdConfigurator con = new UniqueIdConfigurator();
    	con.configure(Case.CustomIdTxt__c, new List<SObject>{aCase}, new List<Schema.SObjectField>{Case.CustomIdTxt__c});
    	
    	// Stop Test
		System.Test.stopTest();
    }
}