force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/DistributionCenterTxt__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenterTxt__c</fullName>
    <label>Centro de Distribuição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DistributionCenter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ItemStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalGrossCostNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossCostNmb__c</fullName>
    <label>Valor total bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/StatusItemOrdem__c/StatusItemOrdem__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Status de Item da Ordem</label>
</CustomObject>

force-app/main/default/objects/StatusItemOrdem__c/fields/StatusValue__c.field-meta.xml
<CustomField>
    <fullName>StatusValue__c</fullName>
    <label>Valor do status</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_OrderItemTriggerHandler.cls
@isTest
private class Test_OrderItemTriggerHandler {
    
    @isTest static void testOrderItem(){
        StatusItemOrdem__c statusItem = new StatusItemOrdem__c(Name = 'LIMITE CREDITO', StatusValue__c = 1);
        insert statusItem;
        statusItem = new StatusItemOrdem__c(Name = 'POLITICA COMERCIAL', StatusValue__c = 2);
        insert statusItem;
        statusItem = new StatusItemOrdem__c(Name = 'AJUSTE DE ORDEM', StatusValue__c = 3);
        insert statusItem;
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Account acct = TestData.createAccount('Test Account', null, null, rtSAPAcc);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, null);
        OrderType__c ordType = TestData.createOrderType('ZNOV');
        Order__c ord = TestData.createOrder(salesArea.Id, null, ordtype.Id, null, '131242114214');
        OrderItem__c ordItem = TestData.createOrderItem(null, ord.Id, null, null);
        ordItem.StatusTxt__c = 'POLITICA COMERCIAL';
        update ordItem;
        ordItem = new OrderItem__c(OrderMdt__c = ord.Id, StatusTxt__c = 'LIMITE CREDITO');
        ordItem.TotalGrossCostNmb__c = 12;
        insert ordItem;
        ordItem.StatusTxt__c = 'AJUSTE DE ORDEM';
        ordItem.DistributionCenterTxt__c = '0100';
        /*ordItem = TestData.createOrderItem(null, ord.Id, null, null);
        ordItem.StatusTxt__c = 'LIMITE CREDITO';
        update ordItem;
        ordItem.StatusTxt__c = 'CADASTRO';
        ordItem.DistributionCenterTxt__c = '0100';*/
        update ordItem;

        delete ordItem;
        
    }

}