force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/OrderTypeLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente com ZNOV caso deixe em branco</inlineHelpText>
    <label>Tipo de Ordem</label>
    <referenceTo>OrderType__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderType__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotação</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Pedido</fullName>
                <isActive>false</isActive>
                <label>Pedido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_CustomFileUploadController.cls
@isTest
private class Test_CustomFileUploadController {
    @isTest static void testAll(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
        Product2 prod1 = TestData.createProduct('11544', 10);
        Product2 prod2 = TestData.createProduct('11560', 8);
        Product2 prod3 = TestData.createProduct('11609', 5);
        Product2 prod4 = TestData.createProduct('11586', 5);
        Product2 prod5 = TestData.createProduct('11587', 5);
        Product2 prod6 = TestData.createProduct('11588', 5);
        Product2 prod7 = TestData.createProduct('11589', 5);
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Account acct = TestData.createAccount('Test Account', null, null, rtSAPAcc);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, null);
        
        OrderType__c ordType = TestData.createOrderType('ZCOV');
        //zcov -- ZNOV
        system.debug('ZCOV');
        system.debug(ordtype.Id);
        Order__c ord = TestData.createOrder(salesArea.Id, null, ordtype.Id, null, '131242114');
        
        //ord.OrderTypeLkp__r.Category__c='Cotação';
        
        PageReference myVfPage = Page.fileupload;
		Test.setCurrentPage(myVfPage);
        
        
        ApexPages.currentPage().getParameters().put('id',ord.Id);
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(ord);
        CustomFileUploadController controller = new CustomFileUploadController(stdController);
        controller.contentType='application/vnd.ms-excel';
        
        String myString = 'Item;Quantidade;Preco \n' + 
            				'11544;600;10 \n' +
            				'11560;600;10 \n' +
							'11585;70;11 \n' +
            				'11586;70;A \n' +
            				'11587;70;0 \n' +
            				'11588;70,4;11 \n' +
           					'11589;7;11 \n' +
							'11609;500;1,5';
        System.debug(myString);
		Blob myBlob = Blob.valueof(myString);
        
        controller.contentFile=myBlob;
        //ApexPages.currentPage().getParameters().put('contentType','application/vnd.ms-excel');
		//String sContentFile = 'Item;Quantidade;Preco';
		//Blob ContentBlob = Blob.valueof(sContentFile);       
        //ApexPages.currentPage().getParameters().put('contentFile',sContentFile);
        
        system.debug(controller.contentType);       
        
        controller.ReadFile();
        
        controller.AdjustDiscounts();
        
        myString = 'Item;Quantidade \n' + 
            '11544;600 \n' +
            '11560;600 \n' +
            '11585;70 \n' +
            '11609;500';
        myBlob=Blob.valueof(myString);
        //ord.OrderTypeLkp__r.Category__c='Cotação';
        
        //System.debug(myString);
        //Blob myBlob = Blob.valueof(myString);
        controller.ReadFile();
    }
     
}