force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/LiquidNmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidNmb__c</fullName>
    <label>Valor líquido</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OriginalROBNoIPINmb__c.field-meta.xml
<CustomField>
    <fullName>OriginalROBNoIPINmb__c</fullName>
    <label>ROB s/ IPI Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalGrossCostNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossCostNmb__c</fullName>
    <label>Valor total bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_OrderSummaryController.cls
@isTest
private class Test_OrderSummaryController {
    
    @isTest static void testGetSystemsAndGroups(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, null, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV');
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '321312313213');
		Product2 prod = TestData.createProduct('TestProduct');
        OrderItem__c ordi = TestData.createOrderItem(prod.Id, ord.Id, null, null);
        
        //Teste Caio 20/04
        ordi.OriginalROBNoIPINmb__c = 120;
        ordi.TotalGrossCostNmb__c = 150;
        ordi.LiquidNmb__c = 120;
        update ordi;
        
        string testSystem = OrderSummaryController.getSystems(ord.Id);
        string testGroup = OrderSummaryController.getGroups(ord.Id);
        system.debug(testSystem);
        system.debug(testGroup);
        System.assertEquals('[{"weight":5.5,"systemDscrp":"Água Fria","systemCode":"1000","itemCount":1,"grossAmountWOIPI":120.0,"grossAmountIPI":150.0,"amountWTaxes":120.0}]', testSystem);
        System.assertEquals('[{"weight":5.5,"itemCount":1,"groupDscrp":"Tubos","groupCode":"01","grossAmountWOIPI":120.0,"grossAmountIPI":150.0,"amountWTaxes":120.0}]', testGroup);
    }

}