force-app/main/default/objects/SalesPlanning__c/SalesPlanning__c.object-meta.xml
<CustomObject>
    <description>[a17][SalesPlanning__c] Planejamento de vendas definido a partir da cota do vendedor para suas contas.</description>
    <label>Planejamento de Vendas</label>
    <nameField>
        <displayFormat>Plan. {0000000}</displayFormat>
        <label>Nome de Planejamento de Vendas</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos de Vendas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesPlanning__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Área de vendas</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Planejamentos de Vendas</relationshipLabel>
    <relationshipName>Planejamentos_de_Vendas</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/CurrentMonthTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentMonthTxt__c</fullName>
    <label>Mês Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/CurrentYearTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentYearTxt__c</fullName>
    <label>Ano Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2017</fullName>
                <default>true</default>
                <label>2017</label>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesPlanning__c/fields/RevenueNmb__c.field-meta.xml
<CustomField>
    <fullName>RevenueNmb__c</fullName>
    <label>Faturamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SummarizedRevenue__c/SummarizedRevenue__c.object-meta.xml
<CustomObject>
    <description>[SummarizedRevenue__c] Faturamentos sumarizados, originados no BI</description>
    <label>Faturamento Sumarizado</label>
    <nameField>
        <label>Nome de Faturamento Sumarizado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos Sumarizados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SummarizedRevenue__c/fields/DateDt__c.field-meta.xml
<CustomField>
    <fullName>DateDt__c</fullName>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SummarizedRevenue__c/fields/ROBNmb__c.field-meta.xml
<CustomField>
    <fullName>ROBNmb__c</fullName>
    <label>ROB s/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SummarizedRevenue__c/fields/SalesAreaLkp__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaLkp__c</fullName>
    <label>Área de Negócios</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Faturamentos Sumarizados</relationshipLabel>
    <relationshipName>Faturamentos_Sumarizados</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SalesPlanUtil.cls
public class SalesPlanUtil {
    
    public static void processSummarizedRevenue(List<SummarizedRevenue__c> records){
        //Based on a list of SummarizedRevenue__c, updates Sales Planning records
        List<Id> areaSalesIdList = new List<Id>();
        Set<Date> dateSet = new Set<Date>(); 
        
        for(SummarizedRevenue__c s : records){
            areaSalesIdList.add(s.SalesAreaLkp__c);
            dateSet.add(s.DateDt__c);
        }
        
        List<SalesPlanning__c> salesPlanningList = [SELECT Id, Name, AccountAreaSalesLkp__c, CurrentMonthTxt__c, CurrentYearTxt__c
                                                    FROM SALESPLANNING__C WHERE AccountAreaSalesLkp__c IN :areaSalesIdList];

        List<Id> areaSalesWithPlanIdLIst = new List<Id>();
        
        for(SalesPlanning__c s: salesPlanningList){
            areaSalesWithPlanIdList.add(s.AccountAreaSalesLkp__c);
        }

        Map<String, Double> aggResultMap = new Map<String, Double>();
        for(Date d : dateSet){
            AggregateResult[] groupedResults = [SELECT 
                                                SUM(ROBNmb__c) sum, SalesAreaLkp__c 
                                                FROM SUMMARIZEDREVENUE__c 
                                                WHERE SalesAreaLkp__c IN :areaSalesWithPlanIdLIst AND DateDt__c = :d
                                                GROUP BY SalesAreaLkp__c];  
            
            System.debug(groupedResults);
            
            for(AggregateResult agg: groupedResults){
            	String key = String.valueOf(d.month()).leftPad(2, '0') + ' - ' + d.year() + ' - ' + agg.get('SalesAreaLkp__c');
                System.debug('CHAVE A PARTIR DO AGG RESULT: '+key);
                aggResultMap.put(key, (Double)agg.get('sum'));	    
                System.debug('VALOR SUMARIZADO: '+(Double)agg.get('sum'));
            }
        }
        
        for(SalesPlanning__c salesPlan : salesPlanningList){
            String key = salesPlan.CurrentMonthTxt__c + ' - ' + salesPlan.CurrentYearTxt__c + ' - ' + salesPlan.AccountAreaSalesLkp__c;
            System.debug('CHAVE A PARTIR DO PLANEJAMENTO: '+key);
            
            if(aggResultMap.containsKey(key)){
                salesPlan.RevenueNmb__c = aggResultMap.get(key);
                System.debug(salesPlan.Id);
                System.debug('NOVO VALOR REGISTRO: '+salesPlan.RevenueNmb__c);
            }
        }
        
        upsert salesPlanningList;        
    }
}