force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>[a10][Quota__c] Cota definida mensalmente para cada coordenador/vendedor.</description>
    <label>Planejamento</label>
    <nameField>
        <displayFormat>Cota {0000000}</displayFormat>
        <label>Nome de Planejamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/CurrentMonthTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentMonthTxt__c</fullName>
    <label>Mês Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/CurrentYearTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentYearTxt__c</fullName>
    <label>Ano Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/TotalValueNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalValueNmb__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AddQuotas.cls
public class AddQuotas {    
    /*
    public Quota__c quota;
    public Quota__c refQuota;
    public Quota__c del;    
    public Quota__c newQuota;
    public List<User> usersList = new List<User>();    
    public List<Quota__c> quotaList {get;set;}
    public List<Quota__c> addQuotaList {get;set;}       
    public Integer rowIndex {get;set;}
    public double value = 0;
    public double sumValue {get;set;}
    public double remainingAmount;
    
    public AddQuotas(ApexPages.StandardController controller) {                
        
        refQuota = (Quota__c) controller.getRecord();
        this.quota = [Select Id, Owner.UserRoleId, TotalValueNmb__c, CurrentMonthTxt__c, CurrentYearTxt__c From Quota__c Where id =: refQuota.id];                                                     
        
        quotaList = new List<Quota__c>();
        
        quotaList = [SELECT Id, TotalValueNmb__c, CurrentMonthTxt__c, CurrentYearTxt__c, OwnerId
                     FROM Quota__c 
        
                    ];
        
        usersList = [SELECT Id, Name, UserRoleId, Profile.Name
                     FROM User
                     WHERE IsActive = true
                     AND UserRoleId IN (SELECT Id
                                         FROM UserRole
                                         Where ParentRoleId =: quota.Owner.UserRoleId
                                        )
                     AND Id NOT IN (SELECT OwnerId
                                    FROM Quota__c

                                    )
                    ];                                        
        
        set<User> usersSet = new set<User>();
        usersSet.addAll(usersList);
        system.debug('usuários:' +usersSet);
        
        
        
                       
        if(usersSet.size() > 0){
            for(user childUser : usersSet){
                Quota__c childQuota = new Quota__c();
                childQuota.OwnerId = childUser.Id;            
                childQuota.CurrentMonthTxt__c = quota.CurrentMonthTxt__c;
                childQuota.CurrentYearTxt__c = quota.CurrentYearTxt__c; 
                
                if(childUser.Profile.Name == 'Vendedor' || childUser.Profile.Name == 'Representante' ||childUser.Profile.Name == 'Partner Community User' || childUser.Profile.Name == 'Representante Partner'){
                    childQuota.RecordTypeId = Schema.SObjectType.Quota__c.getRecordTypeInfosByName().get('Cota de Vendas').getRecordTypeId();
                } else {
                    childQuota.RecordTypeId = Schema.SObjectType.Quota__c.getRecordTypeInfosByName().get('Cota de Coordenador').getRecordTypeId();
                }
                quotaList.add(childQuota);
            }                
            
            
            else { 
                childQuota.CurrentMonthTxt__c = quota.CurrentMonthTxt__c;
                childQuota.CurrentYearTxt__c = quota.CurrentYearTxt__c;                                   
                quotaList.add(childQuota);
            }
            
        }

    }
    
    public void addRow() {        
        
        addQuotaList = new List<Quota__c> ();
        newQuota = new Quota__c();        
        newQuota.CurrentMonthTxt__c = quota.CurrentMonthTxt__c;
        newQuota.CurrentYearTxt__c = quota.CurrentYearTxt__c;
       
        quotaList.add(newQuota);
        
    }
    
    public void deleteRow() {
        
        rowIndex = Integer.valueOf(ApexPages.currentPage().getParameters().get('rowIndex'));
        del = quotaList.remove(rowIndex);        
        
    }
    
    public void save() {           
        
        try{    
            for (Quota__c quotaValue: quotaList){            
                if(quotaValue.TotalValueNmb__c != null){
                    value = value + quotaValue.TotalValueNmb__c;
                } else {
                    quotaValue.TotalValueNmb__c = 0;
                }
            }
            
            if(value == 0){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Insira um valor para as cotas distribuídas.'));    
            }
            
            if(value > quota.TotalValueNmb__c){
                upsert quotaList;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'O valor total das cotas distribuídas é maior do que a sua cota.'));                    
                value = 0;                       
            }
            
            if(value < quota.TotalValueNmb__c && value != 0)    {
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,'Sua cota não foi totalmente distribuída. Não foram criadas novas cotas.'));
                value = 0;            
            }                                
            
            if (value == quota.TotalValueNmb__c){
                for (integer i = 0; i < quotaList.size(); i++){            
                    if(quotaList.get(i).TotalValueNmb__c == 0){                  
                        quotaList.remove(i);
                        i=i-1;
                    }        
                } 
                upsert quotaList;
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.INFO,'Sua cota foi distribuída com sucesso!'));
                value = 0;
            }
        } catch (Exception ex){
            ApexPages.addMessages(ex);             
            }
        
    }
    
    public Double getRemainingAmount(){
        
        sumValue = 0;
        analisa os valores dos planejamentos que estão sendo criados.            
        for (Quota__c quotaValue: quotaList){            
            if(quotaValue.TotalValueNmb__c != null){
                sumValue = sumValue + quotaValue.TotalValueNmb__c;
            } else {
                quotaValue.TotalValueNmb__c = 0;
                sumValue = sumValue + quotaValue.TotalValueNmb__c;
            }
        }
        system.debug('run');
        remainingAmount = quota.TotalValueNmb__c - sumValue;        
        
        return remainingAmount;
    }    
    
    public PageReference returnToQuota(){
        
        PageReference pageRef = new PageReference('/apex/AddQuotasPage');
        pageRef.getParameters().put('id',quota.Id);               
        PageReference pageRef2 = new PageReference('/' + quota.Id);                               
        value = 0;
        //return pageRef;
                    
        return pageRef2;
    }
	*/
}