force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>[a10][Quota__c] Cota definida mensalmente para cada coordenador/vendedor.</description>
    <label>Planejamento</label>
    <nameField>
        <displayFormat>Cota {0000000}</displayFormat>
        <label>Nome de Planejamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/fields/CurrentMonthTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentMonthTxt__c</fullName>
    <label>Mês Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01</fullName>
                <default>true</default>
                <label>Janeiro</label>
            </value>
            <value>
                <fullName>02</fullName>
                <label>Fevereiro</label>
            </value>
            <value>
                <fullName>03</fullName>
                <label>Março</label>
            </value>
            <value>
                <fullName>04</fullName>
                <label>Abril</label>
            </value>
            <value>
                <fullName>05</fullName>
                <label>Maio</label>
            </value>
            <value>
                <fullName>06</fullName>
                <label>Junho</label>
            </value>
            <value>
                <fullName>07</fullName>
                <label>Julho</label>
            </value>
            <value>
                <fullName>08</fullName>
                <label>Agosto</label>
            </value>
            <value>
                <fullName>09</fullName>
                <label>Setembro</label>
            </value>
            <value>
                <fullName>10</fullName>
                <label>Outubro</label>
            </value>
            <value>
                <fullName>11</fullName>
                <label>Novembro</label>
            </value>
            <value>
                <fullName>12</fullName>
                <label>Dezembro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/CurrentYearTxt__c.field-meta.xml
<CustomField>
    <fullName>CurrentYearTxt__c</fullName>
    <label>Ano Vigente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
            <value>
                <fullName>2026</fullName>
            </value>
            <value>
                <fullName>2027</fullName>
            </value>
            <value>
                <fullName>2028</fullName>
            </value>
            <value>
                <fullName>2029</fullName>
            </value>
            <value>
                <fullName>2030</fullName>
            </value>
            <value>
                <fullName>2031</fullName>
            </value>
            <value>
                <fullName>2032</fullName>
            </value>
            <value>
                <fullName>2033</fullName>
            </value>
            <value>
                <fullName>2034</fullName>
            </value>
            <value>
                <fullName>2035</fullName>
            </value>
            <value>
                <fullName>2036</fullName>
            </value>
            <value>
                <fullName>2037</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/IdentifierTxt__c.field-meta.xml
<CustomField>
    <fullName>IdentifierTxt__c</fullName>
    <externalId>true</externalId>
    <label>Identificador</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Quota__c/fields/OrderBacklogNmb__c.field-meta.xml
<CustomField>
    <fullName>OrderBacklogNmb__c</fullName>
    <label>Carteira</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/QuotaTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>QuotaTypeTxt__c</fullName>
    <label>Tipo de Cota</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001</fullName>
                <label>ROL Total</label>
            </value>
            <value>
                <fullName>002</fullName>
                <label>ROL de Conexões</label>
            </value>
            <value>
                <fullName>013</fullName>
                <label>Positivação Varejos</label>
            </value>
            <value>
                <fullName>021</fullName>
                <label>SUPERCPVC</label>
            </value>
            <value>
                <fullName>010</fullName>
                <label>ROL de Tubos</label>
            </value>
            <value>
                <fullName>014</fullName>
                <label>Positivação Cliente</label>
            </value>
            <value>
                <fullName>018</fullName>
                <label>ROL Água Quente</label>
            </value>
            <value>
                <fullName>025</fullName>
                <label>ROL/Kg</label>
            </value>
            <value>
                <fullName>027</fullName>
                <label>BIAX PN 12,5</label>
            </value>
            <value>
                <fullName>028</fullName>
                <label>BIAX PN 16</label>
            </value>
            <value>
                <fullName>029</fullName>
                <label>ROL Total Lançamentos/Produtos</label>
            </value>
            <value>
                <fullName>003</fullName>
                <label>Microaspersão Gotejamento</label>
            </value>
            <value>
                <fullName>005</fullName>
                <label>ROL Água Fria</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quota__c/fields/RevenueNmb__c.field-meta.xml
<CustomField>
    <fullName>RevenueNmb__c</fullName>
    <label>Faturamento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>Cotas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quota__c/fields/TotalValueNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalValueNmb__c</fullName>
    <label>Valor Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <externalId>true</externalId>
    <label>Código do vendedor</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuotaIntegrationUtils.cls
public class QuotaIntegrationUtils {
    
    @AuraEnabled
    public static void execBatchApex(){
        System.debug('AAAAAAAAAAA');
        Batch_QuotaDailyUpdate myBatch = new Batch_QuotaDailyUpdate();
        Database.executeBatch(myBatch);
    }
    
    public static void getQuota(List<Seller__c> sellerList, List<Date> dateList){
        System.debug('LISTA VENDEDORES '+sellerList.size()+' registros');
        //System.debug(sellerList);
        
        List<String> sellerCodeList = new List<String>();
        List<Id> sellerIdList = new List<Id>();
        List<String> dateStringList = new List<String>();
        Map<String, Seller__c> sellerMap = new Map<String, Seller__c>();
        
        for(Seller__c seller : sellerList){
            String sellerCode = seller.SellerNumberNmb__c.leftPad(8, '0');
        	sellerCodeList.add(sellerCode);
			sellerIdList.add(seller.Id);
            sellerMap.put(sellerCode, seller);
        }
        
        //sellerCodeList.add('00001700');
        
        for(Date dte : dateList){
            String strDate = dte.year() + String.valueOf(dte.month()).leftPad(2, '0');
            dateStringList.add(strDate);
        }
        
        HTTPResponse res = SAPInteg.getQuotas(sellerCodeList, dateStringList);
        System.debug('RECEBIDO DO SAP: ');
        System.debug(res.getBody());
        System.debug('##########STATUS:'+res.getStatusCode());
        if(res.getStatusCode() == 200){
            Map<String, Object> jsonObj = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
            Map<String,Object> quotas = (Map<String,Object>)jsonObj.get('T_ZPH_PREM_OUT');        
            //System.debug(quotas);
            
            List<Object> quotaListJSON = (List<Object>) quotas.get('item');
            //System.debug(quotaListJSON);
            
            List<Quota__c> quotaList = new List<Quota__c>();
            
            for(Object quotaJSON : quotaListJSON){
                Map<String, Object> quotaMap = (Map<String, Object>) quotaJSON;
                //System.debug(quotaJSON);
                
                Quota__c quota = new Quota__c();
                quota.OrderBacklogNmb__c = quotaMap.get('VLCART') instanceof String ? Decimal.valueOf((String)quotaMap.get('VLCART')) : (Decimal)quotaMap.get('VLCART');
                quota.QuotaTypeTxt__c = (String)quotaMap.get('TIPOPREM');
                
                Decimal quotaRevenue = quotaMap.get('REALIZADO') instanceof String ? Decimal.valueOf((String)quotaMap.get('REALIZADO')) : (Decimal)quotaMap.get('REALIZADO');
                Decimal quotaTotalValue = quotaMap.get('PREVISTO') instanceof String ? Decimal.valueOf((String)quotaMap.get('PREVISTO')) : (Decimal)quotaMap.get('PREVISTO');
    
                quota.RevenueNmb__c = quotaRevenue;
                quota.TotalValueNmb__c = quotaTotalValue;
                
                String quotaDate = String.valueOf((Decimal)quotaMap.get('SPMON'));
                String quotaYear = quotaDate.substring(0, 4);
                String quotaMonth = quotaDate.substring(4, 6);
                quota.CurrentMonthTxt__c = quotaMonth;
                quota.CurrentYearTxt__c = quotaYear;
                    
                String sellerSAPCode = (String)quotaMap.get('PERNR');
                sellerSAPCode = sellerSAPCode.replaceFirst('^0+', '');
                
                String sellerSAPCodeWith0 = (String)quotaMap.get('PERNR');
                if(sellerMap.containsKey(sellerSAPCodeWith0)){
                    //quota.SellerLkp__r = sellerMap.get(sellerSAPCodeWith0);
                    quota.SellerLkp__c = sellerMap.get(sellerSAPCodeWith0).Id;
                    quota.OwnerId = sellerMap.get(sellerSAPCodeWith0).UserLkp__c;
                }
                else{
                    System.debug('Não achou o Id do Vendedor com Cod SAP = '+sellerSAPCodeWith0);
                }
                
                String quotaIdentifier = sellerSAPCode + ' ' + quota.QuotaTypeTxt__c + ' ' + quota.CurrentMonthTxt__c + ' ' + quota.CurrentYearTxt__c;
                quota.IdentifierTxt__c = quotaIdentifier;
                
                //System.debug(quota);
                quotaList.add(quota);
            }
            System.debug('Recebido do SAP: '+quotaList.size()+' cotas de vendedores para os períodos');
            /*
            List<Quota__c> currentQuotaList = [SELECT Id, IdentifierTxt__c, CurrentMonthTxt__c, CurrentYearTxt__c, SellerLkp__c, SellerLkp__r.SellerNumberNmb__c 
                                               FROM Quota__c 
                                               WHERE SellerLkp__c IN :sellerIdList];
            
            Map<String, Quota__c> currentQuotaMap = new Map<String, Quota__c>();
            
            for(Quota__c currQuota: currentQuotaList){
                currentQuotaMap.put(currQuota.IdentifierTxt__c, currQuota);
            }
            
            System.debug('MAPA DE COTAS EXISTENTES:');
            for (String key : currentQuotaMap.keySet()) {
                Quota__c c = currentQuotaMap.get(key);
                System.debug(key + ' - '+c);
            }
            
            Integer quotaAtualizacao = 0;
            for(Quota__c quota: quotaList){
                String quotaKey = quota.IdentifierTxt__c;
                
                if (currentQuotaMap.containsKey(quotaKey)){
                    quota.Id = currentQuotaMap.get(quotaKey).Id;
                    System.debug('ESSA COTA JÁ EXISTE. DEVE ATUALIZAR '+quota.Id);
                    quotaAtualizacao++;
                }
                currentQuotaMap.put(quotaKey, quota);
            } 
            
            System.debug('Deve atualizar '+quotaAtualizacao+' cotas');
            */
            //System.debug(quotaList);
            Integer I = 0;
            System.debug('MAPA DE COTAS PARA O UPSERT:');
            for (Quota__c q : quotaList) {
                I++;
                System.debug('['+I+'] SellerId = '+q.SellerLkp__c+' ; OwnerId = '+q.OwnerId);
                
            }
            
            try{
                upsert quotaList IdentifierTxt__c;    
            }
            catch (DmlException e) {
                System.debug(e.getTypeName()+' - '+e.getMessage()+' - '+e.getStackTraceString());
            }            
        }
        else{
            
        }
    }
}