force-app/main/default/objects/Account/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de Negócios do Emissor</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>Email Comercial</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <formula>AccountLkp__r.CNPJTxt__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ApexRedirectMap__c/ApexRedirectMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ApexRedirectMap</label>
</CustomObject>

force-app/main/default/objects/ApexRedirectMap__c/fields/UrlSufix__c.field-meta.xml
<CustomField>
    <fullName>UrlSufix__c</fullName>
    <label>UrlSufix</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>E-mail</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Preenchido automaticamente caso só haja uma opção</description>
    <inlineHelpText>Preenchido automaticamente caso só haja uma opção</inlineHelpText>
    <label>Área de Negócios</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/AlteracaoPedido.recordType-meta.xml
<RecordType>
    <fullName>AlteracaoPedido</fullName>
    <active>true</active>
    <businessProcess>SAC Alteração de pedido</businessProcess>
    <description>Abertura de alteração de pedido</description>
    <label>Alteração de pedido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CancelamentoPedido.recordType-meta.xml
<RecordType>
    <fullName>CancelamentoPedido</fullName>
    <active>true</active>
    <businessProcess>SAC Cancelamento de pedido</businessProcess>
    <description>Abertura de caso para cancelamento de pedido</description>
    <label>Cancelamento de pedido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CartaCorrecao.recordType-meta.xml
<RecordType>
    <fullName>CartaCorrecao</fullName>
    <active>true</active>
    <businessProcess>SAC Carta de correção</businessProcess>
    <description>Abertura de caso para carta de correção</description>
    <label>Carta de correção</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ConsultaPedido.recordType-meta.xml
<RecordType>
    <fullName>ConsultaPedido</fullName>
    <active>true</active>
    <businessProcess>SAC Consulta de pedido</businessProcess>
    <description>Abertura de consulta de pedido</description>
    <label>Consulta de pedido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <businessProcess>SAC Devolução</businessProcess>
    <description>Abertura de devolução de produto</description>
    <label>Devolução</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ExtravioNotaFiscal.recordType-meta.xml
<RecordType>
    <fullName>ExtravioNotaFiscal</fullName>
    <active>true</active>
    <businessProcess>SAC Extravio de nota fiscal</businessProcess>
    <description>Abertura caso extravio de nota fiscal</description>
    <label>Extravio de nota fiscal</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ProdutoTrocado.recordType-meta.xml
<RecordType>
    <fullName>ProdutoTrocado</fullName>
    <active>true</active>
    <businessProcess>SAC Produto trocado</businessProcess>
    <description>Abertura de caso tipo produto trocado</description>
    <label>Produto trocado</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Prorrogacao.recordType-meta.xml
<RecordType>
    <fullName>Prorrogacao</fullName>
    <active>true</active>
    <businessProcess>SAC Prorrogação</businessProcess>
    <description>Abertura de prorrogação</description>
    <label>Prorrogação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reclamacao.recordType-meta.xml
<RecordType>
    <fullName>Reclamacao</fullName>
    <active>true</active>
    <businessProcess>SAC Reclamação</businessProcess>
    <description>Abertura de reclamação de produto</description>
    <label>Reclamação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ReclamacaoContraVendedor.recordType-meta.xml
<RecordType>
    <fullName>ReclamacaoContraVendedor</fullName>
    <active>true</active>
    <businessProcess>SAC Reclamação contra o vendedor</businessProcess>
    <description>Abertura de caso referente a reclamação contra o vendedor</description>
    <label>Reclamação contra o vendedor</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Refaturamento.recordType-meta.xml
<RecordType>
    <fullName>Refaturamento</fullName>
    <active>true</active>
    <businessProcess>SAC Refaturamento</businessProcess>
    <description>Abertura de caso refaturamento</description>
    <label>Refaturamento</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Reposicao.recordType-meta.xml
<RecordType>
    <fullName>Reposicao</fullName>
    <active>true</active>
    <businessProcess>SAC Reposição</businessProcess>
    <description>Abertura de reposição de volume ou item</description>
    <label>Reposição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sinistro.recordType-meta.xml
<RecordType>
    <fullName>Sinistro</fullName>
    <active>true</active>
    <businessProcess>SAC Sinistro</businessProcess>
    <description>Abertura de caso onde houve sinistro</description>
    <label>Sinistro</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Substituicao.recordType-meta.xml
<RecordType>
    <fullName>Substituicao</fullName>
    <active>true</active>
    <businessProcess>SAC Substituição</businessProcess>
    <description>Abertura de substituição de produto</description>
    <label>Substituição</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Sustacao.recordType-meta.xml
<RecordType>
    <fullName>Sustacao</fullName>
    <active>true</active>
    <businessProcess>SAC Sustação</businessProcess>
    <description>Abertura de caso referente a sustação</description>
    <label>Sustação</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/TranstornoNaEntrega.recordType-meta.xml
<RecordType>
    <fullName>TranstornoNaEntrega</fullName>
    <active>true</active>
    <businessProcess>SAC Transtorno na entrega</businessProcess>
    <description>Abertura de caso referente a transtorno na entrega</description>
    <label>Transtorno na entrega</label>
</RecordType>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorista</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Carrier__c.TypeTxt__c</field>
            <operation>equals</operation>
            <value>PE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SellerEmailTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerEmailTxt__c</fullName>
    <label>Email</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ZTCaseCreateInvoiceAndOrderCtrl.cls
@isTest
private class ZTCaseCreateInvoiceAndOrderCtrl
{
    static testMethod void testManipulateCaseCreateInvoiceAndOrder()
    {
    	RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
    	
    	Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
    	insert account;    	
    	
    	Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
    	insert carrier;
    	
    	Seller__c seller = new Seller__c(Name = 'Vendedor', SellerEmailTxt__c = 'vendedor@traportatudo.com.br');
    	insert seller;
        
        Channel__c channel = TestData.createChannel('TES', null); 
        
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(account.Id, channel.Id, null);  
    	
    	Order__c pedido = new Order__c(CustomIDTxt__c = 'abc123', SellerLkp__c = seller.Id);
        pedido.AccountLkp__c = account.Id;
        pedido.AccountAreaSalesLkp__c = salesArea.id;
    	insert pedido;
    	
    	Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id, OrderLkp__c = pedido.Id, AccountLkp__c = account.Id);
    	insert invoice;
    	
    
    	List<ApexRedirectMap__c> redirectMapList = new List<ApexRedirectMap__c>();
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CaseList', UrlSufix__c = '/500/o'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CreateCase', UrlSufix__c = '/500/e?retURL=%2F500%2Fo'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'InvoiceName', UrlSufix__c = 'CF00N55000000iEy3'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'OrderName', UrlSufix__c = 'CF00N55000000iGoF'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'OrderLkpCase', UrlSufix__c = '00N55000000iGoF_lkid'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'InvoiceLkpCase', UrlSufix__c = 'CF00N55000000iEy3_lkid'));
    	
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'ContactCase', UrlSufix__c = 'cas11'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CoordinatorEmailCase', UrlSufix__c = '00N55000000iZtE'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'SellerNameCase', UrlSufix__c = 'CF00N55000000iGXn'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CategoryCase', UrlSufix__c = '00N55000000ibw0'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CarrierLkpCase', UrlSufix__c = 'CF00N55000000iGXi_lkid'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CarrierNameCase', UrlSufix__c = 'CF00N55000000iGXi'));
    	
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'SellerEmail', UrlSufix__c = '00N55000000iNsO'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'CarrierEmail', UrlSufix__c = '00N55000000iNvc'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'ReasonCase', UrlSufix__c = 'cas6'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'ManagerEmailCase', UrlSufix__c = '00N55000000iZzv'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'SellerLkpCase', UrlSufix__c = 'C00N55000000iGXn_lkid'));
    	redirectMapList.add(new ApexRedirectMap__c(Name = 'NatureCase', UrlSufix__c = '00N55000000ibvv'));
    	insert redirectMapList;
    	
    	Case caso = new Case();
		
		PageReference pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	ApexPages.StandardController sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Devolucao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	CaseCreateInvoiceAndOrderCtrl caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doNext();
    	
    	//reposicao
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Reposicao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//subtituicao
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Substituicao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//prorrogacao
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Prorrogacao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//produto trocado
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'ProdutoTrocado' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//extravio de nota fiscal
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'ExtravioNotaFiscal' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//sinistro
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Sinistro' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//sustacao
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Sustacao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//refaturamento
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'Refaturamento' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//carta de correcao
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'CartaCorrecao' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//transtorno na entrega
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'TranstornoNaEntrega' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.invoiceNumber = '02568';
    	caseCreateInvoiceAndOrderCtrl.findInvoice();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	    	
    	//consulta de pedido
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'ConsultaPedido' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.orderNumber = '12345';
    	caseCreateInvoiceAndOrderCtrl.findOrder();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//alteracao de pedido
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'AlteracaoPedido' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.orderNumber = '12345';
    	caseCreateInvoiceAndOrderCtrl.findOrder();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//cancelamento de pedido
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'CancelamentoPedido' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.orderNumber = '12345';
    	caseCreateInvoiceAndOrderCtrl.findOrder();
    	caseCreateInvoiceAndOrderCtrl.doBack();
    	
    	//reclamacao contra o vendedor
    	caso = new Case();
    	pageRef = Page.CaseCreateInvoiceAndOrder;
    	Test.setCurrentPage(pageRef);
    	sc = new ApexPages.StandardController(caso);
    	
    	Apexpages.currentPage().getParameters().put('inConsole', 'no');
    	Apexpages.currentPage().getParameters().put('reason', 'Negociação comercial');
    	Apexpages.currentPage().getParameters().put('def_account_id', String.valueOf(account.Id));	
    	
    	recordType = [Select Id from RecordType where DeveloperName = 'ReclamacaoContraVendedor' and SobjectType = 'Case'];
    	Apexpages.currentPage().getParameters().put('RecordType', String.valueOf(recordType.Id));
    	
    	caseCreateInvoiceAndOrderCtrl = new CaseCreateInvoiceAndOrderCtrl(sc);  	
    	caseCreateInvoiceAndOrderCtrl.orderNumber = '12345';
    	caseCreateInvoiceAndOrderCtrl.findOrder();
    	caseCreateInvoiceAndOrderCtrl.doNext();
    }
}