force-app/main/default/objects/Account/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de Negócios do Emissor</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Organização de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0143</fullName>
            </value>
            <value>
                <fullName>AM01</fullName>
            </value>
            <value>
                <fullName>0099</fullName>
            </value>
            <value>
                <fullName>0141</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Código organização de vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SkipValidations__c/SkipValidations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Skip Validations</label>
</CustomObject>

force-app/main/default/objects/SkipValidations__c/fields/Skip__c.field-meta.xml
<CustomField>
    <fullName>Skip__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/BatchSetOrderAVOwner.cls
global class BatchSetOrderAVOwner implements Database.Batchable<sObject>{
    public Decimal numMultipleAVs = 0;
    
	global Database.QueryLocator start(Database.BatchableContext BC) {

        return Database.getQueryLocator([SELECT Id, AccountLkp__c, CodeSalesOrganizationTxt__c FROM Order__c WHERE AccountAreaSalesLkp__c = null]);
    }

    global void execute(Database.BatchableContext BC, List<Order__c> scope) {
        List<Id> listAccIds = new List<Id>();
        Map<Id, Id> mapOrderAccount = new Map<Id, Id>();
        Map<Id, List<AccountAreaSales__c>> mapAccountAV = new Map<Id, List<AccountAreaSales__c>>();
        List<Order__c> listOrderToUpdate = new List<Order__c>();
        
        for(Order__c o : scope){
			listAccIds.add(o.AccountLkp__c);
		}
        
        for(Account a : [SELECT Id, 
                         (SELECT Id, SellerLkp__r.UserLkp__c, CodeSalesOrganizationTxt__c
                          FROM AreasDeVendas__r WHERE SellerLkp__r.Userlkp__c != null) 
                         FROM Account WHERE Id IN :listAccIds 
                         AND Id IN (SELECT AccountLkp__c FROM AccountAreaSales__c)])
        {
            
            mapAccountAV.put(a.Id, a.AreasDeVendas__r);
            
        }
    
        for(Order__c o : scope){
            if(mapAccountAv.containsKey(o.AccountLkp__c)){
                for(AccountAreaSales__c av : mapAccountAV.get(o.AccountLkp__c)){
                    if(av.CodeSalesOrganizationTxt__c == o.CodeSalesOrganizationTxt__c){
                        o.AccountAreaSalesLkp__c = av.Id;
                        o.OwnerId = av.SellerLkp__r.UserLkp__c;
                        listOrderToUpdate.add(o);
                        break;
                    }
                }
                
                
            }
        }
        
        SkipValidations__c skipVal = SkipValidations__c.getOrgDefaults();
        skipVal.Skip__c = true;
        update skipVal;
        
		update listOrderToUpdate;
        
        skipVal.Skip__c = false;
        update skipVal;

    }
    
    global void finish(Database.BatchableContext BC) {
        system.debug(numMultipleAVs);
    }
}