force-app/main/default/objects/Account/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de Negócios do Emissor</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>Email Comercial</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <formula>AccountLkp__r.CNPJTxt__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/ApexRedirectMap__c/ApexRedirectMap__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>ApexRedirectMap</label>
</CustomObject>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Carrier__c/fields/EmailTxt__c.field-meta.xml
<CustomField>
    <fullName>EmailTxt__c</fullName>
    <label>E-mail</label>
    <length>241</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Preenchido automaticamente caso só haja uma opção</description>
    <inlineHelpText>Preenchido automaticamente caso só haja uma opção</inlineHelpText>
    <label>Área de Negócios</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/ContactTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>ContactTypeTxt__c</fullName>
    <label>Tipo de contato</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Facebook</fullName>
            </value>
            <value>
                <fullName>Mídia Social</fullName>
            </value>
            <value>
                <fullName>Reclame Aqui</fullName>
            </value>
            <value>
                <fullName>Telefone</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Case/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Invoice__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Ordem não pertence a conta selecionada ou Duplicada</errorMessage>
        <filterItems>
            <field>Order__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Casos</relationshipLabel>
    <relationshipName>Casos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case/recordTypes/AbatimentoCredito.recordType-meta.xml
<RecordType>
    <fullName>AbatimentoCredito</fullName>
    <active>true</active>
    <businessProcess>SAC Abatimento de crédito</businessProcess>
    <description>Abertura de caso referente a abatimento de crédito</description>
    <label>Abatimento de crédito</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/CaminhaoRetido.recordType-meta.xml
<RecordType>
    <fullName>CaminhaoRetido</fullName>
    <active>true</active>
    <businessProcess>SAC Caminhão retido</businessProcess>
    <description>Abertura de caso referente a caminhão retido em posto fiscal</description>
    <label>Caminhão retido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/DuvidasTributarias.recordType-meta.xml
<RecordType>
    <fullName>DuvidasTributarias</fullName>
    <active>true</active>
    <businessProcess>SAC Dúvidas tributárias</businessProcess>
    <description>Abertura caso referente a dúvidas tributárias</description>
    <label>Dúvidas tributárias</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/NegociacaoDebito.recordType-meta.xml
<RecordType>
    <fullName>NegociacaoDebito</fullName>
    <active>true</active>
    <businessProcess>SAC Negociação de débito</businessProcess>
    <description>Abertura de negociação de débito</description>
    <label>Negociação de débito</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/ProrrogacaoFluxoCaixa.recordType-meta.xml
<RecordType>
    <fullName>ProrrogacaoFluxoCaixa</fullName>
    <active>true</active>
    <businessProcess>SAC Prorrogação por fluxo de caixa</businessProcess>
    <description>Abertura de prorrogação por fluxo de caixa</description>
    <label>Prorrogação por fluxo de caixa</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/SolicitacaoBoleto.recordType-meta.xml
<RecordType>
    <fullName>SolicitacaoBoleto</fullName>
    <active>true</active>
    <businessProcess>SAC Solicitação de boleto</businessProcess>
    <description>Abertura de caso referente a solicitação de boleto</description>
    <label>Solicitação de boleto</label>
</RecordType>

force-app/main/default/objects/CaseInvoice__c/CaseInvoice__c.object-meta.xml
<CustomObject>
    <description>[a00][CaseInvoice__c] Notas fiscais do caso.</description>
    <label>Nota fiscal do caso</label>
    <nameField>
        <label>Nota fiscal do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseInvoice__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/InvoiceLkp__c.field-meta.xml
<CustomField>
    <fullName>InvoiceLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nota fiscal</label>
    <referenceTo>Invoice__c</referenceTo>
    <relationshipLabel>Notas fiscais do caso</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseInvoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais do caso</relationshipLabel>
    <relationshipName>NotasFiscaisCaso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/ContactSAC.recordType-meta.xml
<RecordType>
    <fullName>ContactSAC</fullName>
    <active>true</active>
    <description>Contatos criados e editados pelo SAC.</description>
    <label>Contato SAC</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Transportadora</label>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CarrierLkp__c.field-meta.xml
<CustomField>
    <fullName>CarrierLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Motorista</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Carrier__c.TypeTxt__c</field>
            <operation>equals</operation>
            <value>PE</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Carrier__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ZTCaseInvoiceCtrl.cls
@isTest
private class ZTCaseInvoiceCtrl
{
    @isTest
    static void testManipulateCaseInvoice_one()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;
        
        recordType = [Select Id from RecordType where DeveloperName = 'DuvidasTributarias' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id);
        insert caseInvoice;
        
        Invoice__c invoiceTwo = new Invoice__c(Name = '02569', AccountLkp__c = account.Id, CarrierLkp__c = carrier.Id);
        insert invoiceTwo;
        
        ApexRedirectMap__c apexRedirectMap = ULTestData.createApexRedirectMap('WebServiceInvoice', 'http://127.0.0.1:50000/xpto');
        insert apexRedirectMap;

        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);      
        caseInvoiceCtrl.invoiceNumber = '02569';        
        //caseInvoiceCtrl.insertInvoice();
        caseInvoiceCtrl.doSave();
    
        // Stop Test
        System.Test.stopTest();
    }

    @isTest
    static void testManipulateCaseInvoice_two()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;
        
        recordType = [Select Id from RecordType where DeveloperName = 'CaminhaoRetido' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id);
        insert caseInvoice;
    
        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);
        caseInvoiceCtrl.invoiceNumber = '02569';        
        //caseInvoiceCtrl.insertInvoice();
        caseInvoiceCtrl.doSave();
    
        // Stop Test
        System.Test.stopTest();
    }

    @isTest
    static void testManipulateCaseInvoice_three()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;
        
        recordType = [Select Id from RecordType where DeveloperName = 'SolicitacaoBoleto' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id);
        insert caseInvoice;

        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);
        caseInvoiceCtrl.invoiceNumber = '02569';        
        //caseInvoiceCtrl.insertInvoice();
        caseInvoiceCtrl.doSave();
    
        // Stop Test
        System.Test.stopTest();
    }

    @isTest
    static void testManipulateCaseInvoice_four()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;        

        recordType = [Select Id from RecordType where DeveloperName = 'ProrrogacaoFluxoCaixa' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id);
        insert caseInvoice;

        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);
        caseInvoiceCtrl.invoiceNumber = '02569';        
        //caseInvoiceCtrl.insertInvoice();
        caseInvoiceCtrl.doSave();
        
        // Stop Test
        System.Test.stopTest();
    }

    @isTest
    static void testManipulateCaseInvoice_five()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;
        
        recordType = [Select Id from RecordType where DeveloperName = 'AbatimentoCredito' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id);
        insert caseInvoice;

        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);
        caseInvoiceCtrl.doCancel();

        // Stop Test
        System.Test.stopTest();
    }

    @isTest
    static void testManipulateCaseInvoice_six()
    {
        // Prepare test data
        RecordType recordType = [Select Id from RecordType where DeveloperName = 'BusinessAccountSAC' and SobjectType = 'Account'];
        
        
        Account account = new Account(Name = 'Testador da pagina', CNPJTxt__c = '26830528000181', RecordTypeId = recordType.Id);
        insert account;     
        
        recordType = [Select Id from RecordType where DeveloperName = 'ContactSAC' and SobjectType = 'Contact'];
        
        Contact contact = new Contact(FirstName = 'Testa', LastName = 'Tudo', AccountId = account.Id, RecordTypeId = recordType.Id);
        insert contact;
        
        Carrier__c carrier = new Carrier__c(Name = 'Transporta tudo', EmailTxt__c = 'teste@transportatudo.com.br');
        insert carrier;
        
        Invoice__c invoice = new Invoice__c(Name = '02568', CarrierLkp__c = carrier.Id);
        insert invoice;
        
        recordType = [Select Id from RecordType where DeveloperName = 'NegociacaoDebito' and SobjectType = 'Case'];
        
        Case caso = new Case(AccountId = account.Id, RecordTypeId = recordType.Id, ContactId = contact.Id, InvoiceLkp__c = invoice.id, Origin = 'Transportadora', ContactTypeTxt__c = 'Email', Status = 'Aberto', Type = 'Item');
        insert caso;
        
        Channel__c channel = TestData.createChannel('TES', null); 
        
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(account.Id, channel.Id, null); 
        
        Order__c ordem = new Order__c(CustomIDTxt__c = 'abc123');
        ordem.AccountLkp__c = account.Id; 
        ordem.AccountAreaSalesLkp__c = salesArea.id; 
        insert ordem;
        
        CaseInvoice__c caseInvoice = new CaseInvoice__c(InvoiceLkp__c = invoice.Id, CaseMdt__c = caso.Id, OrderLkp__c = ordem.Id);
        insert caseInvoice;

        // Start Test
        System.Test.startTest();
        
        PageReference pageRef = Page.CaseInvoice;
        Test.setCurrentPage(pageRef);
        ApexPages.StandardController sc = new ApexPages.StandardController(caseInvoice);
        Apexpages.currentPage().getParameters().put('id', String.valueOf(caseInvoice.Id));  
        
        CaseInvoiceCtrl caseInvoiceCtrl = new CaseInvoiceCtrl(sc);
        caseInvoiceCtrl.invoiceNumber = '02569';        
        //caseInvoiceCtrl.insertInvoice();
        caseInvoiceCtrl.listCaseInvoiceDAO[0].selected = true;
        caseInvoiceCtrl.removeInvoice();
        caseInvoiceCtrl.doSave();

        // Stop Test
        System.Test.stopTest();
    }
}