force-app/main/default/objects/Account/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de Negócios do Emissor</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Parceiros</relationshipLabel>
    <relationshipName>Partners</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Organização de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Descrição organização de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AMANCO</fullName>
            </value>
            <value>
                <fullName>PLASTUBOS</fullName>
            </value>
            <value>
                <fullName>BIDIM</fullName>
            </value>
            <value>
                <fullName>ALPHAGARY</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Organização vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/SellerPhoneTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerPhoneTxt__c</fullName>
    <label>Telefone vendedor</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SendOrderPDFEmailController.cls
public with sharing class SendOrderPDFEmailController{
    
    public String subject { get; set; }
    public String body { get; set; }
    public String emailid{get; set;}
    public String mailBody{get; set;}
    public String salesOrg{get; set;}
    private final Order__c Order;
    
    public string fileExtension {get;set;}
    
    
    public SendOrderPDFEmailController(ApexPages.StandardController controller) {
        Order= [SELECT Name, CustomIdTxt__c, id, AccountAreaSalesLkp__r.SalesOrganizationTxt__c, AccountLkp__c, AccountLkp__r.Name,
                SellerLkp__r.Name, SellerLkp__r.UserLkp__r.Email, SellerLkp__r.SellerPhoneTxt__c, AccountLkp__r.EmailNFTxt__c
              	FROM Order__c
              	WHERE Id=:ApexPages.currentPage().getParameters().get('id')];
        
        emailid = Order.AccountLkp__r.EmailNFTxt__c;
    }
    
    public Order__c getOrder() {
        return Order;
    }
    
    public list<SelectOption> getFileExtensions (){
        List<SelectOption> fileExtensions = new List<SelectOption>();       
        
        fileExtensions.add(new SelectOption('PDF', 'PDF'));
		fileExtensions.add(new SelectOption('CSV', 'CSV'));
		fileExtensions.add(new SelectOption('XLS', 'XLS'));
       
        return fileExtensions;
    }
    
    public void send() {       
        
        try{
            if(Order.AccountAreaSalesLkp__r.SalesOrganizationTxt__c !=null){
            	salesOrg = Order.AccountAreaSalesLkp__r.SalesOrganizationTxt__c;
            } else {
                salesOrg = 'Mexichem';
            }
            
            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            
            Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
            Blob b;
            
            if(fileExtension=='PDF'){
                PageReference pdf =  Page.OrderPDFView;                
                pdf.getParameters().put('id',(String)Order.id);
                pdf.setRedirect(true);
                
                if(Test.isRunningTest()){
                    b = Blob.valueOf('UnitTest');
                }
                else{
                    b = pdf.getContentAsPdf();
                }                                                
                                
                efa.setContentType('application/pdf');
                efa.setFileName(salesOrg + ' - Ordem ' + Order.CustomIdTxt__c + '.pdf');
                efa.setBody(b);
            }
            
            if(fileExtension=='CSV'){
                PageReference csv = page.OrderCSVExport;
                csv.getParameters().put('id',(String)Order.id);
                csv.setRedirect(true);
                
                if(Test.isRunningTest()){
                    b = Blob.valueOf('UnitTest');
                }
                else{
                    b = csv.getContent();
                }
                
                efa.setContentType('text/csv');
                efa.setFileName(salesOrg + ' - Ordem ' + Order.CustomIdTxt__c + '.csv');
                efa.setBody(b);
                
            }
            
            if(fileExtension=='XLS'){
                PageReference xls =  Page.OrderXLSExport;                
                xls.getParameters().put('id',(String)Order.id);
                xls.setRedirect(true);
                
                if(Test.isRunningTest()){
                    b = Blob.valueOf('UnitTest');
                }
                else{
                    b = xls.getContent();
                }                                                
                                
                efa.setContentType('application/vnd.ms-excel');
                efa.setFileName(salesOrg + ' - Ordem ' + Order.CustomIdTxt__c + '.xls');
                efa.setBody(b);
            }
            
            Contact sendFileToCon = new Contact(); 
            Contact sendFileToNewCon = new Contact(FirstName = 'Destinatário Ordem:', LastName = emailid, Email = emailid, AccountId = Order.AccountLkp__c);
            List<Contact> sendFileToExistingCon = [SELECT Id, Name, Email FROM Contact WHERE Email =: emailid AND AccountId =: Order.AccountLkp__c LIMIT 1];                                 
            if(sendFileToExistingCon.size() > 0){
                sendFileToCon.id 	= sendFileToExistingCon[0].Id;                
            } else {
                sendFileToCon = sendFileToNewCon;
                insert sendFileToCon;
            }
            
            //String addresses;
            //addresses=emailid;
            //String[] toAddresses = addresses.split(';', 0);
            
            string subject = salesOrg + ' - Ordem ' + Order.CustomIdTxt__c;
            string sellerPhone = '';
            if(Order.SellerLkp__r.SellerPhoneTxt__c != null){
                sellerPhone = Order.SellerLkp__r.SellerPhoneTxt__c;
            }            
            
            email.setSubject( subject );
            //email.setToAddresses( toAddresses );            
            email.setHtmlBody(                
                'Prezado <b>'+ Order.AccountLkp__r.Name + ',</b> <br/>' +
                '<br/>' +
                'Segue anexo a cotação solicitada.<br/>' +
                'Estamos à disposição para esclarecer eventuais dúvidas.<br/>' +
                '<br/>' +
                'Ciente de sua atenção, desde já agradeço.<br/>' +
                '<br/>' +
                '<b>'+ Order.SellerLkp__r.Name + '</b><br/>' +
                Order.SellerLkp__r.UserLkp__r.Email + '<br/>' +
                sellerPhone);
            email.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
            email.setTargetObjectId(sendFileToCon.Id);
            email.setWhatId(Order.Id);
            email.setSaveAsActivity(true);
            
            // Sends the email
            Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,'O email foi enviado com sucesso!'));
            
            string taskSubject = 'Email: ' + salesOrg + ' - Ordem ' + Order.CustomIdTxt__c;
            List<Task> emailTasks = [SELECT Id FROM Task WHERE Subject =: taskSubject AND WhatId =: Order.Id ORDER BY CreatedDate DESC LIMIT 1];
            Task emailTask = !emailTasks.isEmpty() ? emailTasks[0] : null;
            Attachment attchmnt = new Attachment();
            attchmnt.body = b;
            attchmnt.name = salesOrg + ' - Ordem ' + Order.CustomIdTxt__c + '.pdf';
            attchmnt.parentId = emailTask.id;
            insert attchmnt;
                        
        } catch (exception ex){
            ApexPages.addMessages(ex);
        }
        
    }
}