force-app/main/default/objects/Account/fields/AssociatedToIssuerBln__c.field-meta.xml
<CustomField>
    <fullName>AssociatedToIssuerBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When a new partner is created, it is not automatically associated to the Issuer Account. This field keeps track of its condition in order to associate it later.</description>
    <label>Associado ao Emissor</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/AccountPartner.recordType-meta.xml
<RecordType>
    <fullName>AccountPartner</fullName>
    <active>true</active>
    <description>Para cadastro de endereços de entrega e pagador</description>
    <label>Parceiros de conta</label>
</RecordType>

force-app/main/default/classes/Batch_AssociatePartner.cls
global class Batch_AssociatePartner implements Database.Batchable<SObject>, Database.AllowsCallouts{
    global Database.QueryLocator start(Database.BatchableContext bc){       
        return Database.getQueryLocator(
            'SELECT CreatedDate, Id, CodeCustomerTxt__c, Parent.Id, Parent.CodeCustomerTxt__c, AssociatedToIssuerBln__c FROM ACCOUNT WHERE '+
            'CodeCustomerTxt__c <> null AND Parent.CodeCustomerTxt__c <> null AND AssociatedToIssuerBln__c = FALSE AND '+
            'RecordType.DeveloperName = \'AccountPartner\''
        );
    }
    
    global void execute(Database.BatchableContext bc, List<Account> scope){                  
        List<Id> accIdList = new List<Id>();
		
        System.debug('SCOPE');        
        System.debug(scope);
        
        for(Account acc : scope){
       		accIdList.add(acc.Id);
        }
        
        AccountIntegrationUtils.associatePartner(accIdList);
    }
    
    global void finish(Database.BatchableContext bc){
    	System.debug('Batch_AssociatePartner Finalizada');
    }
}