force-app/main/default/objects/Account/fields/BillingDistrict__c.field-meta.xml
<CustomField>
    <fullName>BillingDistrict__c</fullName>
    <label>Bairro</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/BillingNumber__c.field-meta.xml
<CustomField>
    <fullName>BillingNumber__c</fullName>
    <label>Número</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ConvertLeadBln__c.field-meta.xml
<CustomField>
    <fullName>ConvertLeadBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que é verdadeiro se a conta é originária de conversão de lead. Preenchido via mapeamento para Emissor, via código para Parceiros</description>
    <label>Lead Convertido?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/CPFTxt__c.field-meta.xml
<CustomField>
    <fullName>CPFTxt__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/PartnerTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerTypeTxt__c</fullName>
    <label>Tipo de Parceiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PGFT</fullName>
                <label>Pagador</label>
            </value>
            <value>
                <fullName>REOR</fullName>
                <label>Recebedor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Organização de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/AccountPartner.recordType-meta.xml
<RecordType>
    <fullName>AccountPartner</fullName>
    <active>true</active>
    <description>Para cadastro de endereços de entrega e pagador</description>
    <label>Parceiros de conta</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>[a03][Address__c] Endereço utilizado em contas.</description>
    <label>Endereço</label>
    <nameField>
        <label>Rua</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/CEPTxt__c.field-meta.xml
<CustomField>
    <fullName>CEPTxt__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/CityTxt__c.field-meta.xml
<CustomField>
    <fullName>CityTxt__c</fullName>
    <label>Cidade</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/LeadLkp__c.field-meta.xml
<CustomField>
    <fullName>LeadLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Novo Cliente</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/NeighborhoodTxt__c.field-meta.xml
<CustomField>
    <fullName>NeighborhoodTxt__c</fullName>
    <label>Bairro</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/NumberTxt__c.field-meta.xml
<CustomField>
    <fullName>NumberTxt__c</fullName>
    <label>Número</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PartnerNameTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerNameTxt__c</fullName>
    <label>Razão Social/Nome do Parceiro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PartnerStateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerStateInscriptionTxt__c</fullName>
    <label>Inscrição Estadual Parceiro</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PartnerTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerTypeTxt__c</fullName>
    <label>Tipo de Parceiro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PGFT</fullName>
                <label>Pagador</label>
            </value>
            <value>
                <fullName>REOR</fullName>
                <label>Recebedor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/CodeTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Lead/fields/ApprovalTxt__c.field-meta.xml
<CustomField>
    <fullName>ApprovalTxt__c</fullName>
    <label>Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando envio para aprovação</fullName>
                <default>true</default>
                <label>Aguardando envio para aprovação</label>
            </value>
            <value>
                <fullName>Enviado para aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado na etapa 1</fullName>
                <label>Aprovado pela área de cadastro</label>
            </value>
            <value>
                <fullName>Aprovado na etapa 2</fullName>
                <label>Aprovado pela área fiscal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <inlineHelpText>Escreva apenas números sem separações entre eles. 
Exemplo: 66753556000167.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConvertLeadBln__c.field-meta.xml
<CustomField>
    <fullName>ConvertLeadBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converter Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CoordinatorLkp__c.field-meta.xml
<CustomField>
    <fullName>CoordinatorLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Novos_Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/PVCChannelTxt__c.field-meta.xml
<CustomField>
    <fullName>PVCChannelTxt__c</fullName>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>Canal PVC</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>PVCChannel</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/RegisteredInDatabaseBln__c.field-meta.xml
<CustomField>
    <fullName>RegisteredInDatabaseBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cadastrado na Base</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <inlineHelpText>Esse campo é preenchido automaticamente se o campo Vendedor for preenchido.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>Organização de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/SellerCPFTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerCPFTxt__c</fullName>
    <label>CPF do Vendedor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Novos Clientes</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <label>Código do Vendedor</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/CoordinatorLkp__c.field-meta.xml
<CustomField>
    <fullName>CoordinatorLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Vendedores1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Organização vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <externalId>true</externalId>
    <label>Código do vendedor</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/User/fields/CPFTxt__c.field-meta.xml
<CustomField>
    <fullName>CPFTxt__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadTriggerHandler.cls
public class LeadTriggerHandler {

    public static void isBeforeInsert(List<Lead> listLead, Map<Id, Lead> oldMap){
		Map<String, List<Lead>> mapChannelLeads = new Map<String, List<Lead>>();
        
        for(Lead l : listLead){
            if(l.PVCChannelTxt__c != null && l.ChannelLkp__c == null){
                if(mapChannelLeads.containsKey(l.PVCChannelTxt__c)){
                    mapChannelLeads.get(l.PVCChannelTxt__c).add(l);
                }
                else{
                    mapChannelLeads.put(l.PVCChannelTxt__c, new List<Lead>{l});
                }
            }
        }
        
        if(!mapChannelLeads.isEmpty()){
            for(Channel__c c : [SELECT Id, CodeTxt__c FROM Channel__c WHERE CodeTxt__c IN :mapChannelLeads.keySet()]){
                for(Lead l : mapChannelLeads.get(c.CodeTxt__c)){
                    l.ChannelLkp__c = c.Id;
                }
            }
        }
        
    	List<Id> listSellerIds = new List<Id>();
        
        for(Lead l: listLead){
            listSellerIds.add(l.SellerLkp__c);
        }
        
        if(listSellerIds.size() > 0){
            Map<Id,Seller__c> mapSellers = new Map<Id,Seller__c>([SELECT Id, SellerNumberNmb__c, UserLkp__r.CPFTxt__c, CoordinatorLkp__c
                                                                  FROM Seller__c
                                                                  WHERE Id IN: listSellerIds]);
            
            for(Lead l: listLead){
                if(mapSellers.containsKey(l.SellerLkp__c)){
                    l.SellerCPFTxt__c =mapSellers.get(l.SellerLkp__c).UserLkp__r.CPFTxt__c;
                    l.CoordinatorLkp__c =mapSellers.get(l.SellerLkp__c).CoordinatorLkp__c;
                }
            }
        }
        
    }
    
    public static void isBeforeUpdate(List<Lead> listLead, Map<Id, Lead> oldMap){ 
		Map<String, List<Lead>> mapChannelLeads = new Map<String, List<Lead>>();
        
        List<String> listCNPJInTrigger = new List<String>();
        
        for(Lead l : listLead){
            if(l.PVCChannelTxt__c != null && l.PVCChannelTxt__c != oldMap.get(l.Id).PVCChannelTxt__c){
                if(mapChannelLeads.containsKey(l.PVCChannelTxt__c)){
                    mapChannelLeads.get(l.PVCChannelTxt__c).add(l);
                }
                else{
                    mapChannelLeads.put(l.PVCChannelTxt__c, new List<Lead>{l});
                }
            }
        }
        if(!mapChannelLeads.isEmpty()){
            for(Channel__c c : [SELECT Id, CodeTxt__c FROM Channel__c WHERE CodeTxt__c IN :mapChannelLeads.keySet()]){
                for(Lead l : mapChannelLeads.get(c.CodeTxt__c)){
                    l.ChannelLkp__c = c.Id;
                }
            }
        }
        
        for(Lead l: listLead){
            if(l.ConvertLeadBln__c && l.ConvertLeadBln__c != oldMap.get(l.Id).ConvertLeadBln__c){
                listCNPJInTrigger.add(l.CNPJTxt__c);
            }
        }                
        
        if(listCNPJInTrigger.size() > 0){
            List<Account> accountList = [Select Id, CNPJTxt__c, SalesOrganizationTxt__c
                                         From Account
                                         WHERE CNPJTxt__c IN :listCNPJInTrigger];
            for(Lead l : listLead){
                if(l.ConvertLeadBln__c && l.ConvertLeadBln__c != oldMap.get(l.Id).ConvertLeadBln__c){
                    for(Account acct : accountList){
                        if(acct.CNPJTxt__c==l.CNPJTxt__c && acct.SalesOrganizationTxt__c==l.SalesOrganizationTxt__c){
                            l.RegisteredInDatabaseBln__c=True;
                        }
                    }   
                }
            }
        }
        
        for(Lead l : listLead){
            String errorString = '';
            if(l.ApprovalTxt__c == 'Enviado para aprovação' && l.ApprovalTxt__c != oldMap.get(l.Id).ApprovalTxt__c){
                if(l.Street==Null || l.City==Null || l.State==Null || l.PostalCode==Null || l.Country==Null){

                    //l.addError('Campo obrigatório ausente: Endereço');
                    errorString += 'Endereço; ';
                }
                for(Schema.FieldSetMember f : SObjectType.Lead.FieldSets.RequiredFieldsStep1.getFields()){
                    if(l.get(f.getFieldPath()) == null){
                        errorString += f.getLabel() + '; ';
                    }
                }
                if(errorString != ''){
                    l.addError('Campos obrigatórios ausentes: ' + errorString);
                }
        	}
        }
        
        
        for(Lead l : listLead){
            String errorString = '';
            if(l.ApprovalTxt__c == 'Aprovado na etapa 1' && l.ApprovalTxt__c != oldMap.get(l.Id).ApprovalTxt__c){
                if(l.Street==Null || l.City==Null || l.State==Null || l.PostalCode==Null || l.Country==Null){
                    //l.addError('Campo obrigatório ausente: Endereço');
                    errorString += 'Endereço; ';
                }
                for(Schema.FieldSetMember f : SObjectType.Lead.FieldSets.RequiredFieldsStep2.getFields()){
                    if(l.get(f.getFieldPath()) == null){
                        errorString += f.getLabel() + '; ';
                    }
                }
                if(errorString != ''){
                    l.addError('Campos obrigatórios ausentes: ' + errorString);
                }
            }
        }
        
        for(Lead l : listLead){
            String errorString = '';
            if(l.ApprovalTxt__c == 'Aprovado na etapa 2' && l.ApprovalTxt__c != oldMap.get(l.Id).ApprovalTxt__c){
                if(l.Street==Null || l.City==Null || l.State==Null || l.PostalCode==Null || l.Country==Null){
                    //l.addError('Campo obrigatório ausente: Endereço');
                    errorString += 'Endereço; ';
                }
                for(Schema.FieldSetMember f : SObjectType.Lead.FieldSets.RequiredFieldsFinalStep.getFields()){
                    if(l.get(f.getFieldPath()) == null){
                        errorString += f.getLabel() + '; ';
                    }
                }
                if(errorString != ''){
                    l.addError('Campos obrigatórios ausentes: ' + errorString);
                }
            }
        }
        
        List<Id> listSellerIds = new List<Id>();
        
        for(Lead l: listLead){
            if(l.SellerLkp__c != null && l.SellerLkp__c != oldMap.get(l.Id).SellerLkp__c){
                listSellerIds.add(l.SellerLkp__c);
            }
        }
        
        if(listSellerIds.size() > 0){
            Map<Id,Seller__c> mapSellers = new Map<Id,Seller__c>([SELECT Id, SellerNumberNmb__c, UserLkp__r.CPFTxt__c, CoordinatorLkp__c
                                                                  FROM Seller__c
                                                                  WHERE Id IN: listSellerIds]);
            
            for(Lead l: listLead){
                if(mapSellers.containsKey(l.SellerLkp__c)){
                    l.SellerCPFTxt__c =mapSellers.get(l.SellerLkp__c).UserLkp__r.CPFTxt__c;
                    l.CoordinatorLkp__c =mapSellers.get(l.SellerLkp__c).CoordinatorLkp__c;
                }
            }
        }
        
    }

    public static void isAfterUpdate(List<Lead> listLead, Map<Id, Lead> oldMap){
        List<String> listCNPJInTrigger = new List<String>();
        
        for(Lead l: listLead){
            if(l.ConvertLeadBln__c && l.ConvertLeadBln__c != oldMap.get(l.Id).ConvertLeadBln__c)
                listCNPJInTrigger.add(l.CNPJTxt__c);
        }    
        
        if(listCNPJInTrigger.size() > 0){
            LeadStatus convertStatus = [SELECT Id, ApiName 
                                        FROM LeadStatus 
                                        WHERE IsConverted=true LIMIT 1];
            
            List<Account> accountList = [Select Id, CNPJTxt__c, SalesOrganizationTxt__c
                                         From Account
                                         WHERE CNPJTxt__c IN :listCNPJInTrigger];
            
            List<Database.LeadConvert> lcList = new List<Database.LeadConvert>();
            
            for(Lead l : listLead){
                if(l.ConvertLeadBln__c && l.ConvertLeadBln__c != oldMap.get(l.Id).ConvertLeadBln__c){
                    Database.LeadConvert lc = LeadConversion.convert(l,accountList,convertStatus);
                    lcList.add(lc);      
                }
            }
            List<Database.LeadConvertResult> lcrList = Database.convertLead(lcList);
            
            convertAddresses(lcrList);
            
            list<Account> listAccUpdate = new List<Account>();
            
            List<RecordType> rts = [SELECT Id FROM RecordType WHERE DeveloperName = 'SAPBusinessAccount'];
            
            if(rts.size() > 0){
                for(Database.LeadConvertResult lcr : lcrList){
                    listAccUpdate.add(new Account(Id = lcr.getAccountId(), 
                                                  RecordTypeId = rts[0].Id));
                }
                update listAccUpdate;
            }
        }
    }


    private static void convertAddresses(List<Database.LeadConvertResult> lcrList){
        Map<Id, Id> mapLeadToAcc = new Map<Id, Id>();
        List<Account> listAccToInsert = new List<Account>();
        for(Database.LeadConvertResult lcr : lcrList){
            mapLeadToAcc.put(lcr.getLeadId(), lcr.getAccountId());
        }
        
        List<Address__c> listAddress = [SELECT Id, CNPJTxt__c, 
                                        CEPTxt__c,
                                        CityTxt__c,
                                        NeighborhoodTxt__c,
                                        PartnerTypeTxt__c,
                                        PartnerNameTxt__c,
                                        PartnerStateInscriptionTxt__c,
                                        Name,
                                        LeadLkp__c,
                                        StateTxt__c,
                                        NumberTxt__c,
                                        Phone__c,
                                        LeadLkp__r.OwnerId,
                                        LeadLkp__r.Company
                                        FROM Address__c
                                       WHERE LeadLkp__c IN :mapLeadToAcc.keyset()];
        
        for(Address__c address : listAddress){
            Account accAux = new Account();
            accAux.ConvertLeadBln__c = true;
            accAux.CNPJTxt__c = address.CNPJTxt__c;
            accAux.ParentId = mapLeadToAcc.get(address.LeadLkp__c);
            accAux.BillingPostalCode = address.CEPTxt__c;
            accAux.BillingCity = address.CityTxt__c;
            accAux.BillingDistrict__c = address.NeighborhoodTxt__c;
            accAux.BillingNumber__c = address.NumberTxt__c;
            accAux.PartnerTypeTxt__c = address.PartnerTypeTxt__c;
            accAux.BillingStateCode = address.StateTxt__c;
            accAux.BillingCountryCode = 'BR';
            accAux.Name = address.PartnerNameTxt__c != null ? address.PartnerNameTxt__c : address.LeadLkp__r.Company;
            accAux.RG_StateInscriptionTxt__c = address.PartnerStateInscriptionTxt__c;
            accAux.BillingStreet = address.Name;
            accAux.Phone = address.Phone__c;
            accAux.OwnerId = address.LeadLkp__r.OwnerId;
            listAccToInsert.add(accAux);
        }
        
        List<RecordType> rts = [SELECT Id FROM RecordType WHERE DeveloperName = 'AccountPartner'];
        
        if(rts.size() > 0){
            for(Account acc : listAccToInsert){
                acc.RecordTypeId = rts[0].Id;
                system.debug(acc.CNPJTxt__c);
            }
        }
        
        insert listAccToInsert;
    }
    
}