force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/ActiveVerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>ActiveVerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco Ativo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>VerdeAmancoKit__c.ChannelLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Canais</relationshipLabel>
    <relationshipName>Channels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoKit__c/VerdeAmancoKit__c.object-meta.xml
<CustomObject>
    <description>[###][VerdeAmancoKit__c]</description>
    <label>Kit Verde Amanco</label>
    <nameField>
        <label>Nome de Kit Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kits Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoSolicitation__c/VerdeAmancoSolicitation__c.object-meta.xml
<CustomObject>
    <description>[a12][VerdeAmancoSolicitation__c]</description>
    <label>Solicitação Verde Amanco</label>
    <nameField>
        <label>Nome da Solicitação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitações Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/AddressTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>AddressTypeTxt__c</fullName>
    <label>Tipo do Endereço</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endereço do Cliente</fullName>
            </value>
            <value>
                <fullName>Endereço do Solicitante</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/ShippingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressTxt__c</fullName>
    <label>Endereço de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Em preenchimento</fullName>
                <default>true</default>
                <label>Em preenchimento</label>
            </value>
            <value>
                <fullName>Enviando para o operador logístico</fullName>
            </value>
            <value>
                <fullName>Recebido pelo operador logístico</fullName>
            </value>
            <value>
                <fullName>Material entregue no endereço solicitado</fullName>
            </value>
            <value>
                <fullName>Fotos aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Fotos não aprovadas</fullName>
            </value>
            <value>
                <fullName>Fotos aprovadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/VerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>VerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco</label>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Solicitações Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoSolicitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_VASolicitationTriggerHandler.cls
@isTest
private class Test_VASolicitationTriggerHandler {
    
    @isTest static void insertEnderecoConta(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        acct.BillingStreet = 'Avenida das Nações Unidas';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Endereço do Cliente');
        solic = [Select Id, ShippingAddressTxt__c, VerdeAmancoKitLkp__c 
                 From VerdeAmancoSolicitation__c
                 Where Id = :solic.Id];
        System.assertEquals('Avenida das Nações Unidas', solic.ShippingAddressTxt__c);
        System.assertEquals(kit.Id, solic.VerdeAmancoKitLkp__c);
        
    }
    
    @isTest static void insertEnderecoSolicitante(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Endereço do Solicitante');
        solic = [Select Id, ShippingAddressTxt__c, VerdeAmancoKitLkp__c 
                 From VerdeAmancoSolicitation__c
                 Where Id = :solic.Id];
        User solicitante = [Select Id, Street
                            From User
                            Where Id = :UserInfo.getUserId()];
        System.assertEquals(solicitante.Street, solic.ShippingAddressTxt__c);
        System.assertEquals(kit.Id, solic.VerdeAmancoKitLkp__c);
        
    }

    @isTest static void updateEnderecoConta(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        acct.BillingStreet = 'Avenida das Nações Unidas';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Outro');
        solic.AddressTypeTxt__c = 'Endereço do Cliente';  
        update solic;
        solic = [Select Id, ShippingAddressTxt__c, VerdeAmancoKitLkp__c 
                 From VerdeAmancoSolicitation__c
                 Where Id = :solic.Id];
        System.assertEquals('Avenida das Nações Unidas', solic.ShippingAddressTxt__c);
        
    }
    
    @isTest static void updateEnderecoOutro(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        acct.BillingStreet = 'Avenida das Nações Unidas';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Endereço do Cliente');
        solic.AddressTypeTxt__c = 'Outro';
        update solic;
        solic = [Select Id, ShippingAddressTxt__c, VerdeAmancoKitLkp__c 
                 From VerdeAmancoSolicitation__c
                 Where Id = :solic.Id];
        System.assertEquals(null, solic.ShippingAddressTxt__c);
    }
    
    @isTest static void updateEnderecoSolicitante(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        acct.BillingStreet = 'Avenida Paulista';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Endereço do Cliente');
        solic.AddressTypeTxt__c = 'Endereço do Solicitante';
        update solic;
        solic = [Select Id, ShippingAddressTxt__c, VerdeAmancoKitLkp__c, CreatedById 
                 From VerdeAmancoSolicitation__c
                 Where Id = :solic.Id];
        User solicitante = [Select Id, Street
                            From  User
                            Where Id = :solic.CreatedById];
        System.debug(solicitante.Street);
        System.assertEquals(solicitante.Street, solic.ShippingAddressTxt__c);
    }

    @isTest static void testFiles(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Outro');
        ContentVersion cv = TestData.createContentVersion('Header_Picture1', '/Header_Picture1.jpg');
       
        ContentVersion cv2 = [SELECT Id, Title, ContentDocumentId 
                              FROM ContentVersion 
                              WHERE Id = :cv.Id LIMIT 1];
        
        ContentDocumentLink cdl = TestData.createContentDocumentLink(cv2.ContentDocumentId, solic.Id);
        solic.StatusTxt__c = 'Aguardando envio';
        update solic;
        solic.StatusTxt__c = 'Aguardando aprovação';
        update solic;
        System.assertEquals('Aguardando aprovação', solic.StatusTxt__c);
            
    }

}