force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesOfficeTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOfficeTxt__c</fullName>
    <label>Escritório de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0010</fullName>
            </value>
            <value>
                <fullName>0020</fullName>
            </value>
            <value>
                <fullName>0030</fullName>
            </value>
            <value>
                <fullName>0040</fullName>
            </value>
            <value>
                <fullName>0050</fullName>
            </value>
            <value>
                <fullName>0060</fullName>
            </value>
            <value>
                <fullName>0070</fullName>
            </value>
            <value>
                <fullName>0090</fullName>
            </value>
            <value>
                <fullName>0100</fullName>
            </value>
            <value>
                <fullName>0110</fullName>
            </value>
            <value>
                <fullName>0120</fullName>
            </value>
            <value>
                <fullName>0130</fullName>
            </value>
            <value>
                <fullName>0150</fullName>
            </value>
            <value>
                <fullName>0001</fullName>
            </value>
            <value>
                <fullName>0160</fullName>
            </value>
            <value>
                <fullName>PL10</fullName>
            </value>
            <value>
                <fullName>PL20</fullName>
            </value>
            <value>
                <fullName>PL30</fullName>
            </value>
            <value>
                <fullName>PL40</fullName>
            </value>
            <value>
                <fullName>PL50</fullName>
            </value>
            <value>
                <fullName>PL55</fullName>
            </value>
            <value>
                <fullName>PL60</fullName>
            </value>
            <value>
                <fullName>PL65</fullName>
            </value>
            <value>
                <fullName>PL70</fullName>
            </value>
            <value>
                <fullName>PL95</fullName>
            </value>
            <value>
                <fullName>PL99</fullName>
            </value>
            <value>
                <fullName>0140</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal PVC</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipName>AccountAreaSales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SalesOfficeTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOfficeTxt__c</fullName>
    <label>Escritório de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0010</fullName>
            </value>
            <value>
                <fullName>0020</fullName>
            </value>
            <value>
                <fullName>0030</fullName>
            </value>
            <value>
                <fullName>0040</fullName>
            </value>
            <value>
                <fullName>0050</fullName>
            </value>
            <value>
                <fullName>0060</fullName>
            </value>
            <value>
                <fullName>0070</fullName>
            </value>
            <value>
                <fullName>0090</fullName>
            </value>
            <value>
                <fullName>0100</fullName>
            </value>
            <value>
                <fullName>0110</fullName>
            </value>
            <value>
                <fullName>0120</fullName>
            </value>
            <value>
                <fullName>0130</fullName>
            </value>
            <value>
                <fullName>0150</fullName>
            </value>
            <value>
                <fullName>0001</fullName>
            </value>
            <value>
                <fullName>0160</fullName>
            </value>
            <value>
                <fullName>PL10</fullName>
            </value>
            <value>
                <fullName>PL20</fullName>
            </value>
            <value>
                <fullName>PL30</fullName>
            </value>
            <value>
                <fullName>PL40</fullName>
            </value>
            <value>
                <fullName>PL50</fullName>
            </value>
            <value>
                <fullName>PL55</fullName>
            </value>
            <value>
                <fullName>PL60</fullName>
            </value>
            <value>
                <fullName>PL65</fullName>
            </value>
            <value>
                <fullName>PL70</fullName>
            </value>
            <value>
                <fullName>PL95</fullName>
            </value>
            <value>
                <fullName>PL99</fullName>
            </value>
            <value>
                <fullName>0140</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CatalogElement__c/CatalogElement__c.object-meta.xml
<CustomObject>
    <description>[###][CatalogElement__c] Elementos de Catálogo de Preços, para montar a hierarquia</description>
    <label>Elemento de Catálogo</label>
    <nameField>
        <label>Nome do Elemento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elementos de Catálogo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplementaryProduct__c/ComplementaryProduct__c.object-meta.xml
<CustomObject>
    <label>Produto Complementar</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Produto Complementar</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos Complementares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplementaryProduct__c/fields/ComplementaryLkp__c.field-meta.xml
<CustomField>
    <fullName>ComplementaryLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material Sugerido</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos Complementares (Complementar)</relationshipLabel>
    <relationshipName>ComplementariesProduct</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplementaryProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos Complementares</relationshipLabel>
    <relationshipName>ComplementariesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ElementProduct__c/ElementProduct__c.object-meta.xml
<CustomObject>
    <description>[###][ElementProduct__c] Join entre elementos e produtos, para configurar a exibição do Catálogo de Preços</description>
    <label>Produto do Elemento</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Produto do Elemento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Elemento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Elementos de Catálogo</relationshipLabel>
    <relationshipName>ElementProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SalesOfficeTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOfficeTxt__c</fullName>
    <label>Escritório de vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuggestedProduct__c/SuggestedProduct__c.object-meta.xml
<CustomObject>
    <description>[a1B][SuggestedProduct__c]</description>
    <label>Produto Sugerido</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Produto Sugerido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos Sugeridos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SuggestedProduct__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Produtos Sugeridos</relationshipLabel>
    <relationshipName>SuggestedProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SuggestedProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos Sugeridos</relationshipLabel>
    <relationshipName>SuggestedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SuggestedProduct__c/fields/SalesOfficeTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOfficeTxt__c</fullName>
    <label>Escritório de Vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_PricebookComponentController.cls
@isTest
public class Test_PricebookComponentController {

    @isTest
    public static void testCatalog(){
        Product2 prod1 = TestData.createProduct('Tubo 1');
        Product2 prod2 = TestData.createProduct('Tubo 2');
        
        Pricebook__c pb = TestData.createPricebook('Catálogo Classe de Teste');
        CatalogElement__c rootElem1 = TestData.createCatalogElement('root1', 1, pb.id, null);
        CatalogElement__c rootElem2 = TestData.createCatalogElement('root2', 2, pb.Id, null);
        
        CatalogElement__c childElem1 = TestData.createCatalogElement('child1', 1, null, rootElem1.Id);
        CatalogElement__c childElem2 = TestData.createCatalogElement('child2', 1, null, rootElem2.Id);
        
        ElementProduct__c elPrd1 = TestData.createElementProduct(prod1, childElem1);
        ElementProduct__c elPrd2 = TestData.createElementProduct(prod2, childElem2);
        
        PricebookComponentController.findProductsPricebook(pb.Id);
        
        System.assertEquals(2, PricebookComponentController.getElementList(pb.Id, null, null).size());
        System.assertEquals(1, PricebookComponentController.getElementList(null, null, rootElem1.Id).size());
        
        System.assertEquals(2, PricebookComponentController.getProducts(pb.Id, null, null, null).size());
        System.assertEquals(0, PricebookComponentController.getProducts(null, rootElem2.Id, 'child1', null).size());
        
    }
    
    @isTest
    public static void testOrder(){
        Product2 prod1 = TestData.createProduct('Tubo 1');
        Product2 prod2 = TestData.createProduct('Tubo 2');
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV');
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '321312313213');
        
        SuggestedProduct__c sugProd = new SuggestedProduct__c(ChannelLkp__c = channel.Id, SalesOfficeTxt__c = salesArea.SalesOfficeTxt__c, ProductLkp__c = prod2.Id);
        insert sugProd;
        ComplementaryProduct__c cmpProd = new ComplementaryProduct__c(ProductLkp__c = prod1.Id, ComplementaryLkp__c = prod2.Id);
        insert cmpProd;
        
        PricebookComponentController.addProduct(prod1.Id, ord.Id, 10, false);
        
        System.assertEquals(1, [SELECT Id FROM OrderItem__c WHERE OrderMdt__c = :ord.Id].size());
        System.assertEquals(1, PricebookComponentController.suggestedProduct(ord.Id).size());
        System.assertEquals(1, PricebookComponentController.complementaryProduct(ord.Id).size());
        
    }
    
}