force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelPVCTxt__c.field-meta.xml
<CustomField>
    <fullName>ChannelPVCTxt__c</fullName>
    <label>Canal PVC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal PVC</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipName>AccountAreaSales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelPVCTxt__c.field-meta.xml
<CustomField>
    <fullName>ChannelPVCTxt__c</fullName>
    <label>Cód. Canal PVC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC1</fullName>
            </value>
            <value>
                <fullName>AC2</fullName>
            </value>
            <value>
                <fullName>AGE</fullName>
            </value>
            <value>
                <fullName>AGN</fullName>
            </value>
            <value>
                <fullName>AGS</fullName>
            </value>
            <value>
                <fullName>AV1</fullName>
            </value>
            <value>
                <fullName>AV2</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CON</fullName>
            </value>
            <value>
                <fullName>CTB</fullName>
            </value>
            <value>
                <fullName>CTD</fullName>
            </value>
            <value>
                <fullName>DTB</fullName>
            </value>
            <value>
                <fullName>DTR</fullName>
            </value>
            <value>
                <fullName>EMP</fullName>
            </value>
            <value>
                <fullName>EXP</fullName>
            </value>
            <value>
                <fullName>FAB</fullName>
            </value>
            <value>
                <fullName>FGB</fullName>
            </value>
            <value>
                <fullName>GEE</fullName>
            </value>
            <value>
                <fullName>GEN</fullName>
            </value>
            <value>
                <fullName>GES</fullName>
            </value>
            <value>
                <fullName>INB</fullName>
            </value>
            <value>
                <fullName>IND</fullName>
            </value>
            <value>
                <fullName>MIB</fullName>
            </value>
            <value>
                <fullName>OTB</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>PRB</fullName>
            </value>
            <value>
                <fullName>PRT</fullName>
            </value>
            <value>
                <fullName>REV</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/recordTypes/Amanco.recordType-meta.xml
<RecordType>
    <fullName>Amanco</fullName>
    <active>true</active>
    <label>Cliente Amanco</label>
</RecordType>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/ActiveVerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>ActiveVerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco Ativo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>VerdeAmancoKit__c.ChannelLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Canais</relationshipLabel>
    <relationshipName>Channels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/fields/CodeTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/VerdeAmancoSolicitation__c.object-meta.xml
<CustomObject>
    <description>[a12][VerdeAmancoSolicitation__c]</description>
    <label>Solicitação Verde Amanco</label>
    <nameField>
        <label>Nome da Solicitação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitações Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/AddressTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>AddressTypeTxt__c</fullName>
    <label>Tipo do Endereço</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Endereço do Cliente</fullName>
            </value>
            <value>
                <fullName>Endereço do Solicitante</fullName>
            </value>
            <value>
                <fullName>Outro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/CEPTxt__c.field-meta.xml
<CustomField>
    <fullName>CEPTxt__c</fullName>
    <label>CEP</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/CityTxt__c.field-meta.xml
<CustomField>
    <fullName>CityTxt__c</fullName>
    <label>Cidade</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/RequesterNameTxt__c.field-meta.xml
<CustomField>
    <fullName>RequesterNameTxt__c</fullName>
    <label>Nome Requisitante</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/SalesAreaLkp__c.field-meta.xml
<CustomField>
    <fullName>SalesAreaLkp__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Área de vendas</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Solicitações Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoSolicitations</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/ShippingAddressTxt__c.field-meta.xml
<CustomField>
    <fullName>ShippingAddressTxt__c</fullName>
    <label>Endereço de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/StateTxt__c.field-meta.xml
<CustomField>
    <fullName>StateTxt__c</fullName>
    <label>Estado</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Em preenchimento</fullName>
                <default>true</default>
                <label>Em preenchimento</label>
            </value>
            <value>
                <fullName>Enviando para o operador logístico</fullName>
            </value>
            <value>
                <fullName>Recebido pelo operador logístico</fullName>
            </value>
            <value>
                <fullName>Material entregue no endereço solicitado</fullName>
            </value>
            <value>
                <fullName>Fotos aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Fotos não aprovadas</fullName>
            </value>
            <value>
                <fullName>Fotos aprovadas</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/fields/VerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>VerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco</label>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Solicitações Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoSolicitations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/VerdeAmancoSolicitationTriggerHandler.cls
public class VerdeAmancoSolicitationTriggerHandler {
    
    public static void isBeforeInsert(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){
        List<Id> userAddressSelected = new List<Id>();
        List<Id> allAcct = new List<Id>();
        List<Id> allSalesAreas = new List<Id>();
        List<String> solicChannel = new List<String>();
        List<AccountAreaSales__c> totalSA = new List<AccountAreaSales__c>();
        List<AccountAreaSales__c> acct = new List<AccountAreaSales__c>();
        List<User> users = new List<User>();
        List<Channel__c> channel = new List<Channel__c>();
        
        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){
            
            if(solic.AddressTypeTxt__c=='Endereço do Solicitante'){
                userAddressSelected.add(UserInfo.getUserId());
            }
            if(solic.AddressTypeTxt__c=='Endereço do Cliente'){
                allAcct.add(solic.SalesAreaLkp__c);
            }
            allSalesAreas.add(solic.SalesAreaLkp__c);
        }
        
        if(!allSalesAreas.isEmpty()){
            totalSA=[Select Id, ChannelLkp__c, AccountLkp__c, ChannelPVCTxt__c
                       From AccountAreaSales__c
                       Where Id IN :allSalesAreas];
        }
        if(!allAcct.isEmpty()){
            acct = [Select Id, AccountLkp__c, AccountLkp__r.BillingStreet, AccountLkp__r.BillingState, AccountLkp__r.BillingCity, AccountLkp__r.BillingPostalCode
                       From AccountAreaSales__c
                       Where Id IN :allAcct];
        }
        
        
        if(!userAddressSelected.isEmpty()){
            users = [Select Id, Street, State, City, PostalCode
                                From User
                                Where Id IN :userAddressSelected];
        }

        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){
            for(AccountAreaSales__c sa : totalSA){
                if(sa.Id==solic.SalesAreaLkp__c){
                    if(sa.ChannelLkp__c!=Null){
                        solicChannel.add(sa.ChannelLkp__c);
                    }
                    else{
                        solic.addError('Só é possível criar uma Solicitação Verde Amanco se a área de vendas escolhida estiver com o campo "Canal PVC" preenchido.');
                    }
                }
            }
            
            if(solic.AddressTypeTxt__c=='Endereço do Cliente'){ 
                if(!acct.isEmpty()){
                    for(AccountAreaSales__c acc : acct){ 
                        if(acc.Id==solic.SalesAreaLkp__c){ 
                            solic.ShippingAddressTxt__c=acc.AccountLkp__r.BillingStreet;
                            solic.StateTxt__c=acc.AccountLkp__r.BillingState;
                            solic.CityTxt__c=acc.AccountLkp__r.BillingCity;
                            solic.CEPTxt__c=acc.AccountLkp__r.BillingPostalCode;
                        }
                
                    }	
                }    
            }
            
            if(solic.AddressTypeTxt__c=='Endereço do Solicitante'){
                if(!users.isEmpty()){
                    for(User us : users){                   
                        if(us.Id==UserInfo.getUserId()){                     
                            solic.ShippingAddressTxt__c=us.Street;
                            solic.StateTxt__c=us.State;
                            solic.CityTxt__c=us.City;
                            solic.CEPTxt__c=us.PostalCode;
                        }
                    }
                }
            }
            
            if(solic.RequesterNameTxt__c == null){
				solic.RequesterNameTxt__c = UserInfo.getName();
            }
            
        }

        channel = [Select Id, ActiveVerdeAmancoKitLkp__c, CodeTxt__c
                   From Channel__c
                   Where Id IN :solicChannel];
    
        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){            
            for(AccountAreaSales__c sa : totalSA){
                if(solic.SalesAreaLkp__c==sa.Id){
                    for(Channel__c cn :channel){
                        //Pega o Canal ao qual a Solicitação está ligada
                        if(sa.ChannelLkp__c==cn.Id){
                            if(cn.ActiveVerdeAmancoKitLkp__c!=Null){
                                //Preenche, com o Id do Kit Verde Amanco ligado ao Canal, o campo de pesquisa "Kit Verde Amanco" da Solicitação
                                solic.VerdeAmancoKitLkp__c = cn.ActiveVerdeAmancoKitLkp__c;
                            }
                            else{
                                solic.addError('Só é possível criar uma Solicitação Verde Amanco se o canal da área de vendas escolhida estiver com o campo "Kit Ativo" preenchido.');
                            }
                        }
                    }
                }
            }
            
        }
        
    }
    public static void isBeforeUpdate(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){
        List<Id> salesAreaAddressSelected = new List<Id>();
        List<Id> acountAddressSelected = new List<Id>();
        List<Id> userAddressSelected = new List<Id>();
        List<AccountAreaSales__c> acct = new List<AccountAreaSales__c>();
        List<User> users = new List<User>();
        List<AccountAreaSales__c> totalSA = new List<AccountAreaSales__c>();
        List<ContentDocumentLink> files = new List<ContentDocumentLink>();
        
        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){
            
            if(solic.AddressTypeTxt__c=='Endereço do Cliente' && solic.AddressTypeTxt__c!=OldMap.get(solic.Id).AddressTypeTxt__c){
                salesAreaAddressSelected.add(solic.SalesAreaLkp__c);
                
            }
            if(solic.AddressTypeTxt__c=='Endereço do Solicitante' && solic.AddressTypeTxt__c!=OldMap.get(solic.Id).AddressTypeTxt__c){
                userAddressSelected.add(solic.CreatedById);
            }
        }
        
        if(!salesAreaAddressSelected.isEmpty()){
            totalSA = [Select Id, AccountLkp__c, AccountLkp__r.BillingStreet, AccountLkp__r.BillingState, AccountLkp__r.BillingCity, AccountLkp__r.BillingPostalCode
                       From AccountAreaSales__c
                       Where Id IN :salesAreaAddressSelected];
        }
        
        if(!userAddressSelected.isEmpty()){
            users = [Select Id, Street, State, City, PostalCode
                     From User
                     Where Id IN :userAddressSelected];
        }

        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){  
            
            if(solic.AddressTypeTxt__c=='Endereço do Cliente' && solic.AddressTypeTxt__c!=OldMap.get(solic.Id).AddressTypeTxt__c){ 
                if(!totalSA.isEmpty()){
                    for(AccountAreaSales__c acc : totalSA){ 
                        if(acc.Id==solic.SalesAreaLkp__c){ 
                            solic.ShippingAddressTxt__c=acc.AccountLkp__r.BillingStreet;
                            solic.StateTxt__c=acc.AccountLkp__r.BillingState;
                            solic.CityTxt__c=acc.AccountLkp__r.BillingCity;
                            solic.CEPTxt__c=acc.AccountLkp__r.BillingPostalCode;
                        }
                    }
                }
            }
            
            if(solic.AddressTypeTxt__c=='Endereço do Solicitante' && solic.AddressTypeTxt__c!=OldMap.get(solic.Id).AddressTypeTxt__c){
                if(!users.isEmpty()){
                    for(User us : users){                   
                        if(us.Id==solic.CreatedById){                     
                            solic.ShippingAddressTxt__c=us.Street;
                            solic.StateTxt__c=us.State;
                            solic.CityTxt__c=us.City;
                            solic.CEPTxt__c=us.PostalCode;
                        }
                    }
                }
            }
            
            if(solic.AddressTypeTxt__c=='Outro' && solic.AddressTypeTxt__c!=OldMap.get(solic.Id).AddressTypeTxt__c){
                solic.ShippingAddressTxt__c=Null;
                solic.StateTxt__c=Null;
                solic.CityTxt__c=Null;
                solic.CEPTxt__c=Null;                                     
            }
            
            if(solic.RequesterNameTxt__c == null){
				solic.RequesterNameTxt__c = UserInfo.getName();
            }
        }
        
        
        for(VerdeAmancoSolicitation__c solic : listVerdeAmanco){
            if(solic.StatusTxt__c=='Aguardando aprovação' && solic.StatusTxt__c!=OldMap.get(solic.Id).StatusTxt__c){
                files = [SELECT ContentDocumentId 
                         FROM ContentDocumentLink 
                         WHERE LinkedEntityId =: solic.Id];
                if(files.isEmpty()){
                    solic.addError('É necessário anexar imagens à solicitação antes de enviar para aprovação.');
                }
                if(files.size()>4){
                    solic.addError('O número máximo de imagens que podem ser enviadas para aprovação é 4.');
                }
            }
        }

    }
    public static void isBeforeDelete(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){
        
    }
    public static void isAfterInsert(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){

    }
    public static void isAfterUpdate(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){

    }
    public static void isAfterDelete(List<VerdeAmancoSolicitation__c> listVerdeAmanco, Map<Id, VerdeAmancoSolicitation__c> oldMap){
        
    }
    

}