force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpeditionCenter__c/ExpeditionCenter__c.object-meta.xml
<CustomObject>
    <label>Local de Expedição</label>
    <nameField>
        <label>Nome de Local de Expedição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais de Expedição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <externalId>true</externalId>
    <label>Código do vendedor</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_QuotaIntegrationUtils.cls
@isTest
public class Test_QuotaIntegrationUtils {
    @isTest static void testQuotaBatch(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
        sel.SellerNumberNmb__c = '10586';
        update sel;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_ZPH_PREM');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('ZPH_PREM', mock);
        
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        QuotaIntegrationUtils.getQuota(new List<Seller__c>{sel}, new List<Date>{Date.newInstance(2018, 1, 1)});
        QuotaIntegrationUtils.execBatchApex();
        Test.stopTest();
        
    }
    
    @isTest static void testReceivables(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        acc.CodeCustomerTxt__c = '0000100944';
        update acc;
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_ZPH_BSID');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('ZPH_BSID', mock);
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        ReceivablesController.calcDelay('2018-01-01');
        
        Test.startTest();
        ReceivablesController.getReceivables(salesArea.Id);
        Test.stopTest();
        
    }
}