force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSurvey__c/CustomerSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço (Cliente)</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Nome de Pesquisa de Preço (Cliente)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço (Cliente)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSurvey__c/fields/IsActiveBln__c.field-meta.xml
<CustomField>
    <fullName>IsActiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/SurveyProduct__c.object-meta.xml
<CustomObject>
    <label>Produto da Pesquisa</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>Nome de Produto da Pesquisa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da Pesquisa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TradeMktSurvey__c/TradeMktSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço</label>
    <nameField>
        <label>Nome de Pesquisa de Preço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TradeMktSurvey__c/fields/BrandsTxt__c.field-meta.xml
<CustomField>
    <fullName>BrandsTxt__c</fullName>
    <label>Marcas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TradeMktSurvey__c/fields/IsActiveBln__c.field-meta.xml
<CustomField>
    <fullName>IsActiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ativa</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TradeMktSurvey__c/fields/LimitDate__c.field-meta.xml
<CustomField>
    <fullName>LimitDate__c</fullName>
    <label>Data Limite</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Test_AddSurveyResult.cls
@istest
public class Test_AddSurveyResult {

    @isTest static void testAll(){        
        
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Vendedor'];
        User u = TestData.createUser('TestSellerSurvey', null, null, prof.Id, 'sellerTestUser123@test.com');
        
        
        Profile profManager = [SELECT Id 
                               FROM Profile 
                               WHERE Name = 'Trade Marketing'];
        User uManager = TestData.createUser('TestManagerSurvey', null, null, profManager.Id, 'managerTestUser123@test.com');
        
        
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', uManager.Id);        
        Seller__c sel = TestData.createSeller('TestSeller', u.Id, so.Id);
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
        String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        
        Channel__c channel = TestData.createChannel('VJ1', null);
        
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Product2 prod1 = TestData.createProduct('Test Product 1');
        
        TradeMktSurvey__c trdMktSurv = TestData.createTrdMktSurvey();       
        
        trdMktSurv = [SELECT Id, Name, BrandsTxt__c, LimitDate__c, IsActiveBln__c FROM TradeMktSurvey__c WHERE Id = :trdMktSurv.Id];
        salesArea = [SELECT Id, Name, SellerLkp__r.UserLkp__c FROM AccountAreaSales__c WHERE Id = :salesArea.Id];
        
        CustomerSurvey__c cstmSurv =  TestData.createCustomerSurvey(trdMktSurv, salesArea, 'Incompleta');
        SurveyProduct__c survProd1 = TestData.createSurveyProduct(trdMktSurv, prod1, null, null);
        SurveyProduct__c survProd2 = TestData.createSurveyProduct(trdMktSurv, null, 'Test Product 2', '01');
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(cstmSurv);
        AddSurveyResult controller = new AddSurveyResult(stdCon);
        	
        system.runAs(u){
            controller.doSave();
        }
    }
    
    
}