force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/fields/ActiveVerdeAmancoKitLkp__c.field-meta.xml
<CustomField>
    <fullName>ActiveVerdeAmancoKitLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Kit Verde Amanco Ativo</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Id</field>
            <operation>equals</operation>
            <valueField>VerdeAmancoKit__c.ChannelLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>VerdeAmancoKit__c</referenceTo>
    <relationshipLabel>Canais</relationshipLabel>
    <relationshipName>Channels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoKit__c/VerdeAmancoKit__c.object-meta.xml
<CustomObject>
    <description>[###][VerdeAmancoKit__c]</description>
    <label>Kit Verde Amanco</label>
    <nameField>
        <label>Nome de Kit Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Kits Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoKitItem__c/VerdeAmancoKitItem__c.object-meta.xml
<CustomObject>
    <label>Item do Kit Verde Amanco</label>
    <nameField>
        <label>Nome de Item do Kit Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do Kit Verde Amanco</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoKitItem__c/fields/MaximumAmountNmb__c.field-meta.xml
<CustomField>
    <fullName>MaximumAmountNmb__c</fullName>
    <label>Quantidade máxima</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoRequestItem__c/VerdeAmancoRequestItem__c.object-meta.xml
<CustomObject>
    <description>[###][VerdeAmancoRequestItem__c]</description>
    <label>Item da Solicitação Verde Amanco</label>
    <nameField>
        <label>Nome de Item da Solicitação Verde Amanco</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Solicitação Verde Amanco</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/VerdeAmancoRequestItem__c/fields/AmountNmb__c.field-meta.xml
<CustomField>
    <fullName>AmountNmb__c</fullName>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoRequestItem__c/fields/VerdeAmancoKitItemLkp__c.field-meta.xml
<CustomField>
    <fullName>VerdeAmancoKitItemLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item do Kit Verde Amanco</label>
    <referenceTo>VerdeAmancoKitItem__c</referenceTo>
    <relationshipLabel>Itens da Solicitação Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoSolicitationItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoRequestItem__c/fields/VerdeAmancoSolicitationIdLkp__c.field-meta.xml
<CustomField>
    <fullName>VerdeAmancoSolicitationIdLkp__c</fullName>
    <label>Id Solicitação Verde Amanco</label>
    <referenceTo>VerdeAmancoSolicitation__c</referenceTo>
    <relationshipLabel>Itens da Solicitação Verde Amanco</relationshipLabel>
    <relationshipName>VerdeAmancoSolicitationItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/VerdeAmancoSolicitation__c/VerdeAmancoSolicitation__c.object-meta.xml
<CustomObject>
    <description>[a12][VerdeAmancoSolicitation__c]</description>
    <label>Solicitação Verde Amanco</label>
    <nameField>
        <label>Nome da Solicitação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Solicitações Verde Amanco</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CreateVARequestItem.cls
@isTest
private class Test_CreateVARequestItem {
    
    @isTest static void testCreateVA(){
        Channel__c chn = TestData.createChannel('TES', null);
        VerdeAmancoKit__c kit = TestData.createVerdeAmancoKit('TestKit', chn.Id);
        VerdeAmancoKitItem__c ki = TestData.createVerdeAmancoKitItem('TestKitItem', kit.Id, 2);
        chn.ActiveVerdeAmancoKitLkp__c = kit.Id;
        update chn;
        Account acct = TestData.createAccount('Test', chn.Id);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, chn.Id, null);
        VerdeAmancoSolicitation__c solic = TestData.createVerdeAmancoSolicitation('Test', salesArea.Id, 'Outro');
        ApexPages.StandardController stdController = new ApexPages.StandardController(solic);
        CreateVerdeAmancoRequestItem controller = new CreateVerdeAmancoRequestItem(stdController);    
        controller.saveSelected();
        //String cancelPage = controller.doCancel().getUrl();
        VerdeAmancoRequestItem__c ri = [Select Id, 	AmountNmb__c, VerdeAmancoKitItemLkp__c
                                        From VerdeAmancoRequestItem__c
                                        Where VerdeAmancoSolicitationIdLkp__c = :solic.Id];
        
        System.assertEquals(ki.Id, ri.VerdeAmancoKitItemLkp__c);
        System.assertEquals(ki.MaximumAmountNmb__c, ri.AmountNmb__c);
        //System.assertEquals('/' + solic.Id, cancelPage);
        //System.assertEquals('/' + solic.Id, savePage);


    } 

}