force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/PVCStringTxt__c.field-meta.xml
<CustomField>
    <fullName>PVCStringTxt__c</fullName>
    <description>String PVC, em formato JSON, para uso do componente do PVC. Vêm via interface</description>
    <label>Parâmetros PVC</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/LiquidIPINmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidIPINmb__c</fullName>
    <description>Valor líquido com IPI, vem via integração</description>
    <label>Preço C/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/LiquidNmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidNmb__c</fullName>
    <label>Valor líquido</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OriginalROBNoIPINmb__c.field-meta.xml
<CustomField>
    <fullName>OriginalROBNoIPINmb__c</fullName>
    <label>ROB s/ IPI Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ZPVO__c.field-meta.xml
<CustomField>
    <fullName>ZPVO__c</fullName>
    <label>Desconto de Volume Praticado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/SpecialProductBln__c.field-meta.xml
<CustomField>
    <fullName>SpecialProductBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se o produto faz parte da Cesta de Produtos Especiais, usado no PVC</description>
    <label>Produto Especial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SummarizedRevenue__c/SummarizedRevenue__c.object-meta.xml
<CustomObject>
    <description>[SummarizedRevenue__c] Faturamentos sumarizados, originados no BI</description>
    <label>Faturamento Sumarizado</label>
    <nameField>
        <label>Nome de Faturamento Sumarizado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos Sumarizados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_PVCController.cls
@isTest
public class Test_PVCController {

    @isTest
    public static void testOrder(){
        Product2 prod1 = TestData.createProduct('Tubo 1');
        prod1.SpecialProductBln__c = true;
        update prod1;
        Product2 prod2 = TestData.createProduct('Tubo 2');
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV');
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '321312313213');
        ord.PVCStringTxt__c = '[{"Scale":[{"Target":0,"Amount":5.000000000}],"Description":"Desconto de Canal","Code":"ZPVC"},' + 
        '"Scale":[{"Target":10000.000000000,"Amount":1.000000000},{"Target":20000.000000000,"Amount":2.000000000}],"Description":"Desconto Por Volume","Code":"YPVO"},' +
        '{"Scale":[{"Target":3.000000000,"Amount":2.000000000},{"Target":6.000000000,"Amount":4.000000000}],"Description":"Desconto de Política","Code":"YPXI"}]';
        update ord;
        
        PricebookComponentController.addProduct(prod1.Id, ord.Id, 10, false);
        ord = PVCController.getOrderData(ord.Id);
        List<OrderItem__c> listItems = [SELECT Id FROM OrderItem__c WHERE OrderMdt__c = :ord.Id];
        for(OrderItem__c oItem : listItems){
            //oItem.LiquidNmb__c = 10;
            //oItem.LiquidIPINmb__c = 10;
            oItem.OriginalROBNoIPINmb__c = 100;
        }
        update listItems;
        system.debug(listItems);
        System.assertEquals(100, PVCController.getOrderAmount(ord.Id, 'YPVO'));
        System.assertEquals(0, PVCController.getOrderAmount(ord.Id, 'YPME'));
        System.assertEquals(0, PVCController.getOrderAmount(ord.Id, 'YPMX'));
        System.assertEquals(0, PVCController.getOrderAmount(ord.Id, 'YPXI'));
        System.assertEquals(1, PVCController.getOrderAmount(ord.Id, 'YPSO'));
        String result = PVCController.applyDiscounts(ord.Id, 'YPVO', 2, 2);

        listItems = [SELECT Id, ZPVO__c FROM OrderItem__c WHERE OrderMdt__c = :ord.Id];
        
        
        System.assertEquals('SUCCESS', result);
        System.assertEquals(2, listItems[0].ZPVO__c);
        
    }
    
    @isTest
    public static void testAccountData(){
        Product2 prod1 = TestData.createProduct('Tubo 1');
        prod1.SpecialProductBln__c = true;
        update prod1;
        Product2 prod2 = TestData.createProduct('Tubo 2');
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV');
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '321312313213');
        
        SummarizedRevenue__c sumRev = TestData.createSummarizedRevenue(salesArea, System.today().addMonths(-2), '01');
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(System.today().year(), System.today().month(), 15), '02');
        PVCController.getAccountHistory(salesArea.Id, ord.Id);
    }
    
}