force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpeditionCenter__c/ExpeditionCenter__c.object-meta.xml
<CustomObject>
    <label>Local de Expedição</label>
    <nameField>
        <label>Nome de Local de Expedição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais de Expedição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpeditionCenter__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do Local</label>
    <length>4</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CommercialRemarkTxt__c.field-meta.xml
<CustomField>
    <fullName>CommercialRemarkTxt__c</fullName>
    <label>Observações comerciais</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/InvoiceHeaderTxt__c.field-meta.xml
<CustomField>
    <fullName>InvoiceHeaderTxt__c</fullName>
    <label>Texto cabeçalho nota fiscal</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/RepresentativeRemarkTxt__c.field-meta.xml
<CustomField>
    <fullName>RepresentativeRemarkTxt__c</fullName>
    <label>Observações representantes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OrderQuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderType__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id Customizado</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Condição de Pagamento</label>
    <nameField>
        <label>Condição de Pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id Customizado</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_OrderIntegrationUtils.cls
@isTest
public class Test_OrderIntegrationUtils {
    
    @isTest static void testQuote(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV', true, true, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, null, null, term281);
        ord.InvoiceHeaderTxt__c = 'TEST Inv';
        ord.CommercialRemarkTxt__c = 'TEST commercial';
        ord.RepresentativeRemarkTxt__c = 'TEST representative';
        update ord;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_CreateQuotation');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('Quotation', mock);

        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        OrderIntegrationUtils.resendQuoteHeader(ord.Id);
        Test.stopTest();
        
        System.assertEquals('60480006', [SELECT CustomIdTxt__c FROM Order__C WHERE Id = :ord.Id].CustomIdTxt__c);
        
    }
    
    @isTest static void testSingleItem(){
        TestData.createIntegrationData();
        TestData.createSkipValidations();
        Product2 prod1 = TestData.createProduct('Tubo 1');
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZOPU', true, true, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '60480006', null, term281);
        ord.InvoiceHeaderTxt__c = 'TEST Inv';
        ord.CommercialRemarkTxt__c = 'TEST commercial';
        ord.RepresentativeRemarkTxt__c = 'TEST representative';
        update ord;
        
        
        OrderItem__c item1 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 800, ProductLkp__c = prod1.Id);
        insert item1;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_QuotationChange');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('QuotationChange', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_OrderGetDetail');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('OrderGetDetail', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_S666');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('S666', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_ZPH_FCUR');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('ZPH_FCUR', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_KONH');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('KONH', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_Order');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('Order', mock);
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        OrderIntegrationUtils.createItemOnSAPFuture(ord.Id, item1.id);
        OrderIntegrationUtils.convertQuoteIntoOrder(ord.Id);
        ord = OrderIntegrationUtils.getOrder(ord.Id);
        Test.stopTest();
        
        
    }
    
    @isTest static void testMultipleItems(){
        TestData.createIntegrationData();
        Product2 prod1 = TestData.createProduct('Tubo 1');
        Product2 prod2 = TestData.createProduct('Tubo 2');
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV', true, true, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '60480006', null, term281);
        
        OrderItem__c item1 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 800, ProductLkp__c = prod1.Id);
        insert item1;
        OrderItem__c item2 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 400, ProductLkp__c = prod2.Id);
        insert item2;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_QuotationChange_Mult');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('QuotationChange', mock);
        
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_OrderGetDetail_Mult');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('OrderGetDetail', mock);
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        OrderIntegrationUtils.resendItems(ord.Id);
        Test.stopTest();
        
    }
    
    
    @isTest static void deleteItem(){
        TestData.createIntegrationData();
        Product2 prod1 = TestData.createProduct('Tubo 1');
        Product2 prod2 = TestData.createProduct('Tubo 2');
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV', true, true, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '60480006', null, term281);
        
        OrderItem__c item1 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 800, ProductLkp__c = prod1.Id);
        insert item1;
        OrderItem__c item2 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 400, ProductLkp__c = prod2.Id);
        insert item2;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_QuotationChange');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('QuotationChange', mock);
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        OrderIntegrationUtils.deleteItemOnSAPFuture(ord.Id, new List<Id>{item1.id});
        Test.stopTest();
    }
    
}