force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ExpeditionCenter__c/ExpeditionCenter__c.object-meta.xml
<CustomObject>
    <label>Local de Expedição</label>
    <nameField>
        <label>Nome de Local de Expedição</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locais de Expedição</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/ShippingSplitDoneBln__c.field-meta.xml
<CustomField>
    <fullName>ShippingSplitDoneBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se já foi realizada a quebra de remessa</description>
    <label>Quebra de Remessa Realizada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SuggestedDoneBln__c.field-meta.xml
<CustomField>
    <fullName>SuggestedDoneBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Marca como verdadeiro quando acessa a tela de &quot;Produtos Sugeridos&quot;</description>
    <label>Visualizou Sugeridos</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/BottleneckDaysNmb__c.field-meta.xml
<CustomField>
    <fullName>BottleneckDaysNmb__c</fullName>
    <description>Número de dias em gargalo, recebido via integração. Deve ser mapeado para um semáforo</description>
    <label>Dias de Gargalo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/DistributionCenterTxt__c.field-meta.xml
<CustomField>
    <fullName>DistributionCenterTxt__c</fullName>
    <label>Centro de Distribuição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>DistributionCenter</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ExpeditionCenterLkp__c.field-meta.xml
<CustomField>
    <fullName>ExpeditionCenterLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Local de Expedição</label>
    <referenceTo>ExpeditionCenter__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/LiquidIPINmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidIPINmb__c</fullName>
    <description>Valor líquido com IPI, vem via integração</description>
    <label>Preço C/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/LiquidNmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidNmb__c</fullName>
    <label>Valor líquido</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OrderQuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OriginalQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OriginalQuantityNmb__c</fullName>
    <description>Quantidade no momento que o item é inserido no pedido, para comparar valores totais vindos do SAP</description>
    <label>Quantidade Original</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OriginalROBNoIPINmb__c.field-meta.xml
<CustomField>
    <fullName>OriginalROBNoIPINmb__c</fullName>
    <label>ROB s/ IPI Inicial</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <description>Preenchido via Workflow</description>
    <label>Código do Produto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/PVCPriceIPINmb__c.field-meta.xml
<CustomField>
    <fullName>PVCPriceIPINmb__c</fullName>
    <description>Preço após políticas PVC, aplicadas sobre o preço com IPI</description>
    <label>Preço com Política e IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/PVCPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>PVCPriceNmb__c</fullName>
    <description>Campo que armazena o preço líquido após aplicação de descontos de política PVC</description>
    <label>Preço com Política</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalGrossCostNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalGrossCostNmb__c</fullName>
    <label>Valor total bruto</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/UnitPriceIPINmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceIPINmb__c</fullName>
    <description>Preço final, com descontos, aplicados sobre o preço com Política e IPI</description>
    <label>Preço Final com IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/UnitPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceNmb__c</fullName>
    <description>Preço final, com descontos aplicados sobre o preço com Política</description>
    <label>Preço Final Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/XXES__c.field-meta.xml
<CustomField>
    <fullName>XXES__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Desconto estratégico de até 5%</description>
    <label>Desconto Estratégico</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PaymentTerm__c/PaymentTerm__c.object-meta.xml
<CustomObject>
    <label>Condição de Pagamento</label>
    <nameField>
        <label>Condição de Pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de Pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product2/fields/GrossWeightNmb__c.field-meta.xml
<CustomField>
    <fullName>GrossWeightNmb__c</fullName>
    <label>Peso bruto</label>
    <precision>15</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IrrigationItemBln__c.field-meta.xml
<CustomField>
    <fullName>IrrigationItemBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item Irrigação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/LoadPercentageNmb__c.field-meta.xml
<CustomField>
    <fullName>LoadPercentageNmb__c</fullName>
    <label>Percentual de Carga</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/SpecialProductBln__c.field-meta.xml
<CustomField>
    <fullName>SpecialProductBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para indicar se o produto faz parte da Cesta de Produtos Especiais, usado no PVC</description>
    <label>Produto Especial</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/StandardPackageAmountNmb__c.field-meta.xml
<CustomField>
    <fullName>StandardPackageAmountNmb__c</fullName>
    <description>Quantidade de itens por embalagem padrão</description>
    <label>Quantidade da Embalagem Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceNmb__c</fullName>
    <description>Campo de Preço Unitário utilizado, provisoriamente, no Mobile</description>
    <label>Preço Unitário Mobile</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitWeightTxt__c.field-meta.xml
<CustomField>
    <fullName>UnitWeightTxt__c</fullName>
    <label>Unidade peso</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_OrderComponentController.cls
@isTest
public class Test_OrderComponentController {

    @isTest static void testOrder(){
        Product2 prod1 = TestData.createProduct('Tubo 1');
        prod1.SpecialProductBln__c = true;
        prod1.StandardPackageAmountNmb__c = 10;
        update prod1;
        Product2 prod2 = TestData.createProduct('Tubo 2');
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV', true, false, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(salesArea.Id, acc.Id, ot.Id, pb.Id, '321312313213', null, term281);
        
        String response = OrderComponentController.addProductFromCart(ord.Id, prod1.ProductCodeTxt__c, 10, true);
        System.assertEquals('SUCCESS:', response);
        List<OrderItem__c> listItems = OrderComponentController.getOrderItems(ord.Id);
        System.assertEquals(100, listItems[0].OrderQuantityNmb__c);
        
        for(OrderItem__c item : listItems){
            item.LiquidNmb__c = 10;
            item.LiquidIpiNmb__c = 11;
            item.PVCPriceNmb__c = 10;
            item.PVCPriceIPINmb__c = 11;
            item.UnitPriceNmb__C = 10;
            item.UnitPriceIPINmb__C = 11;
        }
        update listItems;
        response = OrderComponentController.saveDiscountGlobal(ord.Id, 'XXES__c', 2);
        System.assertEquals('SUCCESS', response);
        listItems = OrderComponentController.getOrderItems(ord.Id);
        System.assertEquals(2, listItems[0].XXES__c);
        System.assertEquals(9.8, listItems[0].UnitPriceNmb__c);
        
        response = OrderComponentController.applyDiscount(listItems[0].id, 0, 0, 0, 50);
        listItems = OrderComponentController.getOrderItems(ord.Id);
        System.assertEquals(0, listItems[0].XXES__c);
        System.assertEquals(10, listItems[0].UnitPriceNmb__c);
        System.assertEquals(50, listItems[0].OrderQuantityNmb__c);
        
        response = OrderComponentController.deleteProduct(listItems[0].Id);
        System.assertEquals('SUCCESS', response);
        System.assertEquals(0, OrderComponentController.getOrderItems(ord.Id).size());
        
        List<PaymentTerm__c> listTerms = OrderCOmponentController.getPaymentTerms(ord.Id);
        system.assertEquals(2, listTerms.size());
        
    }
    
    @isTest static void testShipping(){
        
        Product2 prod1 = TestData.createProduct('Tubo 1');
        prod1.LoadPercentageNmb__c = 0.143;
        prod1.StandardPackageAmountNmb__c = 5;
        prod1.GrossWeightNmb__c = 5;
        prod1.UnitWeightTxt__c = 'G';
        prod1.IrrigationItemBln__c = true;
        update prod1;
        
        Product2 prod2 = TestData.createProduct('Tubo 2');
        prod2.LoadPercentageNmb__c = 0.1;
        prod2.StandardPackageAmountNmb__c = 10;
        prod2.GrossWeightNmb__c = 5;
        prod2.UnitWeightTxt__c = 'G';
        prod2.IrrigationItemBln__c = true;
        update prod2;
        
        Product2 prod20159 = TestData.createProduct('20159');
        prod20159.LoadPercentageNmb__c = 0.001;
        prod20159.StandardPackageAmountNmb__c = 1;
        prod20159.GrossWeightNmb__c = 1;
        prod20159.UnitWeightTxt__c = 'G';
        prod20159.IrrigationItemBln__c = true;
        update prod20159;
        
        Product2 prod20109 = TestData.createProduct('20109');
        prod20109.LoadPercentageNmb__c = 0.001;
        prod20109.StandardPackageAmountNmb__c = 1;
        prod20109.GrossWeightNmb__c = 1;
        prod20109.UnitWeightTxt__c = 'G';
        prod20109.IrrigationItemBln__c = true;
        update prod20109;
        
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        ExpeditionCenter__c expCenter = TestData.createExpeditionCenter('0070', '0700');
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        Pricebook__c pb = TestData.createPricebook('TestPricebook');
        OrderType__c ot = TestData.createOrderType('ZNOV', true, true, true, false);
        PaymentTerm__c term281 = TestData.createPaymentTerm('C281', 1, 28);
        PaymentTerm__c term282 = TestData.createPaymentTerm('C282', 2, 28);
        Order__c ord = TestData.createOrder(null, acc.Id, ot.Id, pb.Id, '321312313213', null, term281);
        
        //String response = OrderComponentController.addProductFromCart(ord.Id, prod2.ProductCodeTxt__c, 1000, false);
        //System.assertEquals('SUCCESS:', response);
        
        OrderItem__c item2 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 1150, ProductLkp__c = prod2.Id);
        item2.ExpeditionCenterLkp__c = expCenter.Id;
        item2.DistributionCenterTxt__c = '0700';
        item2.OriginalROBNoIPINmb__c = 23000;
        item2.TotalGrossCostNmb__c = 23000;
        item2.BottleneckDaysNmb__c = 2;
        /*
        item2.LiquidNmb__c = 20;
        item2.LiquidIpiNmb__c = 22;
        item2.PVCPriceNmb__c = 20;
        item2.PVCPriceIPINmb__c = 22;
        item2.UnitPriceNmb__C = 20;
        item2.UnitPriceIPINmb__C = 22;
*/
        //Teste Caio
        //item2.OrderQuantityNmb__c = 30;
        //item2.OriginalROBNoIPINmb__c = 200;
        //item2.OriginalQuantityNmb__c = 20;
        //
        insert item2;
        
        //response = OrderComponentController.addProductFromCart(ord.Id, prod1.ProductCodeTxt__c, 800, false);
        //System.assertEquals('SUCCESS:', response);
        
        OrderItem__c item1 = new OrderItem__c (OrderMdt__c = ord.Id, OrderQuantityNmb__c = 800, ProductLkp__c = prod1.Id);
        item1.ExpeditionCenterLkp__c = expCenter.Id;
        item1.DistributionCenterTxt__c = '0700';
        item1.OriginalROBNoIPINmb__c = 8000;
        item1.TotalGrossCostNmb__c = 8500;
        item1.BottleneckDaysNmb__c = 45;
        /*
        item1.LiquidNmb__c = 10;
        item1.LiquidIpiNmb__c = 11;
        item1.PVCPriceNmb__c = 10;
        item1.PVCPriceIPINmb__c = 11;
        item1.UnitPriceNmb__C = 10;
        item1.UnitPriceIPINmb__C = 11;
*/
        //Teste Caio
        //item1.OrderQuantityNmb__c = 3;
        //item1.OriginalROBNoIPINmb__c = 1;
        //item1.OriginalQuantityNmb__c = 1;
        //
        insert item1;
        
        Test.startTest();
        
        String remessas = OrderComponentController.getRemessas(ord.Id, false);
        remessas = OrderComponentController.getRemessas(ord.Id, true);
        system.debug(remessas);
        
        String response = OrderComponentController.alocateKits(ord.Id, remessas);
        System.assertEquals('SUCCESS', response);
        
        //System.assertEquals(8, [SELECT Id FROM OrderItem__c WHERE OrderMdt__c = :ord.Id].size());
                        
        response = OrderComponentController.saveRemessas(ord.Id, remessas);
        System.assertEquals('SUCCESS', response);
        response = OrderComponentController.saveRemessas(ord.Id, remessas);
        
        OrderItem__c item3 = [SELECT Id FROM OrderItem__c WHERE ProductLkp__c = :prod2.Id AND OrderQuantityNmb__c = 150];
        
        remessas = OrderComponentController.getRemessas(ord.Id, true);
        system.debug(remessas);

        OrderComponentController.modifyRemessas(remessas, item1.Id, 1, 6);
        OrderComponentController.modifyRemessas(remessas, item2.Id, 3, 1);
        OrderComponentController.modifyRemessas(remessas, item3.Id, 4, 3);
        
        //System.assertEquals(true, [SELECT ShippingSplitDoneBln__c FROM Order__c Where Id = :ord.Id].ShippingSplitDoneBln__c);
        System.assertEquals(12, [SELECT Id FROM OrderItem__c WHERE OrderMdt__c = :ord.Id].size());
        
        ord.SuggestedDoneBln__c = true;
        update ord;
        
        response = OrderComponentController.convertQuoteIntoOrderAsync(ord.Id);
        response = OrderComponentController.convertQuoteIntoOrder(ord.Id);
        system.debug(response);
        
        Test.stopTest();
        
        
    }
    
}