force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ChannelPVCTxt__c.field-meta.xml
<CustomField>
    <fullName>ChannelPVCTxt__c</fullName>
    <label>Canal PVC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/FidelityTxt__c.field-meta.xml
<CustomField>
    <fullName>FidelityTxt__c</fullName>
    <label>Fidelidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fidelity</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelPVCTxt__c.field-meta.xml
<CustomField>
    <fullName>ChannelPVCTxt__c</fullName>
    <label>Cód. Canal PVC</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>AC1</fullName>
            </value>
            <value>
                <fullName>AC2</fullName>
            </value>
            <value>
                <fullName>AGE</fullName>
            </value>
            <value>
                <fullName>AGN</fullName>
            </value>
            <value>
                <fullName>AGS</fullName>
            </value>
            <value>
                <fullName>AV1</fullName>
            </value>
            <value>
                <fullName>AV2</fullName>
            </value>
            <value>
                <fullName>CAB</fullName>
            </value>
            <value>
                <fullName>CAP</fullName>
            </value>
            <value>
                <fullName>CAS</fullName>
            </value>
            <value>
                <fullName>CON</fullName>
            </value>
            <value>
                <fullName>CTB</fullName>
            </value>
            <value>
                <fullName>CTD</fullName>
            </value>
            <value>
                <fullName>DTB</fullName>
            </value>
            <value>
                <fullName>DTR</fullName>
            </value>
            <value>
                <fullName>EMP</fullName>
            </value>
            <value>
                <fullName>EXP</fullName>
            </value>
            <value>
                <fullName>FAB</fullName>
            </value>
            <value>
                <fullName>FGB</fullName>
            </value>
            <value>
                <fullName>GEE</fullName>
            </value>
            <value>
                <fullName>GEN</fullName>
            </value>
            <value>
                <fullName>GES</fullName>
            </value>
            <value>
                <fullName>INB</fullName>
            </value>
            <value>
                <fullName>IND</fullName>
            </value>
            <value>
                <fullName>MIB</fullName>
            </value>
            <value>
                <fullName>OTB</fullName>
            </value>
            <value>
                <fullName>OTR</fullName>
            </value>
            <value>
                <fullName>PRB</fullName>
            </value>
            <value>
                <fullName>PRT</fullName>
            </value>
            <value>
                <fullName>REV</fullName>
            </value>
            <value>
                <fullName>VJ1</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Quota__c/Quota__c.object-meta.xml
<CustomObject>
    <description>[a10][Quota__c] Cota definida mensalmente para cada coordenador/vendedor.</description>
    <label>Planejamento</label>
    <nameField>
        <displayFormat>Cota {0000000}</displayFormat>
        <label>Nome de Planejamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planejamentos</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SummarizedRevenue__c/SummarizedRevenue__c.object-meta.xml
<CustomObject>
    <description>[SummarizedRevenue__c] Faturamentos sumarizados, originados no BI</description>
    <label>Faturamento Sumarizado</label>
    <nameField>
        <label>Nome de Faturamento Sumarizado</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Faturamentos Sumarizados</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AddSalesPlan.cls
@isTest
public class Test_AddSalesPlan {

    @isTest static void testAll(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User u = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', u.Id);
        Seller__c sel = TestData.createSeller('TestSeller', u.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        AccountAreaSales__c salesArea2 = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        
        SummarizedRevenue__c sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2018, 01, 1), '01');
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 02, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 03, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 04, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 05, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 06, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 07, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 08, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 09, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 10, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 11, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 12, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 01, 1), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 12, 10), 100);   
		sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2018, 01, 10), 100);  
        
        sumRev = TestData.createSummarizedRevenue(salesArea2, System.today().addMonths(-8), '01');
        sumRev = TestData.createSummarizedRevenue(salesArea2, Date.newInstance(System.today().year(), System.today().month(), 15), '02');
        
        Quota__c quota = TestData.createQuota(sel, '2018', '01', 'Atingimento de Cota', u);
        
        Event evt = new Event(WhatId = salesArea.Id,                              
                              StartDateTime = Datetime.newInstance(2018, 01, 10,10,10,10),
                              DurationInMinutes = 120);
    
        insert evt;
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(quota);
        AddSalesPlan controller = new AddSalesPlan(stdCon);
        controller.getRemainingAmount();
        
		controller.getFilterOptions();
        controller.planFilter = 'AccountCityTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'AccountPostalCodeTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'CampaignLkp__c';
        controller.getFilterValues();
        controller.planFilter = 'ChannelPVCTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'FidelityTxt__c';
        controller.getFilterValues();
        
        controller.planFilterValue = channel.Id;
        controller.getPlanList();
               
        controller.getCustomerLossReason();
        controller.getPageNums();
        controller.getPriority1();
        controller.getPriority2();
        controller.getTrdMktActions();
        
        controller.doSave();
        
        /*String salesAreaId, String dateTimeString, String durationString, String trdMktActionString, String priority1String, String priority2String,
            String priority3String, String customerLossReasonString, String guestId, Boolean isRecurrent, string recurrenceTypeString, string limitDateString
          */   
        AddSalesPlan.doSaveEventRemote(salesArea.Id, '2018-01-01', '12', 'Ação1', 'priority1String', 'priority2String', 'priority3String', 'customerLossReasonString',
                                      null, true, 'Semanal', '2018-01-19');
        //System.assertEquals(2, [SELECT Id FROM Event WHERE QuotaLkp__c = :quota.Id].size());
        
        Quota__c quota2 = TestData.createQuota(sel, '2017', '05', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota2);
        AddSalesPlan controller2 = new AddSalesPlan(stdCon);
        
        /*Quota__c quota3 = TestData.createQuota(sel, '2017', '09', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota3);
        AddSalesPlan controller3 = new AddSalesPlan(stdCon);
        
        Quota__c quota4 = TestData.createQuota(sel, '2017', '11', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota4);
        AddSalesPlan controller4 = new AddSalesPlan(stdCon);*/
    }
    
    @isTest static void test2ndSemester(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User u = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', u.Id);
        Seller__c sel = TestData.createSeller('TestSeller', u.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        Channel__c channel = TestData.createChannel('VJ1', null);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        AccountAreaSales__c salesArea2 = TestData.createAccountAreaSales(acc.Id, channel.Id, sel.Id);
        
        SummarizedRevenue__c sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2018, 08, 1), '01');
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 02, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 03, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 04, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 05, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 06, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 07, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 08, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 09, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 10, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 11, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 12, 15), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 01, 1), 100);
        sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2017, 12, 10), 100);  
		sumRev = TestData.createSummarizedRevenue(salesArea, Date.newInstance(2018, 08, 10), 100);  
        
        sumRev = TestData.createSummarizedRevenue(salesArea2, System.today().addMonths(-8), '01');
        sumRev = TestData.createSummarizedRevenue(salesArea2, Date.newInstance(System.today().year(), System.today().month(), 15), '02');
        
        Quota__c quota = TestData.createQuota(sel, '2018', '08', 'Atingimento de Cota', u);
        
        Event evt = new Event(WhatId = salesArea.Id,                              
                              StartDateTime = Datetime.newInstance(2018, 08, 10,10,10,10),
                              DurationInMinutes = 120);
    
        insert evt;
        
        ApexPages.StandardController stdCon = new ApexPages.StandardController(quota);
        AddSalesPlan controller = new AddSalesPlan(stdCon);
        controller.getRemainingAmount();
        
		controller.getFilterOptions();
        controller.planFilter = 'AccountCityTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'AccountPostalCodeTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'CampaignLkp__c';
        controller.getFilterValues();
        controller.planFilter = 'ChannelPVCTxt__c';
        controller.getFilterValues();
        controller.planFilter = 'FidelityTxt__c';
        controller.getFilterValues();
        
        controller.planFilterValue = channel.Id;
        controller.getPlanList();
               
        controller.getCustomerLossReason();
        controller.getPageNums();
        controller.getPriority1();
        controller.getPriority2();
        controller.getTrdMktActions();
        
        controller.doSave();
        
        /*String salesAreaId, String dateTimeString, String durationString, String trdMktActionString, String priority1String, String priority2String,
            String priority3String, String customerLossReasonString, String guestId, Boolean isRecurrent, string recurrenceTypeString, string limitDateString
          */   
        AddSalesPlan.doSaveEventRemote(salesArea.Id, '2018-08-01', '12', 'Ação1', 'priority1String', 'priority2String', 'priority3String', 'customerLossReasonString',
                                      null, true, 'Mensal', '2018-11-19');
        //System.assertEquals(2, [SELECT Id FROM Event WHERE QuotaLkp__c = :quota.Id].size());
        
        Quota__c quota2 = TestData.createQuota(sel, '2017', '12', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota2);
        AddSalesPlan controller2 = new AddSalesPlan(stdCon);
        
        /*Quota__c quota3 = TestData.createQuota(sel, '2017', '09', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota3);
        AddSalesPlan controller3 = new AddSalesPlan(stdCon);
        
        Quota__c quota4 = TestData.createQuota(sel, '2017', '11', 'Atingimento de Cota', u);
        stdCon = new ApexPages.StandardController(quota4);
        AddSalesPlan controller4 = new AddSalesPlan(stdCon);*/
    }
    
}