force-app/main/default/objects/Account/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Campo fórmula com o nome do canal. Utilizado apenas para Contas do tipo Agrupamento de Campanha</description>
    <formula>MainAccountLkp__r.ChannelLkp__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/ConvertLeadBln__c.field-meta.xml
<CustomField>
    <fullName>ConvertLeadBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que é verdadeiro se a conta é originária de conversão de lead. Preenchido via mapeamento para Emissor, via código para Parceiros</description>
    <label>Lead Convertido?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>[a03][Address__c] Endereço utilizado em contas.</description>
    <label>Endereço</label>
    <nameField>
        <label>Rua</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/CEPTxt__c.field-meta.xml
<CustomField>
    <fullName>CEPTxt__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/CityTxt__c.field-meta.xml
<CustomField>
    <fullName>CityTxt__c</fullName>
    <label>Cidade</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/LeadLkp__c.field-meta.xml
<CustomField>
    <fullName>LeadLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Novo Cliente</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PartnerStateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerStateInscriptionTxt__c</fullName>
    <label>Inscrição Estadual Parceiro</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Channel__c/Channel__c.object-meta.xml
<CustomObject>
    <description>[###][Channel__c]</description>
    <label>Canal</label>
    <nameField>
        <label>Nome de Canal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Canais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead/fields/ApprovalStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatusTxt__c</fullName>
    <description>Campo utilizado para impedir um usuário de pular etapas no Sales Path de Lead. Existe uma regra de validação que verifica se o valor desse campo é igual ao do campo &quot;Aprovação&quot; e, caso não seja, não permite que o Sales Path seja alterado.</description>
    <label>Status da aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando envio para aprovação</fullName>
                <default>true</default>
                <label>Vendedor</label>
            </value>
            <value>
                <fullName>Enviado para aprovação</fullName>
                <label>Cadastro</label>
            </value>
            <value>
                <fullName>Aprovado na etapa 1</fullName>
                <label>Fiscal</label>
            </value>
            <value>
                <fullName>Aprovado na etapa 2</fullName>
                <label>Enviado ao SAP</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/ApprovalTxt__c.field-meta.xml
<CustomField>
    <fullName>ApprovalTxt__c</fullName>
    <label>Aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando envio para aprovação</fullName>
                <default>true</default>
                <label>Aguardando envio para aprovação</label>
            </value>
            <value>
                <fullName>Enviado para aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado na etapa 1</fullName>
                <label>Aprovado pela área de cadastro</label>
            </value>
            <value>
                <fullName>Aprovado na etapa 2</fullName>
                <label>Aprovado pela área fiscal</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <inlineHelpText>Escreva apenas números sem separações entre eles. 
Exemplo: 66753556000167.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/ConvertLeadBln__c.field-meta.xml
<CustomField>
    <fullName>ConvertLeadBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Converter Lead</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RegisteredInDatabaseBln__c.field-meta.xml
<CustomField>
    <fullName>RegisteredInDatabaseBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Cadastrado na Base</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_LeadTriggerHandler.cls
@isTest
private class Test_LeadTriggerHandler {

    @isTest static void isRegistered(){
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', null, so.Id);
        Lead l = TestData.createLead('TestCompany', null, sel.Id);
        Address__c add = new Address__c (Name = 'Rua 1', 
                                         Leadlkp__c = l.Id, 
                                         CNPJTxt__c = l.CNPJTxt__c, 
                                         CEPTxt__c = l.PostalCode,
                                         StateTxt__c = l.StateCode,
                                         PartnerStateInscriptionTxt__c = l.RG_StateInscriptionTxt__c,
                                         CityTxt__c = 'São Paulo',
                                         Phone__c = l.Phone
                                        );
        insert add;
        Account acc = TestData.createAccount('TestCompany', null);
        
        l.ConvertLeadBln__c = true;
        update l;
        l = [Select Id, RegisteredInDatabaseBln__c
             From Lead 
             Where Id =: l.Id];
        System.assertEquals(true, l.RegisteredInDatabaseBln__c);
        List<RecordType> rts = [SELECT Id 
                                FROM RecordType 
                                WHERE DeveloperName = 'SAPBusinessAccount' LIMIT 1];
        acc = [Select Id, RecordTypeId, CNPJTxt__c 
          	   From Account 
               Where Id =: acc.Id];
        System.assertEquals(rts[0].Id, acc.RecordTypeId);

    }
    
    @isTest static void testApprovalStep1(){
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', null, so.Id);
        Channel__c chn = TestData.createChannel('TES', null);
        Lead l = TestData.createLead('Nome de Teste', chn.Id, sel.Id);
        l.ApprovalTxt__C = 'Enviado para aprovação';
        l.ApprovalStatusTxt__C = 'Enviado para aprovação';
        update l;
        System.assertEquals('Enviado para aprovação', l.ApprovalTxt__c);
    }
    
    @isTest static void testApprovalStep2(){
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', null, so.Id);
        Channel__c chn = TestData.createChannel('TES', null);
        Lead l = TestData.createLead('Nome de Teste', chn.Id, sel.Id);
        l.ApprovalTxt__C = 'Aprovado na etapa 1';
        l.ApprovalStatusTxt__C = 'Aprovado na etapa 1';
        update l;
        System.assertEquals('Aprovado na etapa 1', l.ApprovalTxt__c);
    }
    
    @isTest static void testApprovalStep3(){
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', null, so.Id);
        Channel__c chn = TestData.createChannel('TES', null);
        Lead l = TestData.createLead('Nome de Teste', chn.Id, sel.Id);
        l.ApprovalTxt__C = 'Aprovado na etapa 2';
        l.ApprovalStatusTxt__C = 'Aprovado na etapa 2';
        update l;
        System.assertEquals('Aprovado na etapa 2', l.ApprovalTxt__c);
    }
}