force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/MainSalesAreaLkp__c.field-meta.xml
<CustomField>
    <fullName>MainSalesAreaLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de Vendas Principal</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Agrupamento de Campanha</relationshipLabel>
    <relationshipName>SalesArea</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CampaignGroup.recordType-meta.xml
<RecordType>
    <fullName>CampaignGroup</fullName>
    <active>true</active>
    <description>Agrupamento utilizado na Campanha de Trade Marketing</description>
    <label>Agrupamento de Campanha</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <formula>AccountLkp__r.CNPJTxt__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/test_AccountAreaSalesTriggerHandler.cls
@isTest
private class test_AccountAreaSalesTriggerHandler {
    
    @isTest static void testInsertAndUpdate(){   
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User oldUserSeller = TestData.createUser('TestUser', null, null, prof.Id, 'testUser321@test.com');
        oldUserSeller.CommunityNickname = 'TestCommunityNicknameX';
        update oldUserSeller;
        User newUserSeller = TestData.createUser('TestUser2', null, null, prof.Id, 'testUser2321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', oldUserSeller.Id);
        Seller__c oldSeller = TestData.returnSeller('TestSeller', oldUserSeller.Id, so.Id);
        insert oldSeller;
        Account acct = TestData.createAccount('Test Account', null, null, rtSACAcc);
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, oldSeller.Id); 
        AccountTeamMember atm = [SELECT Id, AccountId, UserId 
                                 FROM AccountTeamMember 
                                 WHERE AccountId =: acct.Id];
        System.assertEquals(oldUserSeller.Id, atm.UserId);   
        
        Seller__c newSeller = TestData.returnSeller('TestSeller2', newUserSeller.Id, so.Id);
        insert newSeller;
        salesArea.SellerLkp__c = newSeller.Id;
        update salesArea;
        atm = [SELECT Id, AccountId, UserId 
               FROM AccountTeamMember 
               WHERE AccountId =: acct.Id];
        System.assertEquals(newUserSeller.Id, atm.UserId);
        
        delete salesArea;
        AccountAreaSales__c deletedSalesArea = [Select Id, IsDeleted
                                                From AccountAreaSales__c
                                                Where Id =: salesArea.Id ALL ROWS];
        System.assertEquals(deletedSalesArea.IsDeleted, true);
    }

    @isTest static void testInsertUpdateAcc(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User oldUserSeller = TestData.createUser('TestUser', null, null, prof.Id, 'testUser321@test.com');
        oldUserSeller.CommunityNickname = 'TestCommunityNicknameX';
        update oldUserSeller;
        User newUserSeller = TestData.createUser('TestUser2', null, null, prof.Id, 'testUser2321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', oldUserSeller.Id);
        Seller__c oldSeller = TestData.returnSeller('TestSeller', oldUserSeller.Id, so.Id);
        insert oldSeller;
        Account acct = TestData.createAccount('Account', null, null, rtSACAcc);
        acct.CNPJTxt__c = '623994827364987';
        update acct;
        Account acct2 = TestData.createAccount('Account2', null, null, rtSACAcc);
        acct2.CNPJTxt__c = '623984827364987';
        update acct2;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, oldSeller.Id); 
        Account cmpAcc = TestData.createAccount('CampaignGroup', null, salesArea.Id, rt.rtMap.get('Account').get('CampaignGroup'));
        
        Seller__c newSeller = TestData.returnSeller('TestSeller2', newUserSeller.Id, so.Id);
        insert newSeller;
        salesArea.SellerLkp__c = newSeller.Id;
        update salesArea;
        
        AccountAreaSales__c salesArea2 = TestData.createAccountAreaSales(acct.Id, null, oldSeller.Id); 
        cmpAcc.MainSalesAreaLkp__c = salesArea2.Id;
        update cmpAcc;
        salesArea2.AccountLkp__c = acct2.Id;
        update salesArea2;
    }
    
}