force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <description>[a03][Address__c] Endereço utilizado em contas.</description>
    <label>Endereço</label>
    <nameField>
        <label>Rua</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/CEPTxt__c.field-meta.xml
<CustomField>
    <fullName>CEPTxt__c</fullName>
    <label>CEP</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/LeadLkp__c.field-meta.xml
<CustomField>
    <fullName>LeadLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Novo Cliente</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Addresses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Address__c/fields/PartnerStateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>PartnerStateInscriptionTxt__c</fullName>
    <label>Inscrição Estadual Parceiro</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <inlineHelpText>Escreva apenas números sem separações entre eles. 
Exemplo: 66753556000167.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <inlineHelpText>*Campo obrigatório para aprovação.</inlineHelpText>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_LeadConversion.cls
@isTest
private class Test_LeadConversion {
    
    @isTest static void testConvertNewAccount(){
        Lead l = TestData.createLead('Nome de Teste', null);
        Address__c add = new Address__c (Name = 'Rua 1', 
                                         Leadlkp__c = l.Id, 
                                         CNPJTxt__c = l.CNPJTxt__c.substring(0,2) + l.CNPJTxt__c.substring(3,6) + l.CNPJTxt__c.substring(7,10) + l.CNPJTxt__c.substring(11,15) + l.CNPJTxt__c.substring(16,18), 
                                         CEPTxt__c = l.PostalCode,
                                         StateTxt__c = l.StateCode,
                                         PartnerStateInscriptionTxt__c = l.RG_StateInscriptionTxt__c,
                                         Phone__c = l.Phone
                                        );
        insert add;
        List<Account> accountList = new List<Account>();
        LeadStatus convertStatus = [SELECT Id, ApiName 
                                    FROM LeadStatus 
                                    WHERE IsConverted=true LIMIT 1];
        Database.LeadConvert lc = LeadConversion.convert(l,accountList,convertStatus);
        System.assertEquals(null, lc.getAccountId());
    }
    
    @isTest static void testConvertExistingAccount(){
        Lead l = TestData.createLead('Nome de Teste', null);
        Account acc = TestData.createAccount('Nome de Teste', null);
        acc.CNPJTxt__c = '44.149.954/0001-36';
        update acc;
        List<Account> accountList = new List<Account>();
        accountList.add(acc);
        LeadStatus convertStatus = [SELECT Id, ApiName 
                                    FROM LeadStatus 
                                    WHERE IsConverted=true LIMIT 1];
        Database.LeadConvert lc = LeadConversion.convert(l,accountList,convertStatus);
        System.assertEquals(acc.Id, lc.getAccountId());        
    }

}