force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/CreditLimit__c.field-meta.xml
<CustomField>
    <fullName>CreditLimit__c</fullName>
    <label>Limite de Crédito</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Account/fields/LeadSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>LeadSalesOrganizationTxt__c</fullName>
    <label>Organização de Vendas do Lead</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/LeadSellerLkp__c.field-meta.xml
<CustomField>
    <fullName>LeadSellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor do Lead</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas (Vendedor do Lead)</relationshipLabel>
    <relationshipName>ConvertedAccounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/RG_StateInscriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>RG_StateInscriptionTxt__c</fullName>
    <label>RG/Inscrição Estadual</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SuframaCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>SuframaCodeTxt__c</fullName>
    <label>Código da Suframa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/AccountPartner.recordType-meta.xml
<RecordType>
    <fullName>AccountPartner</fullName>
    <active>true</active>
    <description>Para cadastro de endereços de entrega e pagador</description>
    <label>Parceiros de conta</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_AccountIntegrationUtils.cls
@isTest
public class Test_AccountIntegrationUtils {

    @isTest static void testCreditLimit(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        acc.CodeCustomerTxt__c = '212396';
        update acc;
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_ZPH_CRED');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        CreditLimitIntegrationUtils.getCreditLimit(new List<Id>{acc.Id});
        Test.stopTest();
        acc = [SELECT CreditLimit__c FROM Account WHERE Id = :acc.Id];
        System.assertEquals(2000000, acc.CreditLimit__c);
        
    }
    
    @isTest static void testAccount(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        acc.CodeCustomerTxt__c = '';
        acc.SuframaCodeTxt__c = '10';
        acc.LeadSellerLkp__c = sel.Id;
        acc.LeadSalesOrganizationTxt__c = '0099';
        update acc;
        //Account partner = TestData.createAccount('TestPartner', null, null, rt.rtmap.get('Account').get('AccountPartner'));
        //partner.CodeCustomerTxt__c = '';
        //update partner;
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_Customer');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);
        
        Test.startTest();
        AccountIntegrationUtils.resendAccount(acc.Id);
        //AccountIntegrationUtils.createPartner(partner.Id, acc.Id);
        Test.stopTest();
        acc = AccountIntegrationUtils.getAccount(acc.Id);
    }
    
    @isTest static void testPartner(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAccount', null, null, rtSAPAcc);
        acc.LeadSellerLkp__c = sel.Id;
        update acc;
        Account partner = TestData.createAccount('TestPartner', null, null, rt.rtmap.get('Account').get('AccountPartner'));
       // partner.CNPJTxt__c = acc.CNPJTxt__c;
       // partner.BillingStateCode = acc.BillingStateCode;
       // partner.BillingState = acc.BillingState;
       // partner.RG_StateInscriptionTxt__c = acc.RG_StateInscriptionTxt__c;
        partner.Name = acc.Name;
        
        partner.CodeCustomerTxt__c = '';
        partner.ParentId = acc.Id;
                
        update partner;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());

        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_Customer_Partner');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('Customer', mock);
        
        /*mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_Customer_AssociatePartner');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('Customer', mock);*/
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        //AccountIntegrationUtils.resendAccount(acc.Id);
        AccountIntegrationUtils.createPartner(partner.Id, acc.Id);
        Test.stopTest();
    }
    
    @isTest static void associatePartner(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
		Account acc = TestData.createAccount('TestAcc', null, null, rtSAPAcc);
        acc.CodeCustomerTxt__c = acc.CodeCustomerTxt__c + 'Partner';
        
        acc.LeadSellerLkp__c = sel.Id;
        update acc;
        Account partner = TestData.createAccount('TestAcc', null, null, rt.rtmap.get('Account').get('AccountPartner'));
        partner.ParentId = acc.Id;
        update partner;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());

        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_Customer_AssociatePartner');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('Customer', mock);
        
        Test.setMock(HttpCalloutMock.class, mrm);
        
        Test.startTest();
        AccountIntegrationUtils.associatePartner(new List<Id>{partner.Id});
        Test.stopTest();
    }
   
}