force-app/main/default/objects/Account/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <label>Organização de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/CNPJTxt__c.field-meta.xml
<CustomField>
    <fullName>CNPJTxt__c</fullName>
    <inlineHelpText>Escreva apenas números sem separações entre eles. 
Exemplo: 66753556000167.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>CNPJ</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/SalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesOrganizationTxt__c</fullName>
    <inlineHelpText>Esse campo é preenchido automaticamente se o campo Vendedor for preenchido.
*Campo obrigatório para aprovação.</inlineHelpText>
    <label>Organização de Vendas</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SalesOrganization</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadConversion.cls
public class LeadConversion {
    
    public static Database.LeadConvert convert(Lead l, List<Account> accountList, LeadStatus converted){
        
        Database.LeadConvert lc = new database.LeadConvert();
        
        lc.setLeadId(l.Id);
        
        for(Account acct : accountList){
            if(l.CNPJTxt__c == acct.CNPJTxt__c && l.SalesOrganizationTxt__c == acct.SalesOrganizationTxt__c){
                lc.setAccountId(acct.Id);
            }
        }
        
        lc.setDoNotCreateOpportunity(True);
        
        lc.setConvertedStatus(converted.ApiName);
        
        return lc;

        
        
    }

}