force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>Notas_fiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderStatusTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderStatusTxt__c</fullName>
    <label>Status da ordem</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
            </value>
            <value>
                <fullName>InApproval</fullName>
                <label>Em Aprovação</label>
            </value>
            <value>
                <fullName>Approved</fullName>
                <label>Aprovado</label>
            </value>
            <value>
                <fullName>SentToSAP</fullName>
                <label>Enviado SAP</label>
            </value>
            <value>
                <fullName>Não processado</fullName>
            </value>
            <value>
                <fullName>Processado parcialmente</fullName>
            </value>
            <value>
                <fullName>Processado completamente</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order__c/fields/QuotationBln__c.field-meta.xml
<CustomField>
    <fullName>QuotationBln__c</fullName>
    <formula>TEXT(OrderStatusTxt__c) = &apos;Rascunho&apos; ||
TEXT(OrderStatusTxt__c) = &apos;InApproval&apos; ||
TEXT(OrderStatusTxt__c) = &apos;Approved&apos; ||
TEXT(OrderStatusTxt__c) = &apos;SentToSAP&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cotação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recebedor mercadoria</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OrderService.cls
global with sharing class OrderService extends integ_SyncIntegrationServiceAbstract  {
    
    global static OrderService instance;
    
    public OrderService(){
        
    }
    
    //************************************************************//
    
    @AuraEnabled
    public static Order__c getorder(Id orderId) {
        system.debug('orderId'+ orderId);      
        
        List<Order__c> order = [
            
            SELECT Id, Name, CustomIDTxt__c, QuotationBln__c, OrderStatusTxt__c 
            FROM Order__c 
            WHERE Id = :orderId
        ];
        system.debug('order'+ order);
        if(order.size()>0)
            return order[0];
        else
            return null;     
    }
    
    @AuraEnabled
    public static Remittance__c getorderRemittance(Id remittanceId) {
        system.debug('remittanceId'+ remittanceId);      
        
        List<Remittance__c> orderRemittance = [
            
            SELECT Id, Name, OrderLkp__r.CustomIDTxt__c 
            FROM Remittance__c 
            WHERE Id = :remittanceId
            LIMIT 1
        ];
        system.debug('orderRemittance'+ orderRemittance);
        if(orderRemittance.size()>0)
            return orderRemittance[0];
        else
            return null;     
    }
    
    @AuraEnabled
    public static Invoice__c getinvoice(Id invoiceId) {
        system.debug('invoiceId'+ invoiceId);      
        
        List<Invoice__c> invoice = [
            
            SELECT Id, Name, AccountLkp__r.CodeCustomerTxt__c 
            FROM Invoice__c 
            WHERE Id = :invoiceId
            LIMIT 1
        ];
        system.debug('invoice'+ invoice);
        if(invoice.size()>0)
            return invoice[0];
        else
            return null;     
    }
    //************************************************************//
    
    public static OrderService getInstance() {
        if (instance == null) {
            instance = new OrderService();
        }
        return instance;
    }
    
    /*
Executes SYNC_ORDER_OUTBOUND syncrony
*/
    @AuraEnabled
    webservice static List<Invoice__c> getInvoiceList(String invoiceNumber, String customerCode){
        return getInstance().retrieveInvoiceFromSAP(invoiceNumber, customerCode, null);
    }
    @AuraEnabled
    webservice static List<Invoice__c> getInvoiceListByOrderNumber(String orderNumber){
        System.debug('*** ' + orderNumber);
        return getInstance().retrieveInvoiceFromSAP(null, null, orderNumber);
    }
    @AuraEnabled
    webservice static List<Invoice__c> getInvoiceListLast30Days(String customerCode){
        return getInstance().retrieveInvoiceFromSAP(null, customerCode, null);
    }
    
    @future(callout=true)
    public static void getInvoiceListByOrderNumberFuture(String orderNum){
        getInvoiceListByOrderNumber(orderNum);
    }
    
    private List<Invoice__c> retrieveInvoiceFromSAP(String invoiceNumber, String customerCode, String orderNumber) {
        OrderRemoteCall remoteCall = new OrderRemoteCall(invoiceNumber, customerCode, orderNumber);
        return (List<Invoice__c>)super.execute(IntegrationIds.SYNC_ORDER_OUTBOUND.name(), remoteCall);
    }
    
}