force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/SAPBusinessAccount.recordType-meta.xml
<RecordType>
    <fullName>SAPBusinessAccount</fullName>
    <active>true</active>
    <description>Contas enviadas do cadastro do SAP. Alterações somente no SAP.</description>
    <label>Conta jurídica SAP</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Carrier__c/Carrier__c.object-meta.xml
<CustomObject>
    <description>[a04][Carrier__c] Companhias de transporte de produtos.</description>
    <label>Transportadora</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Transportadoras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case/recordTypes/AlteracaoPedido.recordType-meta.xml
<RecordType>
    <fullName>AlteracaoPedido</fullName>
    <active>true</active>
    <businessProcess>SAC Alteração de pedido</businessProcess>
    <description>Abertura de alteração de pedido</description>
    <label>Alteração de pedido</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <businessProcess>SAC Devolução</businessProcess>
    <description>Abertura de devolução de produto</description>
    <label>Devolução</label>
</RecordType>

force-app/main/default/objects/Case/recordTypes/IndicacaoVendedor.recordType-meta.xml
<RecordType>
    <fullName>IndicacaoVendedor</fullName>
    <active>true</active>
    <businessProcess>SAC Indicação de vendedor</businessProcess>
    <description>Abertura de caso solicitando indicação de vendedor</description>
    <label>Indicação de vendedor</label>
</RecordType>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ZTCreateNewCaseCtrl.cls
@istest
public class ZTCreateNewCaseCtrl {
 
    static testMethod void testcreatecase()
    {
        // Prepare test data
        RecordTypeMap rt = RecordTypeMap.getInstance();
        
        Seller__c seller = TestData.createSeller('TestSellerName');
        
        String rtSAPAcc = rt.rtmap.get('Account').get('SAPBusinessAccount');
        
        Account account = TestData.createAccount('TestNameAccount',null, null,rtSAPAcc);
        account.CodeCustomerTxt__c = '2345678';
        update account;
        
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(account.Id, null, seller.Id);
                
        Carrier__c carrier = TestData.createCarrier ('TestNameCarrier', 'carrier@email.com.br');
        
        Order__c order = TestData.createOrder(salesArea.Id, account.Id, null, null,  '135795', seller.Id);
        
        Remittance__c remittance = TestData.createRemittance('TestNameRemittance', order.Id, carrier.Id);
                
        Invoice__c invoice = TestData.createInvoice('TestNameInvoice', account.Id,remittance.Id);

        Invoice__c inv2 = CreateNewCaseCtrl.getinvoice(invoice.Id);
        
        Order__c order2 = CreateNewCaseCtrl.getorder(order.Id);
        
        String rtCase1 = rt.rtmap.get('Case').get('Devolucao');
        String rtCase2 = rt.rtmap.get('Case').get('AlteracaoPedido');
        String rtCase3 = rt.rtmap.get('Case').get('IndicacaoVendedor');
        
        List<RecordType> rt1 = CreateNewCaseCtrl.getcaserecordtype();
        List<RecordType> rt2 = CreateNewCaseCtrl.getcaserecordtypeO();
        List<RecordType> rt3 = CreateNewCaseCtrl.getcaserecordtypeA();
       
        order = [SELECT Name FROM Order__c WHERE id =: order.Id];
        
        // Verify data
       
        System.assert(rtCase1 != null);
        System.assert(rtCase2 != null);
        System.assert(rtCase3 != null);
        System.debug('invoice.Name :'+invoice.Name+'inv2.Name :'+inv2.Name);
        System.assert(invoice.Name == inv2.Name);
        System.debug('order.Name :'+order.Name +'>>'+'order2.Name :'+'>>'+order2.Name);
        System.assert(order.Name == order2.Name);
        
    }
}