force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CampaignGroup.recordType-meta.xml
<RecordType>
    <fullName>CampaignGroup</fullName>
    <active>true</active>
    <description>Agrupamento utilizado na Campanha de Trade Marketing</description>
    <label>Agrupamento de Campanha</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>[a0q][Campaign__c] Campanha de Trade Marketing</description>
    <label>Campanha</label>
    <nameField>
        <label>Nome da Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Specific</fullName>
                <label>Pontual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignAccount__c/CampaignAccount__c.object-meta.xml
<CustomObject>
    <description>[a0r][CampaignAccount__c] Guarda o relacionamento entre Contas e Campanhas de Trade</description>
    <label>Agrupamento da Campanha</label>
    <nameField>
        <displayFormat>CAC-{YYYY}{00000}</displayFormat>
        <label>Código de Agrupamento da Campanha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupamentos da Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <description>[###][CreditNote__c] Notas de crédito</description>
    <label>Nota de Crédito</label>
    <nameField>
        <displayFormat>NC-{000000000}</displayFormat>
        <label>Nome de Nota de Crédito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/fields/ErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageTxt__c</fullName>
    <label>Mensagem Erro</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/InstallmentNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>InstallmentNumberNmb__c</fullName>
    <label>Número de Parcelas</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditNoteType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/TypeTxt__c.field-meta.xml
<CustomField>
    <fullName>TypeTxt__c</fullName>
    <label>Tipo de Solicitação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditSolcitationType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CreditNoteIntegrationUtils.cls
@isTest
public class Test_CreditNoteIntegrationUtils {
    @isTest static void testCreateCreditNote(){
        TestData.createIntegrationData();
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        RecordTypeMap rtm = RecordTypeMap.getInstance();
 		String rtGroupAcc = rtm.rtmap.get('Account').get('CampaignGroup');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
        Account acct = TestData.createAccount('Test Account', null, null, rtSACAcc);
        acct.CodeCustomerTxt__c = '12312321';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, sel.Id);
		Account acc = TestData.createAccount('Test', null, salesArea.Id, rtGroupAcc);
        Campaign__c campaing = TestData.createCampaign(Date.newInstance(2018, 01, 01), Date.newInstance(2018, 12, 31));
        CampaignAccount__c campaingAccount = TestData.createCampaignAccount(campaing, acc);
        CreditNote__c cn1 = TestData.createCreditNote(acc.Id, null, campaing.id);
        cn1.Type__c = 'Crédito Campanha';
        cn1.Value__c = 3000;
        update cn1;
        CreditNote__c cn2 = TestData.createCreditNote(acc.Id, null, campaing.id);
        //cn.TypeTxt__c = 'Valor solicitado';
        cn2.Value__c = 2000;
        cn2.InstallmentNumberNmb__c = 1;
        update cn2;
        
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_CreateNc');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('CreateNc', mock);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mrm);
        CreditNoteIntegrationUtils.createCreditNote(cn2.Id);
        Test.stopTest();
//        system.assertEquals('teste', cn2.ErrorMessageTxt__c);
    }
}