force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/BusinessAccountSAC.recordType-meta.xml
<RecordType>
    <fullName>BusinessAccountSAC</fullName>
    <active>true</active>
    <description>Contas cadastradas pelo SAC no atendimento dos casos.</description>
    <label>Conta jurídica SAC</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/CampaignGroup.recordType-meta.xml
<RecordType>
    <fullName>CampaignGroup</fullName>
    <active>true</active>
    <description>Agrupamento utilizado na Campanha de Trade Marketing</description>
    <label>Agrupamento de Campanha</label>
</RecordType>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/OwnersManagerFml__c.field-meta.xml
<CustomField>
    <fullName>OwnersManagerFml__c</fullName>
    <formula>SellerLkp__r.SalesOfficeLkp__r.ManagerLkp__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Gerente do escritório de vendas</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>[a0q][Campaign__c] Campanha de Trade Marketing</description>
    <label>Campanha</label>
    <nameField>
        <label>Nome da Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Campaign__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Fixa</fullName>
            </value>
            <value>
                <fullName>Specific</fullName>
                <label>Pontual</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignAccount__c/CampaignAccount__c.object-meta.xml
<CustomObject>
    <description>[a0r][CampaignAccount__c] Guarda o relacionamento entre Contas e Campanhas de Trade</description>
    <label>Agrupamento da Campanha</label>
    <nameField>
        <displayFormat>CAC-{YYYY}{00000}</displayFormat>
        <label>Código de Agrupamento da Campanha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agrupamentos da Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <description>[###][CreditNote__c] Notas de crédito</description>
    <label>Nota de Crédito</label>
    <nameField>
        <displayFormat>NC-{000000000}</displayFormat>
        <label>Nome de Nota de Crédito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/fields/ManagersManagerLkp__c.field-meta.xml
<CustomField>
    <fullName>ManagersManagerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente do gerente</label>
    <referenceTo>User</referenceTo>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditNoteStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditNoteType</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SalesOffice__c/SalesOffice__c.object-meta.xml
<CustomObject>
    <description>[###][SalesOffice__c]</description>
    <label>Escritório de Vendas</label>
    <nameField>
        <label>Nome de Escritório de Vendas</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Escritórios de Vendas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_CreditNoteTriggerHandler.cls
@isTest
private class Test_CreditNoteTriggerHandler {

    @isTest static void testCreditNote(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        RecordTypeMap rtm = RecordTypeMap.getInstance();
 		String rtGroupAcc = rtm.rtmap.get('Account').get('CampaignGroup');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
        Account acct = TestData.createAccount('Test Account', null, null, rtSACAcc);
        acct.CodeCustomerTxt__c = '12312321';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, sel.Id);
		Account acc = TestData.createAccount('Test', null, salesArea.Id, rtGroupAcc);
        Campaign__c campaing = TestData.createCampaign(Date.newInstance(2018, 01, 01), Date.newInstance(2018, 12, 31));
        CampaignAccount__c campaingAccount = TestData.createCampaignAccount(campaing, acc);
        CreditNote__c cn = TestData.createCreditNote(acc.Id, null, campaing.id);

        System.assertEquals(salesArea.OwnersManagerFml__c, cn.ManagersManagerLkp__c);
    }
    
    @isTest static void testCreditNoteFile(){
        RecordTypeMap rt = RecordTypeMap.getInstance();
 		String rtSACAcc = rt.rtmap.get('Account').get('BusinessAccountSAC');
        RecordTypeMap rtm = RecordTypeMap.getInstance();
 		String rtGroupAcc = rtm.rtmap.get('Account').get('CampaignGroup');
        Profile prof = [SELECT Id 
                        FROM Profile 
                        WHERE Name = 'Gerente de Vendas'];
        User salesOfficeManager = TestData.createUser('TestManager', null, null, prof.Id, 'testUser321@test.com');
        SalesOffice__c so = TestData.createSalesOffice('TestSalesOffice', salesOfficeManager.Id);
        Seller__c sel = TestData.createSeller('TestSeller', salesOfficeManager.Id, so.Id);
        Account acct = TestData.createAccount('Test Account', null, null, rtSACAcc);
        acct.CodeCustomerTxt__c = '12312321';
        update acct;
        AccountAreaSales__c salesArea = TestData.createAccountAreaSales(acct.Id, null, sel.Id);
        Account acc = TestData.createAccount('Test', null, salesArea.Id, rtGroupAcc);
        Campaign__c campaing = TestData.createCampaign(Date.newInstance(2018, 01, 01), Date.newInstance(2018, 12, 31));
        CampaignAccount__c campaingAccount = TestData.createCampaignAccount(campaing, acc);
        CreditNote__c cn = TestData.createCreditNote(acc.Id, null, campaing.id);
        ContentVersion cv = TestData.createContentVersion('Header_Picture1', '/Header_Picture1.jpg');
       
        ContentVersion cv2 = [SELECT Id, Title, ContentDocumentId 
                              FROM ContentVersion 
                              WHERE Id = :cv.Id LIMIT 1];
        
        ContentDocumentLink cdl = TestData.createContentDocumentLink(cv2.ContentDocumentId, cn.Id);
        cn.Type__c = 'Solicitação';
        update cn;
        cn.Status__c = 'Solicitado';
        update cn;
        System.assertEquals('Solicitado', cn.Status__c);
    }

}