force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SkipValidations__c/SkipValidations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Skip Validations</label>
</CustomObject>

force-app/main/default/objects/SkipValidations__c/fields/Skip__c.field-meta.xml
<CustomField>
    <fullName>Skip__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/integ_CustomOperationAccount.cls
public with sharing class integ_CustomOperationAccount implements integ_IIntegrationOperation {
	public Object execute(List<SObject> recordList) {
		System.debug('*** integ_CustomOperationAccount::execute() ' + recordList);
		List<Account> accountList = new List<Account>();
		accountList.addAll((List<Account>)recordList);
        
        SkipValidations__c skipVal = SkipValidations__c.getOrgDefaults();
        skipVal.Skip__c = true;

        update skipVal;
        
		upsert accountList CodeCustomerTxt__c;
        
        skipVal.Skip__c = false;
        update skipVal;
        
		return accountList;
	}
}