force-app/main/default/objects/Account/fields/CodeCustomerTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeCustomerTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do cliente</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLabelTxt__c.field-meta.xml
<CustomField>
    <fullName>AccountLabelTxt__c</fullName>
    <label>Label da conta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/InactiveBln__c.field-meta.xml
<CustomField>
    <fullName>InactiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Inativo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/InactiveAccounts__c/InactiveAccounts__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Código da Conta Mexichem Inativos</description>
    <label>Conta Mexichem Inativos</label>
</CustomObject>

force-app/main/default/objects/InactiveAccounts__c/fields/InactiveAccountsCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>InactiveAccountsCodeTxt__c</fullName>
    <defaultValue>&apos;9999999999&apos;</defaultValue>
    <label>Código Mexichem Inativos</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AccountAreaSalesTriggerHandler.cls
public class AccountAreaSalesTriggerHandler {
    public static void doBeforeInsert(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        List<String> listCodes = new List<String>();
        for(AccountAreaSales__c av : records){
            if(av.InactiveBln__c){
                listCodes.add(av.CustomIdTxt__c.substring(0,6));
            }
        }
        if(listCodes.size() > 0){
            Map<string, Account> mapAccounts = new Map<string, Account>();
            InactiveAccounts__c inAcc = InactiveAccounts__c.getInstance();                        
            Account inactiveAcc = [SELECT Id, CodeCustomerTxt__c, Name FROM Account WHERE CodeCustomerTxt__c =: inAcc.InactiveAccountsCodeTxt__c];
            
            for(Account acc : [SELECT Id, CodeCustomerTxt__c FROM Account WHERE CodeCustomerTxt__c IN :listCodes]){
                mapAccounts.put(acc.CodeCustomerTxt__c, acc);
            }
            
            for(AccountAreaSales__c av : records){
                if(av.InactiveBln__c)
                    av.AccountLkp__c = inactiveAcc.Id;
                else{
                    if(mapAccounts.containsKey(av.CustomIdTxt__c.substring(0,6))){
                        av.AccountLkp__c = mapAccounts.get(av.CustomIdTxt__c.substring(0,6)).Id;
                    }
                }
            }
        }
        
        /*Map<Id, Id> idSellerByAv = new Map<Id, Id>();
        Map<Id, Id> idUserBySeller = new Map<Id, Id>();
        for(AccountAreaSales__c av : records){
            idSellerByAv.put(av.Id, av.SellerLkp__c);
        }
        for(Seller__c s : [SELECT ID, UserLkp__c FROM Seller__c WHERE ID IN: idSellerByAv.values() AND UserLkp__c != null]){
            idUserBySeller.put(s.Id, s.UserLkp__c);
        }
        for(AccountAreaSales__c av : records){
            if(idSellerByAv.containsKey(av.Id)){
                if(idUserBySeller.containsKey(idSellerByAv.get(av.Id))){
                    av.OwnerId = idUserBySeller.get(idSellerByAv.get(av.Id)); 
                }
            }
        }*/
        
        List<ID> accIdList = new List<ID>();
        List<Account> listAcc = new List<Account>(); 
        Map<Id, AccountAreaSales__c> accByAv = new Map<Id, AccountAreaSales__c>();
        for(AccountAreaSales__c av : records){
            if(av.AccountLkp__c != null){
            	accByAv.put(av.AccountLkp__c, av); 
                accIdList.add(av.AccountLkp__c);
            }
        }
        if(!accIdList.isEmpty()){
            listAcc = [Select Id, Name
                       From Account
                       Where Id IN : accIdList];
            for(Account acc : listAcc){
                if(acc.Name != null){
                    accByAv.get(acc.Id).AccountLabelTxt__c = acc.Name;
                }
            }
        }
    }
    public static void doBeforeUpdate(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        List<String> listCodes = new List<String>();
        for(AccountAreaSales__c av : records){
            if(av.InactiveBln__c != oldRecords.get(av.Id).InactiveBln__c){
                listCodes.add(av.CustomIdTxt__c.substring(0,6));
            }
        }
        if(listCodes.size() > 0){
            Map<string, Account> mapAccounts = new Map<string, Account>();
            InactiveAccounts__c inAcc = InactiveAccounts__c.getInstance();                        
            Account inactiveAcc = [SELECT Id, CodeCustomerTxt__c, Name FROM Account WHERE CodeCustomerTxt__c =: inAcc.InactiveAccountsCodeTxt__c];
            
            for(Account acc : [SELECT Id, CodeCustomerTxt__c FROM Account WHERE CodeCustomerTxt__c IN :listCodes]){
                mapAccounts.put(acc.CodeCustomerTxt__c, acc);
            }
            
            for(AccountAreaSales__c av : records){
                if(av.InactiveBln__c)
                    av.AccountLkp__c = inactiveAcc.Id;
                    else{
                        if(mapAccounts.containsKey(av.CustomIdTxt__c.substring(0,6))){
                            av.AccountLkp__c = mapAccounts.get(av.CustomIdTxt__c.substring(0,6)).Id;
                        }
                    }
            }		
        }
        /*Map<Id, Id> idSellerByAv = new Map<Id, Id>();
        Map<Id, Id> idUserBySeller = new Map<Id, Id>();
        for(AccountAreaSales__c av : records){
            //if(av.SellerLkp__c != oldRecords.get(av.Id).SellerLkp__c)
            	idSellerByAv.put(av.Id, av.SellerLkp__c);
        }
        for(Seller__c s : [SELECT ID, UserLkp__c FROM Seller__c WHERE ID IN: idSellerByAv.values() AND UserLkp__c != null]){
            idUserBySeller.put(s.Id, s.UserLkp__c);
        }
        for(AccountAreaSales__c av : records){
            if(idSellerByAv.containsKey(av.Id)){
                if(idUserBySeller.containsKey(idSellerByAv.get(av.Id))){
                    av.OwnerId = idUserBySeller.get(idSellerByAv.get(av.Id));
                }
            }
        }*/
    }
    public static void doBeforeDelete(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        
    }
    public static void doAfterInsert(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        AccountSharingUtil.processSalesAreaInsert(records, oldRecords);
        
    }
    public static void doAfterUpdate(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        AccountSharingUtil.processSalesAreaUpdate(records, oldRecords);
        
        List<AccountAreaSales__c> listAreas = new List<AccountAreaSales__c>();
        Map<Id, AccountAreaSales__c> mapOldAreaS = new Map<Id, AccountAreaSales__c>();
        
        for(AccountAreaSales__c av : records){
            if(av.AccountLkp__c != oldRecords.get(av.Id).AccountLkp__c){
                listAreas.add(av);
                mapOldAreas.put(av.Id, oldRecords.get(av.Id));
            }
        }
        if(listAreas.size() > 0){
            AccountSharingUtil.processSalesAreaChangeAccount(listAreas, mapOldAreas);
        }        

    }
    public static void doAfterDelete(List<AccountAreaSales__c> records, Map<Id, AccountAreaSales__c> oldRecords){
        AccountSharingUtil.processSalesAreaDelete(records, oldRecords);
        
    }
    
    public static void removeAreaSales(AccountAreaSales__c av){
        
        InactiveAccounts__c inAcc = InactiveAccounts__c.getInstance();                  
        
        av.AccountLkp__r = new Account(CodeCustomerTxt__c = inAcc.InactiveAccountsCodeTxt__c);                                               
        
    }
    
    public static void reAddSalesArea(AccountAreaSales__c av){
                       
        string accCode = av.CustomIdTxt__c.substring(0,6);
        
        av.AccountLkp__r = new Account(CodeCustomerTxt__c = accCode);                                            
        
    }
}