force-app/main/default/objects/Account/fields/CPFTxt__c.field-meta.xml
<CustomField>
    <fullName>CPFTxt__c</fullName>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Organização de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0143</fullName>
            </value>
            <value>
                <fullName>AM01</fullName>
            </value>
            <value>
                <fullName>0099</fullName>
            </value>
            <value>
                <fullName>0141</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opty_Sales_Area__c.field-meta.xml
<CustomField>
    <fullName>Opty_Sales_Area__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <filterItems>
            <field>AccountAreaSales__c.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>Cliente Concorrência</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Oportunidades</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SellerCPFTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerCPFTxt__c</fullName>
    <label>CPF do Vendedor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <label>Código do Vendedor</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Código organização de vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerCPFTxt__c.field-meta.xml
<CustomField>
    <fullName>SellerCPFTxt__c</fullName>
    <label>CPF do Vendedor</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Responsável Vendas</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <label>Código do Vendedor</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seller__c/fields/SellerNumberNmb__c.field-meta.xml
<CustomField>
    <fullName>SellerNumberNmb__c</fullName>
    <externalId>true</externalId>
    <label>Código do vendedor</label>
    <length>8</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Seller__c/fields/UserLkp__c.field-meta.xml
<CustomField>
    <fullName>UserLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Sellers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OpportunityTriggerHandler.cls
public with sharing class OpportunityTriggerHandler extends fflib_SObjectDomain implements ITestAble {
    
    public OpportunityTriggerHandler(List<Order__c> sObjectList){
        super((List<SObject>)sObjectList);
    }
    
    public override void onBeforeInsert(){
        this.setSalesAreaOrAccount((List<Opportunity>) records);
    }
    
    
    public class Constructor implements fflib_SObjectDomain.IConstructable {
        public fflib_SObjectDomain construct(List<SObject> sObjectList) {
            return new OpportunityTriggerHandler(sObjectList);
        }
    }
    
    public static Opportunity getSampleObject() {
        return new Opportunity();
    }
    
    private void setSalesAreaOrAccount(List<Opportunity> records){
        List<Id> listIds = new List<Id>();
        List<Id> listAccIds = new List<Id>();
        List<Id> listAvIds = new List<Id>();
        Map<Id, List<AccountAreaSales__c>> mapSalesAreaByAccount = new Map<Id, List<AccountAreaSales__c>>();
        for(Opportunity o : records){
            if(o.Account == null || o.Opty_Sales_Area__c == null){
                listIds.add(o.Id);
                if(o.AccountId != null) listAccIds.add(o.AccountId);
                if(o.Opty_Sales_Area__c != null) listAvIds.add(o.Opty_Sales_Area__c);
            }
        }
        if(listIds.size() > 0){
            Map<Id, AccountAreaSales__c> mapAv = new Map<Id, AccountAreaSales__c>([
                SELECT Id, 
                AccountLkp__c, 
                CodeSalesOrganizationTxt__c, 
                SellerLkp__c, 
                SellerLkp__r.UserLkp__c,
                SellerLkp__r.SellerNumberNmb__c,
                SellerLkp__r.UserLkp__r.CPFTxt__c
                //OwnerId 
                FROM AccountAreaSales__c 
                WHERE AccountLkp__c IN :listAccIds 
                OR Id IN :listAvIds
            ]);
            for(AccountAreaSales__c av : mapAv.values()){
                List<AccountAreaSales__c> listAux = new List<AccountAreaSales__c>();
                if(mapSalesAreaByAccount.containsKey(av.AccountLkp__c)){
                    listAux = mapSalesAreaByAccount.get(av.AccountLkp__c);
                }
                listAux.add(av);
                mapSalesAreaByAccount.put(av.AccountLkp__c, listAux);
            }
            for(Opportunity o : records){
                if(o.AccountId == null && o.Opty_Sales_Area__c == null){
                    o.addError('A conta ou área de vendas devem estar selecionadas');
                }
                else if(o.AccountId == null){
                    o.AccountId = mapAv.get(o.Opty_Sales_Area__c).AccountLkp__c;
                    if(o.Opty_Sales_Area__r.SellerLkp__r.UserLkp__r.CPFTxt__c != null){
                    	o.SellerCPFTxt__c = mapAv.get(o.Opty_Sales_Area__c).SellerLkp__r.UserLkp__r.CPFTxt__c;
                    }
                }
                else if(o.Opty_Sales_Area__c == null){
                    if(mapSalesAreaByAccount.containsKey(o.AccountId)){
                        List<AccountAreaSales__c> listAux = mapSalesAreaByAccount.get(o.AccountId);
                        if(listAux.size() == 1){
                            o.Opty_Sales_Area__c = listAux[0].Id;
                            if(listAux[0].SellerLkp__r.UserLkp__r.CPFTxt__c != null){
                            	o.SellerCPFTxt__c = listAux[0].SellerLkp__r.UserLkp__r.CPFTxt__c;
                            }  
                        }
                        else{
                            o.addError('Existe mais de uma Área de Vendas possível para esse cliente, favor selecionar');
                        }
                    }	
                }
                
            }
        }
    }
}