force-app/main/default/objects/ExpurgoNotaFiscal__c/ExpurgoNotaFiscal__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Dias para deletar registros de nota fiscal.</description>
    <label>Expurgo Nota Fiscal</label>
</CustomObject>

force-app/main/default/objects/ExpurgoNotaFiscal__c/fields/Dias_para_expurgo__c.field-meta.xml
<CustomField>
    <fullName>Dias_para_expurgo__c</fullName>
    <label>Dias para expurgo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Schedule_CleanInvoice.cls
@isTest
private class Test_Schedule_CleanInvoice {
    
    @isTest static void schedule(){
        ExpurgoNotaFiscal__c numDias = TestData.createExpurgoNotaFiscal('DaysToPurgeInvoice', 730);
        Datetime purgeDate = Date.today().addDays(-Integer.valueOf(numDias.Dias_para_expurgo__c+1));
        Invoice__c nota = TestData.createInvoice('Nome de Teste');
        Test.setCreatedDate(nota.Id, purgeDate);
        nota = [Select Id, CreatedDate From Invoice__c Where Id =: nota.Id];
        Test.startTest();
        Schedule_CleanInvoice sci = new Schedule_CleanInvoice();
        Datetime dt = Datetime.now().addMinutes(1);
        String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
        System.schedule('TestCleanInvoice', CRON_EXP, sci);
        Test.stopTest();

    }

}