force-app/main/default/objects/ExpurgoNotaFiscal__c/ExpurgoNotaFiscal__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Dias para deletar registros de nota fiscal.</description>
    <label>Expurgo Nota Fiscal</label>
</CustomObject>

force-app/main/default/objects/ExpurgoNotaFiscal__c/fields/Dias_para_expurgo__c.field-meta.xml
<CustomField>
    <fullName>Dias_para_expurgo__c</fullName>
    <label>Dias para expurgo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <description>[a0B][Invoice__c] Notas fiscais do sistema.</description>
    <label>Nota fiscal</label>
    <nameField>
        <label>Nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_CleanInvoice.cls
global class Batch_CleanInvoice implements Database.Batchable<sObject>{
    ExpurgoNotaFiscal__c numDias = ExpurgoNotaFiscal__c.getInstance('DaysToPurgeInvoice');
	global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
        	'SELECT ID FROM Invoice__c WHERE isDeleted = false AND CreatedDate <= LAST_N_DAYS:' + Integer.valueOf(numDias.Dias_para_expurgo__c)
        ); 
    }
    global void execute(Database.BatchableContext bc, List<Invoice__c> scope){
        delete scope;
    }
    global void finish(Database.BatchableContext bc){

    }

}