force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <description>[a0G][Queue__c] Responsável por prover garantia de entrega para camada de integração</description>
    <label>Item da fila de integração</label>
    <nameField>
        <displayFormat>QIT-{0000000000}</displayFormat>
        <label>Item da fila de integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da fila de integração</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>Event Name or Transaction Name</description>
    <label>Event Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <description>Used only for error messages, fill this field using getStackTraceString() method</description>
    <label>Exception Stack Trace</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <description>External last modified date based on iDoc date (using the external system date/timezone) to ensure the integration between systems will keep the transactions sequence as they were triggered by the original System</description>
    <label>External Creation Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/InternalId__c.field-meta.xml
<CustomField>
    <fullName>InternalId__c</fullName>
    <description>Internal ID from External system related to this event (used to identify original transaction from external system)</description>
    <label>Internal ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>Is Retry Disable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/NotificationReceivers__c.field-meta.xml
<CustomField>
    <fullName>NotificationReceivers__c</fullName>
    <label>NotificationReceivers</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <description>Object ID (internal Sales Force Id) related to this event (used to retrieve information to create the transaction to the receiver Account)</description>
    <label>ObjectId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload
(Valor do Objeto Corrente, para atribuir esta informação concatene o objeto a uma string e atribua este valor concatenado ao payload. Este Atributo podera ser utilizado no futuro para Determinar o estado do Evento Corrente dispensando o uso do RecordType QUEUED nos Objetos que necessitam gerenciamento de estado)</description>
    <label>Payload</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ReceiverAccount__c.field-meta.xml
<CustomField>
    <fullName>ReceiverAccount__c</fullName>
    <label>ReceiverAccount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/RetryCount__c.field-meta.xml
<CustomField>
    <fullName>RetryCount__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Identify the number of retries for this event</description>
    <label>Retry Count</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/SenderAccount__c.field-meta.xml
<CustomField>
    <fullName>SenderAccount__c</fullName>
    <label>SenderAccount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEQUEUED</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>WORKFLOW</fullName>
            </value>
            <value>
                <fullName>LOADING_DATA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Queue__c/fields/StatusMessage__c.field-meta.xml
<CustomField>
    <fullName>StatusMessage__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>Status Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventQueueActiveRecord.cls
public abstract with sharing class EventQueueActiveRecord {
	
	public void updateAll ( List<Queue__c> events ) {
		update events;
	}

	public Queue__c save (Queue__c event) {
		upsert event;
		return event;
	}
	
	public Queue__c save (Queue__c event, List<Attachment> attachList) {
		upsert event;
		storePayloads(event, attachList);
		return event;
	}

	public List<Queue__c> findAllQueuedEvents (Set<String> keys) {
		return [Select q.Status__c, 
					q.StatusMessage__c, 
					q.SenderAccount__c, 
					q.RetryCount__c, 
					q.ReceiverAccount__c, 
					q.Payload__c, 
					q.OwnerId, 
					q.ObjectId__c, 
					q.NotificationReceivers__c, 
					q.Name, 
					q.IsRetryDisabled__c, 
					q.InternalId__c, 
					q.Id, 
					q.ExternalCreationDate__c, 
					q.ExceptionStackTrace__c, 
					q.EventName__c, 
					(SELECT Id FROM Attachments LIMIT 1)
					From Queue__c q where q.id in :keys ] ; 
	}

	public List<Queue__c> findAllWithErrors () {
		return [

				Select q.Status__c, 
					q.StatusMessage__c, 
					q.SenderAccount__c, 
					q.RetryCount__c, 
					q.ReceiverAccount__c, 
					q.Payload__c, 
					q.OwnerId, 
					q.ObjectId__c, 
					q.NotificationReceivers__c, 
					q.Name, 
					q.IsRetryDisabled__c, 
					q.InternalId__c, 
					q.Id, 
					q.ExternalCreationDate__c, 
					q.ExceptionStackTrace__c, 
					q.EventName__c
					FROM Queue__c q 
					WHERE Status__c = 'ERROR'
					LIMIT 50000
				] ; 
	}

	public Queue__c findOne (String id) {
		List<Queue__c> queues = findAllQueuedEvents ( new Set<String> {id});
		return (!queues.isEmpty()) ? queues.get(0) : null ; 
	}
	
	public void storePayloads (Queue__c queue, List<Attachment> payloads) {
		if (payloads.size() == 0) return; 
		for (Attachment attach : payloads) {
			if (attach.ParentId == null) {
				attach.ParentId = queue.id;
			}
		}
		upsert payloads;  
	}
	
	public void storePayloads (List<Attachment> payloads) {
		if (payloads.size() == 0) return; 
		upsert payloads;  
	}

}