force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <description>[a0G][Queue__c] Responsável por prover garantia de entrega para camada de integração</description>
    <label>Item da fila de integração</label>
    <nameField>
        <displayFormat>QIT-{0000000000}</displayFormat>
        <label>Item da fila de integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da fila de integração</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <description>Event Name or Transaction Name</description>
    <label>Event Name</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ExceptionStackTrace__c.field-meta.xml
<CustomField>
    <fullName>ExceptionStackTrace__c</fullName>
    <description>Used only for error messages, fill this field using getStackTraceString() method</description>
    <label>Exception Stack Trace</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/InternalId__c.field-meta.xml
<CustomField>
    <fullName>InternalId__c</fullName>
    <description>Internal ID from External system related to this event (used to identify original transaction from external system)</description>
    <label>Internal ID</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/IsRetryDisabled__c.field-meta.xml
<CustomField>
    <fullName>IsRetryDisabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Identify if the retries should be executed for this event. If equal TRUE disable retries even if retry count is bigger than zero (can be used for errors as errors does not require retries)</description>
    <label>Is Retry Disable?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/IsSync__c.field-meta.xml
<CustomField>
    <fullName>IsSync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>É síncrona</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ObjectId__c.field-meta.xml
<CustomField>
    <fullName>ObjectId__c</fullName>
    <description>Object ID (internal Sales Force Id) related to this event (used to retrieve information to create the transaction to the receiver Account)</description>
    <label>ObjectId</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <description>Payload
(Valor do Objeto Corrente, para atribuir esta informação concatene o objeto a uma string e atribua este valor concatenado ao payload. Este Atributo podera ser utilizado no futuro para Determinar o estado do Evento Corrente dispensando o uso do RecordType QUEUED nos Objetos que necessitam gerenciamento de estado)</description>
    <label>Payload</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/ReceiverAccount__c.field-meta.xml
<CustomField>
    <fullName>ReceiverAccount__c</fullName>
    <label>ReceiverAccount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/SenderAccount__c.field-meta.xml
<CustomField>
    <fullName>SenderAccount__c</fullName>
    <label>SenderAccount</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DEQUEUED</fullName>
            </value>
            <value>
                <fullName>DELIVERED</fullName>
            </value>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>QUEUED</fullName>
            </value>
            <value>
                <fullName>SUCCESS</fullName>
            </value>
            <value>
                <fullName>INVALID</fullName>
            </value>
            <value>
                <fullName>DONE</fullName>
            </value>
            <value>
                <fullName>WORKFLOW</fullName>
            </value>
            <value>
                <fullName>LOADING_DATA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Queue__c/fields/StatusMessage__c.field-meta.xml
<CustomField>
    <fullName>StatusMessage__c</fullName>
    <description>Error Message from internal or external System</description>
    <label>Status Message</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/EventBuilder.cls
public with sharing class EventBuilder {
	
	private Queue__c event; 
		
    public EventBuilder createEventBaseOn(Queue__c event, String eventName ) {   
    	this.event = event;      
        this.event.eventName__c = eventName;
        this.event.status__c = EventQueueStatusType.LOADING_DATA.name();
        return this; 
    }	
		
    public EventBuilder createEventFor(String eventName) {
        event = new Queue__c();
        return createEventBaseOn (event,eventName); 
    }
	
	public EventBuilder createOutboundEventFor(String eventName) { 
		return createEventFor(eventName); 
	}

	
	public EventBuilder forEvent(String eventName) {
		event.eventName__c = eventName;
		return this;
	} 
	
	
	public EventBuilder forObjectId (String id) {
		event.ObjectId__c = id;
		return this; 		
	}	

	public EventBuilder usingRetryStrategy () {
		event.IsRetryDisabled__c = false;
		return this; 		
	}	

	public EventBuilder disablingRetryStrategy () {
		event.IsRetryDisabled__c = true;
		return this; 		
	}	

	public EventBuilder withSender (String sender) {
		event.senderAccount__c = sender;
		return this; 		
	}
	
	public EventBuilder withReceiver (String receiver) {
		event.receiverAccount__c = receiver;
		return this; 		
	}
	
	//deprecated
	public EventBuilder withPayload (String payload) {
		event.payload__c = payload;
		return this; 		
	}	
	
	public EventBuilder withInternalID (String internalId) {
		event.internalId__c  = internalId;
		return this; 		
	}

	public EventBuilder withStatus (String status) {
		event.Status__c  = status;
		return this; 		
	}

	public EventBuilder withException (Exception ex) {
		event.ExceptionStackTrace__c  = ex.getStackTraceString();
		event.StatusMessage__c = ex.getMessage();
		return this; 		
	}

	public EventBuilder isSync () {
		event.IsSync__c  = true;
		return this; 		
	}

	public Queue__c build() {
		return event;
	}
	

}