force-app/main/default/objects/CaseItem__c/CaseItem__c.object-meta.xml
<CustomObject>
    <description>[a01][CaseItem__c] Itens relacionados ao caso.</description>
    <label>Item do caso</label>
    <nameField>
        <label>Número Item do caso</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens do caso</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CaseItem__c/fields/CaseMdt__c.field-meta.xml
<CustomField>
    <fullName>CaseMdt__c</fullName>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/CommentsTxt__c.field-meta.xml
<CustomField>
    <fullName>CommentsTxt__c</fullName>
    <label>Observação</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/FailureTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>FailureTypeTxt__c</fullName>
    <label>Tipo de avaria</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Extravio de produto</fullName>
            </value>
            <value>
                <fullName>Produto faltante</fullName>
            </value>
            <value>
                <fullName>Negociação comercial</fullName>
            </value>
            <value>
                <fullName>Extravio de volume</fullName>
            </value>
            <value>
                <fullName>Código de barras divergente</fullName>
            </value>
            <value>
                <fullName>Danificado dentro embalagem</fullName>
            </value>
            <value>
                <fullName>Deformação</fullName>
            </value>
            <value>
                <fullName>Desbitolamento</fullName>
            </value>
            <value>
                <fullName>Embalagem com produto trocado</fullName>
            </value>
            <value>
                <fullName>Embalagem danificada</fullName>
            </value>
            <value>
                <fullName>Embalagem errada</fullName>
            </value>
            <value>
                <fullName>Liga e não puxa agua</fullName>
            </value>
            <value>
                <fullName>Produto com problema fabricação</fullName>
            </value>
            <value>
                <fullName>Produto Danificado Expedição</fullName>
            </value>
            <value>
                <fullName>Produto danificado transporte</fullName>
            </value>
            <value>
                <fullName>Produto danificado cliente</fullName>
            </value>
            <value>
                <fullName>Produto amassado</fullName>
            </value>
            <value>
                <fullName>Produto com Vazamento</fullName>
            </value>
            <value>
                <fullName>Produto com Bolha</fullName>
            </value>
            <value>
                <fullName>Produto danificado</fullName>
            </value>
            <value>
                <fullName>Produto evaporou</fullName>
            </value>
            <value>
                <fullName>Produto furado</fullName>
            </value>
            <value>
                <fullName>Produto não aquece</fullName>
            </value>
            <value>
                <fullName>Produto não liga</fullName>
            </value>
            <value>
                <fullName>Produto quebrado</fullName>
            </value>
            <value>
                <fullName>Produto queimado</fullName>
            </value>
            <value>
                <fullName>Produto trincado</fullName>
            </value>
            <value>
                <fullName>Super Aquecimento</fullName>
            </value>
            <value>
                <fullName>Tubo sem marcação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ManufacturingCenterTxt__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingCenterTxt__c</fullName>
    <label>Centro de fabricação</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0100-Fábrica de Sumaré</fullName>
            </value>
            <value>
                <fullName>0600-Fábrica de Joinville - Floresta</fullName>
            </value>
            <value>
                <fullName>0700-Fábrica de Joinville - Glória</fullName>
            </value>
            <value>
                <fullName>0870-Fábrica de Anápolis</fullName>
            </value>
            <value>
                <fullName>0900-Fábrica de Suape</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductActivitySectorTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductActivitySectorTxt__c</fullName>
    <label>Setor atividade produto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01-Família produtos 01</fullName>
            </value>
            <value>
                <fullName>46-Setor Comum</fullName>
            </value>
            <value>
                <fullName>54-Serviços</fullName>
            </value>
            <value>
                <fullName>B1-Broker</fullName>
            </value>
            <value>
                <fullName>CO-Composto</fullName>
            </value>
            <value>
                <fullName>CR-Construção</fullName>
            </value>
            <value>
                <fullName>EB-Embalagem</fullName>
            </value>
            <value>
                <fullName>GE-Geomecânico</fullName>
            </value>
            <value>
                <fullName>IA-Industria</fullName>
            </value>
            <value>
                <fullName>ID-Item Descontinuado</fullName>
            </value>
            <value>
                <fullName>IE-Infra-Estrutura</fullName>
            </value>
            <value>
                <fullName>IN-Industrial</fullName>
            </value>
            <value>
                <fullName>IR-Irrigação</fullName>
            </value>
            <value>
                <fullName>MM-Material Manutenção</fullName>
            </value>
            <value>
                <fullName>MP-Matéria Prima</fullName>
            </value>
            <value>
                <fullName>PR-Predial</fullName>
            </value>
            <value>
                <fullName>RF-Refugo</fullName>
            </value>
            <value>
                <fullName>SC-Sucata</fullName>
            </value>
            <value>
                <fullName>SE-Serviço</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductChangedLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductChangedLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto trocado</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso (Produto trocado)</relationshipLabel>
    <relationshipName>Itens_do_caso1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductDistributionChannelTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductDistributionChannelTxt__c</fullName>
    <label>Canal distribuição produto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>01-Can.distribuição 01</fullName>
            </value>
            <value>
                <fullName>03-Exportação</fullName>
            </value>
            <value>
                <fullName>06-Intercompany</fullName>
            </value>
            <value>
                <fullName>07-Nacional</fullName>
            </value>
            <value>
                <fullName>16-Canal Comun</fullName>
            </value>
            <value>
                <fullName>CC-Atendimento Mexichem</fullName>
            </value>
            <value>
                <fullName>EX-Exportação</fullName>
            </value>
            <value>
                <fullName>RV-Repres/Vendedor</fullName>
            </value>
            <value>
                <fullName>VD-Venda Direta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductSalesOfficeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductSalesOfficeTxt__c</fullName>
    <label>Escritório vendas produto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0010-Regional Sul</fullName>
            </value>
            <value>
                <fullName>0020-Regional SP Capital</fullName>
            </value>
            <value>
                <fullName>0030-Regional RJ/ES</fullName>
            </value>
            <value>
                <fullName>0040-Regional Nordeste</fullName>
            </value>
            <value>
                <fullName>0050-Regional SP Interior</fullName>
            </value>
            <value>
                <fullName>0060-Regional MG</fullName>
            </value>
            <value>
                <fullName>0070-REgional CO/NO</fullName>
            </value>
            <value>
                <fullName>0090-Venda Direta</fullName>
            </value>
            <value>
                <fullName>0100-Exportação</fullName>
            </value>
            <value>
                <fullName>0110-Regional Irriga</fullName>
            </value>
            <value>
                <fullName>0120-Regional Construtora</fullName>
            </value>
            <value>
                <fullName>0130-Reg Infra Industria</fullName>
            </value>
            <value>
                <fullName>0140-Alphagary</fullName>
            </value>
            <value>
                <fullName>0150-Regional Infra</fullName>
            </value>
            <value>
                <fullName>0160-Assistência Técnica</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductSalesOrganizationTxt__c</fullName>
    <label>Organização vendas produto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0099-BIDIM</fullName>
            </value>
            <value>
                <fullName>0125-DOUTORES DA CONST.</fullName>
            </value>
            <value>
                <fullName>0141-ALPHAGARY CORP.</fullName>
            </value>
            <value>
                <fullName>0143-PLASTUBOS</fullName>
            </value>
            <value>
                <fullName>0147-MEXICHEM TRADING</fullName>
            </value>
            <value>
                <fullName>0155-BR - CredConstrução</fullName>
            </value>
            <value>
                <fullName>AM01-AMANCO</fullName>
            </value>
            <value>
                <fullName>PL01-OrgV Plastubos</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/ProductSalesTeamTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductSalesTeamTxt__c</fullName>
    <label>Equipe vendas produto</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>001-Vendedor Interno</fullName>
            </value>
            <value>
                <fullName>002-Representante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QMLkp__c.field-meta.xml
<CustomField>
    <fullName>QMLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>QM</label>
    <referenceTo>QM__c</referenceTo>
    <relationshipLabel>Itens do caso</relationshipLabel>
    <relationshipName>Itens_do_caso</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QualityProblemTxt__c.field-meta.xml
<CustomField>
    <fullName>QualityProblemTxt__c</fullName>
    <label>Problemas de qualidade</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CaseItem__c/fields/QuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>QuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>13</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CSECaseItemSelector.cls
public with sharing class CSECaseItemSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		CaseItem__c.Id,
    		CaseItem__c.CaseMdt__c,
    		CaseItem__c.ProductLkp__c,
    		CaseItem__c.QuantityNmb__c,
    		CaseItem__c.FailureTypeTxt__c,
    		CaseItem__c.CommentsTxt__c,
    		CaseItem__c.QualityProblemTxt__c,
    		CaseItem__c.ProductChangedLkp__c,
    		CaseItem__c.ManufacturingCenterTxt__c,
    		CaseItem__c.ProductSalesOrganizationTxt__c,
    		CaseItem__c.ProductDistributionChannelTxt__c,
    		CaseItem__c.ProductActivitySectorTxt__c,
    		CaseItem__c.ProductSalesOfficeTxt__c,
    		CaseItem__c.ProductSalesTeamTxt__c,
    		CaseItem__c.QMLkp__c
    	};
    }
    
    public Schema.SObjectType getSObjectType() {
    	return CaseItem__c.sObjectType;
    }
    
    public List<CaseItem__c> selectById(Set<Id> idSet) {
    	String query = String.format(
    		' SELECT {0}' +
    		' FROM {1}' +
    		' WHERE Id IN :idSet' +
    		' ORDER BY {2}',
    		new List<String>{
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<CaseItem__c>)Database.query(query);
    }
    
    public List<CaseItem__c> selectByCaseId(Id caseId) {
    	String query = String.format(
    		' SELECT {0}' +
    		' FROM {1}' +
    		' WHERE CaseMdt__c = :caseId' +
    		' ORDER BY {2}',
    		new List<String>{
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<CaseItem__c>)Database.query(query);
    }
}