force-app/main/default/objects/QMMeasure__c/QMMeasure__c.object-meta.xml
<CustomObject>
    <description>[a0E][QMMeasure__c] Medidas da QM.</description>
    <label>Medida da QM</label>
    <nameField>
        <label>Numeração medida da QM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medidas da QM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QMMeasure__c/fields/QMSalesforceMdt__c.field-meta.xml
<CustomField>
    <fullName>QMSalesforceMdt__c</fullName>
    <label>QM Salesforce</label>
    <referenceTo>QM__c</referenceTo>
    <relationshipLabel>Medidas da QM</relationshipLabel>
    <relationshipName>Medidas_da_QM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QMMeasure__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Em aberto</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QMMeasureDAO.cls
public with sharing class QMMeasureDAO {
    
    public static List<QMMeasure__c> getById(Set<Id> qmMeasureIdSet) {
        return [
            SELECT Id,
            	   QMSalesforceMdt__c,
            	   StatusTxt__c
            FROM QMMeasure__c
            WHERE Id IN :qmMeasureIdSet
        ];      
    }

    public static List<QMMeasure__c> getByQmId(Set<Id> qmIdSet) {
        return [
            SELECT Id,
            	   QMSalesforceMdt__c,
            	   StatusTxt__c
            FROM QMMeasure__c
            WHERE QMSalesforceMdt__c IN :qmIdSet
        ];      
    }
}