force-app/main/default/objects/ExpurgoItemDaIntegracao__c/ExpurgoItemDaIntegracao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Dias para expurgo de item da integração.</description>
    <label>Expurgo Item da Integração</label>
</CustomObject>

force-app/main/default/objects/ExpurgoItemDaIntegracao__c/fields/DiasParaExpurgo__c.field-meta.xml
<CustomField>
    <fullName>DiasParaExpurgo__c</fullName>
    <label>Dias para expurgo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <description>[a0G][Queue__c] Responsável por prover garantia de entrega para camada de integração</description>
    <label>Item da fila de integração</label>
    <nameField>
        <displayFormat>QIT-{0000000000}</displayFormat>
        <label>Item da fila de integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da fila de integração</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Test_Batch_CleanIntegrationItem.cls
@isTest
private class Test_Batch_CleanIntegrationItem {
    @isTest static  void testDeleteIntegrationItem(){
        ExpurgoItemDaIntegracao__c numDias = TestData.createExpurgoItemDaIntegracao('DaysToPurgeIntegrationItem', 365);
        Datetime purgeDate = Date.today().addDays(-Integer.valueOf(numDias.DiasParaExpurgo__c+1));
        Queue__c integrationItem = TestData.createQueue('Nome de Teste');
        Test.setCreatedDate(integrationItem.Id, purgeDate);
        integrationItem = [Select Id, CreatedDate From Queue__c Where Id =:integrationItem.Id];
        Test.startTest();
            Batch_CleanIntegrationItem obj = new Batch_CleanIntegrationItem();
            DataBase.executeBatch(obj); 
        Test.stopTest(); 
        integrationItem = [Select Id, isDeleted From Queue__c Where Id =:integrationItem.Id ALL ROWS];
        System.assertEquals(true, integrationItem.IsDeleted);
    }
}