force-app/main/default/objects/ExpurgoItemDaIntegracao__c/ExpurgoItemDaIntegracao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Dias para expurgo de item da integração.</description>
    <label>Expurgo Item da Integração</label>
</CustomObject>

force-app/main/default/objects/ExpurgoItemDaIntegracao__c/fields/DiasParaExpurgo__c.field-meta.xml
<CustomField>
    <fullName>DiasParaExpurgo__c</fullName>
    <label>Dias para expurgo</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <description>[a0G][Queue__c] Responsável por prover garantia de entrega para camada de integração</description>
    <label>Item da fila de integração</label>
    <nameField>
        <displayFormat>QIT-{0000000000}</displayFormat>
        <label>Item da fila de integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da fila de integração</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/Batch_CleanIntegrationItem.cls
global class Batch_CleanIntegrationItem implements Database.Batchable<sObject> {
    ExpurgoItemDaIntegracao__c numDias = ExpurgoItemDaIntegracao__c.getInstance('DaysToPurgeIntegrationItem');
	global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(
        	'SELECT ID FROM Queue__c WHERE isDeleted = false AND CreatedDate <= LAST_N_DAYS:' + Integer.valueOf(numDias.DiasParaExpurgo__c)
        ); 
    }
    global void execute(Database.BatchableContext bc, List<Queue__c> scope){
        delete scope;
    }
    global void finish(Database.BatchableContext bc){

    }

}