force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/ConvertOrderAsync.cls
public class ConvertOrderAsync implements Queueable, Database.AllowsCallouts{
    
    public final Id orderId;
    
    public void execute(QueueableContext context) {
        OrderIntegrationUtils.convertQuoteIntoOrder(orderId);
        
        Order__c ord = [SELECT Id, CustomIDTxt__c FROM Order__c WHERE Id = :orderId];
        
        Id jobID = System.enqueueJob(new UpdateOrderAsync(ord.CustomIDTxt__c));
    }
    
    public ConvertOrderAsync(Id orderId){
        this.orderId = orderId;
    }
}