force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RemittanceItem__c/RemittanceItem__c.object-meta.xml
<CustomObject>
    <description>[a0H][RemittanceItem__c] Itens da Remessa.</description>
    <label>Item da remessa</label>
    <nameField>
        <label>Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da remessa</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RemittanceItem__c/fields/RemittanceMdt__c.field-meta.xml
<CustomField>
    <fullName>RemittanceMdt__c</fullName>
    <label>Remessa</label>
    <referenceTo>Remittance__c</referenceTo>
    <relationshipLabel>Itens da remessa</relationshipLabel>
    <relationshipName>Itens_da_remessa</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_RemittanceItem.cls
/*
    Rotinas de limpeza:
    PurgeOrderItemSchedule + Batch_OrderItem
    PurgeOrderSchedule + PurgeOrderBatch
    PurgeInvoiceSchedule + Batch_Invoice
    PurgeOrderRemittanceSchedule + PurgeOrderRemittanceBatch

    Data: 02/02/2017
    Dev: Carlos Diogo de Oliveira
    Caso : 00025639
    Objetivo: Excluir Itens das remessas que estejam relacionadas aos casos, desde que o caso já esteja fechado e não seja do tipo "Reclamação" ou "Substituição"
*/

global class Batch_RemittanceItem implements Database.Batchable<sObject>{
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Itens que nao podem ser excluídos
        Set<Id> ids = DAO_Case.getOrdersIdInCase();
        
        // Itens para excluir
        return Database.getQueryLocator([SELECT Id 
                                         FROM RemittanceItem__c  
                                         WHERE RemittanceMdt__r.OrderLkp__r.Id NOT IN : ids
                                         AND RemittanceMdt__r.OrderLkp__r.CreatedDate < LAST_N_DAYS:30
                                         AND (RemittanceMdt__r.OrderLkp__r.CaseLkp__r.Id != null 
                                              AND RemittanceMdt__r.OrderLkp__r.CaseLkp__r.IsClosed = true 
                                              AND RemittanceMdt__r.OrderLkp__r.CaseLkp__r.RecordType.Name != 'Reclamação'
                                              AND RemittanceMdt__r.OrderLkp__r.CaseLkp__r.RecordType.Name != 'Substituição')]);
    }

    global void execute(Database.BatchableContext BC, List<RemittanceItem__c> remittanceItemList) {
        System.debug(remittanceItemList.size());
        
        Database.delete(remittanceItemList);
    }
    
    global void finish(Database.BatchableContext BC) {}
}