force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/Remittance__c.object-meta.xml
<CustomObject>
    <description>[a0I][Remittance__c] Pedidos de remessa.</description>
    <label>Remessa</label>
    <nameField>
        <label>Número da Remessa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Remessas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Remittance__c/fields/OrderLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Remessas</relationshipLabel>
    <relationshipName>Remessas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Remittance__c/fields/StatusFml__c.field-meta.xml
<CustomField>
    <fullName>StatusFml__c</fullName>
    <formula>IF(
   RemittanceStatusBln__c = TRUE, &quot;Remessa cancelada&quot;,
   IF(
      NOT(ISBLANK( ShipmentDeliveredDte__c )) , &quot;Mercadoria entregue&quot;,
      IF(
         NOT(ISBLANK( ShipmentTransitDte__c )), &quot;Mercadoria em transito&quot;,
         IF(
            NOT(ISBLANK(  ShipmentFinishedDte__c )), &quot;Carregamento finalizado&quot;,
            IF(
               NOT(ISBLANK(   InLadingDte__c )), &quot;Em carregamento&quot;,
&quot;&quot;)))))</formula>
    <inlineHelpText>Status de acordo com as datas de carregamento até data de Mercadoria entregue.</inlineHelpText>
    <label>Status da remessa</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RMTRemittanceSelector.cls
public with sharing class RMTRemittanceSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
		return new List<Schema.SObjectField> {
			Remittance__c.Id,
			Remittance__c.OrderLkp__c,
			Remittance__c.StatusFml__c
		};
	}
	
	public Schema.SObjectType getSObjectType() {
		return Remittance__c.sObjectType;
	}
	
	public List<Remittance__c> selectById(Set<Id> idSet) {

        String query = String.format(
            ' SELECT {0}, OrderLkp__r.CaseLkp__c, OrderLkp__r.CaseLkp__r.Status, OrderLkp__r.CaseLkp__r.RecordType.DeveloperName ' + 
            ' FROM {1}' +
            ' WHERE Id IN :idSet',
            new List<String>{
                getFieldListString(),
                getSObjectName()                     
            }
        );  

        return (List<Remittance__c>)Database.query(query);       
    }
}