force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SkipValidations__c/SkipValidations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Skip Validations</label>
</CustomObject>

force-app/main/default/objects/SkipValidations__c/fields/Skip__c.field-meta.xml
<CustomField>
    <fullName>Skip__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Skip</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/integ_CustomOperationOrder.cls
public with sharing class integ_CustomOperationOrder implements integ_IIntegrationOperation {
	
	public Object execute(List<SObject> recordList) {
        
        System.debug(LoggingLevel.INFO, '*** integ_CustomOperationOrder::execute() ' + recordList);
		system.debug('ALOU CUSTOMOPERATIONORDER: ');
		List<Order__c> orderList = new List<Order__c>();
		orderList.addAll((List<Order__c>)recordList);
		
		Map<String, Order__c> orderMap = new Map<String, Order__c>();
		
		//unify list by inv
		for (Order__c ord : orderList) {
            system.debug('ordem atual: '+ord);
            system.debug('ordem caso atual: '+ord.CaseLkp__c);
			if (!orderMap.containsKey(ord.CustomIDTxt__c)) {
				orderMap.put(ord.CustomIDTxt__c, ord);
			}
		}
		
        SkipValidations__c skipVal = SkipValidations__c.getOrgDefaults();
        skipVal.Skip__c = true;
        update skipVal;
        
		orderList = orderMap.values(); 
		System.debug('*** orderList' + orderList);
		
        
        
		//System.debug('=======================External ID da ordem: ' + Order__c.CustomIDTxt__c);
		//
		Database.UpsertResult[] resultList = Database.upsert(orderList, Order__c.CustomIDTxt__c, true);
		
        skipVal.Skip__c = false;
        update skipVal;
        
		integer i = 0;
		for (Database.UpsertResult result : resultList) {
			if (!result.isSuccess()) {
        		System.debug(LoggingLevel.INFO, '*** DML ERROR : integ_CustomOperationOrder::execute() ' + orderList[i] +  result.getErrors());
        		
			}
			i++;
		}
		
		return orderList;
	}
}