force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/Batch_OrderItem.cls
/*
    Rotinas de limpeza:
    PurgeOrderItemSchedule + Batch_OrderItem
    PurgeOrderSchedule + PurgeOrderBatch
    PurgeInvoiceSchedule + Batch_Invoice
    PurgeOrderRemittanceSchedule + PurgeOrderRemittanceBatch

    Data: 23/01/2017
    Dev: Renata
    Caso: 00025639
    Objetivo: Excluir Itens das ordens que estejam relacionadas aos casos, desde que o caso já esteja fechado
    ===============================================
    
    Data: 02/02/2017
    Dev: Carlos Diogo de Oliveira
    Caso : 00025639
    Alteração: Excluir Itens das ordens que estejam relacionadas aos casos, desde que o caso já esteja fechado e não seja do tipo "Reclamação" ou "Substituição"
*/
global class Batch_OrderItem implements Database.Batchable<sObject> {
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        //Itens que nao podem ser excluídos
        Set<Id> ids = DAO_Case.getOrdersIdInCase();
        
        // Itens para excluir
        return Database.getQueryLocator([SELECT Id 
                                         FROM OrderItem__c  
                                         WHERE OrderMdt__r.Id NOT IN : ids
                                         AND OrderMdt__r.CreatedDate < LAST_N_DAYS:30
                                         AND (OrderMdt__r.CaseLkp__r.Id != null 
                                              AND OrderMdt__r.CaseLkp__r.IsClosed = true 
                                              AND OrderMdt__r.CaseLkp__r.RecordType.Name != 'Reclamação'
                                              AND OrderMdt__r.CaseLkp__r.RecordType.Name != 'Substituição')]);
    }

    global void execute(Database.BatchableContext BC, List<OrderItem__c> OrderItemList) {
        System.debug(OrderItemList.size());
        
        Database.delete(OrderItemList);

    }
    
    global void finish(Database.BatchableContext BC) {
     
    }
    
}