force-app/main/default/objects/AccountGoal__c/AccountGoal__c.object-meta.xml
<CustomObject>
    <description>[a0w][AccountGoal__c] Objetos que guardam as metas individuais de cada cliente, para cada período da Campanha de Trade Marketing</description>
    <label>Meta de Campanha</label>
    <nameField>
        <displayFormat>AGO-{YYYY}{00000}</displayFormat>
        <label>Código de Meta da Conta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas de Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountGoal__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Conta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agrupamento de Campanha</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/BenefitPercentage__c.field-meta.xml
<CustomField>
    <fullName>BenefitPercentage__c</fullName>
    <label>Porcentagem do Benefício</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CalculationBasis__c.field-meta.xml
<CustomField>
    <fullName>CalculationBasis__c</fullName>
    <inlineHelpText>Total sumarizado que será utilizado no pagamento do benefício.</inlineHelpText>
    <label>Base de Cálculo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/RealizedPercentage__c.field-meta.xml
<CustomField>
    <fullName>RealizedPercentage__c</fullName>
    <formula>IF(GoalRlp__c &lt;&gt; 0, RealizedRlp__c / GoalRlp__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porcentagem Realizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountGoalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <description>[###][CreditNote__c] Notas de crédito</description>
    <label>Nota de Crédito</label>
    <nameField>
        <displayFormat>NC-{000000000}</displayFormat>
        <label>Nome de Nota de Crédito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/fields/AccountGoalLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountGoalLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Meta de campanha atingida que deu origem à nota de crédito.</description>
    <label>Meta de Campanha</label>
    <referenceTo>AccountGoal__c</referenceTo>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Agrupamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agrupamento de Campanha</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas de Crédito</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditNoteStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/AccountGoalTriggerHandler.cls
public class AccountGoalTriggerHandler {
/*    public static void isAfterInsert(List<AccountGoal__c> listAccGoal, Map<Id, AccountGoal__c> oldMap){
        
    }
    public static void isAfterUpdate(List<AccountGoal__c> listAccGoal, Map<Id, AccountGoal__c> oldMap){
       
        List<AccountGoal__c> listFlexAccGoal = new List<AccountGoal__c>();
        
        for(AccountGoal__c accGoal : listAccGoal){
            if(accGoal.Status__c == 'Flexibilizado' && (accGoal.Status__c != oldMap.get(accGoal.Id).Status__c)
              && (accGoal.BenefitPercentage__c != null) && (accGoal.RealizedPercentage__c == 100)){
                listFlexAccGoal.add(accGoal);
            }
        }
        System.debug('Trigger after AccountGoal update - '+listFlexAccGoal.size()+' records');
        if(listFlexAccGoal.size() > 0){
            //System.debug('UPDATE DE FLEXIBILIZADO!!!');
            List<CreditNote__c> listCreditNote = new List<CreditNote__c>();
			      
            for(AccountGoal__c accGoal : listFlexAccGoal){
                //System.debug(accGoal);
           		CreditNote__c credNote = new CreditNote__c();
                credNote.Value__c = accGoal.CalculationBasis__c * accGoal.BenefitPercentage__c/100;
                credNote.AccountGoalLkp__c = accGoal.Id;
                credNote.AccountLkp__c = accGoal.AccountLkp__c;
                credNote.Date__c = Date.today();
                credNote.Status__c = 'Aprovado';
                
                listCreditNote.add(credNote);
            }
            Database.insert(listCreditNote);
        }        
    }
    public static void isAfterDelete(List<AccountGoal__c> listAccGoal, Map<Id, AccountGoal__c> oldMap){
        
    }*/
}