force-app/main/default/objects/AccountGoal__c/AccountGoal__c.object-meta.xml
<CustomObject>
    <description>[a0w][AccountGoal__c] Objetos que guardam as metas individuais de cada cliente, para cada período da Campanha de Trade Marketing</description>
    <label>Meta de Campanha</label>
    <nameField>
        <displayFormat>AGO-{YYYY}{00000}</displayFormat>
        <label>Código de Meta da Conta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas de Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountGoal__c/fields/CalculationBasis__c.field-meta.xml
<CustomField>
    <fullName>CalculationBasis__c</fullName>
    <inlineHelpText>Total sumarizado que será utilizado no pagamento do benefício.</inlineHelpText>
    <label>Base de Cálculo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CampaignCalculationLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignCalculationLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apuração de Campanha</label>
    <referenceTo>CampaignCalculation__c</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CampaignLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Campanha</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CreatedCreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreatedCreditNote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo onde é indicado se a a meta de conta já gerou uma nota de crédito. Utilizado na recuperação de campanha.</description>
    <label>Gerou Nota de Crédito</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/FlexValueNmb__c.field-meta.xml
<CustomField>
    <fullName>FlexValueNmb__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Flexibilizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/FlexValueRlp__c.field-meta.xml
<CustomField>
    <fullName>FlexValueRlp__c</fullName>
    <label>Flexibilizado</label>
    <summarizedField>MonthlyGoal__c.FlexValueNmb__c</summarizedField>
    <summaryForeignKey>MonthlyGoal__c.AccountGoalMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/Goal__c.field-meta.xml
<CustomField>
    <fullName>Goal__c</fullName>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/GoalRlp__c.field-meta.xml
<CustomField>
    <fullName>GoalRlp__c</fullName>
    <label>Meta</label>
    <summarizedField>MonthlyGoal__c.GoalNmb__c</summarizedField>
    <summaryForeignKey>MonthlyGoal__c.AccountGoalMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/Realized__c.field-meta.xml
<CustomField>
    <fullName>Realized__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Realizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/RealizedRlp__c.field-meta.xml
<CustomField>
    <fullName>RealizedRlp__c</fullName>
    <label>Realizado</label>
    <summarizedField>MonthlyGoal__c.RealizedFml__c</summarizedField>
    <summaryForeignKey>MonthlyGoal__c.AccountGoalMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountGoalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Campaign__c/Campaign__c.object-meta.xml
<CustomObject>
    <description>[a0q][Campaign__c] Campanha de Trade Marketing</description>
    <label>Campanha</label>
    <nameField>
        <label>Nome da Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campanhas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignCalculation__c/CampaignCalculation__c.object-meta.xml
<CustomObject>
    <description>[a0v][CampaignCalculation__c] Período de apuração da Campanha de Trade Marketing</description>
    <label>Apuração de Campanha</label>
    <nameField>
        <label>Nome de Apuração de Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apurações de Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignCalculation__c/fields/CampaignLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignLkp__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign__c</referenceTo>
    <relationshipLabel>Apurações de Campanha</relationshipLabel>
    <relationshipName>CampaignCalculations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CampaignCalculation__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Posição</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_CampaignUtility.cls
@isTest
private class Test_CampaignUtility {
    @isTest static void testResetCalculation(){
        Campaign__c cmp = TestData.createCompleteCampaign(true);
        
        CampaignUtility.resetCalculation(cmp.Id);
        
        List<AccountGoal__c> accGoalList = [SELECT Id, CreatedCreditNote__c, Status__c, FlexValueNmb__c, Realized__c, CalculationBasis__c FROM ACCOUNTGOAL__C WHERE CAMPAIGNLKP__R.ID = :cmp.Id];
        
        for (AccountGoal__c accGoal : accGoalList){
            System.debug(accGoal);
            System.assertEquals(false, accGoal.CreatedCreditNote__c);
            //System.assertEquals('', accGoal.Status__c);
            System.assertEquals(0, accGoal.FlexValueNmb__c);
            System.assertEquals(0, accGoal.Realized__c);
            System.assertEquals(0, accGoal.CalculationBasis__c);
        }
    }
    
    @isTest static void testCleanAccountGoals(){
        Campaign__c cmp = TestData.createCompleteCampaign(true);
        
        CampaignUtility.cleanAccountGoals(cmp.Id);
        
        List<AccountGoal__c> accGoalList = [SELECT Id, CreatedCreditNote__c, Status__c, FlexValueNmb__c, Realized__c, CalculationBasis__c FROM ACCOUNTGOAL__C WHERE CAMPAIGNLKP__R.ID = :cmp.Id];
        
        for (AccountGoal__c accGoal : accGoalList){
            System.debug(accGoal);
            System.assertEquals(false, accGoal.CreatedCreditNote__c);
            //System.assertEquals('', accGoal.Status__c);
            System.assertEquals(0, accGoal.FlexValueNmb__c);
            System.assertEquals(0, accGoal.CalculationBasis__c);
        }
    }
    
    @isTest static void testDeleteCampaignGoals(){
        Campaign__c cmp = TestData.createCompleteCampaign(true);
        CampaignUtility.deleteCampaignGoals(cmp.Id);
        List<AccountGoal__c> accGoalList = [SELECT Id, CreatedCreditNote__c, Status__c, FlexValueNmb__c, Realized__c, CalculationBasis__c FROM ACCOUNTGOAL__C WHERE CAMPAIGNLKP__R.ID = :cmp.Id];
        System.assertEquals(0, accGoalList.size());
    }
      
    @isTest static void testGenerateCampaignGoals(){
        Campaign__c cmp = TestData.createCompleteCampaign(false);
        CampaignUtility.generateCampaignGoals(cmp.Id);        
        List<AccountGoal__c> accGoalList = [SELECT Id, Name FROM ACCOUNTGOAL__C WHERE CAMPAIGNLKP__R.ID = :cmp.Id];
        System.assertEquals(4, accGoalList.size());
    }
    
    @isTest static void testGetAccountGoalList(){
        Campaign__c cmp = TestData.createCompleteCampaign(true);
        List<AccountGoal__c> goalList = CampaignUtility.getAccountGoalList(cmp.Id);
        System.assertNotEquals(0, goalList.size());
        goalList = CampaignUtility.getAccountGoalToFlexList(cmp.Id);
        System.assertNotEquals(0, goalList.size());
    }
    
    @isTest static void testGetNCDiscount(){
        TestData.createIntegrationData();
        MultiRequestMock mrm = new MultiRequestMock(new Map<String, StaticResourceCalloutMock>());
        
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('Mock_NcCompensated');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        mrm.addRequestMock('NcCompensated', mock);
        Campaign__c cmp = TestData.createCompleteCampaignNcDiscount(true);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, mrm);
        
        CampaignUtility.getNCDiscount(cmp.Id, Date.newInstance(2017, 10, 20));
        Test.stopTest();
    }
    
    @isTest static void testFlexAccountGoals(){
        Campaign__c cmp = TestData.createCompleteCampaign(true);
        CampaignUtility.startCampaign(cmp.Id);
        List<AccountGoal__c> goalList = CampaignUtility.getAccountGoalToFlexList(cmp.Id);
        List<AccountGoal__c> flexGoalList = new List<AccountGoal__c>();
        System.debug(goalList);
        for(Integer I = 0; I < goalList.size(); I++){
            if((Math.mod(I, 2) == 0) && (goalList[I].RealizedRlp__c < goalList[I].GoalRlp__c)) flexGoalList.add(goalList[I]);
        }
        System.debug('##flexGoalList');
        System.debug(flexGoalList);
       	String flexGoalListJSON = JSON.serialize(flexGoalList);
        String res = CampaignUtility.flexAccountGoals(cmp.Id, flexGoalListJSON);
        System.assertEquals('SUCCESS', res);
        
        List<AccountGoal__c> goalListUpdated = CampaignUtility.getAccountGoalList(cmp.Id);
        System.debug(goalListUpdated);
        for(Integer I = 0; I < goalListUpdated.size(); I++){
            if((Math.mod(I, 2) == 0)  && (goalList[I].RealizedRlp__c < goalList[I].GoalRlp__c)){
                System.assertEquals(goalListUpdated[I].RealizedRlp__c, goalListUpdated[I].GoalRlp__c);
 				System.assertEquals(goalList[I].GoalRlp__c - goalList[I].RealizedRlp__c, goalListUpdated[I].FlexValueRlp__c);
                System.assertEquals('Flexibilizado', goalListUpdated[I].Status__c);
            }
        }        
    }

    @isTest static void testComplete(){
        /*CREATING CAMPAIGN*/
        Campaign__c cmp = TestData.createCompleteCampaign(true);

        /*STARTING CAMPAIGN*/
      
        CampaignUtility.startCampaign(cmp.Id);  
        Campaign__c cmpAux = [SELECT Id, Active__c FROM Campaign__c WHERE Id = :cmp.Id];
        System.assertEquals(true, cmpAux.Active__c);
        
        System.Debug('TesteGoalList1');
        System.Debug(cmp.Id);

        /*CAMPAIGN CALCULATION*/
        CampaignUtility.computeRealized(cmp.Id, Date.newInstance(2017, 12, 20));
        List<AccountGoal__c> goalList = [SELECT Id, Name, Goal__c, Realized__c, RealizedRlp__c, CampaignCalculationLkp__r.Position__c 
                                         FROM ACCOUNTGOAL__C WHERE CampaignLkp__c = :cmp.Id
                                         ORDER BY CampaignCalculationLkp__r.Position__c];
        System.Debug('TesteGoalList');
        System.Debug(goalList[3].RealizedRlp__c);
        System.Debug(goalList);
        System.assertEquals(3000, goalList[3].RealizedRlp__c);
        
        /*CAMPAIGN RECOVERY*/
        CampaignUtility.campaignRecovery(cmp.Id);
        goalList = [SELECT Id, Name, Goal__c, Realized__c, CampaignCalculationLkp__r.Position__c, Status__c 
                    FROM ACCOUNTGOAL__C WHERE CampaignLkp__c = :cmp.Id
                    ORDER BY CampaignCalculationLkp__r.Position__c];
        System.assertEquals('Recuperado', goalList[0].Status__c);
        System.assertNotEquals('Recuperado', goalList[1].Status__c);
        System.assertNotEquals('Recuperado', goalList[2].Status__c);
        System.assertNotEquals('Recuperado', goalList[3].Status__c);
        
        /*CREATE CREDIT NOTE*/
        CampaignUtility.createCreditNote(cmp.Id, Date.newInstance(2017, 12, 20));
        goalList = [SELECT Id, Name, Goal__c, Realized__c, CampaignCalculationLkp__r.Position__c, Status__c, CreatedCreditNote__c 
                    FROM ACCOUNTGOAL__C WHERE CampaignLkp__c = :cmp.Id
                    ORDER BY CampaignCalculationLkp__r.Position__c];
		System.assertEquals(true, goalList[0].CreatedCreditNote__c);
        System.assertEquals(true, goalList[1].CreatedCreditNote__c);    
        System.assertEquals(false, goalList[2].CreatedCreditNote__c);    
        System.assertEquals(false, goalList[3].CreatedCreditNote__c);            
    }
}