force-app/main/default/objects/AccountGoal__c/AccountGoal__c.object-meta.xml
<CustomObject>
    <description>[a0w][AccountGoal__c] Objetos que guardam as metas individuais de cada cliente, para cada período da Campanha de Trade Marketing</description>
    <label>Meta de Campanha</label>
    <nameField>
        <displayFormat>AGO-{YYYY}{00000}</displayFormat>
        <label>Código de Meta da Conta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas de Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountGoal__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Conta</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agrupamento de Campanha</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/BenefitPercentage__c.field-meta.xml
<CustomField>
    <fullName>BenefitPercentage__c</fullName>
    <label>Porcentagem do Benefício</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CalculationBasis__c.field-meta.xml
<CustomField>
    <fullName>CalculationBasis__c</fullName>
    <inlineHelpText>Total sumarizado que será utilizado no pagamento do benefício.</inlineHelpText>
    <label>Base de Cálculo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CampaignCalculationLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignCalculationLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Apuração de Campanha</label>
    <referenceTo>CampaignCalculation__c</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CampaignMechanicsLkp__c.field-meta.xml
<CustomField>
    <fullName>CampaignMechanicsLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mecânica de Campanha</label>
    <referenceTo>CampaignMechanics__c</referenceTo>
    <relationshipName>AccountGoals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/CreatedCreditNote__c.field-meta.xml
<CustomField>
    <fullName>CreatedCreditNote__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo onde é indicado se a a meta de conta já gerou uma nota de crédito. Utilizado na recuperação de campanha.</description>
    <label>Gerou Nota de Crédito</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/RealizedPercentage__c.field-meta.xml
<CustomField>
    <fullName>RealizedPercentage__c</fullName>
    <formula>IF(GoalRlp__c &lt;&gt; 0, RealizedRlp__c / GoalRlp__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Porcentagem Realizado</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/AccountGoal__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>AccountGoalStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CampaignCalculation__c/CampaignCalculation__c.object-meta.xml
<CustomObject>
    <description>[a0v][CampaignCalculation__c] Período de apuração da Campanha de Trade Marketing</description>
    <label>Apuração de Campanha</label>
    <nameField>
        <label>Nome de Apuração de Campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Apurações de Campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMechanics__c/CampaignMechanics__c.object-meta.xml
<CustomObject>
    <description>[a0t][CampaignMechanics__c] Mecânica definida para a campanha de Trade: Maneira de apuração e pagamento de benefício</description>
    <label>Mecânica de Campanha</label>
    <nameField>
        <displayFormat>CGO-{YYYY}{00000}</displayFormat>
        <label>Código de Mecânica de Campanha</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mecânicas de Campanhas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CampaignMechanics__c/fields/BenefitCriteriaLkp__c.field-meta.xml
<CustomField>
    <fullName>BenefitCriteriaLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Critério do Beneficio</label>
    <referenceTo>CampaignIndicator__c</referenceTo>
    <relationshipName>BenefitCriteria</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/CreditNote__c.object-meta.xml
<CustomObject>
    <description>[###][CreditNote__c] Notas de crédito</description>
    <label>Nota de Crédito</label>
    <nameField>
        <displayFormat>NC-{000000000}</displayFormat>
        <label>Nome de Nota de Crédito</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notas de Crédito</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditNote__c/fields/AccountGoalLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountGoalLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Meta de campanha atingida que deu origem à nota de crédito.</description>
    <label>Meta de Campanha</label>
    <referenceTo>AccountGoal__c</referenceTo>
    <relationshipName>CreditNotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Agrupamento</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Agrupamento de Campanha</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas de Crédito</relationshipLabel>
    <relationshipName>CreditNotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Data</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>CreditNoteStatus</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/CreditNote__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/Batch_GenerateCreditNote.cls
global class Batch_GenerateCreditNote implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext bc){
    	//System.debug('Batch_GenerateCreditNote start');
        return Database.getQueryLocator(
            'SELECT Id, BenefitPercentage__c, CalculationBasis__c, AccountLkp__c FROM AccountGoal__c WHERE CampaignCalculationLkp__r.EndDate__c <= TODAY '+
            'AND CreatedCreditNote__c = FALSE AND CampaignMechanicsLkp__r.BenefitCriteriaLkp__c <> null AND (RealizedPercentage__c >= 100 OR Status__c = \'Recuperado\')'
        );   
    }
    global void execute(Database.BatchableContext bc, List<AccountGoal__c> scope){
        List<CreditNote__c> credNoteList = new List<CreditNote__c>();
        
        //System.debug('Metas atingidas da campanha: '+scope.size());
        
        for(AccountGoal__C accGoal : scope){
            //System.debug('Porcentagem do Beneficio: '+ accGoal.BenefitPercentage__c);
            //System.debug('Base de Calculo: '+ accGoal.CalculationBasis__c);
            Double creditAmount = accGoal.BenefitPercentage__c/100 * accGoal.CalculationBasis__c;
            //System.debug('A ser pago : '+creditAmount);
            
            CreditNote__c credNote = new CreditNote__c();
            credNote.Value__c = creditAmount;
            credNote.AccountGoalLkp__c = accGoal.Id;
            credNote.AccountLkp__c = accGoal.AccountLkp__c;
            credNote.Date__c = Date.today();
            credNote.Status__c = 'Aprovado';
            
            credNoteList.add(credNote);
            
            accGoal.CreatedCreditNote__c = true;
        }
        insert credNoteList;
        update scope;
        
    }
    global void finish(Database.BatchableContext bc){
     	System.debug('Fim execução Batch Nota de Crédito');   
    }
}