force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal PVC</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipName>AccountAreaSales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/OfflinePrices__c.object-meta.xml
<CustomObject>
    <description>Tabela de preços do Offline</description>
    <label>Preços Offline</label>
    <nameField>
        <label>Nome de Preços Offline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Offline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfflinePrices__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Preços Offline</relationshipLabel>
    <relationshipName>ProductLkp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageTxt__c</fullName>
    <description>Mensagens de erro na integração</description>
    <label>Mensagem de Erro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente com ZNOV caso deixe em branco</inlineHelpText>
    <label>Tipo de Ordem</label>
    <referenceTo>OrderType__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/ErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageTxt__c</fullName>
    <description>Mensagens de erro na integração</description>
    <label>Mensagens de Erro</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/TotalNetWeightKgNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalNetWeightKgNmb__c</fullName>
    <label>Peso Líquido Total (Kg)</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ValueROBFml__c.field-meta.xml
<CustomField>
    <fullName>ValueROBFml__c</fullName>
    <formula>IF(OriginalQuantityNmb__c != 0 &amp;&amp; SyncedSAPBln__c = false, 
( TotalGrossCostNmb__c / OriginalQuantityNmb__c ) * OrderQuantityNmb__c * (1 - ZPRO__c) * (1 - ZCOT__c) * (1 - ZPVO__c) * (1 - ZVJ1__c) * (1 - ZPME__c) * (1 - ZPSO__c) * (1 - XXES__c) * (1 - ZPXI__c),
TotalGrossCostNmb__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ValueROBNoIPIFml__c.field-meta.xml
<CustomField>
    <fullName>ValueROBNoIPIFml__c</fullName>
    <formula>IF(OriginalQuantityNmb__c != 0 &amp;&amp; SyncedSAPBln__c = false, 
( OriginalROBNoIPINmb__c / OriginalQuantityNmb__c ) * OrderQuantityNmb__c * (1 - ZPRO__c) * (1 - ZCOT__c) * (1 - ZPVO__c) * (1 - ZVJ1__c) * (1 - ZPME__c) * (1 - ZPSO__c) * (1 - XXES__c) * (1 - ZPXI__c),
OriginalROBNoIPINmb__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROB s/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ValueROLFml__c.field-meta.xml
<CustomField>
    <fullName>ValueROLFml__c</fullName>
    <formula>IF(OriginalQuantityNmb__c != 0 &amp;&amp; SyncedSAPBln__c = false, 
( LiquidNmb__c / OriginalQuantityNmb__c ) * OrderQuantityNmb__c * (1 - ZPRO__c) * (1 - ZCOT__c) * (1 - ZPVO__c) * (1 - ZVJ1__c) * (1 - ZPME__c) * (1 - ZPSO__c) * (1 - XXES__c) * (1 - ZPXI__c),
LiquidNmb__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROL</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/MaterialGroup__c.field-meta.xml
<CustomField>
    <fullName>MaterialGroup__c</fullName>
    <label>Grupo de Material</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>MaterialsGroup</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductSystemTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductSystemTxt__c</fullName>
    <label>Sistema de Produtos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>System</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/OrderSummaryController.cls
public class OrderSummaryController {    
    
    @AuraEnabled
    public static string getSystems(Id orderId){
        
        Order__c o = [SELECT Id, ErrorMessageTxt__c, AccountLkp__c, AccountAreaSalesLkp__c, AccountAreaSalesLkp__r.ChannelLkp__c, OrderTypeLkp__c FROM Order__c WHERE Id =: orderId];
        
        
        AggregateResult [] systemTotals = [SELECT		ProductLkp__r.ProductSystemTxt__c systemCode,                                                        				
                                           Count(Id) itemCount,                                                                        
                                           SUM(TotalNetWeightKgNmb__c) weight,
                                           SUM(ValueROBFml__c) grossAmountIPI,
                                           SUM(ValueROBNoIPIFml__c) grossAmountWOIPI,
                                           SUM(ValueROLFml__c) amountWTaxes
                                           // definir AmountWTaxes -> valor sem impostos
                                           FROM		OrderItem__c
                                           WHERE		OrderMdt__c =: orderId
                                           GROUP BY	ProductLkp__r.ProductSystemTxt__c
                                          ];
                
        List <Product2> orderProducts = [SELECT ProductSystemTxt__c, toLabel(ProductSystemTxt__c) systDesc
                                         FROM Product2
                                         WHERE Id IN (SELECT ProductLkp__c 
                                                      FROM OrderItem__c 
                                                      WHERE OrderMdt__c =: orderId
                                                     )
                                        ];
        
        Map<String,String> systMap = new Map<String,String>();
        
        for (Product2 prod : orderProducts){
            systMap.put(prod.ProductSystemTxt__c, (string)prod.get('systDesc'));
        }
        
        system.debug('Sistemas: '+ systMap);
        
        List<prodSystem> systemSummary = new List<prodSystem>();
        
        for (AggregateResult res: systemTotals){            
            prodSystem syst = new prodSystem();            
            syst.systemCode = (String)res.get('systemCode');
            syst.systemDscrp = systMap.get(syst.systemCode);
            syst.itemCount = (Integer)res.get('itemCount');
            syst.weight = (Decimal)res.get('weight');
            syst.grossAmountIPI = (Decimal)res.get('grossAmountIPI');
            syst.grossAmountWOIPI = (Decimal)res.get('grossAmountWOIPI');
            syst.amountWTaxes = (Decimal)res.get('amountWTaxes'); //utilizar definição de AmountWTaxes
            systemSummary.add(syst);
        }
        
        system.debug(JSON.serialize(systemSummary));                       
        
        return JSON.serialize(systemSummary);
        
    }
    
    @AuraEnabled
    public static string getGroups(Id orderId){
        
        Order__c o = [SELECT Id, ErrorMessageTxt__c, AccountLkp__c, AccountAreaSalesLkp__c, AccountAreaSalesLkp__r.ChannelLkp__c, OrderTypeLkp__c FROM Order__c WHERE Id =: orderId];                
        
        AggregateResult [] groupTotals = [SELECT	ProductLkp__r.MaterialGroup__c groupCode,                                                                                                        
                                          Count(Id) itemCount,
                                          SUM(TotalNetWeightKgNmb__c) weight,
                                          SUM(ValueROBFml__c) grossAmountIPI,
                                          SUM(ValueROBNoIPIFml__c) grossAmountWOIPI,
                                          SUM(ValueROLFml__c) amountWTaxes                                        				
                                          FROM		OrderItem__c
                                          WHERE	OrderMdt__c =: orderId
                                          GROUP BY	ProductLkp__r.MaterialGroup__c
                                         ];
        system.debug(groupTotals);                       
        
        List <Product2> orderProducts = [SELECT MaterialGroup__c, toLabel(MaterialGroup__c) groupDesc
                                         FROM Product2
                                         WHERE Id IN (SELECT ProductLkp__c 
                                                      FROM OrderItem__c 
                                                      WHERE OrderMdt__c =: orderId
                                                     )
                                        ];
        
        Map<String,String> groupMap = new Map<String,String>();
        
        for (Product2 prod : orderProducts){
            groupMap.put(prod.MaterialGroup__c, (string)prod.get('groupDesc'));
        }
        
        system.debug('Grupos: '+ groupMap);
        
        List<prodGroup> groupSummary = new List<prodGroup>();                
        
        for (AggregateResult res: groupTotals){            
            prodGroup grp = new prodGroup();            
            grp.groupCode = (String)res.get('groupCode');
            grp.groupDscrp = groupMap.get(grp.groupCode);
            grp.itemCount = (Integer)res.get('itemCount');
            grp.weight = (Decimal)res.get('weight');
            grp.grossAmountIPI = (Decimal)res.get('grossAmountIPI');
            grp.grossAmountWOIPI = (Decimal)res.get('grossAmountWOIPI');
            grp.amountWTaxes = (Decimal)res.get('amountWTaxes'); //utilizar definição de AmountWTaxes
            groupSummary.add(grp);
            
        }                             
        
        system.debug(JSON.serialize(groupSummary));                       
        
        return JSON.serialize(groupSummary);        

    }
        
    @AuraEnabled
    public static string getNotTubes(Id orderId){
        
        Order__c o = [SELECT Id, ErrorMessageTxt__c, AccountLkp__c, AccountAreaSalesLkp__c, AccountAreaSalesLkp__r.ChannelLkp__c, OrderTypeLkp__c FROM Order__c WHERE Id =: orderId];                
        
        AggregateResult [] groupTotals = [SELECT	ProductLkp__r.MaterialGroup__c groupCode,                                                                                                        
                                          Count(Id) itemCount,
                                          SUM(TotalNetWeightKgNmb__c) weight,
                                          SUM(ValueROBFml__c) grossAmountIPI,
                                          SUM(ValueROBNoIPIFml__c) grossAmountWOIPI,
                                          SUM(ValueROLFml__c) amountWTaxes                                        				
                                          FROM		OrderItem__c
                                          WHERE	OrderMdt__c =: orderId
                                          AND ProductLkp__r.MaterialGroup__c != '01'
                                          AND ProductLkp__r.MaterialGroup__c != '06'
                                          GROUP BY	ProductLkp__r.MaterialGroup__c
                                         ];

        List <Product2> orderProducts = [SELECT MaterialGroup__c, toLabel(MaterialGroup__c) groupDesc
                                         FROM Product2
                                         WHERE Id IN (SELECT ProductLkp__c 
                                                      FROM OrderItem__c 
                                                      WHERE OrderMdt__c =: orderId
                                                     )
                                        ];
        
        Map<String,String> groupMap = new Map<String,String>();
        
        for (Product2 prod : orderProducts){
            groupMap.put(prod.MaterialGroup__c, (string)prod.get('groupDesc'));
        }
        
        system.debug('Grupos: '+ groupMap);

        prodNotTubes notTubes = new prodNotTubes();

        for (AggregateResult res: groupTotals){            
            prodGroup grp = new prodGroup();            
            grp.groupCode = (String)res.get('groupCode');
            grp.groupDscrp = groupMap.get(grp.groupCode);
            grp.itemCount = (Integer)res.get('itemCount');
            grp.weight = (Decimal)res.get('weight');
            grp.grossAmountIPI = (Decimal)res.get('grossAmountIPI');
            grp.grossAmountWOIPI = (Decimal)res.get('grossAmountWOIPI');
            grp.amountWTaxes = (Decimal)res.get('amountWTaxes'); //utilizar definição de AmountWTaxes            

            if(grp.groupCode != '01' && grp.groupCode != '06'){
                notTubes.notTubesItemCount 	+= (grp.itemCount != null ? grp.itemCount : 0);
                notTubes.notTubesWeight 	+= (grp.weight != null ? grp.weight : 0);
                notTubes.notTubesROB 		+= (grp.grossAmountIPI != null ? grp.grossAmountIPI : 0);
                notTubes.notTubesROBwoIPI 	+= (grp.grossAmountWOIPI != null ? grp.grossAmountWOIPI : 0);                
                notTubes.notTubesROL 		+= (grp.amountWTaxes != null ? grp.amountWTaxes : 0);                 
            }            
        }

        system.debug(JSON.serialize(notTubes));
        
		return JSON.serialize(notTubes);		        
        
    }
    
    
    private class prodSystem{
        public string systemCode;
        public string systemDscrp;
        public integer itemCount;
        public decimal weight;
        public decimal grossAmountIPI;
        public decimal grossAmountWOIPI;
        public decimal amountWTaxes;            
    }
    
    
    private class prodGroup{
        public string groupCode;
        public string groupDscrp;
        public integer itemCount;
        public decimal weight;
        public decimal grossAmountIPI;
        public decimal grossAmountWOIPI;
        public decimal amountWTaxes;		       
    }
    
    private class prodNotTubes{
        public integer notTubesItemCount 	= 0;
        public decimal notTubesWeight 		= 0;
        public decimal notTubesROBwoIPI 	= 0;
        public decimal notTubesROB 			= 0;
        public decimal notTubesROL 			= 0; 
    }
    
}