force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/BlockedItem__c/BlockedItem__c.object-meta.xml
<CustomObject>
    <label>Parametrização</label>
    <nameField>
        <displayFormat>Param-{000000000}</displayFormat>
        <label>Nome de Itens Bloqueados</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BlockedItem__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BlockedItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Itens_Bloqueados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/recordTypes/MasterPackageRT.recordType-meta.xml
<RecordType>
    <fullName>MasterPackageRT</fullName>
    <active>true</active>
    <description>Indica que para esse material/cliente existe uma embalagem master</description>
    <label>Embalagem Master</label>
</RecordType>

force-app/main/default/objects/BlockedItem__c/recordTypes/PackageSeparationRT.recordType-meta.xml
<RecordType>
    <fullName>PackageSeparationRT</fullName>
    <active>true</active>
    <description>Bloqueio quebra de embalagem por tipo de ordem canal</description>
    <label>Quebra de Embalagem</label>
</RecordType>

force-app/main/default/objects/CatalogElement__c/CatalogElement__c.object-meta.xml
<CustomObject>
    <description>[###][CatalogElement__c] Elementos de Catálogo de Preços, para montar a hierarquia</description>
    <label>Elemento de Catálogo</label>
    <nameField>
        <label>Nome do Elemento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Elementos de Catálogo</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CatalogElement__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <externalId>true</externalId>
    <label>ID Customizado</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/ImageFml__c.field-meta.xml
<CustomField>
    <fullName>ImageFml__c</fullName>
    <formula>&quot;/servlet/servlet.FileDownload?file=&quot;&amp;ImageIdTxt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/IndexNmb__c.field-meta.xml
<CustomField>
    <fullName>IndexNmb__c</fullName>
    <description>Indica a ordem que os elementos serão exibidos</description>
    <inlineHelpText>Ordem de exibição dos elementos no catálogo. Exibidos em ordem crescente, nulos por último</inlineHelpText>
    <label>Ordem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/ParentElementLkp__c.field-meta.xml
<CustomField>
    <fullName>ParentElementLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Elemento Pai</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Elementos Filhos</relationshipLabel>
    <relationshipName>ChildElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CatalogElement__c/fields/PricebookLkp__c.field-meta.xml
<CustomField>
    <fullName>PricebookLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catálogo de Preços</label>
    <referenceTo>Pricebook__c</referenceTo>
    <relationshipLabel>Elementos de Catálogo</relationshipLabel>
    <relationshipName>CatalogElements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ComplementaryProduct__c/ComplementaryProduct__c.object-meta.xml
<CustomObject>
    <label>Produto Complementar</label>
    <nameField>
        <displayFormat>PC-{0000000}</displayFormat>
        <label>Produto Complementar</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos Complementares</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ComplementaryProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos Complementares</relationshipLabel>
    <relationshipName>ComplementariesProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ElementProduct__c/ElementProduct__c.object-meta.xml
<CustomObject>
    <description>[###][ElementProduct__c] Join entre elementos e produtos, para configurar a exibição do Catálogo de Preços</description>
    <label>Produto do Elemento</label>
    <nameField>
        <displayFormat>PE-{000000}</displayFormat>
        <label>Produto do Elemento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos do Elemento</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ElementProduct__c/fields/CatalogElementLkp__c.field-meta.xml
<CustomField>
    <fullName>CatalogElementLkp__c</fullName>
    <label>Elemento de Catálogo</label>
    <referenceTo>CatalogElement__c</referenceTo>
    <relationshipLabel>Produtos do Elemento</relationshipLabel>
    <relationshipName>ElementProducts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ElementProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Elementos de Catálogo</relationshipLabel>
    <relationshipName>ElementProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/ErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageTxt__c</fullName>
    <description>Mensagens de erro na integração</description>
    <label>Mensagem de Erro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PricebookLkp__c.field-meta.xml
<CustomField>
    <fullName>PricebookLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Catálogo de Produtos</label>
    <referenceTo>Pricebook__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/recordTypes/Order.recordType-meta.xml
<RecordType>
    <fullName>Order</fullName>
    <active>true</active>
    <label>Ordem</label>
</RecordType>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessageTxt__c</fullName>
    <description>Mensagens de erro na integração</description>
    <label>Mensagens de Erro</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <description>Preenchido via Workflow</description>
    <label>Código do Produto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderType__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id Customizado</label>
    <length>4</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricebook__c/Pricebook__c.object-meta.xml
<CustomObject>
    <description>[a0O][Pricebook__c] Catálogo Personalizado</description>
    <label>Catálogo de Produtos</label>
    <nameField>
        <label>Nome do Catálogo</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catálogos de Produtos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Pricebook__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Id Customizado</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Pricebook__c/fields/IsActiveBln__c.field-meta.xml
<CustomField>
    <fullName>IsActiveBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indica se o catálogo está ativo</description>
    <label>Ativo?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImageExtensionTxt__c.field-meta.xml
<CustomField>
    <fullName>ImageExtensionTxt__c</fullName>
    <label>Imagem Extensão</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImageFml__c.field-meta.xml
<CustomField>
    <fullName>ImageFml__c</fullName>
    <formula>&quot;/servlet/servlet.FileDownload?file=&quot;&amp;ImageIdTxt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>URL da Imagem</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ImageTxt__c.field-meta.xml
<CustomField>
    <fullName>ImageTxt__c</fullName>
    <label>Imagem Base64</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/InstructionsTxt__c.field-meta.xml
<CustomField>
    <fullName>InstructionsTxt__c</fullName>
    <label>Instruções de Instalação</label>
    <length>100000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/StandardPackageAmountNmb__c.field-meta.xml
<CustomField>
    <fullName>StandardPackageAmountNmb__c</fullName>
    <description>Quantidade de itens por embalagem padrão</description>
    <label>Quantidade da Embalagem Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuggestedProduct__c/SuggestedProduct__c.object-meta.xml
<CustomObject>
    <description>[a1B][SuggestedProduct__c]</description>
    <label>Produto Sugerido</label>
    <nameField>
        <displayFormat>PS-{0000000}</displayFormat>
        <label>Produto Sugerido</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos Sugeridos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SuggestedProduct__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos Sugeridos</relationshipLabel>
    <relationshipName>SuggestedProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PricebookComponentController.cls
public  without sharing class PricebookComponentController {
    
    @AuraEnabled
    public static Product2 getProduct(Id productId){
        Product2 p = [SELECT Id, Name, ProductCodeTxt__c, InstructionsTxt__c, ImageFml__c, ImageTxt__c, ImageExtensionTxt__c FROM Product2 WHERE Id = :productId];
        return p;
    }
    
    @AuraEnabled
    public static List<CatalogElement__c> getElementList(Id pricebookId, Id orderId, Id elementId){
        Id pbId;        
        if(pricebookId != null)
            pbId = pricebookId;
        if(orderId != null){
            Order__c o = [SELECT PricebookLkp__c FROM Order__c WHERE Id = :orderId];
            pbId = o.PricebookLkp__c;
        }
        if(pbId == null && elementId == null)
            return new List<CatalogElement__c>();
        if(elementId == null ){
            return [SELECT Id, Name
                    FROM CatalogElement__c 
                    WHERE PricebookLkp__c = :pbId
                    ORDER BY IndexNmb__c ASC NULLS LAST, Name
                   ];
        }
        else{
            return [SELECT Id, Name
                    FROM CatalogElement__c 
                    WHERE ParentElementLkp__c = :elementId
                    ORDER BY IndexNmb__c ASC NULLS LAST, Name
                   ];
        }
    }
    
    @AuraEnabled
    public static List<Product2> getProducts(Id pricebookId, Id elementId, String searchString, Id orderId){
        Id pbId;        
        if(pricebookId != null)
            pbId = pricebookId;
        if(orderId != null){
            Order__c o = [SELECT PricebookLkp__c FROM Order__c WHERE Id = :orderId];
            pbId = o.PricebookLkp__c;
        }
        if(pbId == null && elementId == null)
            return new List<Product2>();
        system.debug('pbId: ' + pbId);
        system.debug('elementId: ' + elementId);
        system.debug('searchString: ' + searchString);
        String query = 'SELECT Id, Name, ProductCodeTxt__c, StandardPackageAmountNmb__c ';
        query += 'FROM Product2 ';
        query += 'WHERE ID IN ';
        if (elementId == null){
            query += '(SELECT ProductLkp__c FROM ElementProduct__c WHERE CatalogElementLkp__r.PricebookLkp__c = \''+ pbId +'\') ';
        }
        else {
            query += '(SELECT ProductLkp__c FROM ElementProduct__c WHERE CatalogElementLkp__c = \''+ elementId +'\') ';
        }
        if(searchString != null){
            query += 'AND (Name LIKE \'%' + searchString + '%\' OR ProductCodeTxt__c LIKE \'%' + searchString + '%\') ';
        }
        query += 'ORDER BY Name';
        system.debug(query);
        return Database.query(query);
    }
    
    @AuraEnabled
    public static String findProductsPricebook(Id pricebookId){
        Pricebook__c pb = [SELECT Id, IsActiveBln__c FROM Pricebook__c WHERE Id = :pricebookId];
        if(pb.IsActiveBln__c == true){
            return 'Catálogo já ativado';
        }
        Map<Id, CatalogElement__c> mapElem = new Map<Id, CatalogElement__c>([SELECT Id, PricebookLkp__c, (SELECT Id, ProductLkp__c FROM ElementProducts__r), (SELECT Id FROM ChildElements__r)
                                  FROM CatalogElement__c WHERE PricebookLkp__c = :pricebookId OR ParentElementLkp__c != null]);
        for(CatalogElement__c elem : mapElem.Values()){
            if(elem.PricebookLkp__c == pricebookId){
                findProducts(elem.Id, mapElem);
            }
        }
        pb.IsActiveBln__c = true;
        try{
            update pb;
            return 'SUCCESS';
        }
        catch(Exception e){
            return e.getMessage();
        }
    }
    
    public static List<ElementProduct__c> findProducts(Id elementId, Map<Id, CatalogElement__c> mapElem){
        CatalogElement__c elem = mapElem.get(elementId);
        List<ElementProduct__c> listElem = new List<ElementProduct__c>();
        List<ElementProduct__c> listElemCreate = new List<ElementProduct__c>();
        
        if(elem.ElementProducts__r.size() != 0){
            listElem.addAll(elem.ElementProducts__r);
            return listElem;
        }
        else{
            for(CatalogElement__c child : elem.ChildElements__r){
                listElem.addAll(findProducts(child.Id, mapElem));
            }
            for(ElementProduct__c newElem : listElem){
                listElemCreate.add(new ElementProduct__c(CatalogElementLkp__c = elementId, ProductLkp__c = newElem.ProductLkp__c));
            }
            insert listElemCreate;
            return listElemCreate;
        }
        
    }
    
    @AuraEnabled
    public static String addProduct(Id idProduct, Id idOrder, Decimal amount, Boolean usePackage){
        Order__c o = [SELECT Id, ErrorMessageTxt__c, AccountLkp__c, CustomIdTxt__c,
                      AccountAreaSalesLkp__r.ChannelLkp__c, OrderTypeLkp__c, OrderTypeLkp__r.OrderIrrigationBln__c,
                      (SELECT Id, OrderQuantityNmb__c FROM Itens_da_Ordem__r WHERE ProductLkp__c = :idProduct)
                      FROM Order__c WHERE Id = :idOrder];
        
        List<BlockedItem__c> listBlock = [SELECT Id, 
                                          MasterPackageAmountNmb__c, 
                                          RecordType.DeveloperName 
                                          FROM BlockedItem__c 
                                          WHERE 
                                          (ProductLkp__c = :idProduct AND AccountLkp__c = :o.AccountLkp__c AND RecordType.DeveloperName = 'MasterPackageRT') OR
                                          (ChannelPvcLkp__c = :o.AccountAreaSalesLkp__r.ChannelLkp__c AND OrderTypeLkp__c = :o.OrderTypeLkp__c AND RecordType.DeveloperName = 'PackageSeparationRT')
                                         ];
                
        Product2 prod = [SELECT Id, StandardPackageAmountNmb__c, UMTxt__c, IrrigationItemBln__c, ProductCodeTxt__c FROM Product2 WHERE Id = :idProduct];
        Integer packageAmt = (prod.StandardPackageAmountNmb__c != null && prod.StandardPackageAmountNmb__c != 0) ? Integer.valueOf(prod.StandardPackageAmountNmb__c) : 1;
        
        if(listBlock.size() > 0){
            for(BlockedItem__c block : listBlock){
                if(block.MasterPackageAmountNmb__c != null){
                    packageAmt = Integer.valueOf(block.MasterPackageAmountNmb__c);
                    break;
                }
                else if(block.RecordType.DeveloperName == 'PackageSeparationRT' && prod.UMTxt__c != 'M') packageAmt = 1;
            }
        }
        
        if(prod.ProductCodeTxt__c == '20109' || prod.ProductCodeTxt__c == '20159')
            packageAmt = 1;
        
        try{
            amount = Integer.valueOf(amount) * ((usePackage && prod.StandardPackageAmountNmb__c !=  0) ? (Integer)prod.StandardPackageAmountNmb__c : 1);
            
        	Integer division = amount.intValue() / packageAmt; 
            
            
            if(o.OrderTypeLkp__r.OrderIrrigationBln__c && !prod.IrrigationItemBln__c){
                return 'Item não está disponível para ordens de Irrigação.';
            }
            if(division * packageAmt != amount){
                return 'Item sendo vendido fora da Embalagem Padrão/Master. Favor negociar em múltiplos de ' + packageAmt;
            }
        }
        catch(Exception e){
            System.debug('EXCEPTION');
            return 'Ocorreu um erro ao adicionar o item. Digite uma quantidade válida.';              
        }
        
        OrderItem__c oItem = new OrderItem__c ();
        if(o.Itens_da_Ordem__r.size() == 0){
            oItem.OrderQuantityNmb__c = amount;
            oItem.ProductLkp__c = idProduct;
            oItem.OrderMdt__c = idOrder;
            oItem.LiquidNmb__c = Integer.valueOf(amount);
        }
        else{
            //oItem = o.Itens_da_Ordem__r[0];
            //oItem.OrderQuantityNmb__c += Integer.valueOf(amount);
            return 'Produto já inserido no pedido';
        }
        
        if(o.ErrorMessageTxt__c != null && o.CustomIDTxt__c == null){
            return o.ErrorMessageTxt__c;
        }
        
        Savepoint sp = Database.setSavepoint();
        
        try{
            upsert oItem;
            if(!Test.isRunningTest()){
                OrderIntegrationUtils.createItemOnSAPFuture(idOrder, oItem.Id);
            }
            o.ShippingSplitDoneBln__c = false;
            update o;
            
            List<ComplementaryProduct__c> listComp = [SELECT ID, ProductLkp__c, ComplementaryLkp__c, ComplementaryLkp__r.ProductCodeTxt__c, ComplementaryLkp__r.Name 
                                                      FROM ComplementaryProduct__c
                                                      WHERE ProductLkp__c = :idProduct];
            
            String compProduct = ':';
            if(listComp.size() > 0){
               compProduct = ':O produto '+listComp[0].ComplementaryLkp__r.ProductCodeTxt__c+' é complementar do item inserido'; 
            }
            
            return 'SUCCESS'+compProduct;
        }
        catch(Exception e){
            Database.rollback( sp );
            return e.getMessage() + ': ' + e.getStackTraceString();
        }
        
    }
    
    
    @AuraEnabled
    public static List<Product2> suggestedProduct(Id orderId){
        Order__c ord =[SELECT 
                       AccountLkp__r.ChannelLkp__c,
                       AccountAreaSalesLkp__r.ChannelLkp__c,
                       AccountAreaSalesLkp__r.SalesOfficeTxt__c,
                       SuggestedDoneBln__c
                       FROM Order__c
                       Where Id =: orderId];
        
        if(!ord.SuggestedDoneBln__c){
            ord.SuggestedDoneBln__c = true;
            update ord;
        }
        
        return [SELECT ID, 
                Name,
                StandardPackageAmountNmb__c,
                ProductCodeTxt__c
                FROM Product2 
                WHERE Id IN 
                (SELECT ProductLkp__c 
                 FROM SuggestedProduct__c 
                 WHERE ChannelLkp__c = :ord.AccountAreaSalesLkp__r.ChannelLkp__c
                AND SalesOfficeTxt__c = :ord.AccountAreaSalesLkp__r.SalesOfficeTxt__c) 
                AND ID NOT IN 
                (SELECT ProductLkp__c 
                 FROM OrderItem__c 
                 WHERE OrderMdt__c = :orderId)
               ORDER BY Name];
    }
    
    @AuraEnabled
    public static List<Product2> productTypeList(ID orderId, String listType){
        List<Product2> emptyList = new List<Product2>();
        system.debug('listType: ' + listType);
        if(listType=='CPE'){
            return [SELECT ID, 
                    Name,
                    StandardPackageAmountNmb__c,
                    ProductCodeTxt__c
                    FROM Product2
                    WHERE SpecialProductBln__c = True
                    ORDER BY Name];
        }
    
        else if(listType=='MIXIrriga'){
            return [SELECT ID, 
                    Name,
                    StandardPackageAmountNmb__c,
                    ProductCodeTxt__c
                    FROM Product2
                    WHERE IrrigationBln__c = True
                    ORDER BY Name];
        }
    
        else if(listType=='Irrigation'){
            return [SELECT ID, 
                    Name,
                    StandardPackageAmountNmb__c,
                    ProductCodeTxt__c
                    FROM Product2
                    WHERE IrrigationItemBln__c = True
                    ORDER BY Name];
        }

        else if(listType=='Release'){
            return [SELECT ID, 
                    Name,
                    StandardPackageAmountNmb__c,
                    ProductCodeTxt__c
                    FROM Product2
                    WHERE ReleaseBln__c = True
                    ORDER BY Name];
        }	
        else if(listType=='Complementary'){
            return complementaryProduct(orderId);
        }
        else if(listType=='MasterPackage'){
            Order__c OrderAccount = [SELECT ID,
                                     AccountLkp__c
                                     FROM Order__c
                                     WHERE ID =: orderId Limit 1];
            return [SELECT ID, 
                    Name,
                    StandardPackageAmountNmb__c,
                    ProductCodeTxt__c
                    FROM Product2
                    WHERE ID IN (SELECT ProductLkp__C FROM BlockedItem__c WHERE AccountLkp__c = :OrderAccount.AccountLkp__c AND RecordType.DeveloperName = 'MasterPackageRT')
                    ORDER BY Name];
        }
        else{
            return emptyList;
        }
    }
    
    @AuraEnabled
    public static List<Product2> complementaryProduct(ID orderId){
        List<OrderItem__c> ordItems = [SELECT ID, ProductLkp__c
                                       FROM OrderItem__c
                                       WHERE OrderMdt__c =: orderId];
        List<ID> listExistingProds = new List<ID>();
        for(OrderItem__c oItem : ordItems){
            listExistingProds.add(oItem.ProductLkp__c);
        }
        
        List<ID> listComplementary = new List<ID>();
        for(ComplementaryProduct__c cmp : [
            SELECT ID, ProductLkp__c, ComplementaryLkp__c 
            FROM ComplementaryProduct__c
            WHERE ProductLkp__c IN :listExistingProds
            //OR ComplementaryLkp__c IN :listExistingProds
        ]){
            //listComplementary.add(cmp.ProductLkp__c);
            listComplementary.add(cmp.ComplementaryLkp__c);
        }
        
        return [SELECT ID, 
                Name,
                StandardPackageAmountNmb__c,
                ProductCodeTxt__c
                FROM Product2
                WHERE ID IN :listComplementary
                AND ID NOT IN :listExistingProds
               ORDER BY Name];
    }
    
}