force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/integ_CustomOperationSalesArea.cls
public with sharing class integ_CustomOperationSalesArea implements integ_IIntegrationOperation {
	
	public Object execute(List<SObject> recordList) {
		System.debug('*** integ_CustomOperationSalesArea::execute() ' + recordList);
		List<AccountAreaSales__c> accAreaSaleList = new List<AccountAreaSales__c>();
		accAreaSaleList.addAll((List<AccountAreaSales__c>)recordList);
		upsert accAreaSaleList CustomIdTxt__c;
		return accAreaSaleList;
	}
	
}