force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/SellerLkp__c.field-meta.xml
<CustomField>
    <fullName>SellerLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>Seller__c</referenceTo>
    <relationshipName>reas_de_vendas</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/CustomerSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço (Cliente)</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Nome de Pesquisa de Preço (Cliente)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço (Cliente)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSurvey__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de vendas</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipName>CustomerSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/fields/RemarkTxt__c.field-meta.xml
<CustomField>
    <fullName>RemarkTxt__c</fullName>
    <label>Observações</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/fields/TradeMktSurveyLkp__c.field-meta.xml
<CustomField>
    <fullName>TradeMktSurveyLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pesquisa de Preço</label>
    <referenceTo>TradeMktSurvey__c</referenceTo>
    <relationshipLabel>Pesquisas de Preço (Cliente)</relationshipLabel>
    <relationshipName>Pesquisas_do_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seller__c/Seller__c.object-meta.xml
<CustomObject>
    <description>[a0K][Seller__c] Objeto que irá representar um vendedor.</description>
    <label>Vendedor</label>
    <nameField>
        <label>Nome do Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyProduct__c/SurveyProduct__c.object-meta.xml
<CustomObject>
    <label>Produto da Pesquisa</label>
    <nameField>
        <displayFormat>PP-{00000000}</displayFormat>
        <label>Nome de Produto da Pesquisa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da Pesquisa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyProduct__c/fields/MaterialGroupFml__c.field-meta.xml
<CustomField>
    <fullName>MaterialGroupFml__c</fullName>
    <formula>IF(TEXT(ProductLkp__r.MaterialGroup__c) != null,
   CASE(
      TEXT(ProductLkp__r.MaterialGroup__c),
      &quot;01&quot;, &quot;Tubos&quot;, 
      &quot;02&quot;, &quot;Conexões&quot;,
      &quot;03&quot;, &quot;Acessórios&quot;, 
      &quot;04&quot;, &quot;Revenda&quot;, 
      &quot;05&quot;, &quot;Metálicos&quot;, 
      &quot;06&quot;, &quot;Reservatórios&quot;, 
      null
   ),
   CASE(
      TEXT(OtherMaterialGroupTxt__c),
      &quot;01&quot;, &quot;Tubos&quot;, 
      &quot;02&quot;, &quot;Conexões&quot;,
      &quot;03&quot;, &quot;Acessórios&quot;, 
      &quot;04&quot;, &quot;Revenda&quot;, 
      &quot;05&quot;, &quot;Metálicos&quot;, 
      &quot;06&quot;, &quot;Reservatórios&quot;, 
      null
   )
)</formula>
    <label>Grupo de Material</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/MaxPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>MaxPriceNmb__c</fullName>
    <label>Preço Máximo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/MinPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>MinPriceNmb__c</fullName>
    <label>Preço Mínimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/OtherSubsystemTxt__c.field-meta.xml
<CustomField>
    <fullName>OtherSubsystemTxt__c</fullName>
    <label>Outros - Subsistema</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Subsystem</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/ProductDescriptionFml__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionFml__c</fullName>
    <formula>IF(ProductLkp__c != null, ProductLkp__r.Name, OtherProductsTxt__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Descrição do Produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/SubsystemFml__c.field-meta.xml
<CustomField>
    <fullName>SubsystemFml__c</fullName>
    <formula>IF(TEXT(ProductLkp__r.ProductSubsystemTxt__c) != null, TEXT(ProductLkp__r.ProductSubsystemTxt__c), TEXT(OtherSubsystemTxt__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Subsistema</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyProduct__c/fields/TradeMktSurveyLkp__c.field-meta.xml
<CustomField>
    <fullName>TradeMktSurveyLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pesquisa de Preço</label>
    <referenceTo>TradeMktSurvey__c</referenceTo>
    <relationshipLabel>Produtos da Pesquisa</relationshipLabel>
    <relationshipName>Produtos_da_Pesquisa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/SurveyResult__c.object-meta.xml
<CustomObject>
    <label>Resultado da Pesquisa</label>
    <nameField>
        <displayFormat>RP-{00000000}</displayFormat>
        <label>Nome de Resultados da Pesquisa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resultados da Pesquisa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SurveyResult__c/fields/AttachmentRequiredBln__c.field-meta.xml
<CustomField>
    <fullName>AttachmentRequiredBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necessário Anexo</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/BrandTxt__c.field-meta.xml
<CustomField>
    <fullName>BrandTxt__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/ChannelTxt__c.field-meta.xml
<CustomField>
    <fullName>ChannelTxt__c</fullName>
    <formula>null</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Canal</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/CustomerSurveyLkp__c.field-meta.xml
<CustomField>
    <fullName>CustomerSurveyLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pesquisa de Preço (Cliente)</label>
    <referenceTo>CustomerSurvey__c</referenceTo>
    <relationshipLabel>Resultados da Pesquisa</relationshipLabel>
    <relationshipName>Resultados_da_Pesquisa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/MaterialGroupTxt__c.field-meta.xml
<CustomField>
    <fullName>MaterialGroupTxt__c</fullName>
    <label>Grupo de Material</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/PriceNmb__c.field-meta.xml
<CustomField>
    <fullName>PriceNmb__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/ProductDescriptionTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductDescriptionTxt__c</fullName>
    <label>Descrição do Produto</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/RemarkTxt__c.field-meta.xml
<CustomField>
    <fullName>RemarkTxt__c</fullName>
    <label>Observações</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/SubsystemTxt__c.field-meta.xml
<CustomField>
    <fullName>SubsystemTxt__c</fullName>
    <label>Subsistema</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SurveyResult__c/fields/SurveyProductLkp__c.field-meta.xml
<CustomField>
    <fullName>SurveyProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto da Pesquisa</label>
    <referenceTo>SurveyProduct__c</referenceTo>
    <relationshipLabel>Resultados da Pesquisa</relationshipLabel>
    <relationshipName>Resultados_da_Pesquisa</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TradeMktSurvey__c/TradeMktSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço</label>
    <nameField>
        <label>Nome de Pesquisa de Preço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TradeMktSurvey__c/fields/BrandsTxt__c.field-meta.xml
<CustomField>
    <fullName>BrandsTxt__c</fullName>
    <label>Marcas</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Brands</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/TradeMktSurvey__c/fields/OtherBrandsTxt__c.field-meta.xml
<CustomField>
    <fullName>OtherBrandsTxt__c</fullName>
    <inlineHelpText>Caso o concorrente não esteja listado nas opções anteriores, insira o nome dos outros concorrentes separados por &quot;;&quot;.</inlineHelpText>
    <label>Outras Marcas</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AddSurveyResult.cls
public class AddSurveyResult {
    
    public CustomerSurvey__c surveyCustomer {get;set;}
    public CustomerSurvey__c refSurveyCustomer;
    public TradeMktSurvey__c survey;
    public List <SurveyResult__c> addResult {get;set;}    
    public List <SurveyResult__c> resultList {get;set;}
    public List <SurveyProduct__c> surveyProducts;
    public List <Product2> productNames;
    public Set <SurveyResult__c> resultSet {get;set;}
    public integer rowNumber;
    public string resultMsgStr;
    
    public AddSurveyResult(ApexPages.StandardController controller) {
        
        Map<String, Id> mapSurveyId = new Map<String, Id>();
        Map<String, Decimal> mapSurveyTotal = new Map<String, Decimal>();
        Map<String, String> mapSurveyRemark = new Map<String, String>();        
        
        refSurveyCustomer = (CustomerSurvey__c) controller.getRecord();
        this.surveyCustomer = [SELECT Id, /*AccountLkp__c, */TradeMktSurveyLkp__c, AccountAreaSalesLkp__c, AccountAreaSalesLkp__r.SellerLkp__r.UserLkp__c FROM CustomerSurvey__c WHERE Id =: refSurveyCustomer.Id];
               
        surveyProducts = [SELECT Id, ProductDescriptionFml__c, MaterialGroupFml__c, SubsystemFml__c, TradeMktSurveyLkp__c, MinPriceNmb__c, MaxPriceNmb__c 
                          FROM SurveyProduct__c 
                          WHERE TradeMktSurveyLkp__c =: surveyCustomer.TradeMktSurveyLkp__c                         
                         ];        
        
        resultList = [SELECT Id, ProductDescriptionTxt__c, BrandTxt__c, CustomerSurveyLkp__c, PriceNmb__c, RemarkTxt__c, ChannelTxt__c, AttachmentRequiredBln__c
                      FROM SurveyResult__c 
                      WHERE CustomerSurveyLkp__c =: surveyCustomer.id
                      ];                
        
        for(SurveyResult__c res : resultList){
            mapSurveyId.put(res.ProductDescriptionTxt__c + res.BrandTxt__c, res.Id);
            mapSurveyTotal.put(res.ProductDescriptionTxt__c + res.BrandTxt__c, res.PriceNmb__c);
            mapSurveyRemark.put(res.ProductDescriptionTxt__c + res.BrandTxt__c, res.RemarkTxt__c);			         
        }
        
        map<string,string> mapSubsystems = new map<string,string>();        
        
        Schema.DescribeFieldResult fieldResult = SurveyProduct__c.OtherSubsystemTxt__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();                
        
        for(Schema.PicklistEntry subsystem: ple){
            mapSubsystems.put(subsystem.getValue(),subsystem.getLabel());
        }
        
        
        resultList = new List<SurveyResult__c>();   
        
        survey = [SELECT BrandsTxt__c, OtherBrandsTxt__c 
                  FROM TradeMktSurvey__c 
              	  WHERE Id =: surveyCustomer.TradeMktSurveyLkp__c                 
        		];
        
        list<String> availableBrands = new List<String>();
        List<String> otherBrands = new List<String>();
		
        if(survey.BrandsTxt__c != null){        
        	availableBrands = survey.BrandsTxt__c.split(';');                       
        }
		system.debug(availableBrands);
        
        if(survey.OtherBrandsTxt__c != null){
            otherBrands = survey.OtherBrandsTxt__c.split(';');            
            
            for(integer j=0; j < otherBrands.size(); j++){
                if(otherBrands[j] == '' || otherBrands[j] == null)
                    otherBrands.remove(j);
            }
			           
        }
        
        list<String> brands = new list<String>();        
                
        brands.addAll(availableBrands);
        
        brands.addAll(otherBrands);
                 
        brands.sort();
        
        if(surveyProducts.size()>0){
            for(SurveyProduct__c sP: surveyProducts){
                if(brands.size()>0){
                    for(string brnd: brands){                        
                        SurveyResult__c result = new SurveyResult__c();
                        if(mapSurveyId.containsKey(sP.ProductDescriptionFml__c + brnd)){
                            result.Id = mapSurveyId.get(sP.ProductDescriptionFml__c + brnd);
                            result.PriceNmb__c = mapSurveyTotal.get(sP.ProductDescriptionFml__c + brnd);
                            result.RemarkTxt__c = mapSurveyRemark.get(sP.ProductDescriptionFml__c + brnd);							                           
                        }
						result.SurveyProductLkp__r = sP;
						result.SurveyProductLkp__c = sP.Id;
                        if(result.PriceNmb__c > result.SurveyProductLkp__r.MaxPriceNmb__c || result.PriceNmb__c < result.SurveyProductLkp__r.MinPriceNmb__c ){
                        	result.AttachmentRequiredBln__c = TRUE;
                        } else {
                            result.AttachmentRequiredBln__c = FALSE;
                        }
                        result.CustomerSurveyLkp__c = surveyCustomer.Id;
                        result.MaterialGroupTxt__c = sP.MaterialGroupFml__c;
                        result.ProductDescriptionTxt__c = sP.ProductDescriptionFml__c;
                        result.SubsystemTxt__c = mapSubsystems.get(sP.SubsystemFml__c);
                        result.BrandTxt__c = brnd;
						result.OwnerId = surveyCustomer.AccountAreaSalesLkp__r.SellerLkp__r.UserLkp__c;                        
                        resultList.add(result);                     
                    }
                }
            }
        }
                
    }
/*
    public Attachment attachment{
        get {
            if (attachment == null)
                attachment = new Attachment();
            return attachment;
        }
        set;
    }
    
    public PageReference upload() {
        
        attachment.OwnerId = UserInfo.getUserId();
        attachment.ParentId = refSurveyCustomer.Id; // the record the file is attached to
        attachment.IsPrivate = true;
        
        try {
            insert attachment;
        } catch (DMLException e) {
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.ERROR,'Ocorreu um erro durante o carregamento do arquivo.'));
            return null;
        } finally {
            attachment = new Attachment(); 
        }
        
        ApexPages.addMessage(new ApexPages.message(ApexPages.severity.CONFIRM,'O arquivo foi carregado com sucesso!'));
        return null;
    }
*/        
    
    public void doSave() {                
        List<SurveyResult__c> listOutOfRange = new List<SurveyResult__c>();
        
        for(SurveyResult__c res: resultList){
            if(res.PriceNmb__c > res.SurveyProductLkp__r.MaxPriceNmb__c || res.PriceNmb__c < res.SurveyProductLkp__r.MinPriceNmb__c ){
                listOutOfRange.add(res);
                res.AttachmentRequiredBln__c = TRUE;
            } else {
                res.AttachmentRequiredBln__c = FALSE;
            }            
        }
        //List<ContentDocumentLink> listSurveyContLink = [SELECT Id FROM ContentDocumentLink WHERE LinkedEntityId =: refSurveyCustomer.Id];
        //List<Attachment> listSurveyAtt = [SELECT Id FROM Attachment WHERE ParentId =: refSurveyCustomer.Id];
		//System.debug(listSurveyAtt);        
        
        try{                      
            //if(listSurveyAtt.isEmpty() && listSurveyContLink.isEmpty()){
            //    resultMsgStr = ' Para que os resultados da pesquisa sejam registrados, é necessário anexar ao menos uma foto.';
            //    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,resultMsgStr));                
            //} else {
                
                upsert resultList;           
                
                if(listOutOfRange.size()>0){
                    resultMsgStr = ' Existem produtos com preço fora da faixa esperada. Por favor, revise o preço inserido ou inclua uma foto como anexo para comprovação.';
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.WARNING,resultMsgStr));                
                } else {            
                    resultMsgStr = ' Os resultados da pesquisa preenchidos foram registrados!';
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.CONFIRM,resultMsgStr));
                }
            //}
        }
        catch (Exception ex){
            ApexPages.addMessages(ex);            
        }
    }    
}