force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSurvey__c/CustomerSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço (Cliente)</label>
    <nameField>
        <displayFormat>PC-{00000000}</displayFormat>
        <label>Nome de Pesquisa de Preço (Cliente)</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço (Cliente)</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerSurvey__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Área de vendas</label>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipName>CustomerSurveys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/fields/LimitDateDte__c.field-meta.xml
<CustomField>
    <fullName>LimitDateDte__c</fullName>
    <label>Data Limite</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Incompleta</fullName>
                <default>true</default>
                <label>Incompleta</label>
            </value>
            <value>
                <fullName>Completa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CustomerSurvey__c/fields/TradeMktSurveyLkp__c.field-meta.xml
<CustomField>
    <fullName>TradeMktSurveyLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pesquisa de Preço</label>
    <referenceTo>TradeMktSurvey__c</referenceTo>
    <relationshipLabel>Pesquisas de Preço (Cliente)</relationshipLabel>
    <relationshipName>Pesquisas_do_Cliente</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/TradeMktSurvey__c/TradeMktSurvey__c.object-meta.xml
<CustomObject>
    <label>Pesquisa de Preço</label>
    <nameField>
        <label>Nome de Pesquisa de Preço</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pesquisas de Preço</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PendingActions.cls
public class PendingActions {
    public AccountAreaSales__c accAreaSales 	{get;set;}
    public AccountAreaSales__c refAccAreaSales	{get;set;}
	public List<CustomerSurvey__c> pendingCustomerSurveys {get;set;}
    
    public PendingActions(ApexPages.StandardController controller){
       	refAccAreaSales = (AccountAreaSales__c)controller.getRecord();
        this.accAreaSales = [SELECT Id 
                             FROM 	AccountAreaSales__c 
                             WHERE 	Id =: refAccAreaSales.Id];
        
        pendingCustomerSurveys = [SELECT 	Id, Name, LimitDateDte__c, StatusTxt__c, TradeMktSurveyLkp__c, TradeMktSurveyLkp__r.Name 
                                  FROM		CustomerSurvey__c 
                                  WHERE 	AccountAreaSalesLkp__c =: accAreaSales.Id 
                                  AND 		StatusTxt__c = 'Incompleta' 
                                  //AND 		LimitDateDte__c >: system.today()
                                 ];
    }

}