force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Organização de vendas</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0143</fullName>
            </value>
            <value>
                <fullName>AM01</fullName>
            </value>
            <value>
                <fullName>0099</fullName>
            </value>
            <value>
                <fullName>0141</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <description>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</description>
    <externalId>true</externalId>
    <inlineHelpText>CONCATENAÇÃO:
Código cliente + Código organização de vendas + Código canal de distribuição + Código setor atividade</inlineHelpText>
    <label>ID customizado</label>
    <length>26</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/OfflinePrices__c.object-meta.xml
<CustomObject>
    <description>Tabela de preços do Offline</description>
    <label>Preços Offline</label>
    <nameField>
        <label>Nome de Preços Offline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Offline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfflinePrices__c/fields/CustomIdTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIdTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id Customizado</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Preços Offline</relationshipLabel>
    <relationshipName>ProductLkp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OfflinePrices__c/fields/UnitPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceNmb__c</fullName>
    <description>Valor Bruto sem IPI, sem ICMS</description>
    <label>Valor Bruto s/ IPI</label>
    <precision>18</precision>
    <required>true</required>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountReceiverLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountReceiverLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Caso seja deixado em branco, será utilizada a conta Emissor</inlineHelpText>
    <label>Recebedor mercadoria</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>1 AND (2 OR 3)</booleanFilter>
        <filterItems>
            <field>Account.PartnerTypeTxt__c</field>
            <operation>equals</operation>
            <value>Recebedor</value>
        </filterItems>
        <filterItems>
            <field>Account.ParentId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <filterItems>
            <field>$Source.AccountLkp__c</field>
            <operation>equals</operation>
            <value/>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recebedor mercadoria</relationshipLabel>
    <relationshipName>Ordens1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CodeSalesOrganizationTxt__c.field-meta.xml
<CustomField>
    <fullName>CodeSalesOrganizationTxt__c</fullName>
    <label>Código organização de vendas</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Número da Ordem SAP</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Order__c/fields/IPITotalValueNmb__c.field-meta.xml
<CustomField>
    <fullName>IPITotalValueNmb__c</fullName>
    <label>Total IPI</label>
    <summarizedField>OrderItem__c.ValueIPI__c</summarizedField>
    <summaryForeignKey>OrderItem__c.OrderMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/NetWeightKgNmb__c.field-meta.xml
<CustomField>
    <fullName>NetWeightKgNmb__c</fullName>
    <label>Peso Líquido (Kg)</label>
    <summarizedField>OrderItem__c.TotalNetWeightKgNmb__c</summarizedField>
    <summaryForeignKey>OrderItem__c.OrderMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderNumberTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderNumberTxt__c</fullName>
    <label>Número do pedido do cliente</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeTxt__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeTxt__c</fullName>
    <label>Código do Tipo de ordem</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PaymentTermLkp__c.field-meta.xml
<CustomField>
    <fullName>PaymentTermLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de Pagamento</label>
    <referenceTo>PaymentTerm__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/PriceExpirationFml__c.field-meta.xml
<CustomField>
    <fullName>PriceExpirationFml__c</fullName>
    <formula>DateValue(CreatedDate) + 15</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Validade Preços</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/QuotationBln__c.field-meta.xml
<CustomField>
    <fullName>QuotationBln__c</fullName>
    <formula>TEXT(OrderStatusTxt__c) = &apos;Rascunho&apos; ||
TEXT(OrderStatusTxt__c) = &apos;InApproval&apos; ||
TEXT(OrderStatusTxt__c) = &apos;Approved&apos; ||
TEXT(OrderStatusTxt__c) = &apos;SentToSAP&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cotação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalLiquidPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalLiquidPriceNmb__c</fullName>
    <label>Total do Pedido Sem IPI</label>
    <summarizedField>OrderItem__c.ValueROBNoIPIFml__c</summarizedField>
    <summaryForeignKey>OrderItem__c.OrderMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalPriceNmb__c</fullName>
    <label>Total do Pedido</label>
    <summarizedField>OrderItem__c.ValueROBFml__c</summarizedField>
    <summaryForeignKey>OrderItem__c.OrderMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/TotalSTValueNmb__c.field-meta.xml
<CustomField>
    <fullName>TotalSTValueNmb__c</fullName>
    <label>Total Subs. Tributária do Pedido</label>
    <summarizedField>OrderItem__c.ValueST__c</summarizedField>
    <summaryForeignKey>OrderItem__c.OrderMdt__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/CustomIDTxt__c.field-meta.xml
<CustomField>
    <fullName>CustomIDTxt__c</fullName>
    <externalId>true</externalId>
    <label>Id customizado</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/IPIPercentFml__c.field-meta.xml
<CustomField>
    <fullName>IPIPercentFml__c</fullName>
    <formula>ValueIPI__c / ValueROBFml__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>% IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/IPIValueFml__c.field-meta.xml
<CustomField>
    <fullName>IPIValueFml__c</fullName>
    <formula>IF ((LiquidIPINmb__c - LiquidNmb__c)&gt;0,(LiquidIPINmb__c - LiquidNmb__c)*  OrderQuantityNmb__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ItemTotalFml__c.field-meta.xml
<CustomField>
    <fullName>ItemTotalFml__c</fullName>
    <formula>OrderQuantityNmb__c * LiquidNmb__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Total Item</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/LiquidNmb__c.field-meta.xml
<CustomField>
    <fullName>LiquidNmb__c</fullName>
    <label>Valor líquido</label>
    <precision>17</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OrderQuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <description>Preenchido via Workflow</description>
    <label>Código do Produto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/UnitPriceIPINmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceIPINmb__c</fullName>
    <description>Preço final, com descontos, aplicados sobre o preço com Política e IPI</description>
    <label>Preço Final com IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/UnitPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceNmb__c</fullName>
    <description>Preço final, com descontos aplicados sobre o preço com Política</description>
    <label>Preço Final Unitário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/UnitPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceNmb__c</fullName>
    <description>Campo de Preço Unitário utilizado, provisoriamente, no Mobile</description>
    <label>Preço Unitário Mobile</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderPDFViewController.cls
public with sharing class OrderPDFViewController {
    public Order__c orderHeader {get;set;}
    public List<OrderItem__c> orderItemList {get;set;}
    public string totalValue {get;set;}
    public string orderNum {get;set;}
    
    public String getDynamicFormatString()
    {
        Decimal value = 1000.10;
        String formattedValue = value.format();
        String thousandSep = formattedValue.substring(1,2);
        String decimalSep = formattedValue.substring(5,6);
        System.debug('{0,number,#'+thousandSep+'###'+thousandSep+'###'+thousandSep+'###'+thousandSep+'###'+thousandSep+'##0'+decimalSep+'00}');
        return '{0,number,#'+thousandSep+'###'+thousandSep+'###'+thousandSep+'###'+thousandSep+'###'+thousandSep+'##0'+decimalSep+'00}';
    }
    
    public OrderPDFViewController (ApexPages.StandardController stdController){        
        
        Order__c orderHeader = new Order__c();
        orderHeader = (Order__c) stdController.getRecord();
        
        orderHeader = 	[	SELECT	Id, name, OrderNumberTxt__c, AccountLkp__c, AccountAreaSalesLkp__c, AccountAreaSalesLkp__r.CodeSalesOrganizationTxt__c, AccountReceiverLkp__c, OrderTypeTxt__c,
                         			PaymentTermLkp__c, CustomIDTxt__c, TotalLiquidPriceNmb__c, IPITotalValueNmb__c, TotalSTValueNmb__c, TotalPriceNmb__c, NetWeightKgNmb__c, QuotationBln__c, 
                         			PriceExpirationFml__c, CreatedDate
            				FROM	Order__c
                         	WHERE	Id =: orderHeader.Id
        				];
        
        orderNum = orderHeader.CustomIDTxt__c;
        
        totalValue = string.valueof(orderHeader.TotalPriceNmb__c).replace(',','*').replace('.',',').replace('*','.');
        
        orderItemList = [	SELECT Id, Name, ProductLkp__r.Name, ProductLkp__r.ProductCodeTxt__c, OrderQuantityNmb__c, LiquidNmb__c, ItemTotalFml__c, UnitPriceNmb__c, UnitPriceIPINmb__c, 
                         	IPIValueFml__c, IPIPercentFml__c, FinalPriceFml__c, STValueFml__c, ValueST__c, ValueIPI__c, ValueICMS__c, ValueROBNoIPIFml__c, ValueROBFml__c, ValueROLFml__c,
                         	UnitValueROLFml__c, UnitValueROBFml__c
                          	FROM OrderItem__c
                            WHERE OrderMdt__c =: orderHeader.Id 
                         	//AND UnitPriceNmb__c != null
                        ];                
    }    
}