force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/ChannelLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal PVC</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipName>AccountAreaSales</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/BlockedItem__c.object-meta.xml
<CustomObject>
    <label>Parametrização</label>
    <nameField>
        <displayFormat>Param-{000000000}</displayFormat>
        <label>Nome de Itens Bloqueados</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BlockedItem__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>BlockedItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/fields/ChannelPVCLkp__c.field-meta.xml
<CustomField>
    <fullName>ChannelPVCLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Canal</label>
    <referenceTo>Channel__c</referenceTo>
    <relationshipName>BlockedItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/fields/MasterPackageAmountNmb__c.field-meta.xml
<CustomField>
    <fullName>MasterPackageAmountNmb__c</fullName>
    <label>Quantidade da Embalagem Master</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/fields/OrderTypeLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tipo de Ordem</label>
    <referenceTo>OrderType__c</referenceTo>
    <relationshipName>BlockedItems</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>Itens_Bloqueados</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/BlockedItem__c/recordTypes/MasterPackageRT.recordType-meta.xml
<RecordType>
    <fullName>MasterPackageRT</fullName>
    <active>true</active>
    <description>Indica que para esse material/cliente existe uma embalagem master</description>
    <label>Embalagem Master</label>
</RecordType>

force-app/main/default/objects/BlockedItem__c/recordTypes/PackageSeparationRT.recordType-meta.xml
<RecordType>
    <fullName>PackageSeparationRT</fullName>
    <active>true</active>
    <description>Bloqueio quebra de embalagem por tipo de ordem canal</description>
    <label>Quebra de Embalagem</label>
</RecordType>

force-app/main/default/objects/OfflinePrices__c/OfflinePrices__c.object-meta.xml
<CustomObject>
    <description>Tabela de preços do Offline</description>
    <label>Preços Offline</label>
    <nameField>
        <label>Nome de Preços Offline</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preços Offline</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OfflinePrices__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Preços Offline</relationshipLabel>
    <relationshipName>ProductLkp</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <description>[a0D][Order__c] Pedidos da organização.</description>
    <label>Ordem</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Número da ordem SF</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ordens</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/AccountAreaSalesLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountAreaSalesLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente caso Conta esteja preenchida. Se houver mais de uma, será necessário preencher o &quot;Responsável Vendas&quot;</inlineHelpText>
    <label>Área de vendas</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>AccountAreaSales__c.AccountLkp__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountLkp__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>AccountAreaSales__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Originalmente Emissor da Ordem no SAP</description>
    <inlineHelpText>Preenchido automaticamente se Área de Vendas for preenchida</inlineHelpText>
    <label>Conta</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Conta jurídica SAP, Conta pessoal SAP</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Ordens</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/ItemErrorMessageTxt__c.field-meta.xml
<CustomField>
    <fullName>ItemErrorMessageTxt__c</fullName>
    <label>Erros Itens</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/OrderTypeLkp__c.field-meta.xml
<CustomField>
    <fullName>OrderTypeLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Preenchido automaticamente com ZNOV caso deixe em branco</inlineHelpText>
    <label>Tipo de Ordem</label>
    <referenceTo>OrderType__c</referenceTo>
    <relationshipLabel>Ordens</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/OrderItem__c.object-meta.xml
<CustomObject>
    <description>[a0C][OrderItem__c] Itens dos pedidos da organização.</description>
    <label>Item da ordem</label>
    <nameField>
        <displayFormat>IT-{000000000}</displayFormat>
        <label>Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da ordem</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderItem__c/fields/CSVPriceNmb__c.field-meta.xml
<CustomField>
    <fullName>CSVPriceNmb__c</fullName>
    <label>Preço CSV</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderMdt__c.field-meta.xml
<CustomField>
    <fullName>OrderMdt__c</fullName>
    <label>Número da ordem</label>
    <referenceTo>Order__c</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OrderQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OrderQuantityNmb__c</fullName>
    <label>Quantidade</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/OriginalQuantityNmb__c.field-meta.xml
<CustomField>
    <fullName>OriginalQuantityNmb__c</fullName>
    <description>Quantidade no momento que o item é inserido no pedido, para comparar valores totais vindos do SAP</description>
    <label>Quantidade Original</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductCode__c.field-meta.xml
<CustomField>
    <fullName>ProductCode__c</fullName>
    <formula>ProductLkp__r.ProductCodeTxt__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código produto</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <description>Preenchido via Workflow</description>
    <label>Código do Produto</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ProductLkp__c.field-meta.xml
<CustomField>
    <fullName>ProductLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Itens da ordem</relationshipLabel>
    <relationshipName>Itens_da_ordem</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/SyncedSAPBln__c.field-meta.xml
<CustomField>
    <fullName>SyncedSAPBln__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Setado via mapa de integração para indicar que o pedido já foi sincronizado do SAP para o SF</description>
    <label>Sincronizado SAP</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ValueROBFml__c.field-meta.xml
<CustomField>
    <fullName>ValueROBFml__c</fullName>
    <formula>IF(OriginalQuantityNmb__c != 0 &amp;&amp; SyncedSAPBln__c = false, 
( TotalGrossCostNmb__c / OriginalQuantityNmb__c ) * OrderQuantityNmb__c * (1 - ZPRO__c) * (1 - ZCOT__c) * (1 - ZPVO__c) * (1 - ZVJ1__c) * (1 - ZPME__c) * (1 - ZPSO__c) * (1 - XXES__c) * (1 - ZPXI__c),
TotalGrossCostNmb__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROB</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ValueROBNoIPIFml__c.field-meta.xml
<CustomField>
    <fullName>ValueROBNoIPIFml__c</fullName>
    <formula>IF(OriginalQuantityNmb__c != 0 &amp;&amp; SyncedSAPBln__c = false, 
( OriginalROBNoIPINmb__c / OriginalQuantityNmb__c ) * OrderQuantityNmb__c * (1 - ZPRO__c) * (1 - ZCOT__c) * (1 - ZPVO__c) * (1 - ZVJ1__c) * (1 - ZPME__c) * (1 - ZPSO__c) * (1 - XXES__c) * (1 - ZPXI__c),
OriginalROBNoIPINmb__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ROB s/ IPI</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/YCOT__c.field-meta.xml
<CustomField>
    <fullName>YCOT__c</fullName>
    <description>Desconto limite de cotação, recebido via integração</description>
    <label>Desconto de Cotação Máximo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/YPRO__c.field-meta.xml
<CustomField>
    <fullName>YPRO__c</fullName>
    <description>Limite do desconto Promocional</description>
    <label>Desconto Promocional Máximo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ZCOT__c.field-meta.xml
<CustomField>
    <fullName>ZCOT__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Desconto aplicado em cotação</description>
    <label>Desconto de Cotação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderItem__c/fields/ZPRO__c.field-meta.xml
<CustomField>
    <fullName>ZPRO__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Desconto promocional aplicado. Limitado pelo campo YPRO</description>
    <label>Desconto Promocional</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/OrderType__c/OrderType__c.object-meta.xml
<CustomObject>
    <description>Tipos de ordem disponíveis</description>
    <label>Tipo de Ordem</label>
    <nameField>
        <label>Tipo de Ordem</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tipos de Ordem</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/OrderType__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Categoria</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotação</fullName>
            </value>
            <value>
                <fullName>Venda</fullName>
            </value>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Pedido</fullName>
                <isActive>false</isActive>
                <label>Pedido</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OrderType__c/fields/OrderIrrigationBln__c.field-meta.xml
<CustomField>
    <fullName>OrderIrrigationBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Ordem irrigação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/IrrigationItemBln__c.field-meta.xml
<CustomField>
    <fullName>IrrigationItemBln__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item Irrigação</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/ProductCodeTxt__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeTxt__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>18</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Product2/fields/StandardPackageAmountNmb__c.field-meta.xml
<CustomField>
    <fullName>StandardPackageAmountNmb__c</fullName>
    <description>Quantidade de itens por embalagem padrão</description>
    <label>Quantidade da Embalagem Padrão</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomFileUploadController.cls
public class CustomFileUploadController {
    public string nameFile{get;set;}
    public Blob contentFile{get;set;}
    String[] filelines = new String[]{};
    List<OrderItem__c> itensToUpload;
    public Order__c ord{get; set;}
    public String contentType{get; set;}
        

        
        

    public class ItemUpload{
        public String productCode;
        //public Double productQty;
        public Boolean productError;
        //public Double productPrice;
        public String productQty;
        public String productPrice;
        
        public ItemUpload(){
            this.productCode = '';
            this.productQty = '0';
            this.productError = false;
            this.productPrice = null;
        }
    }

    private List<String> checkItemUpload(List<ItemUpload> itemUploadList, Id orderId){
        Order__c ord = [SELECT Id, Name, 
                        OrderTypeLkp__r.OrderIrrigationBln__c, 
                        AccountLkp__c,
                        AccountAreaSalesLkp__r.ChannelLkp__c,
                        OrderTypeLkp__c
                        FROM Order__c WHERE Id = :orderId];

        List<ItemUpload> auxList = itemUploadList.clone();
        Boolean skipPackage = false;
        Map<String, Product2> productMap = new Map<String, Product2>();
        Map<String, Decimal> masterPackageMap = new Map<String, Decimal>();
        List<String> errorList = new List<String>();
        List<String> productCodeList = new List<String>();
        for(ItemUpload item : itemUploadList){
            productCodeList.add(item.ProductCode);
        }
        
        List<Product2> productList = [SELECT Id, Name, ProductCodeTxt__c, StandardPackageAmountNmb__c, IrrigationItemBln__c FROM Product2 WHERE ProductCodeTxt__c IN :productCodeList];
        
        
        for(Product2 p : productList){
            productMap.put(p.ProductCodeTxt__c, p);    
        }    
        
        List<BlockedItem__c> listBlock = [SELECT Id, 
                                          MasterPackageAmountNmb__c, 
                                          RecordType.DeveloperName,
                                          ProductLkp__r.ProductCodeTxt__c
                                          FROM BlockedItem__c 
                                          WHERE 
                                          (ProductLkp__r.ProductCodeTxt__c IN :productMap.keySet() AND AccountLkp__c = :ord.AccountLkp__c AND RecordType.DeveloperName = 'MasterPackageRT') OR
                                          (ChannelPvcLkp__c = :ord.AccountAreaSalesLkp__r.ChannelLkp__c AND OrderTypeLkp__c = :ord.OrderTypeLkp__c AND RecordType.DeveloperName = 'PackageSeparationRT')
                                         ];
        for(BlockedItem__c param : listBlock){
            if(param.RecordType.DeveloperName == 'PackageSeparationRT') 
                skipPackage = true;
            else{
                masterPackageMap.put(param.ProductLkp__r.ProductCodeTxt__c, param.MasterPackageAmountNmb__c);
            }
        }

        
        for(ItemUpload item : itemUploadList){
            item.productError = false;
            
            if(!productMap.containsKey(item.productCode)){
                errorList.add(item.productCode + ': Item não encontrado');
                item.productError = true;
            }else{
                Product2 prod = productMap.get(item.productCode);
                //Integer packageAmt = (prod.StandardPackageAmountNmb__c != null && prod.StandardPackageAmountNmb__c != 0) ? Integer.valueOf(prod.StandardPackageAmountNmb__c) : 1;
                Integer packageAmt = 1;
                if(!skipPackage){
                    if(masterPackageMap.containsKey(item.productCode))
                        packageAmt = Integer.valueOf(masterPackageMap.get(item.productCode));
                    else packageAmt = (prod.StandardPackageAmountNmb__c != null && prod.StandardPackageAmountNmb__c != 0) ? Integer.valueOf(prod.StandardPackageAmountNmb__c) : 1;
                }
                
                if(item.productQty.trim().isNumeric()){
                    System.debug(item.productQty.trim());
                    for(Integer J = 0; J < item.productQty.trim().length(); J++){
                        String aux = item.productQty.trim();
                        System.debug(J+' = '+aux.charAt(J));
                    }
                    Integer division = Integer.valueOf(item.productQty.trim()) / packageAmt;
                    if(division * packageAmt != Integer.valueOf(item.productQty.trim())){
                        errorList.add(item.productCode + ': Item fora da embalagem padrão/master. Favor negociar em múltiplo de '+packageAmt);      
                        item.productError = true;
                    }         
                }else{
                    errorList.add(item.productCode + ': '+item.productQty+' não é um valor válido para Quantidade');
                    item.productError = true;                    
                }                

                if((ord.OrderTypeLkp__r.OrderIrrigationBln__c) && (!prod.IrrigationItemBln__c)){
                    errorList.add(item.productCode + ': Item não disponível para irrigação');
                    item.productError = true;
                }
                
                if(item.productPrice != null){
                    try{
                        Double productPrice = Double.valueOf(item.productPrice);
                        /*if(productPrice == 0){
                            errorList.add(item.productCode + ': '+item.productPrice+' não é um valor válido para o preço');
                            item.productError = true;
                        }*/
                    }catch(TypeException e){
                        errorList.add(item.productCode + ': '+item.productPrice+' não é um valor válido para o preço');
                        item.productError = true;
                    }
                }
            }
        }
        
        return errorList;
    }
        
    public CustomFileUploadController(ApexPages.StandardController stdController) {
        this.ord = (Order__c)stdController.getRecord();
        this.ord = [SELECT Id, OrderTypeLkp__r.Category__c FROM Order__C WHERE Id = :ord.id];
    }
    
    public Pagereference AdjustDiscounts(){
        List<OrderItem__c> itemList = [SELECT Id, Name, ProductCode__c, CSVPriceNmb__c, ZCOT__c, YCOT__c, ZPRO__c, YPRO__c,
                                       ValueROBNoIPIFml__c, ValueROBFml__c, OrderQuantityNmb__c, OriginalQuantityNmb__c, SyncedSAPBln__c 
                                       FROM OrderItem__c 
                                       WHERE OrderMdt__c = :ord.Id];
        
        //Boolean zcotAcima = false;
        Boolean zproAcima = false;
        for(OrderItem__c item : itemList){
            if((item.CSVPriceNmb__c != null) && (item.ValueROBNoIPIFml__c > 0) && (item.OrderQuantityNmb__c > 0)){
                //Double newZCOT = (1 - (item.CSVPriceNmb__c/(item.ValueROBNoIPIFml__c / item.OrderQuantityNmb__c)))*100;
                Double newZPRO = (1 - (item.CSVPriceNmb__c/(item.ValueROBNoIPIFml__c / item.OrderQuantityNmb__c)))*100;
                
                System.debug('Comparar: '+ item.CSVPriceNmb__c + ' e ' + (item.ValueROBNoIPIFml__c / item.OrderQuantityNmb__c));  
                //System.debug('Desconto Calculado: '+newZCOT+'; Desconto Máximo: '+item.YCOT__c);
                System.debug('Desconto Calculado: '+newZPRO+'; Desconto Máximo: '+item.YPRO__c);
                
                if(newZPRO > item.YPRO__c){
                    item.ZPRO__c = item.YPRO__c;
                    zproAcima = true;
                }else{
                    item.ZPRO__c = newZPRO;
                }
                
                /*if(newZCOT > item.YCOT__c){
                    item.ZCOT__c = item.YCOT__c;
                	zcotAcima = true;
                }else{
                    item.ZCOT__c = newZCOT;
                }*/
            }
        }
        
        if(zproAcima){
           	//String str = 'Para um ou mais itens, o desconto de cotação máximo não é suficiente para atingir os valores carregados no CSV. Para esses casos foi utilizado o desconto de cotação máximo.';
            String str = 'Para um ou mais itens, o desconto promocional máximo não é suficiente para atingir os valores carregados no CSV. Para esses casos foi utilizado o desconto promocional máximo.';
            ApexPages.Message warningMessage = new ApexPages.Message(ApexPages.severity.WARNING, str);
            ApexPages.addMessage(warningMessage);              
        }else{
            //ApexPages.Message sucessMsg = new ApexPages.Message(ApexPages.severity.INFO,'Os valores de desconto de cotação foram ajustados para que os valores de preço do CSV forem atingidos.');
            ApexPages.Message sucessMsg = new ApexPages.Message(ApexPages.severity.INFO,'Os valores de desconto promocional foram ajustados para que os valores de preço do CSV fossem atingidos.');
            ApexPages.addMessage(sucessMsg);                       
        }
        update itemList;
        
        return null;
    }
    
    public Pagereference ReadFile(){

     	System.debug(contentType);
        
        if(contentType == 'application/vnd.ms-excel'){
            nameFile = contentFile.toString();
            if(nameFile.indexOf(';') != -1){
                try{
                    filelines = nameFile.split('\n');
                    itensToUpload = new List<OrderItem__c>();
                    
                    List<ItemUpload> itemUploadList = new List<ItemUpload>();
                    
                    if(filelines.size() > 0){
                        String[] inputHeader = new String[]{};
                        inputHeader = filelines[0].split(';');
                        
                        
                        if((inputHeader.size() == 2)){
                            system.debug('Tipo de ordem');
                            system.debug(ord.OrderTypeLkp__r.Category__c);
                            for (Integer i=1;i<filelines.size();i++)
                            {
                                String[] inputvalues = new String[]{};
                                inputvalues = filelines[i].split(';');
                                System.debug(inputvalues);
                                
                                ItemUpload item = new ItemUpload();
                                item.productCode = inputvalues[0];
                                item.productQty = inputvalues[1];
                                
                                itemUploadList.add(item);
                            }
                        }else if(inputHeader.size() == 3){
                            System.debug('TRÊS COLUNAS');
                            for (Integer i=1;i<filelines.size();i++)
                            {
                                String[] inputvalues = new String[]{};
                                inputvalues = filelines[i].split(';');
                                System.debug(inputvalues);
                                
                                for(Integer J = 0 ; J < inputvalues.size(); J++){
                                    System.debug('['+I+', '+J+'] = '+inputvalues[J]);
                                }
                                
                                ItemUpload item = new ItemUpload();
                                item.productCode = inputvalues[0];
                                item.productQty = inputvalues[1];
                                
                                System.debug(inputValues[2].length());
                                if((inputvalues[2] != '') && (inputvalues[2] != '\n') && (inputvalues[2] != '\r')){
                                    String priceStr = inputvalues[2];
                                    priceStr = priceStr.replace(',', '.');
                                    item.productPrice = priceStr;
                                }
                                itemUploadList.add(item);
                            }                           
                        }
                    }
                    
                    System.debug('UploadList antes:');
                    System.debug(itemUploadList);
                    List<String> errorList = checkItemUpload(itemUploadList, ord.Id);
                    System.debug('UploadList depois:');
                    System.debug(itemUploadList);
                    
                    System.debug(errorList);
                    
                    for(ItemUpload item : itemUploadList){
                        if( !item.productError ){
                            OrderItem__c ordItem = new OrderItem__c();
                            ordItem.ProductLkp__r = new Product2(ProductCodeTxt__C = item.productCode);
                            ordItem.OrderQuantityNmb__c = Integer.valueOf(item.productQty.trim());
                            if(item.productPrice != null){
                                Double productPrice = Double.valueOf(item.productPrice);
                                if(productPrice != 0){
                                    ordItem.CSVPriceNmb__c = Double.valueOf(item.productPrice);
                                }
                            }
                            ordItem.OrderMdt__c = ord.Id;
                            
                            itensToUpload.add(ordItem);
                        }
                    }
                    System.debug('Serão inseridos:');
                    System.debug(itensToUpload);
                    Database.SaveResult[] srList = Database.insert(itensToUpload, false);
                    
                    Integer sucessCount = 0;
                    for(Database.SaveResult sr : srList){
                        if(sr.isSuccess()){
                            sucessCount++;
                        }else{               
                            for(Database.Error err : sr.getErrors()){
                                String errorMsg = err.getStatusCode()+': '+err.getMessage()+' - '+err.getFields();
                                errorList.add(errorMsg);
                            }                            
                        }
                    }
                    if(itemUploadList.size() == sucessCount){
                    	ApexPages.Message sucessMsg = new ApexPages.Message(ApexPages.severity.CONFIRM,'Foram carregados '+sucessCount+' itens no pedido');
                        ApexPages.addMessage(sucessMsg);                        
                    }else{
                    	ApexPages.Message warningMessage = new ApexPages.Message(ApexPages.severity.WARNING,'Dos '+itemUploadList.size()+' itens lidos a partir do CSV, foram carregados '+sucessCount+' no pedido');
                        ApexPages.addMessage(warningMessage);
                    }
                    
                    ord.ItemErrorMessageTxt__c = '';
                    for(Integer I = 0; I < errorList.size(); I++){
                        ord.ItemErrorMessageTxt__c = ord.ItemErrorMessageTxt__c + errorList[I]+'\n';
                    }
                    upsert ord;
                }
                catch (Exception e){
                    ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'Erro na inclusão dos pedidos: '+e.getMessage());
                    ApexPages.addMessage(errormsg);
                }                      
            }else{
				ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'Utilize um CSV separado com ponto e vírgula');
            	ApexPages.addMessage(errormsg);                      
            }
        }else{
            ApexPages.Message errormsg = new ApexPages.Message(ApexPages.severity.ERROR,'Formato de arquivo inválido. Utilize .CSV');
            ApexPages.addMessage(errormsg);            
        }
        return null;
    }
    
    public List<OrderItem__c> getuploadedAccounts()
    {
        if (itensToUpload != NULL)
            if (itensToUpload.size() > 0)
                return itensToUpload;
            else
                return null;                    
        else
            return null;
    }            

}