force-app/main/default/objects/AccountAreaSales__c/AccountAreaSales__c.object-meta.xml
<CustomObject>
    <description>[a02][AccountAreaSales__c] Contém informações sobre Áreas de Vendas.</description>
    <label>Cliente</label>
    <nameField>
        <displayFormat>MEX-{0000000}</displayFormat>
        <label>Área de Negócios</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Clientes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAreaSales__c/fields/AccountLkp__c.field-meta.xml
<CustomField>
    <fullName>AccountLkp__c</fullName>
    <label>Nome da conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Clientes (Nome da conta)</relationshipLabel>
    <relationshipName>AreasDeVendas</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountAreaSales__c/fields/FiscalClassificationTxt__c.field-meta.xml
<CustomField>
    <fullName>FiscalClassificationTxt__c</fullName>
    <label>Descrição classificação fiscal</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Não sujeito a impst.</fullName>
            </value>
            <value>
                <fullName>Imposto normal</fullName>
            </value>
            <value>
                <fullName>Área Livre Com IPI</fullName>
            </value>
            <value>
                <fullName>ZFM - ICMS e IPI</fullName>
            </value>
            <value>
                <fullName>Clientes exportação</fullName>
            </value>
            <value>
                <fullName>Área Livre Comer. ST</fullName>
            </value>
            <value>
                <fullName>Imposto Futuro</fullName>
            </value>
            <value>
                <fullName>Desc. REIDI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CSEAccountAreaSalesSelector.cls
public with sharing class CSEAccountAreaSalesSelector extends fflib_SObjectSelector {
    public List<Schema.SObjectField> getSObjectFieldList() {
    	return new List<Schema.SObjectField> {
    		AccountAreaSales__c.Id,
    		AccountAreaSales__c.FiscalClassificationTxt__c
    	};
    }
    
    public Schema.SObjectType getSObjectType() {
    	return AccountAreaSales__c.sObjectType;
    }
    
    public List<AccountAreaSales__c> selectById(Set<Id> idSet) {
    	String query = String.format(
    		' SELECT {0} ' +
    		' FROM {1}' +
    		' WHERE Id IN :idSet' +
    		' ORDER BY {2}',
    		new List<String> {
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<AccountAreaSales__c>)Database.query(query);
    }
    
    public List<AccountAreaSales__c> selectByAccountId(Set<Id> accountIdSet) {
    	String query = String.format(
    		' SELECT {0} ' +
    		' FROM {1} ' +
    		' WHERE AccountLkp__c IN :accountIdSet' +
    		' ORDER BY {2}',
    		new List<String> {
    			getFieldListString(),
    			getSObjectName(),
    			getOrderBy()
    		}
    	);
    	return (List<AccountAreaSales__c>)Database.query(query);
    }
}