force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/CaseLkp__c.field-meta.xml
<CustomField>
    <fullName>CaseLkp__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Caso</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>QMs</relationshipLabel>
    <relationshipName>QMs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/ErrorTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorTxt__c</fullName>
    <label>Erro</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/QMSAPTxt__c.field-meta.xml
<CustomField>
    <fullName>QMSAPTxt__c</fullName>
    <label>QM SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/SalesforceQMTxt__c.field-meta.xml
<CustomField>
    <fullName>SalesforceQMTxt__c</fullName>
    <description>ID externo alimentado por trigger. Recebe valor número do caso + número da QM.</description>
    <externalId>true</externalId>
    <label>QM Salesforce</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/QM__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QM criada Salesforce</fullName>
                <default>true</default>
                <label>QM criada Salesforce</label>
            </value>
            <value>
                <fullName>QM enviada SAP</fullName>
            </value>
            <value>
                <fullName>QM criada SAP</fullName>
            </value>
            <value>
                <fullName>QM com erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QM.cls
public without sharing class QM {
	
	public class QMException extends Exception {}
	
	private QMMapping mapping;
	private List<QM__c> qmList;
	
	public QM(List<QM__c> qmList) {
		this.mapping = new QMMapping();
		this.qmList = qmList;
	}	
	
	/*
		Loads aditional information by record type
	*/
	public QM enrich(){
		
		Set<Id> caseIdSet = new Set<Id>();
		for (QM__c qm : this.qmList) {
			caseIdSet.add(qm.CaseLkp__c);
		}
		
		List<Case> caseList = new List<Case>();
		caseList = CaseDAO.getById(caseIdSet);
		Map<Id, Case> caseMap = new Map<Id, Case>(caseList);
		
		for (QM__c qm : qmList) {
			//get configuration according to qm's recordtype
			IQMConfigurator cfg = mapping.findByRecordTypeId(qm.RecordTypeId);
			System.debug(LoggingLevel.FINEST, '*** IQMConfigurator: ' + cfg);
			if (cfg == null) {
				throw new QMException('QM configurator not found for [' + qm.RecordTypeId + '] recordtypeId.');
			}
			
			//get related case to QM
			Case relatedCase = caseMap.get(qm.CaseLkp__c);
			//do configuration
			cfg.configure(qm, relatedCase);
		}
		
		return this;
	}
	
	public QM save() {
		upsert this.qmList;
		return this;
	}
	
	public static void setExternalIdQM(Set<Id> qmIdSet) {
		List<QM__c> auxList = QMDAO.getById(qmIdSet);
		for(QM__c aux : auxList) {
			aux.SalesforceQMTxt__c = aux.CaseLkp__r.CaseNumber + aux.Name;
		}
		update auxList;
	}
	
	public static void checkSentStatus(List<QM__C> qmList) {
		for(QM__c aux : qmList) {
			if(aux.ErrorTxt__c != null && !aux.ErrorTxt__c.equals('')) {
				aux.StatusTxt__c = 'QM com erro';
			} else if(aux.QMSAPTxt__c != null && !aux.QMSAPTxt__c.equals('') && aux.StatusTxt__c != 'Concluído'){
				aux.StatusTxt__c = 'QM criada SAP';
			}
		}
	}
	public static void setStatusInCase(List<QM__C> qmList){
		
		Set<Id> caseIdSet = new Set<Id>();
		for (QM__c qm : qmList) {
			caseIdSet.add(qm.CaseLkp__c);
		}
		
		Map<String, Id> recordMap = new Map<String, Id>();
		List<RecordType> recordType = [SELECT Id, Name FROM RecordType  where SobjectType = 'Case'];
    	for(RecordType rec : recordType) {
    		recordMap.put(rec.Name, rec.Id);
    	}
		
		List<Case> caseList = new List<Case>();
		caseList = CaseDAO.getById(caseIdSet);
		Map<Id, Case> caseMap = new Map<Id, Case>(caseList);
		
		for (QM__c qm : qmList) {
			
			Case relatedCase = caseMap.get(qm.CaseLkp__c);
			
			if (relatedCase.RecordTypeId != recordMap.get('Reclamação') && relatedCase.Status != 'Encerrado' && relatedCase.Status != 'Cancelado' && relatedCase.Status != 'Aguardando encerramento'){
					
				relatedCase.Status = 'QM em andamento';
				
				update relatedCase;
			}
		}
	}
}