force-app/main/default/objects/QM__c/QM__c.object-meta.xml
<CustomObject>
    <description>[a0F][QM__c]  Gestão de qualidade.</description>
    <label>QM</label>
    <nameField>
        <displayFormat>QM{000}</displayFormat>
        <label>Numeração QM</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QMs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QM__c/fields/ErrorTxt__c.field-meta.xml
<CustomField>
    <fullName>ErrorTxt__c</fullName>
    <label>Erro</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/QMSAPTxt__c.field-meta.xml
<CustomField>
    <fullName>QMSAPTxt__c</fullName>
    <label>QM SAP</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QM__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>QM criada Salesforce</fullName>
                <default>true</default>
                <label>QM criada Salesforce</label>
            </value>
            <value>
                <fullName>QM enviada SAP</fullName>
            </value>
            <value>
                <fullName>QM criada SAP</fullName>
            </value>
            <value>
                <fullName>QM com erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QMMeasure__c/QMMeasure__c.object-meta.xml
<CustomObject>
    <description>[a0E][QMMeasure__c] Medidas da QM.</description>
    <label>Medida da QM</label>
    <nameField>
        <label>Numeração medida da QM</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Medidas da QM</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QMMeasure__c/fields/QMSalesforceMdt__c.field-meta.xml
<CustomField>
    <fullName>QMSalesforceMdt__c</fullName>
    <label>QM Salesforce</label>
    <referenceTo>QM__c</referenceTo>
    <relationshipLabel>Medidas da QM</relationshipLabel>
    <relationshipName>Medidas_da_QM</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/QMMeasure__c/fields/QMSAPTxt__c.field-meta.xml
<CustomField>
    <fullName>QMSAPTxt__c</fullName>
    <label>QM SAP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QMMeasure__c/fields/StatusTxt__c.field-meta.xml
<CustomField>
    <fullName>StatusTxt__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Em aberto</fullName>
            </value>
            <value>
                <fullName>Concluído</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/QMMeasureBO.cls
public with sharing class QMMeasureBO {
    public void setQMSapNumber(Set<Id> qmMeasureIdSet) {
    	List<QMMeasure__c> listMeasure = [Select QMSalesforceMdt__c, QMSAPTxt__c From QMMeasure__c where Id in :qmMeasureIdSet];
    	
    	Set<Id> qmIdSet = new Set<Id>();
    	for(QMMeasure__c auxQmM : listMeasure) {
    		qmIdSet.add(auxQmM.QMSalesforceMdt__c);
    	}
    	
    	List<QM__c> qmList = QMDAO.getById(qmIdSet);
    	
    	for(QM__c auxQM : qmList) {
    		for(QMMeasure__c auxQmM : listMeasure) {
    			if(auxQmM.QMSalesforceMdt__c == auxQm.Id) {
    				auxQM.QMSAPTxt__c =	auxQmM.QMSAPTxt__c;
    				auxQM.ErrorTxt__c = '';
    			}
    		}
    	}
    	update qmList;
    }

    public void concludeQM(Set<Id> qmMeasureIdSet) {
        List<QMMeasure__c> qmMeasureCandidateList = QMMeasureDAO.getById(qmMeasureIdSet);
        Set<Id> qmIdCandidateSet = new Set<Id>();
        String status;

        for(QMMeasure__c qmMeasureCandidate : qmMeasureCandidateList) {

            if(qmMeasureCandidate.StatusTxt__c != null) {

                status = qmMeasureCandidate.StatusTxt__c.toLowerCase();

                if((status == 'concluido') || (status == 'concluído')) {

                    qmIdCandidateSet.add(qmMeasureCandidate.QMSalesforceMdt__c);
                }
            }
        }

        // Creating a map to store the candidates to be concluded and its status.
        Map<Id, boolean> qmStatusMap = new Map<Id, boolean>();

        for(Id qmIdCandidate : qmIdCandidateSet) { 

            qmStatusMap.put(qmIdCandidate, true); 
        }

        List<QMMeasure__c> qmMeasureList = QMMeasureDAO.getByQmId(qmIdCandidateSet);

        // Deciding which candidates will be concluded.
        for(QMMeasure__c qmMeasure : qmMeasureList) {

            if(qmMeasure.StatusTxt__c != null) {

                status = qmMeasure.StatusTxt__c.toLowerCase();

                if((status != 'concluido') && (status != 'concluído')) {
                    qmStatusMap.put(qmMeasure.QMSalesforceMdt__c, false);
                }
            } 
            else {

                qmStatusMap.put(qmMeasure.QMSalesforceMdt__c, false);
            }
        }

        Set<Id> qmIdSet = new Set<Id>();

        // Creating list of selected candidates.
        for (Id id : qmStatusMap.keySet()) {

            if(qmStatusMap.get(id)) { qmIdSet.add(id); }
        }

        List<QM__c> qmList = QMDAO.getById(qmIdSet);

        // Concluding selected candidates.
        for(QM__c qm : qmList) {

            if(qm.StatusTxt__c != 'Concluído') {

                System.debug('*** Updating: ' + qm.id);
                qm.StatusTxt__c = 'Concluído';   
            }
        }

        update qmList;
    }
}